force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Today__c.field-meta.xml
<CustomField>
    <fullName>Today__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateDateTodayFields.cls
public class UpdateDateTodayFields implements Schedulable {
  public void execute(SchedulableContext sc) {
    Date dt = date.today();
    List<Grantee_Report__c> items = [SELECT Today__c FROM Grantee_Report__c];
    for (Grantee_Report__c i : items) {
      i.Today__c = dt;
    }
    try {
      update items;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }
}