force-app/main/default/objects/Field_Label__c/Field_Label__c.object-meta.xml
<CustomObject>
    <label>Field Label</label>
    <nameField>
        <displayFormat>FL-{000}</displayFormat>
        <label>Field Label Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Label__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <inlineHelpText>DO NOT EDIT THIS FIELD!!!!</inlineHelpText>
    <label>Field API</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>GREAT</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>MDGO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>20000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application__c</fullName>
            </value>
            <value>
                <fullName>Application_Site__c</fullName>
            </value>
            <value>
                <fullName>Assessment__c</fullName>
                <default>true</default>
                <label>Assessment__c</label>
            </value>
            <value>
                <fullName>Grantee_Report__c</fullName>
            </value>
            <value>
                <fullName>Progress_Report__c</fullName>
            </value>
            <value>
                <fullName>Victims_Served_Report__c</fullName>
            </value>
            <value>
                <fullName>Program_Plan__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Label__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FieldLabelClass.cls
public without sharing class FieldLabelClass {
  public Map<String, String> getFieldLabelMap(
    String objectType,
    String grantType,
    String appType,
    String soqlAND
  ) {
    Map<String, String> labels = new Map<String, String>();
    String soql =
      'SELECT Field_API__c, Label__c FROM Field_Label__c WHERE Object__c includes (\'' +
      objectType +
      '\')';
    if (grantType != null) {
      if (grantType.contains('GREAT'))
        grantType = 'GREAT';
      soql += ' AND Grant_Type__c INCLUDES (\'' + grantType + '\', \'All\')';
    }
    if (appType != null)
      soql +=
        ' AND (Application_Type__c  = \'' +
        appType +
        '\' OR Application_Type__c  = \'All\')';
    if (soqlAND != null)
      soql += soqlAND;
    soql += ' ORDER BY Order__c';

    system.debug('FieldLabelClass getFieldLabelMap soql = ' + soql);
    for (Field_Label__c i : database.query(soql)) {
      labels.put(i.Field_API__c, i.Label__c);
    }
    return labels;
  }

  public List<Field_Label__c> getFields(
    String objectType,
    String grantType,
    String appType,
    String soqlAND
  ) {
    String soql =
      'SELECT Field_API__c, Label__c, Required__c, Order__c FROM Field_Label__c WHERE Object__c includes (\'' +
      objectType +
      '\')';
    if (grantType != null) {
      if (grantType.contains('GREAT'))
        grantType = 'GREAT';
      soql += ' AND Grant_Type__c INCLUDES (\'' + grantType + '\', \'All\')';
    }
    if (appType != null)
      soql +=
        ' AND (Application_Type__c  = \'' +
        appType +
        '\' OR Application_Type__c  = \'All\')';
    if (soqlAND != null)
      soql += soqlAND;
    soql += ' ORDER BY Order__c';
    system.debug('FieldLabelClass getFieldMap soql = ' + soql);

    Set<String> names = new Set<String>();
    List<Field_Label__c> fields = new List<Field_Label__c>();
    for (Field_Label__c i : database.query(soql)) {
      if (!names.contains(i.Field_API__c))
        fields.add(i);
      names.add(i.Field_API__c);
    }
    system.debug('FieldLabelClass getFieldMap fields = ' + fields);
    return fields;
  }

  public Map<String, String> getFieldNameMap(
    String objectType,
    String grantType,
    String appType,
    String soqlAND
  ) {
    Map<String, String> labels = new Map<String, String>();
    String soql =
      'SELECT Field_API__c, Field_Name__c FROM Field_Label__c WHERE Object__c includes (\'' +
      objectType +
      '\')';
    if (grantType != null) {
      if (grantType.contains('GREAT'))
        grantType = 'GREAT';
      soql += ' AND Grant_Type__c INCLUDES (\'' + grantType + '\', \'All\')';
    }
    if (appType != null)
      soql +=
        ' AND (Application_Type__c  = \'' +
        appType +
        '\' OR Application_Type__c  = \'All\')';
    if (soqlAND != null)
      soql += soqlAND;
    soql += ' ORDER BY Order__c';

    system.debug('FieldLabelClass getFieldNameMap soql = ' + soql);
    for (Field_Label__c i : database.query(soql)) {
      labels.put(i.Field_API__c.toLowerCase(), i.Field_Name__c);
    }
    return labels;
  }
}