force-app/main/default/objects/Chapter_Report__c/Chapter_Report__c.object-meta.xml
<CustomObject>
    <label>Chapter Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Chapter Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chapter_Report__c/fields/Youth_in_Program_Report__c.field-meta.xml
<CustomField>
    <fullName>Youth_in_Program_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Youth in Program Report</label>
    <referenceTo>Youth_in_Program_Report__c</referenceTo>
    <relationshipLabel>Chapter Reports</relationshipLabel>
    <relationshipName>Chapter_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/Youth_in_Program_Report__c.object-meta.xml
<CustomObject>
    <label>Youth in Program Report</label>
    <nameField>
        <displayFormat>Y-{0000}</displayFormat>
        <label>Youth in Program Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Youth in Program Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChapterReportClass.cls
public without sharing class ChapterReportClass {
  public String soql { get; set; }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Chapter_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet())
      expr += fieldName + ', ';
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM Chapter_Report__c';
    return soql;
  }

  public List<Chapter_Report__c> getReportList(Set<Id> yprIds) {
    getSOQL();
    soql += ' WHERE Youth_in_Program_Report__c IN :yprIds AND Youth_in_Program_Report__r.Is_Deleted__c = false';
    List<Chapter_Report__c> crs = Database.query(soql);
    return crs;
  }

  public void upsertCR(Chapter_Report__c cr) {
    try {
      upsert cr;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  public void upsertCRs(List<Chapter_Report__c> crs) {
    try {
      upsert crs;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}