force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Test</fullName>
            </value>
            <value>
                <fullName>Post-Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/Youth_in_Program_Report__c.object-meta.xml
<CustomObject>
    <label>Youth in Program Report</label>
    <nameField>
        <displayFormat>Y-{0000}</displayFormat>
        <label>Youth in Program Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Youth in Program Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Post_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Post_Test_Status__c</fullName>
    <formula>TEXT(Post_Test__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post-Test Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Pre_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Pre_Test_Status__c</fullName>
    <formula>TEXT(Pre_Test__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre-Test Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurveyClass.cls
public without sharing class SurveyClass {
  public SurveyClass() {
  }
  public String soql { get; set; }

  public void getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Survey__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM Survey__c';
  }

  public Survey__c getSurvey(Id surveyId) {
    getSOQL();
    Survey__c survey = new Survey__c();
    if (surveyId != null) {
      soql += ' WHERE Id = \'' + surveyId + '\'';
      Survey__c[] surveys = Database.query(soql);
      if (surveys.size() > 0) {
        survey = surveys[0];
      }
    }
    return survey;
  }

  public void upsertSurvey(Survey__c survey) {
    try {
      upsert survey;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  /*
    public void updateStatuses(Set<Id> ids) {
        Youth_in_Program_Report__c[] records = [SELECT Pre_Test_Status__c, Post_Test_Status__c FROM Youth_in_Program_Report__c WHERE Id IN :ids];
        for(Survey__c s : [SELECT Youth_in_Program_Report__c, Type__c, Status__c FROM Survey__c WHERE Youth_in_Program_Report__c IN :records]) {
            for(Youth_in_Program_Report__c r : records) {
                if(s.Youth_in_Program_Report__c == r.Id) {
                    if(s.Type__c == 'Pre-Test') r.Pre_Test_Status__c = s.Status__c;
                    if(s.Type__c == 'Post-Test') r.Post_Test_Status__c = s.Status__c;
                }
            }
        }
        try {
            update records;
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
    }
    */
}