force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Areas_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Areas_of_Service__c</fullName>
    <label>Areas of Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Providing information to crime victims</fullName>
            </value>
            <value>
                <fullName>Referral services for crime victims</fullName>
            </value>
            <value>
                <fullName>Victim advocacy/accompaniment</fullName>
            </value>
            <value>
                <fullName
        >Law enforcement interview advocacy/accompaniment</fullName>
                <label>Law enforcement interview advocacy/accompaniment</label>
            </value>
            <value>
                <fullName
        >Intervention with employer, creditor, landlord or academic institution</fullName>
                <label
        >Intervention with employer, creditor, landlord or academic institution</label>
            </value>
            <value>
                <fullName>Child and/or dependent care assistance</fullName>
            </value>
            <value>
                <fullName>Transportation assistance</fullName>
            </value>
            <value>
                <fullName>Interpreter services</fullName>
            </value>
            <value>
                <fullName>Crisis intervention</fullName>
            </value>
            <value>
                <fullName>Hotline/crisis line counseling</fullName>
            </value>
            <value>
                <fullName>On-scene crisis response</fullName>
            </value>
            <value>
                <fullName
        >Sexual Assault Response Team (SART) team development</fullName>
                <label
        >Sexual Assault Response Team (SART) team development</label>
            </value>
            <value>
                <fullName
        >Coordinated Community Response (CCR) team development</fullName>
                <label
        >Coordinated Community Response (CCR) team development</label>
            </value>
            <value>
                <fullName>Updating tribal codes for victim services</fullName>
            </value>
            <value>
                <fullName
        >Access to Traditional/Cultural Healing ceremonies for victims</fullName>
                <label
        >Access to Traditional/Cultural Healing ceremonies for victims</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contractor_Travel_Budget__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Travel_Budget__c</fullName>
    <label>Contractor Travel Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contracts_Budget__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Budget__c</fullName>
    <label>Contracts Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Fringe_Benefits_Budget__c.field-meta.xml
<CustomField>
    <fullName>Fringe_Benefits_Budget__c</fullName>
    <label>Fringe Benefits Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <formula
  >IF(CONTAINS(RecordType.Name, &apos;GREAT&apos;), &quot;I&apos;m GREAT&quot;,
IF(CONTAINS(RecordType.Name, &apos;Baseball&apos;), &apos;Badges for Baseball&apos;, 
IF(CONTAINS(RecordType.Name, &apos;Special Initiative&apos;), &apos;Special Initiative&apos;,
IF(CONTAINS(RecordType.Name, &apos;Healthy Lifestyles&apos;), &apos;Healthy Lifestyles&apos;,
IF(CONTAINS(RecordType.Name, &apos;TRAIL&apos;), &apos;TRAIL&apos;,
IF(CONTAINS(RecordType.Name, &apos;OVC&apos;), &apos;OVC&apos;,
IF(CONTAINS(RecordType.Name, &apos;SOI&apos;), &apos;SOI&apos;,
&apos;&apos;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Indirect_Costs_Budget__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Costs_Budget__c</fullName>
    <label>Indirect Costs Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <label>National Organization Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Other_Costs_Budget__c.field-meta.xml
<CustomField>
    <fullName>Other_Costs_Budget__c</fullName>
    <label>Other Costs Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Personnel_Budget__c.field-meta.xml
<CustomField>
    <fullName>Personnel_Budget__c</fullName>
    <label>Personnel Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Support_Received__c.field-meta.xml
<CustomField>
    <fullName>Previous_Support_Received__c</fullName>
    <label>Previous Support Received</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Supplies_Budget__c.field-meta.xml
<CustomField>
    <fullName>Supplies_Budget__c</fullName>
    <label>Supplies Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Total_Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Requested__c</fullName>
    <label>Total Amount Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Travel_Budget__c.field-meta.xml
<CustomField>
    <fullName>Travel_Budget__c</fullName>
    <label>Travel Budget</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Challenge</fullName>
                <default>true</default>
                <label>Challenge</label>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicApplicationCtrl.cls
public without sharing class PublicApplicationCtrl {
  private FieldLabelClass flc = new FieldLabelClass();
  private AccountClass acctClass = new AccountClass();
  private ApplicationClass appClass = new ApplicationClass();
  private SchemaPicklistFields spf = new SchemaPicklistFields();

  public Map<String, String> fields { get; set; }
  public String appType { get; set; }
  public Application__c app { get; set; }
  public String title { get; set; }

  public List<SelectOption> serviceOptions {
    get {
      return spf.getPicklistOptions(
        'Application__c',
        'Areas_of_Service__c',
        null
      );
    }
    set;
  }
  public String[] services {
    get {
      String[] selected = new List<String>();
      List<SelectOption> sos = this.serviceOptions;
      for (SelectOption s : sos) {
        if (
          this.app.Areas_of_Service__c != null &&
          this.app.Areas_of_Service__c.contains(s.getValue())
        )
          selected.add(s.getValue());
      }
      return selected;
    }
    public set {
      String selectedConcat = '';
      for (String s : value) {
        if (selectedConcat == '')
          selectedConcat += s;
        else
          selectedConcat += ';' + s;
      }
      app.Areas_of_Service__c = selectedConcat;
    }
  }

  Date dt = date.today();
  public Boolean showSuccess { get; set; }
  public String errorMessage { get; set; }

  public PublicApplicationCtrl() {
    fields = new Map<String, String>();
    app = new Application__c();
    app.Previous_Support_Received__c = 'No';
  }

  public void setOVCAppType() {
    app.National_Organization_Id__c = '0013600001Pxcii';
    app.RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName()
      .get('NCAI - OVC')
      .getRecordTypeId();
    app.Grant_Year__c = '2021 - 2022';
    fields = flc.getFieldLabelMap(
      'Application__c',
      app.Grant_Type__c,
      app.Type__c,
      ' AND Year__c includes (\'' +
      app.Grant_Year__c +
      '\')'
    );
  }
  // END getFields

  // BEGIN getTotal
  public void getTotal() {
    Decimal total = 0;
    if (app.Personnel_Budget__c != null) {
      total += app.Personnel_Budget__c;
    }
    if (app.Fringe_Benefits_Budget__c != null) {
      total += app.Fringe_Benefits_Budget__c;
    }
    if (app.Travel_Budget__c != null) {
      total += app.Travel_Budget__c;
    }
    if (app.Supplies_Budget__c != null) {
      total += app.Supplies_Budget__c;
    }
    if (app.Contracts_Budget__c != null) {
      total += app.Contracts_Budget__c;
    }
    if (app.Contractor_Travel_Budget__c != null) {
      total += app.Contractor_Travel_Budget__c;
    }
    if (app.Other_Costs_Budget__c != null) {
      total += app.Other_Costs_Budget__c;
    }
    if (app.Indirect_Costs_Budget__c != null) {
      total += app.Indirect_Costs_Budget__c;
    }
    app.Total_Amount_Requested__c = total;
  }
  // END getTotal

  // BEGIN submit
  public void submit() {
    app.Status__c = 'Submitted';
    app.Submitted_Date__c = date.today();
    getTotal();
    appClass.upsertApplication(app);

    if (ApexPages.hasMessages())
      errorMessage += string.valueOf(ApexPages.getMessages());
    else
      showSuccess = true;
  }
  // END submit
}