force-app/main/default/objects/Account/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName
        >Currently Implementing Site Proposing To Continue</fullName>
                <label>Currently Implementing Site Proposing To Continue</label>
            </value>
            <value>
                <fullName>Currently Implementing Site Not Continuing</fullName>
            </value>
            <value>
                <fullName
        >Not Currently Implementing Site Proposing to Reinstate</fullName>
                <label
        >Not Currently Implementing Site Proposing to Reinstate</label>
            </value>
            <value>
                <fullName>Not Currently Implementing Site</fullName>
            </value>
            <value>
                <fullName>New Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Coaches__c.field-meta.xml
<CustomField>
    <fullName>Coaches__c</fullName>
    <label>Coaches</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Date_of_Expo__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Expo__c</fullName>
    <label>Estimated Date of Expo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Date_of_Project__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Project__c</fullName>
    <label>Estimated Date of Project</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Implementation_Model__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Model__c</fullName>
    <label>Implementation Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Twice a Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/New_DUNS_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>New_DUNS_Exp_Date__c</fullName>
    <label>New DUNS Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_8_13_Year_Olds_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Number_of_8_13_Year_Olds_Enrolled__c</fullName>
    <label>Number of 8-13 Year Olds Enrolled</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Teens_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Teens_Enrolled__c</fullName>
    <label>Number of Teens Enrolled</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive - Did Not Complete Program</fullName>
            </value>
            <value>
                <fullName>Inactive - Successfully Completed Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK( Birthdate ) ) , 
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), 
YEAR (Today()) - YEAR ( Birthdate ), 
YEAR (Today()) - YEAR ( Birthdate ) -1 ), 
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Not specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_Guardian__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent/Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Parents_Guardians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_Guardian_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_Name__c</fullName>
    <label>Parent/Guardian Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>School Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Youth_ID_Number__c</fullName>
    <label>Youth ID  Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <label>Coach</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/listViews/Youth.recordType-meta.xml
<RecordType>
    <fullName>Youth</fullName>
    <active>true</active>
    <label>Youth</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Coaches__c.field-meta.xml
<CustomField>
    <fullName>Coaches__c</fullName>
    <label>Coaches</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Cohort_Size__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Size__c</fullName>
    <label>Cohort Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Estimated_Date_of_Expo__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Expo__c</fullName>
    <label>Estimated Date of Expo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/AboutCtrl.cls
public with sharing class AboutCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public String profileName { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public Account acct { get; set; }
  public String portalName { get; set; }

  public AccountClass accountClass = new AccountClass();
  public ContactClass contactClass = new ContactClass();
  public Id SessionId { get; set; }
  public List<SelectOption> options { get; set; }
  public Id SiteId = ApexPages.currentPage().getParameters().get('SiteId');

  public Contact newContact { get; set; }
  public List<Contact> contact_list { get; set; }
  public Id selectedContactId { get; set; }
  public Contact selectedContact { get; set; }
  public List<SelectOption> profiles { get; set; }

  public Id YouthId { get; set; }
  public Contact youth { get; set; }
  public List<Contact> youth_list { get; set; }

  public Id CohortId { get; set; }
  public Session__c session { get; set; }
  public List<Session__c> cohort_list { get; set; }
  public Set<Id> cohortId_set { get; set; }
  public Session__c newCohort { get; set; }

  public Date startDate { get; set; }
  public Date expoDate { get; set; }
  public Date dunsExpDate { get; set; }

  public List<SelectOption> coaches { get; set; }
  public List<SelectOption> models { get; set; }

  public Boolean displayEditOrgPopup { get; set; }
  public Boolean displayEditAddressPopup { get; set; }
  public Boolean displayAddContactPopup { get; set; }
  public Boolean displayEditContactPopup { get; set; }
  public Boolean displayAddCohortPopup { get; set; }
  public Boolean displayDeleteYouthPopup { get; set; }
  public Boolean displayDeleteContactPopup { get; set; }

  public string errorMessage { get; set; }

  public ID coachRt = Schema.SObjectType.Contact.getRecordTypeInfosByName()
    .get('Coach')
    .getRecordTypeId();
  public ID cohortRt = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
    .get('Cohort')
    .getRecordTypeId();

  public AboutCtrl() {
    currentUser = userClass.currentUser;
    profileName = currentUser.Profile.Name;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;

    newContact = new Contact();
    youth = new Contact();
    selectedContact = new Contact();

    session = new Session__c();
    newCohort = new Session__c();
    newCohort.RecordTypeId = cohortRt;

    errorMessage = '';

    models = new List<SelectOption>();
    coaches = new List<SelectOption>();
    contact_list = new List<Contact>();
    youth_list = new List<Contact>();
    cohortId_set = new Set<Id>();
    cohort_list = new List<Session__c>();

    displayEditAddressPopup = false;
    displayAddContactPopup = false;
    displayEditContactPopup = false;
    displayAddCohortPopup = false;

    acct = new Account();
    if (SiteId != null) {
      acct = accountClass.getAccount(SiteId);
    } else if (userAcct != null) {
      acct = accountClass.getAccount(userAcct.Id);
    }
    expoDate = acct.Estimated_Date_of_Expo__c;
    dunsExpDate = acct.Estimated_Date_of_Project__c;

    if (portalName == 'LEGO') {
      Schema.DescribeFieldResult fieldResult = Account.Implementation_Model__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      for (Schema.PicklistEntry f : ple) {
        models.add(new SelectOption(f.getLabel(), f.getValue()));
      }

      SessionSelectOptionsCtrl ssoc = new SessionSelectOptionsCtrl();
      options = ssoc.options;

      String sId = ApexPages.currentPage().getParameters().get('SessionId');
      system.debug('sId = ' + sId);
      if ((sId == null || sId == '') && options.size() == 2) {
        String i = options[1].getValue();
        sId = Id.valueOf(i);
      }
      if (sId != null && sId != '')
        SessionId = sId;
      else
        SessionId = ssoc.sessionId;
    } else {
      profiles = new List<SelectOption>();
      profiles.add(new SelectOption('', '-- Select a Profile --'));
      if (userAcctType == 'Local Organization') {
        profiles.add(new SelectOption('Program Admin', 'Program Admin'));
        profiles.add(new SelectOption('All Access', 'All Access'));
      }
      if (userAcctType == 'National Organization') {
        profiles.add(new SelectOption('Level One', 'Level One'));
        profiles.add(new SelectOption('Level Two', 'Level Two'));
        profiles.add(new SelectOption('Level Three', 'Level Three'));
        profiles.add(new SelectOption('Treasurer', 'Treasurer'));
        profiles.add(new SelectOption('Report Builder', 'Report Builder'));
        profiles.add(new SelectOption('Read Only', 'Read Only'));
      }
      profiles.add(new SelectOption('Inactive User', 'Inactive User'));
    }
  }

  public void init() {
    cohort_list.clear();

    if (SessionId != null) {
      Session__c[] sessions = [
        SELECT Id, Name, Start_Date__c
        FROM Session__c
        WHERE Id = :SessionId
      ];
      if (sessions.size() > 0) {
        session = sessions[0];
        startDate = sessions[0].Start_Date__c;
      }

      for (Session__c s : [
        SELECT Id, Name, Coaches__c, Cohort_Size__c, Session__c
        FROM Session__c
        WHERE
          RecordType.Name = 'Cohort'
          AND Site__c = :acct.Id
          AND Session__c = :session.Id
      ]) {
        cohortId_set.add(s.Id);
        cohort_list.add(s);
      }
    }
    if (
      SessionId != null ||
      portalName == 'NPAL' ||
      portalName == 'DMV' ||
      portalName == 'MDGO'
    ) {
      getContactList();
      getYouthList();
    }
  }

  public void getContactList() {
    contact_list.clear();
    coaches.clear();

    for (Contact c : [
      SELECT
        Name,
        AccountId,
        RecordType.Name,
        Active_Status__c,
        FirstName,
        LastName,
        Email,
        Phone,
        Role__c
      FROM Contact
      WHERE AccountId = :acct.Id
    ]) {
      if (portalName == 'LEGO') {
        if (c.RecordType.Name == 'Coach') {
          contact_list.add(c);
          coaches.add(new SelectOption(c.Name, c.Name));
        }
      } else if (c.RecordType.Name != 'Youth') {
        contact_list.add(c);
      }
    }
  }

  public void getYouthList() {
    youth_list.clear();

    for (Contact c : [
      SELECT
        Id,
        AccountId,
        FirstName,
        LastName,
        Youth_ID_Number__c,
        Active_Status__c,
        Cohort__r.Session__c,
        Cohort__r.Name,
        Parent_Guardian__r.Name,
        Parent_Guardian_Name__c,
        Birthdate,
        Grade_Level__c,
        Gender__c,
        Age__c,
        School_Name__c
      FROM Contact
      WHERE AccountId = :acct.Id AND RecordType.Name = 'Youth'
      ORDER BY Name
      LIMIT 100
    ]) {
      if (portalName == 'LEGO') {
        //if(c.Parent_Guardian__r.AccountId == acct.Id || c.AccountId == acct.Id || cohortId_set.contains(c.AccountId)) {
        if (
          c.Cohort__r.Session__c == SessionId ||
          cohortId_set.contains(c.AccountId)
        ) {
          youth_list.add(c);
        }
      } else {
        youth_list.add(c);
      }
    }

    Decimal totalEnrolled = 0;
    Decimal youth = 0;
    Decimal teens = 0;
    for (Contact c : youth_list) {
      if (c.Active_Status__c == 'Active') {
        totalEnrolled += 1;
        if (c.Age__c >= 8 && c.Age__c <= 13) {
          youth += 1;
        }
        if (c.Age__c > 13) {
          teens += 1;
        }
      }
    }
    //acct.Youth_Served__c = totalEnrolled;
    acct.Number_of_8_13_Year_Olds_Enrolled__c = youth;
    acct.Number_of_Teens_Enrolled__c = teens;
  }

  public PageReference updateOrg() {
    if (expoDate != null)
      acct.Estimated_Date_of_Expo__c = expoDate;
    if (dunsExpDate != null)
      acct.New_DUNS_Exp_Date__c = dunsExpDate;
    if (startDate != null)
      session.Start_Date__c = startDate;
    try {
      accountClass.upsertAccount(acct);
      update session;
    } catch (Exception e) {
      system.debug(e.getMessage());
      errorMessage = e.getMessage();
    }

    PageReference pr = new PageReference('/' + portalName + 'About');
    pr.setRedirect(true);
    return pr;
  }

  public void addContact() {
    if (newContact.LastName != null & newContact.Email != null) {
      newContact.AccountId = acct.Id;
      if (portalName == 'LEGO') {
        newContact.RecordTypeId = coachRt;
      }
      try {
        contactClass.upsertContact(newContact);
        contact_list.add(newContact);
        displayAddContactPopup = false;
        newContact = new Contact();
      } catch (Exception e) {
        system.debug(e.getMessage());
        errorMessage = e.getMessage();
      }
    } else if (newContact.LastName == null) {
      errorMessage = 'Last name is required';
    } else if (newContact.Email == null) {
      errorMessage = 'Email is required';
    }
  }

  public void updateContacts() {
    errorMessage = '';
    for (Contact c : contact_list) {
      if (c.LastName == null) {
        errorMessage = 'Last name is required';
      } else if (c.Email == null) {
        errorMessage = 'Email is required';
      }
      if (c.Id == null)
        c.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
          .get('Contact')
          .getRecordTypeId();
    }
    system.debug('>>> errorMessage = ' + errorMessage);
    if (errorMessage == '') {
      try {
        contactClass.upsertContactList(contact_list);
        displayEditContactPopup = false;
      } catch (Exception e) {
        system.debug(e.getMessage());
        errorMessage = e.getMessage();
      }
    }
  }

  public void deleteContact() {
    if (selectedContact.Id != null) {
      contactClass.deleteContact(selectedContact);
      displayDeleteContactPopup = false;
      init();
    }
  }

  public void deleteYouth() {
    if (youth.Id != null) {
      try {
        contactClass.deleteContact(youth);
        displayDeleteYouthPopup = false;
        getYouthList();
      } catch (Exception e) {
        system.debug(e.getMessage());
      }
    }
  }

  public void addCohort() {
    if (newCohort.Name != null) {
      if (newCohort.Coaches__c != null) {
        String c = newCohort.Coaches__c;
        c = c.replace('[', '');
        c = c.replace(']', '');
        newCohort.Coaches__c = c;
      }
      newCohort.Site__c = acct.Id;
      newCohort.Session__c = session.Id;
      try {
        upsert newCohort;
        cohort_list.add(newCohort);
        displayAddCohortPopup = false;

        newCohort = new Session__c();
        newCohort.RecordTypeId = cohortRt;
        newCohort.Site__c = acct.Id;
        newCohort.Session__c = session.Id;
      } catch (Exception e) {
        system.debug(e.getMessage());
        errorMessage = e.getMessage();
      }
    }
  }

  // BEGIN Popups
  public void editOrgPopup() {
    if (displayEditOrgPopup == true) {
      displayEditOrgPopup = false;
    } else {
      displayEditOrgPopup = true;
    }
  }

  public void showEditAddressPopup() {
    displayEditAddressPopup = true;
  }
  public void hideEditAddressPopup() {
    displayEditAddressPopup = false;
  }

  public void addContactPopup() {
    displayAddContactPopup = true;
  }

  public void cancelAddContactPopup() {
    newContact = new Contact();
    displayAddContactPopup = false;
  }

  public void editContactPopup() {
    if (displayEditContactPopup == true) {
      displayEditContactPopup = false;
    } else {
      displayEditContactPopup = true;
    }
  }

  public void cancelEditContactPopup() {
    getContactList();
    displayEditContactPopup = false;
  }

  public void deleteContactPopup() {
    if (selectedContactId != null) {
      Contact[] contacts = [
        SELECT Id, Name
        FROM Contact
        WHERE Id = :selectedContactId
      ];
      if (contacts.size() > 0) {
        selectedContact = contacts[0];
        displayDeleteContactPopup = true;
      }
    }
  }
  public void cancelDeleteContactPopup() {
    displayDeleteContactPopup = false;
  }

  public void addCohortPopup() {
    if (displayAddCohortPopup == true) {
      displayAddCohortPopup = false;
    } else {
      displayAddCohortPopup = true;
    }
  }

  public void deleteYouthPopup() {
    if (displayDeleteYouthPopup == true) {
      displayDeleteYouthPopup = false;
    } else {
      if (YouthId != null) {
        Contact[] youths = [SELECT Id, Name FROM Contact WHERE Id = :YouthId];
        if (youths.size() > 0) {
          youth = youths[0];
          //youthName = youths[0].Name;
        }
      }
      displayDeleteYouthPopup = true;
    }
  }
}