force-app/main/default/objects/Account/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName
        >Currently Implementing Site Proposing To Continue</fullName>
                <label>Currently Implementing Site Proposing To Continue</label>
            </value>
            <value>
                <fullName>Currently Implementing Site Not Continuing</fullName>
            </value>
            <value>
                <fullName
        >Not Currently Implementing Site Proposing to Reinstate</fullName>
                <label
        >Not Currently Implementing Site Proposing to Reinstate</label>
            </value>
            <value>
                <fullName>Not Currently Implementing Site</fullName>
            </value>
            <value>
                <fullName>New Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Active_Date__c</fullName>
    <label>Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive - Did Not Complete Program</fullName>
            </value>
            <value>
                <fullName>Inactive - Successfully Completed Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Ethnicity__c</fullName>
    <label>Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hispanic/Latino/Latina</fullName>
            </value>
            <value>
                <fullName>Not Hispanic/Latino/Latina</fullName>
            </value>
            <value>
                <fullName>Prefer not to provide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exited_Date__c.field-meta.xml
<CustomField>
    <fullName>Exited_Date__c</fullName>
    <label>Exited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_Guardian_is_Active_Military__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_is_Active_Military__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent/Guardian is Active Military</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_is_Currently_Incarcerated__c.field-meta.xml
<CustomField>
    <fullName>Parent_is_Currently_Incarcerated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent is Currently Incarcerated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Specified</fullName>
            </value>
            <value>
                <fullName>American Indian or Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black or African American</fullName>
            </value>
            <value>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </value>
            <value>
                <fullName>White or Caucasian</fullName>
            </value>
            <value>
                <fullName>Multi Racial</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prefer not to provide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/listViews/Youth.recordType-meta.xml
<RecordType>
    <fullName>Youth</fullName>
    <active>true</active>
    <label>Youth</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Have_Youth_Offended__c.field-meta.xml
<CustomField>
    <fullName>Have_Youth_Offended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have Youth Offended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Match_Closed_Early__c.field-meta.xml
<CustomField>
    <fullName>Match_Closed_Early__c</fullName>
    <label>Match Closed Early</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Match_Exceeded_Minimum_Match_Length__c.field-meta.xml
<CustomField>
    <fullName>Match_Exceeded_Minimum_Match_Length__c</fullName>
    <label>Match Exceeded Minimum Match Length</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Match_Met_Minimum_Match_Length__c.field-meta.xml
<CustomField>
    <fullName>Match_Met_Minimum_Match_Length__c</fullName>
    <label>Match Met Minimum Match Length</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Mentoring_Programs_Operated__c.field-meta.xml
<CustomField>
    <fullName>Mentoring_Programs_Operated__c</fullName>
    <label>Mentoring Programs Operated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/New_Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>New_Youth_Served__c</fullName>
    <label>New Youth Served</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Previous_Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Previous_Youth_Served__c</fullName>
    <label>Previous Youth Served</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Programs_with_Active_Partners__c.field-meta.xml
<CustomField>
    <fullName>Programs_with_Active_Partners__c</fullName>
    <label>Programs with Active Partners</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Report_Status__c</fullName>
    <label>Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <label>Reporting Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017 Q2</fullName>
            </value>
            <value>
                <fullName>2017 Q3</fullName>
            </value>
            <value>
                <fullName>2017 Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>GranteeReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Total_Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Total_Youth_Served__c</fullName>
    <formula
  >VALUE(Previous_Youth_Served__c) + VALUE(New_Youth_Served__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Completed_Program__c.field-meta.xml
<CustomField>
    <fullName>Youth_Completed_Program__c</fullName>
    <label>Youth Completed Program</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Exited_Program__c.field-meta.xml
<CustomField>
    <fullName>Youth_Exited_Program__c</fullName>
    <label>Youth Exited Program</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Identify_as_Native_American__c.field-meta.xml
<CustomField>
    <fullName>Youth_Identify_as_Native_American__c</fullName>
    <label>Youth Identify as Native American</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Received_Additional_Sentence__c.field-meta.xml
<CustomField>
    <fullName>Youth_Received_Additional_Sentence__c</fullName>
    <label>Youth Received Additional Sentence</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Recommitted_to_Juvenile_Facility__c.field-meta.xml
<CustomField>
    <fullName>Youth_Recommitted_to_Juvenile_Facility__c</fullName>
    <label>Youth Recommitted to Juvenile Facility</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Sentenced_to_Adult_Prison__c.field-meta.xml
<CustomField>
    <fullName>Youth_Sentenced_to_Adult_Prison__c</fullName>
    <label>Youth Sentenced to Adult Prison</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Served_via_Evidence_Based_Program__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_via_Evidence_Based_Program__c</fullName>
    <label>Youth Served via Evidence-Based Program</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_Tracked_for_Juvenile_Offenses__c.field-meta.xml
<CustomField>
    <fullName>Youth_Tracked_for_Juvenile_Offenses__c</fullName>
    <label>Youth Tracked for Juvenile Offenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_with_Delinquent_Offenses__c.field-meta.xml
<CustomField>
    <fullName>Youth_with_Delinquent_Offenses__c</fullName>
    <label>Youth with Delinquent Offenses</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_with_Incarcerate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Youth_with_Incarcerate_Parent__c</fullName>
    <label>Youth with Incarcerated Parent</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_with_Parents_Actively_Serving__c.field-meta.xml
<CustomField>
    <fullName>Youth_with_Parents_Actively_Serving__c</fullName>
    <label>Youth with Parents Actively Serving</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Youth_with_Social_Support_Mentoring__c.field-meta.xml
<CustomField>
    <fullName>Youth_with_Social_Support_Mentoring__c</fullName>
    <label>Youth with Social Support Mentoring</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GranteeReportController.cls
public with sharing class GranteeReportController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  public DCTATReportClass reportClass = new DCTATReportClass();

  public Account acct { get; set; }
  public ID GrantID { get; set; }
  public ID ReportID { get; set; }
  public Grant__c grant { get; set; }
  public Grantee_Report__c report { get; set; }

  public Decimal currentPage { get; set; }
  public Decimal totalYouthServed { get; set; }
  public Decimal youthAdded { get; set; }
  public Decimal youthCompleted { get; set; }
  public Decimal youthExited { get; set; }
  public Decimal matchLength8 { get; set; }
  public Decimal matchLengthMoreThan8 { get; set; }
  public Decimal matchLengthLessThan8 { get; set; }
  public Decimal parentsMilitary { get; set; }
  public Decimal parentsIncarcerated { get; set; }
  public Decimal nativeAmerican { get; set; }

  public Attachment att { get; set; }
  public List<Attachment> att_list { get; set; }
  public Id deleteAttId { get; set; }
  public Boolean displayAttPopup { get; set; }
  public Boolean displaySendBackPopup { get; set; }

  public Date dt = date.today();
  public String fdt = dt.format();
  public Date startDate { get; set; }
  public Date endDate { get; set; }
  public String errorMessage { get; set; }

  public GranteeReportController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;

    GrantID = ApexPages.currentPage().getParameters().get('GrantId');
    ReportID = ApexPages.currentPage().getParameters().get('ReportID');
    String PageId = ApexPages.currentPage().getParameters().get('currentPage');
    if (PageId != null) {
      currentPage = Integer.valueOf(PageId);
    } else {
      currentPage = 0;
    }
    errorMessage = '';

    report = new Grantee_Report__c();
    grant = new Grant__c();
    acct = new Account();

    att = new Attachment();
    att_list = new List<Attachment>();

    totalYouthServed = 0;
    youthAdded = 0;
    youthCompleted = 0;
    youthExited = 0;
    matchLength8 = 0;
    matchLengthMoreThan8 = 0;
    matchLengthLessThan8 = 0;

    parentsMilitary = 0;
    parentsIncarcerated = 0;
    nativeAmerican = 0;

    if (ReportID != null) {
      report = reportClass.getReport(ReportId);
      grant = [
        SELECT
          ID,
          Account__r.Id,
          Account__r.Name,
          RecordType.Name,
          Name,
          Youth_Served__c,
          Start_Date__c,
          End_Date__c
        FROM Grant__c
        WHERE ID = :report.Grant__c
      ];
      GrantId = grant.Id;
      startDate = report.Start_Date__c;
      endDate = report.End_Date__c;
    } else if (GrantID != null) {
      grant = [
        SELECT
          ID,
          Account__r.Id,
          Account__r.Name,
          RecordType.Name,
          Name,
          Youth_Served__c
        FROM Grant__c
        WHERE ID = :GrantID
      ];
    }
    for (Attachment a : report.Attachments) {
      att_list.add(a);
    }
    acct = [
      SELECT ID, Name, Youth_Served__c, RecordType.Name
      FROM Account
      WHERE ID = :grant.Account__r.Id
    ];

    getTotals();
    getTotalYouthServerd();
    errorCheck();
  }

  public ApexPages.PageReference init() {
    if ((ReportID == null || report == null) && GrantID == null) {
      PageReference pr = new PageReference('/ReportList');
      pr.setRedirect(true);
      return pr;
    }
    /*
        if(userAcctType == 'Local Organization' && grant.Account__c != userAcct.Id){
            PageReference pr = new PageReference('/Error');
            pr.setRedirect(true);
            return pr;
        }
        */
    return null;
  }

  public void getTotals() {
    for (Contact c : [
      SELECT
        Name,
        AccountId,
        Active_Status__c,
        Active_Date__c,
        Exited_Date__c,
        Parent_Guardian_is_Active_Military__c,
        Parent_is_Currently_Incarcerated__c,
        Ethnicity__c,
        Race__c
      FROM Contact
      WHERE AccountId = :acct.Id AND RecordType.Name = 'Youth'
      ORDER BY Name
    ]) {
      if (
        report.Start_Date__c != null &&
        report.End_Date__c != null &&
        c.Active_Date__c != null
      ) {
        if (
          c.Active_Date__c >= report.Start_Date__c &&
          c.Active_Date__c <= report.End_Date__c
        ) {
          youthAdded++;
        }
        if (
          c.Exited_Date__c != null &&
          c.Exited_Date__c >= report.Start_Date__c &&
          c.Exited_Date__c <= report.End_Date__c
        ) {
          youthExited++;
          if (
            c.Active_Status__c == 'Inactive - Successfully Completed Program'
          ) {
            youthCompleted++;
          }
          if (
            c.Exited_Date__c >= c.Active_Date__c.addDays(+224) &&
            c.Exited_Date__c <= c.Active_Date__c.addDays(+252)
          ) {
            matchLength8++;
          } else if (c.Exited_Date__c > c.Active_Date__c.addDays(+252)) {
            matchLengthMoreThan8++;
          } else if (c.Exited_Date__c < c.Active_Date__c.addDays(+224)) {
            matchLengthLessThan8++;
          }
        } else if (c.Exited_Date__c == null) {
          if (
            report.End_Date__c >= c.Active_Date__c.addDays(+224) &&
            report.End_Date__c <= c.Active_Date__c.addDays(+252)
          ) {
            matchLength8++;
          } else if (report.End_Date__c > c.Active_Date__c.addDays(+252)) {
            matchLengthMoreThan8++;
          }
        }
      }
      if (c.Parent_Guardian_is_Active_Military__c) {
        parentsMilitary++;
      }
      if (c.Parent_is_Currently_Incarcerated__c) {
        parentsIncarcerated++;
      }
      if (c.Race__c == 'American Indian or Alaska Native') {
        nativeAmerican++;
      }
    }
    system.debug('matchLength8 = ' + matchLength8);
    system.debug('matchLengthMoreThan8 = ' + matchLengthMoreThan8);
    system.debug('matchLengthLessThan8 = ' + matchLengthLessThan8);

    String period = '';
    String year = '';
    String previousPeriod = '';
    if (report.Reporting_Period__c != null) {
      period = report.Reporting_Period__c;
      year = period.substring(0, 4);
      previousPeriod = year + ' Q2';
    }
    if (period.contains('Q3') || period.contains('Q4')) {
      Grantee_Report__c[] previous = [
        SELECT ID, Total_Youth_Served__c, Youth_Exited_Program__c
        FROM Grantee_Report__c
        WHERE
          Grant__c = :report.Grant__c
          AND Reporting_Period__c = :previousPeriod
      ];
      if (previous.size() > 0) {
        report.Previous_Youth_Served__c = String.valueOf(
          previous[0].Total_Youth_Served__c
        );
        if (previous[0].Youth_Exited_Program__c != null)
          report.Previous_Youth_Served__c = String.valueOf(
            previous[0].Total_Youth_Served__c -
            Integer.valueOf(previous[0].Youth_Exited_Program__c)
          );
      }
    }
    if (report.New_Youth_Served__c == null && youthAdded > 0) {
      report.New_Youth_Served__c = String.valueOf(youthAdded);
    }
    if (report.Youth_Exited_Program__c == null && youthExited > 0) {
      report.Youth_Exited_Program__c = String.valueOf(youthExited);
    }
    if (report.Youth_Completed_Program__c == null && youthCompleted > 0) {
      report.Youth_Completed_Program__c = String.valueOf(youthCompleted);
    }

    if (report.Match_Met_Minimum_Match_Length__c == null && matchLength8 > 0) {
      report.Match_Met_Minimum_Match_Length__c = matchLength8;
    }
    if (
      report.Match_Exceeded_Minimum_Match_Length__c == null &&
      matchLengthMoreThan8 > 0
    ) {
      report.Match_Exceeded_Minimum_Match_Length__c = matchLengthMoreThan8;
    }
    if (report.Match_Closed_Early__c == null && matchLengthLessThan8 > 0) {
      report.Match_Closed_Early__c = matchLengthLessThan8;
    }

    if (report.Youth_with_Parents_Actively_Serving__c == null) {
      report.Youth_with_Parents_Actively_Serving__c = String.valueOf(
        parentsMilitary
      );
    }
    if (report.Youth_with_Incarcerate_Parent__c == null) {
      report.Youth_with_Incarcerate_Parent__c = String.valueOf(
        parentsIncarcerated
      );
    }
    if (report.Youth_Identify_as_Native_American__c == null) {
      report.Youth_Identify_as_Native_American__c = nativeAmerican;
    }

    if (
      report.Youth_with_Delinquent_Offenses__c == null ||
      report.Youth_Recommitted_to_Juvenile_Facility__c == null ||
      report.Youth_Sentenced_to_Adult_Prison__c == null ||
      report.Youth_Received_Additional_Sentence__c == null
    ) {
      report.Have_Youth_Offended__c = false;
    }
  }

  public void getTotalYouthServerd() {
    //report.New_Youth_Served__c = youthAdded;
    if (
      report.Previous_Youth_Served__c != null &&
      report.New_Youth_Served__c != null
    ) {
      totalYouthServed =
        Integer.valueOf(report.Previous_Youth_Served__c) +
        Integer.valueOf(report.New_Youth_Served__c);
    }
    system.debug('>>> totalYouthServed = ' + totalYouthServed);
    report.Youth_Served_via_Evidence_Based_Program__c = totalYouthServed;
    report.Youth_with_Social_Support_Mentoring__c = totalYouthServed;
    report.Youth_Tracked_for_Juvenile_Offenses__c = totalYouthServed;
  }

  public void resetOutputs() {
    report.New_Youth_Served__c = String.valueOf(youthAdded);
    report.Youth_Exited_Program__c = String.valueOf(youthExited);
    report.Youth_Completed_Program__c = String.valueOf(youthCompleted);
    report.Youth_with_Parents_Actively_Serving__c = String.valueOf(
      parentsMilitary
    );
    report.Youth_with_Incarcerate_Parent__c = String.valueOf(
      parentsIncarcerated
    );
    report.Youth_Identify_as_Native_American__c = nativeAmerican;
  }

  public void resetMatchDetails() {
    report.Match_Met_Minimum_Match_Length__c = matchLength8;
    report.Match_Exceeded_Minimum_Match_Length__c = matchLengthMoreThan8;
    report.Match_Closed_Early__c = matchLengthLessThan8;
  }

  // BEGIN getAttList
  public void getAttList() {
    att_list.clear();
    Grantee_Report__c g = [
      SELECT
        Id,
        (
          SELECT Id, Name, Description
          FROM Attachments
          ORDER BY LastModifiedDate DESC
        )
      FROM Grantee_Report__c
      WHERE Id = :report.Id
    ];
    for (Attachment a : g.Attachments) {
      att_list.add(a);
    }
  }
  // END getAttList

  // BEGIN deleteAtt
  public void deleteAtt() {
    if (deleteAttId != null) {
      Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteAttId];
      if (a != null) {
        delete a;
      }
    }
    getAttList();
  }
  // END deleteAtt

  public PageReference previous() {
    //CurrentPage = CurrentPage - 1;
    PageReference pr = new PageReference(
      '/' +
      portalName +
      'GranteeReportForm?ReportId=' +
      report.Id +
      '&currentPage=' +
      (currentPage - 1)
    );
    pr.setRedirect(true);
    return pr;
  }

  public void errorCheck() {
    errorMessage = '';
    if (
      report.Programs_with_Active_Partners__c != null &&
      report.Mentoring_Programs_Operated__c != null &&
      Integer.valueOf(report.Programs_with_Active_Partners__c) >
      report.Mentoring_Programs_Operated__c
    ) {
      errorMessage = 'Outcomes 1A: Number of mentoring programs with active partners should not exceed number of mentoring programs.';
    }
  }

  public PageReference saveReport() {
    getTotals();
    getTotalYouthServerd();
    errorCheck();
    if (errorMessage == '') {
      if (report.Report_Status__c == null) {
        report.Report_Status__c = 'In Progress';
      }
      if (report.Grant__c == null && GrantId != null) {
        report.Grant__c = GrantId;
      }
      report.Start_Date__c = startDate;
      report.End_Date__c = endDate;

      try {
        reportClass.upsertReport(report);
        PageReference pr = new PageReference(
          '/' +
          portalName +
          'GranteeReportForm?ReportId=' +
          report.Id +
          '&currentPage=' +
          (currentPage + 1)
        );
        pr.setRedirect(true);
        return pr;
      } catch (Exception e) {
        errorMessage = e.getMessage();
        system.debug('error = ' + e.getMessage());
        return null;
      }
    }
    return null;
  }

  public PageReference submit() {
    report.Report_Status__c = 'Submitted';
    report.Submitted_Date__c = date.today();
    report.Submitted_By__c = currentUser.ContactID;

    String mh =
      fdt +
      ': Modification Submitted by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (report.Modification_History__c == null) {
      report.Modification_History__c = '';
    }
    report.Modification_History__c += ' \r\n' + mh;

    reportClass.upsertReport(report);

    PageReference pr = new PageReference('/' + portalName + 'ReportList');
    pr.setRedirect(true);
    return pr;
  }

  public PageReference sendBack() {
    report.Report_Status__c = 'Revisions Needed';

    String mh =
      fdt +
      ': Report Sent Back by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (report.Modification_History__c == null) {
      report.Modification_History__c = '';
    }
    report.Modification_History__c += ' \r\n' + mh;

    try {
      update report;
      system.debug('>>>> Report update successful. report = ' + report);
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
      return null;
    }

    PageReference pr = new PageReference('/' + portalName + 'ReportList');
    pr.setRedirect(true);
    return pr;
  }

  public PageReference approveReport() {
    report.Report_Status__c = 'Approved';
    report.Approved_Date__c = date.today();

    String mh =
      fdt +
      ': Report Approved by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (report.Modification_History__c == null) {
      report.Modification_History__c = '';
    }
    report.Modification_History__c += ' \r\n' + mh;

    try {
      update report;
      system.debug('>>>> Report update successful. report = ' + report);
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
      return null;
    }

    PageReference pr = new PageReference('/' + portalName + 'ReportList');
    pr.setRedirect(true);
    return pr;
  }

  public void attPopup() {
    getAttList();
    if (displayAttPopup == true) {
      displayAttPopup = false;
    } else {
      displayAttPopup = true;
    }
  }

  public void sendBackPopup() {
    if (displaySendBackPopup == true) {
      displaySendBackPopup = false;
    } else {
      displaySendBackPopup = true;
    }
  }
}