force-app/main/default/objects/Account/fields/Active_Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Grant_Status__c</fullName>
    <label>Active Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Previous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName
        >Currently Implementing Site Proposing To Continue</fullName>
                <label>Currently Implementing Site Proposing To Continue</label>
            </value>
            <value>
                <fullName>Currently Implementing Site Not Continuing</fullName>
            </value>
            <value>
                <fullName
        >Not Currently Implementing Site Proposing to Reinstate</fullName>
                <label
        >Not Currently Implementing Site Proposing to Reinstate</label>
            </value>
            <value>
                <fullName>Not Currently Implementing Site</fullName>
            </value>
            <value>
                <fullName>New Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BBBS_ID__c.field-meta.xml
<CustomField>
    <fullName>BBBS_ID__c</fullName>
    <label>BBBS ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Grant_Year__c</fullName>
    <label>Current Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Current_Status__c</fullName>
    <formula
  >IF(DUNS_Exp_Date__c &gt; TODAY(), &apos;Active&apos;, &apos;Expired&apos;)</formula>
    <label>DUNS Current Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grant_Year_Options__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year_Options__c</fullName>
    <label>Grant Year Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Date__c.field-meta.xml
<CustomField>
    <fullName>Hold_Date__c</fullName>
    <label>Hold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_History__c.field-meta.xml
<CustomField>
    <fullName>Hold_History__c</fullName>
    <label>Hold History</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Notes__c.field-meta.xml
<CustomField>
    <fullName>Hold_Notes__c</fullName>
    <label>Hold Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Reason__c.field-meta.xml
<CustomField>
    <fullName>Hold_Reason__c</fullName>
    <label>Hold Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SAM.gov Expired</fullName>
            </value>
            <value>
                <fullName>Current FYE Audit Past Due</fullName>
            </value>
            <value>
                <fullName>DOJ Certification Past Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <label>Hold Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Local_Organization__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grants__c.field-meta.xml
<CustomField>
    <fullName>National_Grants__c</fullName>
    <label>National Grants</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Primary Approver)</relationshipLabel>
    <relationshipName>Accounts_Primary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula
  >Primary_Approver__r.FirstName + &apos; &apos; + Primary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Secondary Approver)</relationshipLabel>
    <relationshipName>Accounts_Secondary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Approver_Name__c</fullName>
    <formula
  >Secondary_Approver__r.FirstName + &apos; &apos; + Secondary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive - Did Not Complete Program</fullName>
            </value>
            <value>
                <fullName>Inactive - Successfully Completed Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/AccountClass.cls
public without sharing class AccountClass {
  public String soql { get; set; }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Account.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    //expr = expr.removeEnd(', ');
    expr += 'RecordType.Name, Primary_Approver__r.Name, Secondary_Approver__r.Name, National_Organization__r.Grant_Year_Options__c, National_Organization__r.Current_Grant_Year__c';

    soql = 'SELECT ' + expr + ' FROM Account';
    return soql;
  }

  public Account getAccount(Id acctId) {
    getSOQL();
    Account acct = new Account();
    if (acctId != null) {
      soql += ' WHERE Id = \'' + acctId + '\'';
      Account[] accts = Database.query(soql);
      if (accts.size() > 0) {
        acct = accts[0];
      }
    }
    return acct;
  }

  public List<Account> getAccountList() {
    getSOQL();
    List<Account> account_list = new List<Account>();
    account_list = Database.query(soql);
    return account_list;
  }

  public List<Account> getRelatedAccountList(
    Id acctId,
    String userAcctType,
    String recordType,
    String keyword,
    String soqlAND
  ) {
    soql = 'SELECT Id, Name, RecordType.Name, Is_Active__c, Active_Status__c, Local_Organization__r.Name, Local_Organization_Id__c, Hold_Status__c, Hold_Reason__c, Hold_Date__c, Hold_History__c, DUNS_Current_Status__c ';
    soql += ', Primary_Approver__c, Primary_Approver_Name__c, Secondary_Approver__c, Secondary_Approver_Name__c, Primary_Approver_On_Leave__c, BBBS_Id__c, Active_Grant_Status__c FROM Account';
    if (userAcctType == 'National Organization') {
      soql +=
        ' WHERE (National_Organization__c = \'' +
        acctId +
        '\' OR Local_Organization__c = \'' +
        acctId +
        '\' OR Id = \'' +
        acctId +
        '\')';
    } else if (userAcctType == 'Local Organization') {
      soql +=
        ' WHERE (Local_Organization__c = \'' +
        acctId +
        '\' OR Id = \'' +
        acctId +
        '\')';
    } else {
      soql += ' WHERE Id = \'' + acctId + '\'';
    }
    if (recordType != null && recordType != '')
      soql += ' AND RecordType.Name = \'' + recordType + '\'';
    if (keyword != null && keyword != '')
      soql +=
        ' AND (Name LIKE \'%' +
        keyword +
        '%\' OR Local_Organization__r.Name LIKE \'%' +
        keyword +
        '%\')';
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    soql += ' ORDER BY Name';
    system.debug('Account soql = ' + soql);
    List<Account> accts = Database.query(soql);
    return accts;
  }

  public List<Account> getSiteList(Id localAcctId, String soqlAND) {
    soql = 'SELECT Id, Name, Active_Status__c, Is_Active__c FROM Account';
    soql += ' WHERE Local_Organization__c = \'' + localAcctId + '\'';
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    soql += ' ORDER BY Name';
    system.debug('Account getSiteList soql = ' + soql);
    List<Account> accts = Database.query(soql);
    return accts;
  }

  public List<SelectOption> getOrgOptions(
    Id acctId,
    String userAcctType,
    String userProfile
  ) {
    String soqlAND = '';
    if (userProfile.contains('TRAIL'))
      soqlAND = ' AND National_Grants__c INCLUDES (\'TRAIL\')';
    else if (userProfile.contains('OVC'))
      soqlAND = ' AND National_Grants__c INCLUDES (\'OVC\')';
    List<SelectOption> orgOptions = new List<SelectOption>();
    orgOptions.add(new SelectOption('', '-- Select a Site --'));
    for (
      Account a : getRelatedAccountList(acctId, userAcctType, '', '', soqlAND)
    ) {
      orgOptions.add(new SelectOption(a.Id, a.Name));
    }
    return orgOptions;
  }

  public void upsertAccount(Account acct) {
    try {
      upsert acct;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public void upsertAccounts(List<Account> accts) {
    try {
      upsert accts;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public String getHoldHistory(User currentUser, Account org) {
    Date dt = date.today();
    String fdt = dt.format();
    String mh = '<b>' + fdt + ':</b> Hold Status updated';
    if (currentUser != null)
      mh += ' by ' + currentUser.Contact.Name + ' (' + currentUser.Id + ')';
    else
      mh += ' by Auto-Hold';
    mh += '<br /> &nbsp;&nbsp;<b>Hold Status:</b> ';
    if (org.Hold_Status__c != null && org.Hold_Status__c != '')
      mh += org.Hold_Status__c;
    mh += '<br /> &nbsp;&nbsp;<b>Hold Reason:</b> ';
    if (org.Hold_Reason__c != null)
      mh += org.Hold_Reason__c;
    mh += '<br /> &nbsp;&nbsp;<b>Hold Notes:</b> ';
    if (org.Hold_Notes__c != null)
      mh += org.Hold_Notes__c;
    if (org.Hold_History__c == null)
      org.Hold_History__c = mh;
    else
      org.Hold_History__c = mh + '<hr />' + org.Hold_History__c;
    return org.Hold_History__c;
  }
}