force-app/main/default/objects/Account/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Names_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Names_of_Sites__c</fullName>
    <label>Names of Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Total Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sites__c</fullName>
    <label>Number of Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child Safety</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contract Specialists</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Other Costs</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Sub Awards</fullName>
            </value>
            <value>
                <fullName>Consultant Travel</fullName>
            </value>
            <value>
                <fullName>Indirect Costs</fullName>
            </value>
            <value>
                <fullName>Procurement Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <inlineHelpText>BBBSA only: 
if Factor Type = FTE, New Item Budget = New Rate * Estimated FTE (from Sub-Grant);
if Factor Type = TCS, New Item Budget = New Rate * Youth Served % (from Sub-Grant);
if Factor Type = Other, New Item Budget = New Rate * Other Factor %;</inlineHelpText>
    <label>Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTE</fullName>
            </value>
            <value>
                <fullName>TCS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description
  >If employee is salaried, hourly rate is calculated as follows: Salary divided by 2,080 = 40 hour/week Hourly Rate. See http://www.calculators.org/savings/wage-conversion.php.</description>
    <label>Hourly Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Hourly__c.field-meta.xml
<CustomField>
    <fullName>Is_Hourly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hourly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: Rate (hourly) * Projected Grant Hours * Number of Weeks (fringe not included);
All Other Personnel: Wages + Fringe Benefits
Expenses: Rate * Quantity</inlineHelpText>
    <label>Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Note__c.field-meta.xml
<CustomField>
    <fullName>Item_Note__c</fullName>
    <label>Item Note</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rate__c</fullName>
    <label>Monthly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>New_Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: New Rate (hourly) * Projected Grant Hours * Number of Weeks;
All Other Personnel: New Wages + New Fringe Benefits
Expenses: New Rate * Quantity</inlineHelpText>
    <label>New Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Rate__c</fullName>
    <label>New Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Other_Benefits__c</fullName>
    <label>Other Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Other_Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Other Factor Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Grant_Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Projected_Grant_Hours_Per_Week__c</fullName>
    <label>Projected Grant Hours Per Week</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Projected_Hours_Per_Week__c</fullName>
    <label>Projected Hours Per Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Percent_Time_on_Grant__c.field-meta.xml
<CustomField>
    <fullName>Projected_Percent_Time_on_Grant__c</fullName>
    <label>Projected Percent Time on Grant</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Estimated_FTE__c.field-meta.xml
<CustomField>
    <fullName>Estimated_FTE__c</fullName>
    <label>Estimated FTE</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Names_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Names_of_Sites__c</fullName>
    <label>Names of Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sites__c</fullName>
    <label>Number of Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/TestBudgetForms.cls
@isTest
public class TestBudgetForms {
  static testMethod void test() {
    Date dt = Date.today();

    ID rtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Local Organization')
      .getRecordTypeId();
    ID rtId2 = Schema.SObjectType.Budget_Item__c.getRecordTypeInfosByName()
      .get('Labor')
      .getRecordTypeId();
    ID rtId3 = Schema.SObjectType.Budget_Item__c.getRecordTypeInfosByName()
      .get('Expense')
      .getRecordTypeId();
    Account a = new Account(
      EIN__c = '98-7654321',
      Name = 'Name',
      Status__c = 'Application Submitted',
      Application_Submitted_Date__c = dt,
      Phone = '5555555555',
      BillingStreet = 'Street',
      BillingCity = 'City',
      BillingState = 'CA',
      BillingPostalCode = '12345',
      Youth_Served__c = 100,
      Number_of_Mentors__c = 10,
      Number_of_Sites__c = 10,
      Names_of_Sites__c = 'Names of Sites',
      RecordTypeId = rtId1
    );
    insert a;

    Grant__c ng = new Grant__c(
      Account__c = a.Id,
      Amount__c = 500000,
      End_Date__c = dt.addDays(600),
      Grant_Status__c = 'Approved',
      Name = 'name',
      Project_Description__c = 'National Grant',
      Project_Name__c = 'name',
      Start_Date__c = dt.addDays(-200)
    );
    insert ng;

    Grant__c g = new Grant__c(
      Account__c = a.Id,
      National_Grant__c = ng.Id,
      Amount__c = 500000,
      Grant_Status__c = 'Pending Review',
      Name = 'name',
      Project_Description__c = 'description test',
      Project_Name__c = 'name',
      Youth_Served__c = 100,
      Youth_Served_with_Grant_Funding__c = 50,
      Estimated_FTE__c = 200
    );
    insert g;

    Budget_Item__c bi1 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId2,
      Name = 'Test Item',
      Title__c = 'Test Title',
      Category__c = 'Test Cat',
      Selected__c = true,
      Is_Hourly__c = true,
      Hourly_Rate__c = 20,
      New_Item_Budget__c = 200,
      Projected_Grant_Hours_Per_Week__c = 30,
      Projected_Hours_Per_Week__c = 40,
      Projected_Percent_Time_on_Grant__c = .75,
      Medical__c = 100,
      Dental__c = 100,
      Short_Term_Disability__c = 100,
      SUTA__c = 100,
      Long_Term_Disability__c = 100,
      Other_Benefits__c = 100,
      Effective_Date__c = dt.addDays(-100),
      Factor_Type__c = 'TCS'
    );
    insert bi1;

    Budget_Item__c bi2 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId2,
      Name = 'Test Item',
      Category__c = 'Test Cat',
      Selected__c = false,
      Factor_Type__c = 'FTE',
      Monthly_Rate__c = 1000,
      New_Item_Budget__c = 4321,
      Projected_Grant_Hours_Per_Week__c = 30,
      Projected_Hours_Per_Week__c = 40,
      Projected_Percent_Time_on_Grant__c = .75,
      Medical__c = 100,
      Dental__c = 100,
      Short_Term_Disability__c = 100,
      SUTA__c = 100,
      Long_Term_Disability__c = 100,
      Other_Benefits__c = 100
    );
    insert bi2;

    Budget_Item__c bi3 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId2,
      Name = 'Benefits',
      Category__c = 'Test Cat',
      Selected__c = false,
      Item_Budget__c = 1234,
      New_Item_Budget__c = 200,
      Factor_Type__c = 'TCS',
      Monthly_Rate__c = 1000,
      Projected_Grant_Hours_Per_Week__c = 30,
      Projected_Hours_Per_Week__c = 40,
      Projected_Percent_Time_on_Grant__c = .75,
      Medical__c = 100,
      Dental__c = 100,
      Short_Term_Disability__c = 100,
      SUTA__c = 100,
      Long_Term_Disability__c = 100,
      Other_Benefits__c = 100
    );
    insert bi3;

    Budget_Item__c bi4 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId3,
      Name = 'Test Item',
      Category__c = 'Test Cat',
      Selected__c = false,
      New_Rate__c = 100,
      New_Item_Budget__c = 200,
      Factor_Type__c = 'TCS'
    );
    insert bi4;

    Budget_Item__c bi5 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId3,
      Name = 'Test Item',
      Selected__c = true,
      Category__c = 'Test Cat 2',
      Factor_Type__c = 'Other',
      Item_Note__c = 'test',
      New_Item_Budget__c = 200,
      Other_Factor_Percent__c = 10
    );
    insert bi5;

    Budget_Item__c bi6 = new Budget_Item__c(
      Grant__c = g.Id,
      RecordTypeId = rtId3,
      Name = 'Test Item',
      New_Rate__c = 100,
      Factor_Type__c = 'FTE'
    );
    insert bi6;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'BBBSA Level Three'];
    Contact c1 = new Contact(
      lastName = 'Contact',
      firstName = 'Test',
      Email = 'test123@example.com',
      accountId = a.Id
    );
    insert c1;
    User u = new User(
      Alias = 'testu',
      Email = 'test123@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1232@example.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u;

    Profile p2 = [SELECT Id FROM Profile WHERE Name = 'NPAL Level Three'];
    Contact c2 = new Contact(
      lastName = 'Contact',
      firstName = 'Test',
      Email = 'newtest@example.com',
      accountId = a.Id
    );
    insert c2;
    User u2 = new User(
      Alias = 'testu',
      Email = 'newtest@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p2.Id,
      UserName = 'newtest1@asdfawer.com',
      Contact = c2,
      ContactId = c2.Id
    );
    insert u2;

    //        System.runAs(u) {
    System.Test.setCurrentPageReference(
      new PageReference('Page.BBBSBudgetPersonnel')
    );
    System.currentPageReference().getParameters().put('GrantID', g.Id);
    BudgetPersonnelCtrl ctrl1 = new BudgetPersonnelCtrl();
    ctrl1.getLists();
    ctrl1.duration = 600;
    /*
        BudgetPersonnelCtrl.itemClass ic1 = new BudgetPersonnelCtrl.itemClass('', 0, bi1);
        BudgetPersonnelCtrl.itemClass ic2 = new BudgetPersonnelCtrl.itemClass('', 1, bi2);
        BudgetPersonnelCtrl.itemClass ic3 = new BudgetPersonnelCtrl.itemClass('', 1, bi3);
        ctrl1.labor_list.add(ic1);
        ctrl1.labor_list.add(ic2);
        ctrl1.newLabor_list.add(ic3);
		*/
    ctrl1.laborCount = 2;
    ctrl1.addItem();
    ctrl1.addItem();
    ctrl1.updateAmounts();
    ctrl1.bulkAction = 'disable';
    ctrl1.updateSelected();
    ctrl1.deleteItems();
    ctrl1.saveAndContinue();
    ctrl1.saveAndExit();
    ctrl1.laborNotesPopup();
    ctrl1.laborNotesPopup();
    ctrl1.ratePopup();
    ctrl1.ratePopup();
    ctrl1.newLaborNotesPopup();
    ctrl1.newLaborNotesPopup();

    System.Test.setCurrentPageReference(
      new PageReference('Page.BBBSBudgetExpenses')
    );
    System.currentPageReference().getParameters().put('GrantID', g.Id);
    BudgetExpensesCtrl ctrl2 = new BudgetExpensesCtrl();
    //BudgetExpensesCtrl.itemClass ic3 = new BudgetExpensesCtrl.itemClass(0, bi2);
    //BudgetExpensesCtrl.itemClass ic4 = new BudgetExpensesCtrl.itemClass(1, bi4);
    ctrl2.addItem();
    List<Budget_Item__c> bi_list = new List<Budget_Item__c>();
    bi_list.add(bi5);
    bi_list.add(bi6);
    ctrl2.expense_map.put('test', bi_list);
    ctrl2.portalName = '';
    ctrl2.addItem();
    ctrl2.addItem();
    for (Budget_Item__c bi : ctrl2.newExpense_list) {
      bi.New_Item_Budget__c = 100;
      bi.New_Rate__c = 100;
    }
    ctrl2.updateAmounts();
    ctrl2.selectedExpense = 1;
    ctrl2.deleteItems();
    ctrl2.previous();
    ctrl2.submit();
    ctrl2.bulkAction = 'disable';
    ctrl2.updateSelected();
    List<List<Budget_Item__c>> expense_list = ctrl2.expense_map.values();
    for (Budget_Item__c bi : expense_list.get(0)) {
      bi.Selected__c = true;
    }
    ctrl2.bulkAction = 'enable';
    ctrl2.updateSelected();
    for (Budget_Item__c bi : expense_list.get(0)) {
      bi.Selected__c = true;
    }
    ctrl2.bulkAction = 'delete';
    ctrl2.updateSelected();
    ctrl2.deleteAtt();
    ctrl2.expenseNotesPopup();
    ctrl2.expenseNotesPopup();
    ctrl2.newExpenseNotesPopup();
    ctrl2.newExpenseNotesPopup();
    ctrl2.attPopup();
    ctrl2.attPopup();
    ctrl2.saveAndExit();

    g.Use_Indirect_Rate__c = 'Yes';
    g.Indirect_Rate__c = 10;
    g.Youth_Served_Percent__c = 75;
    g.Estimated_FTE__c = 50;
    update g;
    ctrl2.errorMessage = '';
    ctrl2.submit();

    System.runAs(u) {
      System.Test.setCurrentPageReference(
        new PageReference('Page.NPALBudgetPersonnel')
      );
      System.currentPageReference().getParameters().put('GrantID', g.Id);
      BudgetPersonnelCtrl ctrl3 = new BudgetPersonnelCtrl();
      ctrl3.duration = 600;
      ctrl3.portalName = 'NPAL';
      ctrl3.laborCount = 2;
      ctrl3.addItem();
      ctrl3.addItem();
      ctrl3.updateAmounts();
      ctrl3.bulkAction = 'delete';
      ctrl3.updateSelected();
      for (Budget_Item__c bi : ctrl3.labor_list) {
        bi.Selected__c = true;
      }

      Budget_Item__c bi = new Budget_Item__c(
        Grant__c = g.Id,
        RecordTypeId = rtId2,
        Name = 'Test Item',
        Is_Hourly__c = true,
        Hourly_Rate__c = 20,
        Projected_Grant_Hours_Per_Week__c = 30,
        Projected_Hours_Per_Week__c = 40,
        Number_of_Weeks_on_Grant__c = 10
      );
      ctrl3.newLabor_list.add(bi);
      ctrl3.updateAmounts();
      ctrl3.bulkAction = 'disable';
      ctrl3.updateSelected();
      ctrl3.deleteItems();
      ctrl3.saveAndContinue();
      ctrl3.saveAndExit();
      ctrl3.laborNotesPopup();
      ctrl3.laborNotesPopup();
      ctrl3.ratePopup();
      ctrl3.ratePopup();
      ctrl3.newLaborNotesPopup();
      ctrl3.newLaborNotesPopup();
      //        }
    }
  }
}