force-app/main/default/objects/Account/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Names_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Names_of_Sites__c</fullName>
    <label>Names of Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Total Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sites__c</fullName>
    <label>Number of Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NationalApplicationController.cls
public class NationalApplicationController {
  public ID AccountId { get; set; }
  public Account acct { get; set; }
  public String errorMessage { get; set; }

  public NationalApplicationController() {
    acct = new Account();
    AccountId = ApexPages.currentPage().getParameters().get('AccountId');

    if (AccountId != null) {
      acct = [
        SELECT
          ID,
          RecordType.Name,
          Name,
          EIN__c,
          Status__c,
          Application_Submitted_Date__c,
          Phone,
          BillingStreet,
          BillingCity,
          BillingState,
          BillingPostalCode,
          Youth_Served__c,
          Number_of_Mentors__c,
          Number_of_Sites__c,
          Names_of_Sites__c
        FROM Account
        WHERE ID = :AccountId
      ];
    }
  }

  public PageReference Submit() {
    system.debug('>>>> acct ' + acct);
    Account a = new Account();

    if (AccountId != null) {
      a = [SELECT ID, EIN__c, Name FROM Account WHERE ID = :AccountId];
    } else if (acct.EIN__c != null) {
      a.EIN__c = acct.EIN__c;
    }
    system.debug('>>>> a ' + a);
    a.Name = acct.Name;
    a.Status__c = 'Application Submitted';
    a.Application_Submitted_Date__c = Date.today();
    a.Phone = acct.Phone;
    a.BillingStreet = acct.BillingStreet;
    a.BillingCity = acct.BillingCity;
    a.BillingState = acct.BillingState;
    a.BillingPostalCode = acct.BillingPostalCode;
    try {
      upsert a;
      System.Debug('>>>> Account update successful. a = ' + a);
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
      return null;
    }
    return null;
  }
}