force-app/main/default/objects/Account/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Names_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Names_of_Sites__c</fullName>
    <label>Names of Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Total Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sites__c</fullName>
    <label>Number of Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/A_133_Audit_Status__c.field-meta.xml
<CustomField>
    <fullName>A_133_Audit_Status__c</fullName>
    <label>A-133 Audit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Compliance_Notes__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Notes__c</fullName>
    <label>Compliance Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Compliance_Status__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Status__c</fullName>
    <label>Compliance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(ISBLANK(Start_Date__c),
Grant_End_Date__c - Grant_Start_Date__c + 1,
End_Date__c - Start_Date__c + 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Names_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Names_of_Sites__c</fullName>
    <label>Names of Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sites__c</fullName>
    <label>Number of Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Approved Amount</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Budget_Item__c.Total_Approved_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Budget__c</fullName>
    <inlineHelpText>Roll-Up Summary of Budget Item: Item Budget</inlineHelpText>
    <label>Total Item Budget</label>
    <summarizedField>Budget_Item__c.Item_Budget__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Requested Amount</inlineHelpText>
    <label>Total Requested Amount</label>
    <summarizedField>Budget_Item__c.Total_Requested_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/SubGrantApplicationController.cls
public class SubGrantApplicationController {
  public ID AccountId { get; set; }
  public Account acct { get; set; }
  public ID GrantId { get; set; }
  public Grant__c grant { get; set; }
  public String errorMessage { get; set; }

  public SubGrantApplicationController() {
    AccountId = ApexPages.currentPage().getParameters().get('AccountId');
    GrantId = ApexPages.currentPage().getParameters().get('GrantId');
    acct = new Account();
    grant = new Grant__c();

    if (GrantID != null) {
      grant = [
        SELECT
          ID,
          Account__c,
          Account__r.Name,
          Name,
          A_133_Audit_Status__c,
          Amount__c,
          Application_Submitted_Date__c,
          Balance__c,
          Compliance_Notes__c,
          Compliance_Status__c,
          Duration__c,
          End_Date__c,
          Grant_Status__c,
          Previous_Status__c,
          Project_Description__c,
          Start_Date__c,
          Total_Approved_Amount__c,
          Total_Item_Budget__c,
          Total_Requested_Amount__c,
          Youth_Served__c
        FROM Grant__c
        WHERE ID = :GrantID
      ];
      AccountID = grant.Account__r.Id;
    }
    if (AccountId != null) {
      acct = [
        SELECT
          ID,
          RecordType.Name,
          Name,
          EIN__c,
          Status__c,
          Application_Submitted_Date__c,
          Phone,
          BillingStreet,
          BillingCity,
          BillingState,
          BillingPostalCode,
          Youth_Served__c,
          Number_of_Mentors__c,
          Number_of_Sites__c,
          Names_of_Sites__c
        FROM Account
        WHERE ID = :AccountId
      ];
    }
  }

  public PageReference Submit() {
    system.debug('>>>> acct ' + acct);
    Account a = new Account();
    Set<ID> aID_set = new Set<ID>();
    Grant__c g = new Grant__c();

    if (AccountId != null) {
      a = [SELECT ID, EIN__c, Name FROM Account WHERE ID = :AccountId];
    } else if (acct.EIN__c != null) {
      a.EIN__c = acct.EIN__c;
    }
    system.debug('>>>> a ' + a);
    a.Name = acct.Name;
    a.Status__c = 'Application Submitted';
    a.Application_Submitted_Date__c = Date.today();
    a.Phone = acct.Phone;
    a.BillingStreet = acct.BillingStreet;
    a.BillingCity = acct.BillingCity;
    a.BillingState = acct.BillingState;
    a.BillingPostalCode = acct.BillingPostalCode;
    a.Youth_Served__c = acct.Youth_Served__c;
    a.Number_of_Mentors__c = acct.Number_of_Mentors__c;
    a.Number_of_Sites__c = acct.Number_of_Sites__c;
    a.Names_of_Sites__c = acct.Names_of_Sites__c;
    try {
      upsert a;
      aID_set.add(a.Id);
      System.Debug('>>>> Account update successful. a = ' + a);
      System.Debug('>>>> aID_set = ' + aID_set);
    } catch (Exception e) {
      ApexPages.addmessage(
        new ApexPages.message(ApexPages.severity.ERROR, e.getMessage())
      );
      return null;
    }

    for (Account aa : [SELECT ID FROM Account WHERE ID IN :aID_set]) {
      g.Account__c = aa.Id;
      //o.A_133_Audit_Status__c = opp.A_133_Audit_Status__c;
      g.Application_Submitted_Date__c = date.today();
      //o.Compliance_Notes__c = opp.Compliance_Notes__c;
      //o.Compliance_Status__c = opp.Compliance_Status__c;
      g.End_Date__c = grant.End_Date__c;
      //o.Names_of_Sites__c = opp.Names_of_Sites__c;
      //o.Mentors__c = opp.Mentors__c;
      //o.Number_of_Sites__c = opp.Number_of_Sites__c;
      //o.Youth_Served__c = opp.Youth_Served__c;
      g.Project_Description__c = grant.Project_Description__c;
      g.Name = grant.Name;
      g.Start_Date__c = grant.Start_Date__c;
      g.Grant_Status__c = 'Application Submitted';
    }
    try {
      insert g;
      System.Debug('>>>> Grant insert successful. g = ' + g);
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
      return null;
    }

    return null;
  }
}