force-app/main/default/objects/Account/fields/BBBS_ID__c.field-meta.xml
<CustomField>
    <fullName>BBBS_ID__c</fullName>
    <label>BBBS ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Lead__c.field-meta.xml
<CustomField>
    <fullName>Finance_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Finance Lead)</relationshipLabel>
    <relationshipName>Accounts_FinanceLead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insurance_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiration_Date__c</fullName>
    <label>Insurance Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <label>Insurance Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Assessment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Status__c</fullName>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Attachment_Notes__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Notes__c</fullName>
    <label>Attachment Notes</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Attachment_Status__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Status__c</fullName>
    <label>Attachment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Compliance_Status__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Status__c</fullName>
    <label>Compliance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Compliance</fullName>
            </value>
            <value>
                <fullName>Out of Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Fiscal_Year_Ended__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_Ended__c</fullName>
    <label>Fiscal Year Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Hide_Standards__c.field-meta.xml
<CustomField>
    <fullName>Hide_Standards__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Standards</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Reviewed__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Reviewed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>IF(Assessment__c != null, TEXT(Assessment__r.Year__c), 
IF(Grant__c != null, Grant__r.Year__c, 
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (CEO)</relationshipLabel>
    <relationshipName>CEOGrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Compliance_Status__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Status__c</fullName>
    <label>Compliance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/ComplianceCtrl.cls
public with sharing class ComplianceCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String approverLevel { get; set; }
  public String portalName { get; set; }

  public Id OrgId { get; set; }
  public String orgName { get; set; }
  public Integer currentYear { get; set; }

  public Id AssessmentId { get; set; }
  public Assessment__c assess { get; set; }
  public List<Assessment__c> sa_list { get; set; }

  private GrantClass gc = new GrantClass();
  public List<SelectOption> grantOptions { get; set; }
  public Id grantId { get; set; }

  public List<SelectOption> years { get; set; }
  public String year { get; set; }
  public String keyword { get; set; }
  public String sortBy { get; set; }

  public List<Contact> contact_list { get; set; }
  public Boolean displayContactPopup { get; set; }

  public String reportType { get; set; }
  public String reportTitle { get; set; }
  public List<itemClass> item_list { get; set; }

  public Boolean runGetLists { get; set; }

  public ComplianceCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    approverLevel = userClass.approverLevel;
    portalName = userClass.userProfile;

    Assessment__c assess = new Assessment__c();
    sa_list = new List<Assessment__c>();
    contact_list = new List<Contact>();

    grantOptions = new List<SelectOption>();
    for (Grant__c g : [
      SELECT Id, Name
      FROM Grant__c
      WHERE Account__c = :userAcct.Id AND RecordType.Name = 'Grant'
      ORDER BY Name DESC
    ]) {
      grantOptions.add(new SelectOption(g.Id, g.Name));
    }
    if (grantOptions.size() > 0)
      grantId = grantOptions[0].getValue();

    year = ApexPages.currentPage().getParameters().get('year');
    currentYear = 2020;
    years = new List<SelectOption>();
    years.add(new SelectOption('2020', '2020'));
    years.add(new SelectOption('2019', '2019'));
    years.add(new SelectOption('2018', '2018'));
    years.add(new SelectOption('2017', '2017'));
    years.add(new SelectOption('2016', '2016'));

    reportType = '';
    String urlType = ApexPages.currentPage().getParameters().get('type');
    if (urlType != null && urlType != '')
      reportType = urlType;
    reportTitle = 'Contacts Report';
    if (reportType == 'audit')
      reportTitle = 'Compliance Audit Report';
    if (reportType == 'ins')
      reportTitle = 'Compliance Insurance Report';
    if (reportType == 'incomplete')
      reportTitle = 'Incomplete Self-Assessments';
    item_list = new List<itemClass>();

    runGetLists = true;
  }

  // BEGIN getLists
  public void getLists() {
    if (runGetLists) {
      sa_list.clear();
      system.debug('>>> sortBy = ' + sortBy);
      system.debug('>>> keyword = ' + keyword);

      String soql = 'SELECT Year__c, Reviewed__c, Submitted_Date__c, Hide_Standards__c, LastModifiedDate, Organization__r.Name, Organization__r.BBBS_Id__c, Organization__r.Insurance_Provider__c, Organization__r.Insurance_Expiration_Date__c, Assessment_Status__c, Compliance_Status__c, Attachment_Status__c, Attachment_Notes__c, Fiscal_Year_Ended__c';
      soql += ', Organization__r.CEO__r.Name, Organization__r.CEO__r.Email, Organization__r.Finance_Lead__r.Name, Organization__r.Finance_Lead__r.Email';
      soql += ' FROM Assessment__c';
      if (year != null) {
        soql +=
          ' WHERE Year__c = ' +
          year +
          ' AND Organization__r.Is_Active__c = true';
      } else {
        soql +=
          ' WHERE Year__c = ' +
          currentYear +
          ' AND Organization__r.Is_Active__c = true';
      }
      if (sortBy != '' && sortBy != null) {
        soql += ' ORDER BY ' + sortBy + ' asc, LastModifiedDate desc';
      } else {
        soql += ' ORDER BY LastModifiedDate desc';
      }

      Set<Id> aIds = new Set<Id>();
      for (Assessment__c a : Database.query(soql)) {
        String s1 = a.Organization__r.Name;
        String s2 = '';
        if (a.Organization__r.BBBS_Id__c != null)
          s2 = String.valueOf(a.Organization__r.BBBS_Id__c);
        String k = '';
        if (keyword != null && keyword != '')
          k = String.valueOf(keyword).toLowerCase();

        if (k == '' || s1.toLowerCase().contains(k) || s2.contains(k)) {
          sa_list.add(a);
          aIds.add(a.Id);
        }
      }

      List<Document__c> docs = new List<Document__c>();
      docs = [
        SELECT Name, Assessment__c
        FROM Document__c
        WHERE Assessment__c IN :aIds
      ];
      for (Assessment__c a : sa_list) {
        if (reportType != '') {
          if (
            reportType != 'incomplete' ||
            (reportType == 'incomplete' &&
            a.Assessment_Status__c != 'Submitted' &&
            a.Assessment_Status__c != 'Closed')
          ) {
            itemClass ic = new itemClass(a, null, docs);
            item_list.add(ic);
          }
        }
      }
      runGetLists = false;
    }
  }
  // END getLists

  // BEGIN getContactList
  public void getContactList() {
    contact_list.clear();
    contact_list = [
      SELECT Id, Account.Name, Name, Title, Role__c, Email, Phone
      FROM Contact
      WHERE AccountId = :OrgId
    ];
  }
  // END getContactList

  // BEGIN popups
  public void contactPopup() {
    displayContactPopup = true;
    getContactList();
  }

  public void closeContactPopup() {
    displayContactPopup = false;
  }
  // END popups

  // BEGIN Inner Class
  public class itemClass {
    public Assessment__c sa { get; set; }
    public Decimal bbbsId { get; set; }
    public String name { get; set; }
    public Boolean hasAIM { get; set; }
    public Boolean hasFeeForm { get; set; }
    public Boolean hasAudit { get; set; }
    public Boolean hasIns { get; set; }
    public Date fiscal { get; set; }
    public Date afterFiscal { get; set; }
    public String insKirby { get; set; }
    public String insName { get; set; }
    public Date insDate { get; set; }
    public String ceoName { get; set; }
    public String ceoEmail { get; set; }
    public String leadName { get; set; }
    public String leadEmail { get; set; }

    // BEGIN Inner Class Constructor
    public itemClass(Assessment__c a, Account acct, List<Document__c> docs) {
      Id acctId;

      if (a != null) {
        sa = a;
        acctId = a.Organization__r.Id;
        bbbsId = a.Organization__r.BBBS_Id__c;
        name = a.Organization__r.Name;

        if (a.Organization__r.CEO__r.Name != null) {
          ceoName = a.Organization__r.CEO__r.Name;
          ceoEmail = a.Organization__r.CEO__r.Email;
        }
        if (a.Organization__r.Finance_Lead__r.Name != null) {
          leadName = a.Organization__r.Finance_Lead__r.Name;
          leadEmail = a.Organization__r.Finance_Lead__r.Email;
        }

        hasAIM = false;
        hasFeeForm = false;
        if (a.Fiscal_Year_Ended__c != null) {
          fiscal = a.Fiscal_Year_Ended__c;
          afterFiscal = fiscal.addMonths(9);
        }

        if (a.Organization__r.Insurance_Expiration_Date__c != null) {
          insDate = a.Organization__r.Insurance_Expiration_Date__c;

          if (a.Organization__r.Insurance_Provider__c != null) {
            insName = a.Organization__r.Insurance_Provider__c;
            insKirby = 'false';
          } else {
            insKirby = 'true';
          }
        }

        for (Document__c d : docs) {
          if (d.Assessment__c == a.Id) {
            String name = d.Name;
            if (name.contains('AIM Fee Form')) {
              hasAIM = true;
            }
            if (name.contains('Affiliation Fee Form')) {
              hasFeeForm = true;
            }
            if (name.contains('Audit')) {
              hasAudit = true;
            }
            if (name.contains('Proof of Insurance')) {
              hasIns = true;
            }
          }
        }
      } else if (acct != null) {
        acctId = acct.Id;
        bbbsId = acct.BBBS_Id__c;
        name = acct.Name;

        if (acct.CEO__r.Name != null) {
          ceoName = acct.CEO__r.Name;
          ceoEmail = acct.CEO__r.Email;
        }
        if (acct.Finance_Lead__r.Name != null) {
          leadName = acct.Finance_Lead__r.Name;
          leadEmail = acct.Finance_Lead__r.Email;
        }
      }
    }
    // END Inner class Constructor
  }
  // END inner Class

  public void testInnerClasses() {
    Account acct = new Account();
    Assessment__c assess = new Assessment__c();
    List<Document__c> docs = new List<Document__c>();
    itemClass ic = new itemClass(assess, acct, docs);
  }
}