force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Name__c.field-meta.xml
<CustomField>
    <fullName>CEO_Name__c</fullName>
    <formula>CEO__r.FirstName + &apos; &apos; + CEO__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEO Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>National_Organization__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Primary Approver)</relationshipLabel>
    <relationshipName>Accounts_Primary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Email__c</fullName>
    <label>Primary Approver Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <label>National Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (National Organization)</relationshipLabel>
    <relationshipName>NationalApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <label>National Organization Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Previous_Award_Amount__c.field-meta.xml
<CustomField>
    <fullName>Previous_Award_Amount__c</fullName>
    <label>Previous Award Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Challenge</fullName>
                <default>true</default>
                <label>Challenge</label>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO_Name__c.field-meta.xml
<CustomField>
    <fullName>CEO_Name__c</fullName>
    <formula>Account__r.CEO_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEO Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>Account__r.National_Organization_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteDetailsCtrl.cls
public with sharing class SiteDetailsCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }
  public String approverLevel { get; set; }

  private AccountClass accountClass = new AccountClass();
  private ContactClass contactClass = new ContactClass();
  private ApplicationClass appClass = new ApplicationClass();
  private PaginationClass pc = new PaginationClass();
  private getIdFromString gifs = new getIdFromString();

  public Contact newContact { get; set; }
  public List<Contact> contacts { get; set; }
  public Id selectedContactId { get; set; }
  public Contact selectedContact { get; set; }
  public String contactSiteId { get; set; }
  public List<SelectOption> siteOptions { get; set; }
  public List<SelectOption> profileOptions { get; set; }

  public Id siteId { get; set; }
  public Account acct { get; set; }
  public List<Account> allSites { get; set; }
  public List<Account> sites { get; set; }
  public String siteName { get; set; }
  public Id selectedSiteId { get; set; }
  public Application__c soi { get; set; }
  public Application__c app { get; set; }
  public String appType { get; set; }
  public List<SelectOption> appTypeOptions { get; set; }

  public List<Contact> allYouth { get; set; }
  public List<Contact> youth { get; set; }
  public String youthName { get; set; }
  public String youthSiteId { get; set; }

  public Boolean displayEditOrgPopup { get; set; }
  public Boolean displayAddContactPopup { get; set; }
  public Boolean displayEditContactPopup { get; set; }
  public Boolean displayDeleteContactPopup { get; set; }
  public Boolean displaySendApplicationPopup { get; set; }

  public string errorMessage { get; set; }

  Integer siteCounter = 0;
  Integer siteLimitSize = 20;
  Integer siteTotalSize = 0;
  public String siteRecordCount { get; set; }
  public Boolean siteDisablePrevious { get; set; }
  public Boolean siteDisableNext { get; set; }

  Integer youthCounter = 0;
  Integer youthLimitSize = 20;
  Integer youthTotalSize = 0;
  public String youthRecordCount { get; set; }
  public Boolean youthDisablePrevious { get; set; }
  public Boolean youthDisableNext { get; set; }

  public TALogCtrl logCtrl = new TALogCtrl();
  public TALogCtrl getTALogCtrl() {
    return logCtrl;
  }

  public SiteDetailsCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;
    approverLevel = userClass.approverLevel;

    newContact = new Contact();
    selectedContact = new Contact();
    contacts = new List<Contact>();
    allSites = new List<Account>();
    sites = new List<Account>();
    allYouth = new List<Contact>();
    youth = new List<Contact>();
    soi = new Application__c();
    app = new Application__c();
    errorMessage = '';

    String urlSiteID = ApexPages.currentPage().getParameters().get('siteId');
    siteId = gifs.getId(urlSiteID);
    String urlOrgID = ApexPages.currentPage().getParameters().get('orgId');
    Id orgId = gifs.getId(urlOrgID);

    acct = new Account();
    if (siteId != null)
      acct = accountClass.getAccount(siteId);
    else if (orgId != null)
      acct = accountClass.getAccount(orgId);
    else if (userAcct != null)
      acct = accountClass.getAccount(userAcct.Id);

    siteOptions = new List<SelectOption>();
    siteOptions.add(new SelectOption('', '-- Select a Site --'));
    for (
      Account a : accountClass.getRelatedAccountList(
        acct.Id,
        userAcctType,
        '',
        '',
        null
      )
    ) {
      siteOptions.add(new SelectOption(a.Id, a.Name));
    }

    profileOptions = new List<SelectOption>();
    profileOptions.add(new SelectOption('', '-- Select a Profile --'));
    profileOptions.add(new SelectOption('Program Admin', 'Program Admin'));
    profileOptions.add(new SelectOption('All Access', 'All Access'));
    profileOptions.add(new SelectOption('Inactive User', 'Inactive User'));

    appTypeOptions = new List<SelectOption>();
    if (portalName == 'Ripken') {
      appTypeOptions.add(
        new SelectOption('Ripken Special Initiative', 'Special Initiative')
      );
      appTypeOptions.add(
        new SelectOption('Ripken Baseball', 'Badges for Baseball')
      );
      appTypeOptions.add(new SelectOption('Ripken I\'m GREAT', 'I\'m GREAT'));
      appTypeOptions.add(
        new SelectOption('Ripken Healthy Lifestyles', 'Healthy Lifestyles')
      );
      appType = 'Ripken Baseball';
    } else if (portalName.contains('TRAIL')) {
      appType = 'NCAI - TRAIL';
    }
  }

  public void getLists() {
    getRelatedContactList();
    getRelatedAccountList();
    if (portalName.contains('NCAI')) {
      getRelatedYouthList();
      Application__c[] items = appClass.getRelatedApplicationList(
        acct.Id,
        null,
        null,
        ' AND RecordType.Name = \'NCAI - SOI\'',
        null,
        null
      );
      if (items.size() > 0) {
        soi = items[0];
      }
    }
  }

  public void getRelatedAccountList() {
    sites.clear();
    allSites = accountClass.getRelatedAccountList(
      acct.Id,
      userAcctType,
      'Local Organization',
      siteName,
      null
    );
    siteTotalSize = allSites.size();
    siteFirst();
  }

  public void getRelatedContactList() {
    contacts.clear();
    contacts = contactClass.getRelatedContactList(
      acct.Id,
      'Contact',
      null,
      null
    );
  }

  public void getRelatedYouthList() {
    youth.clear();
    Id aId = acct.Id;
    if (youthSiteId != null && youthSiteId != '')
      aId = Id.valueOf(youthSiteId);
    allYouth = contactClass.getRelatedContactList(
      aId,
      'Youth',
      youthName,
      null
    );
    youthTotalSize = allYouth.size();
    youthFirst();
  }

  public void upsertOrg() {
    accountClass.upsertAccount(acct);
    displayEditOrgPopup = false;
  }

  public void upsertContact() {
    if (selectedContact.LastName != null & selectedContact.Email != null) {
      if (selectedContact.RecordTypeId == null)
        selectedContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
          .get('Contact')
          .getRecordTypeId();
      if (contactSiteId != null && contactSiteId != '')
        selectedContact.AccountId = Id.valueOf(contactSiteId);
      if (selectedContact.AccountID == null)
        selectedContact.AccountID = acct.Id;
      try {
        contactClass.upsertContact(selectedContact);
        displayEditContactPopup = false;
        errorMessage = '';
        getRelatedContactList();
      } catch (Exception e) {
        system.debug(e.getMessage());
        errorMessage = e.getMessage();
      }
    } else if (selectedContact.LastName == null) {
      errorMessage = 'Last name is required';
    } else if (selectedContact.Email == null) {
      errorMessage = 'Email is required';
    }
  }

  public void deleteContact() {
    if (selectedContact.Id != null) {
      contactClass.deleteContact(selectedContact);
      displayDeleteContactPopup = false;
    }
  }

  public void sendApplication() {
    if (app.National_Organization__c == null)
      app.National_Organization__c = userAcct.Id;
    if (appType != null)
      app.RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName()
        .get(appType)
        .getRecordTypeId();
    if (app.Organization__c == null || app.Primary_Approver__c == null) {
      app.Primary_Approver__c = currentUser.ContactId;
      app.Primary_Approver_Email__c = currentUser.Contact.Email;
    }
    app.Status__c = 'Sent to Applicant';
    appClass.upsertApplication(app);
    if (!ApexPages.hasMessages())
      displaySendApplicationPopup = false;
    else
      errorMessage = String.valueOf(ApexPages.getMessages());
  }

  // BEGIN Popups
  public void showEditOrgPopup() {
    displayEditOrgPopup = true;
  }
  public void hideEditOrgPopup() {
    displayEditOrgPopup = false;
  }

  public void showEditRelatedContactPopup() {
    if (selectedContactId != null) {
      selectedContact = contactClass.getContact(selectedContactId);
      contactSiteId = selectedContact.AccountId;
    } else {
      selectedContact = new Contact();
      contactSiteId = '';
    }
    displayEditContactPopup = true;
  }
  public void hideEditRelatedContactPopup() {
    displayEditContactPopup = false;
  }

  public void showDeleteContactPopup() {
    if (selectedContactId != null) {
      Contact[] c = [
        SELECT Id, Name
        FROM Contact
        WHERE Id = :selectedContactId
      ];
      if (c.size() > 0) {
        selectedContact = c[0];
        displayDeleteContactPopup = true;
      }
    }
  }
  public void hideDeleteContactPopup() {
    displayDeleteContactPopup = false;
  }

  public void showSendApplicationPopup() {
    app = new Application__c();
    system.debug('selectedSiteId = ' + selectedSiteId);
    if (selectedSiteId != null) {
      Account a = accountClass.getAccount(selectedSiteId);
      if (a.Id != null) {
        if (portalName.contains('NCAI')) {
          Grant__c[] grants = [
            SELECT Amount__c
            FROM Grant__c
            WHERE Account__c = :a.Id
          ];
          if (grants.size() > 0) {
            app.Previous_Award_Amount__c = grants[0].Amount__c;
            app.Type__c = 'Existing';
          } else {
            app.Type__c = 'New';
          }
        }
        app.Organization__c = a.Id;
        app.Organization_Name__c = a.Name;
        app.National_Organization__c = a.National_Organization_Id__c;
        app.Primary_Approver__c = a.Primary_Approver__c;
        app.Primary_Approver_Email__c = a.Primary_Approver_Email__c;
        app.Applicant_Name__c = a.CEO_Name__c;
        app.Applicant_Email__c = a.CEO_Email__c;
        app.Address__c = a.BillingStreet;
        app.City__c = a.BillingCity;
        app.State__c = a.Billing_State_Long__c;
        app.Postal_Zip_Code__c = a.BillingPostalCode;
        app.Mailing_Address__c = a.ShippingStreet;
        app.Mailing_City__c = a.ShippingCity;
        app.Mailing_State__c = a.Shipping_State_Long__c;
        app.Mailing_Postal_Code__c = a.ShippingPostalCode;
        app.EIN__c = a.EIN__c;
        app.Website__c = a.Website;
        app.Phone__c = a.Phone;
        app.Fax__c = a.Fax;
        app.DUNS_Number__c = a.DUNS_Number__c;
      }
    }
    displaySendApplicationPopup = true;
  }
  public void hideSendApplicationPopup() {
    displaySendApplicationPopup = false;
  }
  // END popups

  // BEGIN Site Pagination
  public void siteFirst() {
    siteCounter = 0;
    if (allSites.size() > 0) {
      sites = pc.first(allSites, siteLimitSize);
      siteRecordCount = pc.getRecordCount(
        siteCounter,
        siteLimitSize,
        siteTotalSize
      );
      siteDisablePrevious = true;
      siteDisableNext = pc.getDisableNext(
        siteCounter,
        siteLimitSize,
        siteTotalSize
      );
    }
  }

  public void siteNext() {
    siteCounter = siteCounter + siteLimitSize;
    sites = pc.next(allSites, siteCounter, siteLimitSize);
    siteRecordCount = pc.getRecordCount(
      siteCounter,
      siteLimitSize,
      siteTotalSize
    );
    siteDisablePrevious = false;
    siteDisableNext = pc.getDisableNext(
      siteCounter,
      siteLimitSize,
      siteTotalSize
    );
  }

  public void sitePrevious() {
    siteCounter = siteCounter - siteLimitSize;
    sites = pc.previous(allSites, siteCounter, siteLimitSize);
    siteRecordCount = pc.getRecordCount(
      siteCounter,
      siteLimitSize,
      siteTotalSize
    );
    siteDisablePrevious = pc.getDisablePrevious(siteCounter);
    siteDisableNext = false;
  }

  public void siteLast() {
    siteCounter = pc.getLastCounter(siteCounter, siteLimitSize, siteTotalSize);
    sites = pc.last(allSites, siteCounter, siteLimitSize);
    siteRecordCount = pc.getRecordCount(
      siteCounter,
      siteLimitSize,
      siteTotalSize
    );
    siteDisablePrevious = false;
    siteDisableNext = true;
  }
  // END Site Pagination

  // BEGIN Youth Pagination
  public void youthFirst() {
    youthCounter = 0;
    if (allYouth.size() > 0) {
      youth = pc.first(allYouth, youthLimitSize);
      youthRecordCount = pc.getRecordCount(
        youthCounter,
        youthLimitSize,
        youthTotalSize
      );
      youthDisablePrevious = true;
      youthDisableNext = pc.getDisableNext(
        youthCounter,
        youthLimitSize,
        youthTotalSize
      );
    }
  }

  public void youthNext() {
    youthCounter = youthCounter + youthLimitSize;
    youth = pc.next(allYouth, youthCounter, youthLimitSize);
    youthRecordCount = pc.getRecordCount(
      youthCounter,
      youthLimitSize,
      youthTotalSize
    );
    youthDisablePrevious = false;
    youthDisableNext = pc.getDisableNext(
      youthCounter,
      youthLimitSize,
      youthTotalSize
    );
  }

  public void youthPrevious() {
    youthCounter = youthCounter - youthLimitSize;
    youth = pc.previous(allYouth, youthCounter, youthLimitSize);
    youthRecordCount = pc.getRecordCount(
      youthCounter,
      youthLimitSize,
      youthTotalSize
    );
    youthDisablePrevious = pc.getDisablePrevious(youthCounter);
    youthDisableNext = false;
  }

  public void youthLast() {
    youthCounter = pc.getLastCounter(
      youthCounter,
      youthLimitSize,
      youthTotalSize
    );
    youth = pc.last(allYouth, youthCounter, youthLimitSize);
    youthRecordCount = pc.getRecordCount(
      youthCounter,
      youthLimitSize,
      youthTotalSize
    );
    youthDisablePrevious = false;
    youthDisableNext = true;
  }
  // END Youth Pagination
}