force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Access_Mode__c.field-meta.xml
<CustomField>
    <fullName>Access_Mode__c</fullName>
    <label>Access Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local Read Only</fullName>
            </value>
            <value>
                <fullName>National Access Only</fullName>
            </value>
            <value>
                <fullName>National L2a/L3a Access Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Organization__c != null, Organization__r.FirstPic_National_Org_Code__c,  
IF(Grant__c != null, Grant__r.FirstPic_National_Org_Code__c, 
IF(Reimbursement__c != null, Reimbursement__r.FirstPic_National_Org_Code__c,
IF(Session_Report__c != null, Session_Report__r.FirstPic_National_Org_Code__c,
&apos;&apos;))))</formula>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <label>Group Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Modification_History__c.field-meta.xml
<CustomField>
    <fullName>Modification_History__c</fullName>
    <label>Modification History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <formula>IF(Assessment__c != null, &apos;Assessment&apos;,
IF(Grant__c  != null, &apos;Grant&apos;,
IF(Reimbursement__c  != null, &apos;Reimbursement&apos;,
IF(Session_Report__c  != null, &apos;Session Report&apos;, 
&apos;&apos;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Previous_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Previous_Due_Date__c</fullName>
    <label>Previous Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>Recipient</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Session_Report__c.field-meta.xml
<CustomField>
    <fullName>Session_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Report</label>
    <referenceTo>Session_Report__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
                <isActive>false</isActive>
                <label>Resubmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>IF(Assessment__c != null, TEXT(Assessment__r.Year__c), 
IF(Grant__c != null, Grant__r.Year__c, 
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Site__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017-2018</fullName>
            </value>
            <value>
                <fullName>2018-2019</fullName>
            </value>
            <value>
                <fullName>2019-2020</fullName>
            </value>
            <value>
                <fullName>2020-2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentCtrl.cls
public without sharing class DocumentCtrl {
  private getIdFromString gifs = new getIdFromString();
  private UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String approverLevel { get; set; }
  public String portalName { get; set; }

  public Id orgId { get; set; }
  public String orgCode { get; set; }
  public Id grantId { get; set; }
  public Id assessmentId { get; set; }
  public Id reportId { get; set; }
  public Id requestId { get; set; }

  public String groupId { get; set; }
  public String newDocGroupId { get; set; }
  public String reportType { get; set; }
  public String objectType { get; set; }
  public String reportTitle { get; set; }
  public String year { get; set; }
  public String years { get; set; }
  public List<SelectOption> yearOptions { get; set; }

  private DocumentClass docClass = new DocumentClass();
  private AttachmentClass attClass = new AttachmentClass();
  public List<Document__c> doc_list { get; set; }
  public List<Attachment> att_list { get; set; }
  public List<Attachment> oldAtt_list { get; set; }

  public String fileNames { get; set; }
  public List<SelectOption> names_list { get; set; }
  public Boolean isNewDoc { get; set; }
  public Boolean attachNewDoc { get; set; }

  public String selectedDocId { get; set; }
  public Document__c selectedDoc { get; set; }
  public Date dueDate { get; set; }
  public Boolean displayDocPopup { get; set; }
  public Boolean displayDeleteDocPopup { get; set; }
  public String selectedAttId { get; set; }
  public Attachment selectedAtt { get; set; }
  public Boolean displayDeleteAttPopup { get; set; }

  private Date dt = date.today();
  private String fdt = dt.format();
  private String modHist = '';
  public String errorMessage { get; set; }

  public DocumentCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    approverLevel = userClass.approverLevel;
    portalName = userClass.userProfile;

    String urlorg = ApexPages.currentPage().getParameters().get('org');
    if (urlorg != null)
      orgCode = urlorg.toUpperCase();

    String urlorgId = ApexPages.currentPage().getParameters().get('orgId');
    String urlsiteId = ApexPages.currentPage().getParameters().get('siteId');
    if (urlorgId != null)
      orgId = gifs.getId(urlorgId);
    if (urlsiteId != null)
      orgId = gifs.getId(urlsiteId);

    String urlgrantId = ApexPages.currentPage().getParameters().get('grantId');
    grantId = gifs.getId(urlgrantId);

    String urlassessmentId = ApexPages.currentPage()
      .getParameters()
      .get('assessmentId');
    assessmentId = gifs.getId(urlassessmentId);

    String urlReportId = ApexPages.currentPage()
      .getParameters()
      .get('reportId');
    reportId = gifs.getId(urlReportId);

    String urlRequestId = ApexPages.currentPage()
      .getParameters()
      .get('requestId');
    requestId = gifs.getId(urlRequestId);

    reportType = ApexPages.currentPage().getParameters().get('reportType');
    objectType = ApexPages.currentPage().getParameters().get('objectType');
    if (objectType != null)
      objectType.capitalize();
    String urlYear = ApexPages.currentPage().getParameters().get('year');
    if (urlYear != null)
      year = urlYear;

    doc_list = new List<Document__c>();
    att_list = new List<Attachment>();
    oldAtt_list = new List<Attachment>();
    names_list = new List<SelectOption>();
    yearOptions = new List<SelectOption>();
    selectedDoc = new Document__c();
    isNewDoc = true;
    selectedAtt = new Attachment();
    errorMessage = '';

    reportTitle = 'Documents';
    if (portalName.contains('NCAI')) {
      reportTitle = 'All Required Documents';
    } else {
      if (reportType == 'compliance')
        reportTitle = 'All Grant Compliance Documents';
      if (reportType == 'grant')
        reportTitle = 'Grant Specific Documents';
    }
  }

  public PageReference setParams() {
    names_list.clear();
    if (fileNames != null) {
      for (String n : fileNames.split(',')) {
        if (n != '') {
          names_list.add(new SelectOption(n.capitalize(), n.capitalize()));
        }
      }
    }

    if (years != null) {
      yearOptions.add(new SelectOption('', 'Filter by Year'));
      for (String n : years.split(';')) {
        if (n != '') {
          yearOptions.add(new SelectOption(n, n));
        }
      }
    }
    getLists();
    return null;
  }

  public String getSOQL() {
    String soqlAND = '';
    if (userAcctType == 'Local Organization')
      soqlAND += ' AND (Access_Mode__c = null OR Access_Mode__c = \'\' OR Access_Mode__c = \'Local Read Only\')';
    else if (!approverLevel.contains('Admin'))
      soqlAND += ' AND Access_Mode__c != \'National L2a/L3a Access Only\'';
    if (reportType == 'required')
      soqlAND += ' AND Required__c = true';
    if (objectType != null && objectType != '')
      soqlAND = ' AND Object_Type__c = \'' + objectType + '\'';
    //        if(year != null && year != '') soqlAND = ' AND Year__c = \'' + year + '\'';
    if (year != null && year != '')
      soqlAND =
        ' AND (Year__c = \'' +
        year +
        '\' OR Name LIKE \'%' +
        year +
        '%\')';
    if (orgCode != null && orgCode != '')
      soqlAND += ' AND FirstPic_National_Org_Code__c  = \'' + orgCode + '\'';
    system.debug('>>>> DocumentCtrl soqlAND = ' + soqlAND);
    return soqlAND;
  }

  public void getLists() {
    String soqlAND = getSOQL();
    Boolean hasId = false;
    if (
      orgId != null ||
      grantId != null ||
      assessmentId != null ||
      reportId != null ||
      requestId != null
    ) {
      hasId = true;
    } else {
      orgId = userAcct.Id;
    }

    doc_list = docClass.getDocList(
      orgId,
      grantId,
      assessmentId,
      reportId,
      requestId,
      groupId,
      soqlAND
    );

    att_list = docClass.getAttList();
    system.debug('>>>> DocumentCtrl docClass soql = ' + docClass.soql);
    system.debug('>>>> DocumentCtrl soqlAND = ' + soqlAND);
    //if(soqlAND == '') att_list = docClass.getAttList();
    if (assessmentId != null) {
      oldAtt_list.clear();
      oldAtt_list = [
        SELECT Id, Name, ParentId
        FROM Attachment
        WHERE ParentId = :assessmentId
      ];
    }
  }

  public void getListWithAtts() {
    String soqlAND = getSOQL();
    if (reportType == 'compliance')
      soqlAND += ' AND Object_Type__c = null';
    if (reportType == 'grant')
      soqlAND += ' AND Object_Type__c = \'Grant\'';
    doc_list = docClass.getDocWithAttList(
      orgId,
      grantId,
      assessmentId,
      reportId,
      requestId,
      groupId,
      soqlAND
    );
  }

  public void saveAndContinue() {
    errorMessage = '';
    if (selectedDoc != null && selectedDoc.Name != null) {
      if (groupId != null && groupId != '')
        selectedDoc.Group_Id__c = groupId;
      selectedDoc.Due_Date__c = dueDate;
      if (dueDate <= date.today())
        selectedDoc.Overdue__c = true;
      docClass.upsertDoc(selectedDoc);
      attachNewDoc = true;
    } else {
      errorMessage = 'Please enter a Document Name';
    }
  }

  public void saveDoc() {
    errorMessage = '';
    if (selectedDoc != null && selectedDoc.Name != null) {
      if (groupId != null && groupId != '')
        selectedDoc.Group_Id__c = groupId;
      selectedDoc.Due_Date__c = dueDate;
      if (dueDate <= date.today())
        selectedDoc.Overdue__c = true;
      else
        selectedDoc.Overdue__c = false;
      modHist =
        fdt +
        ': Modification Submitted by ' +
        currentUser.Contact.Name +
        ' (' +
        currentUser.Id +
        ')';
      if (selectedDoc.Modification_History__c == null)
        selectedDoc.Modification_History__c = modHist;
      else
        selectedDoc.Modification_History__c += ' \r\n' + modHist;
      docClass.upsertDoc(selectedDoc);
      displayDocPopup = false;
      getLists();
    } else {
      errorMessage = 'Please enter a Document Name';
    }
  }

  public void deleteDoc() {
    docClass.deleteDoc(selectedDoc);
    displayDeleteDocPopup = false;
    getLists();
  }

  public void deleteAtt() {
    attClass.deleteAttachment(selectedAtt);
    Document__c[] docs = [
      SELECT Status__c, (SELECT Id FROM Attachments)
      FROM Document__c
      WHERE Id = :selectedAtt.ParentId
    ];
    if (docs.size() > 0) {
      Document__c d = docs[0];
      if (d.Attachments.size() == 0) {
        d.Status__c = 'Requested';
        docClass.upsertDoc(d);
      }
    }
    displayDeleteAttPopup = false;
    getLists();
  }

  // BEGIN Popups
  public void showDocPopup() {
    selectedDoc = new Document__c();
    if (isNewDoc) {
      if (orgId != null) {
        selectedDoc.Organization__c = orgId;
        Account[] accts = [SELECT CEO_Email__c FROM Account WHERE Id = :orgId];
        if (accts.size() > 0)
          selectedDoc.CEO_Email__c = accts[0].CEO_Email__c;
      }
      if (grantId != null)
        selectedDoc.Grant__c = grantId;
      if (assessmentId != null)
        selectedDoc.Assessment__c = assessmentId;
      if (reportId != null)
        selectedDoc.Session_Report__c = reportId;
      if (requestId != null)
        selectedDoc.Reimbursement__c = requestId;
      if (newDocGroupId != null)
        selectedDoc.Group_Id__c = newDocGroupId;
    } else if (selectedDocId != null && selectedDocId != '') {
      List<Document__c> selectedDocs = docClass.getDocList(
        null,
        null,
        null,
        null,
        null,
        null,
        ' AND Id = \'' +
        selectedDocId +
        '\''
      );
      if (selectedDocs.size() > 0)
        selectedDoc = selectedDocs[0];
      if (selectedDoc.CEO_Email__c != null && selectedDoc.Recipient__c == null)
        selectedDoc.Recipient__c = selectedDoc.CEO_Email__c;
      selectedDoc.Previous_Due_Date__c = selectedDoc.Due_Date__c;
      dueDate = selectedDoc.Due_Date__c;
    }
    displayDocPopup = true;
  }
  public void cancelDocPopup() {
    errorMessage = '';
    if (attachNewDoc == true) {
      getLists();
    }
    selectedDocId = null;
    selectedDoc = new Document__c();
    displayDocPopup = false;
  }

  public void showDeleteDocPopup() {
    if (selectedDocId != null && selectedDocId != '') {
      Document__c[] docs = [
        SELECT Name, Status__c, Notes__c
        FROM Document__c
        WHERE Id = :Id.valueOf(selectedDocId)
      ];
      if (docs.size() > 0)
        selectedDoc = docs[0];
    }
    displayDeleteDocPopup = true;
  }
  public void cancelDeleteDocPopup() {
    selectedDocId = null;
    selectedDoc = new Document__c();
    displayDeleteDocPopup = false;
  }

  public void showDeleteAttPopup() {
    if (selectedAttId != null && selectedAttId != '') {
      Attachment[] atts = [
        SELECT Name, ParentId
        FROM Attachment
        WHERE Id = :Id.valueOf(selectedAttId)
      ];
      if (atts.size() > 0)
        selectedAtt = atts[0];
    }
    displayDeleteAttPopup = true;
  }
  public void cancelDeleteAttPopup() {
    selectedAttId = null;
    selectedAtt = new Attachment();
    displayDeleteAttPopup = false;
  }
}