force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Exp_Date__c</fullName>
    <label>DUNS Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Expired__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DUNS Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_Org_Code__c</fullName>
    <label>FirstPic Org Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <label>Hold Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <label>Group Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Has_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Has_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Attachment(s)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Overdue__c.field-meta.xml
<CustomField>
    <fullName>Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Session_Report__c.field-meta.xml
<CustomField>
    <fullName>Session_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Report</label>
    <referenceTo>Session_Report__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/Reimbursement_Item__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Item</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Item__c/fields/Budget_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Item__c</fullName>
    <label>Budget Item</label>
    <referenceTo>Budget_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Item__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement Item</label>
    <referenceTo>Reimbursement_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Request__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Request__c</fullName>
    <label>Reimbursement Request</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <formula>TEXT(Grant__r.Account__r.Hold_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hold Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <formula>Grant__r.Account__r.Name</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestObjectCtrls.cls
@isTest
public class TestObjectCtrls {
  static testMethod void test1() {
    Account a = new Account(
      EIN__c = '98-3846892',
      Name = 'National',
      FirstPic_Org_Code__c = 'BBBSA',
      CEO_Email__c = 'test@test.com',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert a;

    Account a2 = new Account(
      EIN__c = '98-1345654',
      Name = 'Local',
      National_Organization__c = a.id,
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a2;

    a2.DUNS_Exp_Date__c = date.today();
    a2.DUNS_Expired__c = true;
    update a2;
    Account a2test = [SELECT Hold_Status__c FROM Account WHERE Id = :a2.Id];
    //system.assertEquals('Hold', a2.Hold_Status__c);
    system.assertEquals(null, a2.Hold_Status__c);

    Contact c = new Contact(
      AccountId = a.Id,
      FirstName = 'Test',
      LastName = 'Qwerty',
      Email = 'asdf@wer.com'
    );
    insert c;

    Grant__c g = new Grant__c(
      Account__c = a.Id,
      Name = 'Test Grant',
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert g;

    Budget_Item__c bi = new Budget_Item__c(Grant__c = g.Id, Name = 'Test Item');
    insert bi;

    Reimbursement_Request__c r = new Reimbursement_Request__c(Grant__c = g.Id);
    insert r;

    Reimbursement_Request__c r2 = new Reimbursement_Request__c(Grant__c = g.Id);
    insert r2;

    List<Reimbursement_Request__c> requests = new List<Reimbursement_Request__c>();
    requests.add(r);
    requests.add(r2);

    Reimbursement_Item__c ri = new Reimbursement_Item__c(
      Reimbursement_Request__c = r.Id,
      Budget_Item__c = bi.Id
    );
    insert ri;

    Session_Report__c sr = new Session_Report__c(Site__c = a.Id);
    insert sr;

    Assessment__c sa = new Assessment__c(Organization__c = a.Id);
    insert sa;

    Document__c d = new Document__c(
      Name = 'Audit',
      Organization__c = a.Id,
      Grant__c = g.Id,
      Assessment__c = sa.Id,
      Reimbursement__c = r.Id,
      Session_Report__c = sr.Id
    );
    insert d;

    d.Overdue__c = true;
    update d;
    Account a1 = [SELECT Hold_Status__c FROM Account WHERE Id = :a.Id];
    //system.assertEquals('Hold', a1.Hold_Status__c);
    system.assertEquals(null, a1.Hold_Status__c);

    Blob body = Blob.valueOf('Test Body');
    Attachment att = new Attachment(
      Name = 'Item Att',
      body = body,
      parentId = d.id
    );
    insert att;
    Attachment att2 = new Attachment(
      Name = 'Item Att 2',
      body = body,
      parentId = d.id
    );
    insert att2;
    Document__c d2 = [
      SELECT Has_Attachments__c
      FROM Document__c
      WHERE Id = :d.Id
    ];
    system.assert(d2.Has_Attachments__c == true);

    system.Test.startTest();

    AccountClass ac = new AccountClass();
    ac.getAccountList();
    ac.getRelatedAccountList(a.Id, 'National Organization', '', '', null);

    ContactClass cc = new ContactClass();
    cc.getRelatedContactList(a.Id, 'Contact', null, null);
    cc.deleteContact(c);

    GrantClass gc = new GrantClass();
    gc.getGrantList();
    gc.getRelatedSubGrants(a.Id, null, '', 'Name', '', 'Test', '');
    gc.getGrant(g.Id);
    gc.upsertGrant(g);

    //ReportClass grc = new ReportClass();
    //grc.getReportList();

    SessionReportClass src = new SessionReportClass();
    src.getLatestReportId(a.Id);
    src.getReportList();

    List<Budget_Item__c> bi_list = new List<Budget_Item__c>();
    bi_list.add(bi);
    BudgetItemClass bic = new BudgetItemClass();
    bic.getBudgetItems(g.Id);
    bic.getBudgetItem(bi.Id);
    bic.upsertItem(bi);
    bic.upsertItems(bi_list);
    bic.deleteItems(bi_list);

    ReimbursementClass rc = new ReimbursementClass();
    rc.getRequestList();
    rc.getRelatedRequests(a.Id, g.Id, '', 'Name', '', 'Test', null, null);
    rc.getRelatedRequests(
      a.Id,
      null,
      'pendingfirst',
      'Name',
      'National',
      'Test',
      c.id,
      null
    );
    rc.getRequest(r.Id);
    rc.upsertRequest(r);
    rc.upsertRequestList(requests);
    rc.deleteRequest(r2);

    AssessmentClass sac = new AssessmentClass();
    sac.createAssessments(2019, false);
    //sac.getAssessment(sa.Id);
    //sac.upsertAssessment(sa);

    AttachmentCtrl attctrl = new AttachmentCtrl();
    attctrl.parentId = d.id;
    attctrl.getAttList();

    attctrl.fileName = 'Item Att';
    attctrl.filterByFileName = true;
    attctrl.getAttList();

    system.assertEquals(1, attctrl.att_list.size());

    attctrl.filterByFileName = false;
    attctrl.getAttList();
    system.assertEquals(2, attctrl.att_list.size());

    attctrl.showAttPopup();
    attctrl.hideAttPopup();
    attctrl.deleteAttId = att2.Id;
    attctrl.deleteAttById();

    AttachmentClass attc = new AttachmentClass();
    attc.deleteAttachment(att);

    /*
        Set<Id> ids = new Set<Id>();
        ids.add(d.Id);
        DocumentClass dcl = new DocumentClass();
        dcl.getHasAtts(ids);
        */

    // BEGIN Test Doc Ctrl
    DocumentCtrl dc = new DocumentCtrl();
    dc.fileNames = 'test';
    dc.requestId = r.Id;
    dc.setParams();
    dc.reportId = sr.Id;
    dc.getLists();
    dc.assessmentId = sa.Id;
    dc.getLists();
    dc.grantId = g.Id;
    dc.getLists();
    dc.groupId = 'test';
    system.assert(dc.doc_list.size() > 0);

    dc.showDocPopup();
    dc.selectedDoc.Name = 'New Doc';
    dc.saveDoc();
    dc.cancelDocPopup();
    Document__c[] docs1 = [SELECT Name FROM Document__c WHERE Grant__c = :g.Id];
    system.assert(docs1.size() == 2);

    dc.selectedDocId = d.Id;
    dc.isNewDoc = false;
    dc.showDocPopup();
    system.assert(dc.selectedDoc.Id != null);
    dc.saveAndContinue();

    dc.selectedAttId = att.Id;
    dc.showDeleteAttPopup();
    dc.deleteAtt();
    dc.cancelDeleteAttPopup();

    dc.selectedDocId = docs1[0].Id;
    dc.showDeleteDocPopup();
    dc.deleteDoc();
    dc.cancelDeleteDocPopup();

    Document__c[] docs2 = [
      SELECT Group_Id__c, Has_Attachments__c
      FROM Document__c
      WHERE Grant__c = :g.Id
    ];
    system.assert(docs2.size() == 1);
    system.assert(docs2[0].Group_Id__c == 'test');
    system.assert(docs2[0].Has_Attachments__c == false);
    Integer i = 0;
    for (Attachment atts : [
      SELECT Id
      FROM Attachment
      WHERE ParentId IN :docs2
    ]) {
      i++;
    }
    system.assert(i == 0);
    // END Test Doc Ctrl

    system.Test.stopTest();
  }
}