force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Email_text__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email_text__c</fullName>
    <formula>CEO__r.Email</formula>
    <label>CEO Email text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contacts_Need_Updating__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Need_Updating__c</fullName>
    <formula>OR(
CEO_Email__c != CEO_Email_text__c, 
AND(Local_Organization__r.CEO_Email__c != null, CEO_Email__c != Local_Organization__r.CEO_Email__c),
DOD_Email__c != DOD_Email_text__c, 
AND(Local_Organization__r.DOD_Email__c != null, DOD_Email__c != Local_Organization__r.DOD_Email__c),
Program_Coordinator_Email__c != Program_Coordinator_Email_text__c, 
AND(Local_Organization__r.Program_Coordinator_Email__c != null, Program_Coordinator_Email__c != Local_Organization__r.Program_Coordinator_Email__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contacts Need Updating</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOD__c.field-meta.xml
<CustomField>
    <fullName>DOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DOD</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Boys &amp; Girls Clubs in Indian Country</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (DOD)</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOD_Email__c.field-meta.xml
<CustomField>
    <fullName>DOD_Email__c</fullName>
    <label>DOD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOD_Email_text__c.field-meta.xml
<CustomField>
    <fullName>DOD_Email_text__c</fullName>
    <formula
  >IF(Local_Organization__r.DOD__c != null, Local_Organization__r.DOD__r.Email, DOD__r.Email)</formula>
    <label>DOD Email text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email_text__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email_text__c</fullName>
    <formula
  >IF(Local_Organization__r.Program_Coordinator__c != null, Local_Organization__r.Program_Coordinator__r.Email, Program_Coordinator__r.Email)</formula>
    <label>Program Coordinator Email text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateAccountRelatedContactFields.cls
public class UpdateAccountRelatedContactFields implements Schedulable {
  public void execute(SchedulableContext sc) {
    List<Account> items = new List<Account>();
    for (Account i : [
      SELECT
        Local_Organization__r.CEO__c,
        CEO__c,
        CEO_Email__c,
        CEO_Email_text__c,
        Local_Organization__r.DOD__c,
        DOD__c,
        DOD_Email__c,
        DOD_Email_text__c,
        Local_Organization__r.Program_Coordinator__c,
        Program_Coordinator__c,
        Program_Coordinator_Email__c,
        Program_Coordinator_Email_text__c
      FROM Account
      WHERE
        Contacts_Need_Updating__c = TRUE
        OR (Local_Organization__r.CEO__c != NULL
        AND CEO__c = NULL)
        OR (CEO_Email__c != NULL
        AND CEO_Email_text__c = NULL)
        OR (Local_Organization__r.DOD__c != NULL
        AND DOD__c = NULL)
        OR (DOD_Email__c != NULL
        AND DOD_Email_text__c = NULL)
        OR (Local_Organization__r.Program_Coordinator__c != NULL
        AND Program_Coordinator__c = NULL)
        OR (Program_Coordinator_Email__c != NULL
        AND Program_Coordinator_Email_text__c = NULL)
    ]) {
      if (i.Local_Organization__r.CEO__c != null && i.CEO__c == null)
        i.CEO__c = i.Local_Organization__r.CEO__c;
      if (i.CEO_Email__c != i.CEO_Email_text__c && i.CEO_Email_text__c != null)
        i.CEO_Email__c = i.CEO_Email_text__c;
      if (i.Local_Organization__r.DOD__c != null && i.DOD__c == null)
        i.DOD__c = i.Local_Organization__r.DOD__c;
      if (i.DOD_Email__c != i.DOD_Email_text__c && i.DOD_Email_text__c != null)
        i.DOD_Email__c = i.DOD_Email_text__c;
      if (
        i.Local_Organization__r.Program_Coordinator__c != null &&
        i.Program_Coordinator__c == null
      )
        i.Program_Coordinator__c = i.Local_Organization__r.Program_Coordinator__c;
      if (
        i.Program_Coordinator_Email__c != i.Program_Coordinator_Email_text__c &&
        i.Program_Coordinator_Email_text__c != null
      )
        i.Program_Coordinator_Email__c = i.Program_Coordinator_Email_text__c;
      items.add(i);
    }
    update items;
  }
}