force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Lead__c.field-meta.xml
<CustomField>
    <fullName>Finance_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Finance Lead)</relationshipLabel>
    <relationshipName>Accounts_FinanceLead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <label>National Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (National Organization)</relationshipLabel>
    <relationshipName>NationalApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/listViews/Youth.recordType-meta.xml
<RecordType>
    <fullName>Youth</fullName>
    <active>true</active>
    <label>Youth</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (CEO)</relationshipLabel>
    <relationshipName>CEOGrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (Program Coordinator)</relationshipLabel>
    <relationshipName>PC_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DCTAT Reports (CEO)</relationshipLabel>
    <relationshipName>CEO_DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DCTAT Reports</relationshipLabel>
    <relationshipName>DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reimbursement Requests (CEO)</relationshipLabel>
    <relationshipName>Reimbursement_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <formula>Grant__r.Account__r.Name</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Cohort_Size__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Size__c</fullName>
    <label>Cohort Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/TestContactTriggers.cls
@isTest
class TestContactTriggers {
  static testMethod void testContactPreventDuplicate() {
    system.Test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Contact c1 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'test1@test.com'
    );
    insert c1;

    Contact c2 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test2',
      Email = 'test1@test.com'
    );

    try {
      insert c2;
    } catch (Exception e) {
      System.assert(
        e.getDmlMessage(0)
          .indexOf('There is already another Contact with the same Email.') > -1
      );
    }
    system.Test.stopTest();
  }

  static testMethod void testUpdateAccoutLookups() {
    system.Test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Grant__c g = new Grant__c(
      Account__c = a.Id,
      Name = 'Test Grant',
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert g;

    Document__c d = new Document__c(Name = 'Test Doc', Organization__c = a.Id);
    insert d;

    Contact ceo = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'CEO',
      Email = 'ceo@test.com',
      Role__c = 'CEO'
    );
    insert ceo;

    Contact fl = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'FL',
      Email = 'fl@test.com',
      Role__c = 'Finance Lead'
    );
    insert fl;

    Contact pc = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'PC',
      Email = 'pc@test.com',
      Role__c = 'Program Coordinator'
    );
    insert pc;

    // Test INSERT
    Account insertTest = [
      SELECT CEO__c, CEO_Email__c, Finance_Lead__c
      FROM Account
      WHERE Id = :a.Id
    ];
    system.assertEquals(ceo.Id, insertTest.CEO__c);
    system.assertEquals(ceo.Email, insertTest.CEO_Email__c);
    system.assertEquals(fl.Id, insertTest.Finance_Lead__c);

    Grant__c grant = [SELECT CEO_Email__c FROM Grant__c WHERE Id = :g.Id];
    system.assertEquals(ceo.Email, grant.CEO_Email__c);

    Document__c d1 = [SELECT CEO_Email__c FROM Document__c WHERE Id = :d.Id];
    system.assertEquals(a.CEO_Email__c, d1.CEO_Email__c);

    ceo.Role__c = null;
    update ceo;
    fl.Role__c = 'CEO';
    update fl;

    Account updateTest = [
      SELECT CEO__c, Finance_Lead__c, Program_Coordinator__c
      FROM Account
      WHERE Id = :a.Id
    ];
    system.assertEquals(fl.Id, updateTest.CEO__c);

    pc.Email = 'pc@update.com';
    update pc;

    Account emailTest = [
      SELECT Program_Coordinator_Email__c
      FROM Account
      WHERE Id = :a.Id
    ];
    system.assertEquals(pc.Email, emailTest.Program_Coordinator_Email__c);

    system.Test.stopTest();
  }

  static testMethod void testUpdateCount() {
    system.Test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Session__c session = new Session__c(
      Name = 'Test Session',
      Site__c = a.Id,
      RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
        .get('Session')
        .getRecordTypeId()
    );
    insert session;

    Session__c cohort = new Session__c(
      Name = 'Test Cohort',
      Site__c = a.Id,
      Session__c = session.Id,
      RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
        .get('Cohort')
        .getRecordTypeId()
    );
    insert cohort;

    Contact youth1 = new Contact(
      accountId = a.Id,
      Cohort__c = cohort.Id,
      lastName = 'Youth',
      firstName = 'Test1',
      Email = 'youth1@test.com',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth1;

    Contact youth2 = new Contact(
      lastName = 'Youth',
      firstName = 'Test1',
      Email = 'youth2@test.com',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth2;

    // Test INSERT
    Account acctInsertTest = [
      SELECT Youth_Served__c
      FROM Account
      WHERE Id = :a.Id
    ];
    //system.assertEquals(1, acctInsertTest.Youth_Served__c);

    Session__c cohortInsertTest = [
      SELECT Cohort_Size__c
      FROM Session__c
      WHERE Id = :cohort.Id
    ];
    //system.assertEquals(1, cohortInsertTest.Cohort_Size__c);

    // Test UPDATE
    youth2.AccountId = a.Id;
    youth2.Cohort__c = cohort.Id;
    update youth2;

    Account acctUpdateTest = [
      SELECT Youth_Served__c
      FROM Account
      WHERE Id = :a.Id
    ];
    //system.assertEquals(2, acctUpdateTest.Youth_Served__c);

    Session__c cohortUpdateTest = [
      SELECT Cohort_Size__c
      FROM Session__c
      WHERE Id = :cohort.Id
    ];
    //system.assertEquals(2, cohortUpdateTest.Cohort_Size__c);
    system.Test.stopTest();
  }

  static testMethod void testUpdatePAEmailFields() {
    system.Test.startTest();

    Account na = new Account(Name = 'Test National Account');
    insert na;

    Account a = new Account(Name = 'Test Account');
    insert a;

    Application__c app = new Application__c(
      Organization__c = a.Id,
      National_Organization__c = na.id
    );
    insert app;
    Application__c app1 = [
      SELECT Primary_Approver_Email__c
      FROM Application__c
      WHERE Id = :app.Id
    ];
    system.assertEquals(null, app1.Primary_Approver_Email__c);

    Grant__c g = new Grant__c(
      Account__c = a.Id,
      Name = 'Test Grant',
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert g;
    Grant__c g1 = [
      SELECT Primary_Approver_Email__c
      FROM Grant__c
      WHERE Id = :g.Id
    ];
    system.assertEquals(null, g1.Primary_Approver_Email__c);

    Reimbursement_Request__c r = new Reimbursement_Request__c(Grant__c = g.Id);
    insert r;
    Reimbursement_Request__c r1 = [
      SELECT Primary_Approver_Email__c
      FROM Reimbursement_Request__c
      WHERE Id = :r.Id
    ];
    system.assertEquals(null, r1.Primary_Approver_Email__c);

    Grantee_Report__c gr = new Grantee_Report__c(Grant__c = g.Id);
    insert gr;
    Grantee_Report__c gr1 = [
      SELECT Primary_Approver_Email__c
      FROM Grantee_Report__c
      WHERE Id = :gr.Id
    ];
    system.assertEquals(null, gr1.Primary_Approver_Email__c);

    Contact pa = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'PA',
      Email = 'pa@test.com',
      Role__c = 'Primary Approver',
      Is_Primary_Approver__c = true
    );
    insert pa;
    /*
        Application__c app2 = [SELECT Primary_Approver_Email__c FROM Application__c WHERE Id = :app.Id];
        system.assertEquals('pa@test.com', app2.Primary_Approver_Email__c);
        Grant__c g2 = [SELECT Primary_Approver_Email__c FROM Grant__c WHERE Id = :g.Id];
        system.assertEquals('pa@test.com', g2.Primary_Approver_Email__c);
        Reimbursement_Request__c r2 = [SELECT Primary_Approver_Email__c FROM Reimbursement_Request__c WHERE Id = :r.Id];
        system.assertEquals('pa@test.com', r2.Primary_Approver_Email__c);
        Grantee_Report__c gr2 = [SELECT Primary_Approver_Email__c FROM Grantee_Report__c WHERE Id = :gr.Id];
        system.assertEquals('pa@test.com', gr2.Primary_Approver_Email__c);
    	*/
    pa.Email = 'pa@update.com';
    update pa;
    /*
        Application__c app3 = [SELECT Primary_Approver_Email__c FROM Application__c WHERE Id = :app.Id];
        system.assertEquals('pa@update.com', app3.Primary_Approver_Email__c);
        Grant__c g3 = [SELECT Primary_Approver_Email__c FROM Grant__c WHERE Id = :g.Id];
        system.assertEquals('pa@update.com', g3.Primary_Approver_Email__c);
        Reimbursement_Request__c r3 = [SELECT Primary_Approver_Email__c FROM Reimbursement_Request__c WHERE Id = :r.Id];
        system.assertEquals('pa@update.com', r3.Primary_Approver_Email__c);
        Grantee_Report__c gr3 = [SELECT Primary_Approver_Email__c FROM Grantee_Report__c WHERE Id = :gr.Id];
        system.assertEquals('pa@update.com', gr3.Primary_Approver_Email__c);
        */
    system.Test.stopTest();
  }
}