force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOD_Email__c.field-meta.xml
<CustomField>
    <fullName>DOD_Email__c</fullName>
    <label>DOD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Reports (CEO)</relationshipLabel>
    <relationshipName>CEO_Session_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Site__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Reports (Program Coordinator)</relationshipLabel>
    <relationshipName>PC_Session_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <label>Reporting Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017-2018 Q1</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q2</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q3</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q4</fullName>
            </value>
            <value>
                <fullName>2017 Q4</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q1</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q2</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q3</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q4</fullName>
            </value>
            <value>
                <fullName>2018 Q1</fullName>
            </value>
            <value>
                <fullName>2018 Q2</fullName>
            </value>
            <value>
                <fullName>2018 Q3</fullName>
            </value>
            <value>
                <fullName>2018 Q4</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q1</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q2</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q3</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q4</fullName>
            </value>
            <value>
                <fullName>2019 Q1</fullName>
            </value>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017-2018</fullName>
            </value>
            <value>
                <fullName>2018-2019</fullName>
            </value>
            <value>
                <fullName>2019-2020</fullName>
            </value>
            <value>
                <fullName>2020-2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateQuarterlySessionReports.cls
public class CreateQuarterlySessionReports implements Schedulable {
  private GetMonthAsString gms = new GetMonthAsString();

  public void execute(SchedulableContext sc) {
    Date dt = date.today();
    GetMonthAsString gms = new GetMonthAsString();
    String month = gms.getMonth(dt.month());
    String thisYear = string.valueOf(dt.year());
    String nextYear = string.valueOf(dt.year() + 1);
    String prevYear = string.valueOf(dt.year() - 1);
    String reportingPeriod = '';
    String yearRange = prevYear + '-' + thisYear;
    if (month == 'February') {
      reportingPeriod = yearRange + ' Q2';
    } else if (month == 'May') {
      reportingPeriod = yearRange + ' Q3';
    } else if (month == 'August') {
      reportingPeriod = yearRange + ' Q4';
    } else if (month == 'November') {
      yearRange = thisYear + '-' + nextYear;
      reportingPeriod = yearRange + ' Q1';
    }

    if (
      month == 'February' ||
      month == 'May' ||
      month == 'August' ||
      month == 'November'
    ) {
      List<Session_Report__c> reports = new List<Session_Report__c>();
      for (Account a : [
        SELECT
          Id,
          Name,
          Local_Organization__r.CEO__c,
          Local_Organization__r.CEO_Email__c,
          Local_Organization__r.Program_Coordinator__c,
          Local_Organization__r.Program_Coordinator_Email__c,
          Local_Organization__r.DOD_Email__c
        FROM Account
        WHERE
          FirstPic_National_Org_Code__c = 'NCAI'
          AND RecordType.Name = 'Site'
          AND Is_Active__c = TRUE
      ]) {
        String name = a.Name;
        List<String> elems = name.split(' ');
        name = '';
        for (String x : elems) {
          name += x.substring(0, 1).toUpperCase();
        }
        name = name.replace('&', '');
        name = name.replace('(', '');
        name = name.replace('-', '');

        Session_Report__c report = new Session_Report__c(
          Name = name + ' ' + reportingPeriod + ' Progress Report',
          Status__c = 'Not Started',
          Site__c = a.Id,
          Reporting_Period__c = reportingPeriod,
          Year__c = yearRange,
          CEO__c = a.Local_Organization__r.CEO__c,
          CEO_Email__c = a.Local_Organization__r.CEO_Email__c,
          Program_Coordinator__c = a.Local_Organization__r.Program_Coordinator__c,
          Program_Coordinator_Email__c = a.Local_Organization__r.Program_Coordinator_Email__c,
          DOD_Email__c = a.Local_Organization__r.DOD_Email__c,
          RecordTypeID = Schema.SObjectType.Session_Report__c.getRecordTypeInfosByName()
            .get('Progress Report')
            .getRecordTypeId()
        );
        reports.add(report);
      }
      insert reports;
    }
  }
}