force-app/main/default/objects/Account/fields/CEO_Email_text__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email_text__c</fullName>
    <formula>CEO__r.Email</formula>
    <label>CEO Email text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child Safety</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contract Specialists</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Other Costs</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Sub Awards</fullName>
            </value>
            <value>
                <fullName>Consultant Travel</fullName>
            </value>
            <value>
                <fullName>Indirect Costs</fullName>
            </value>
            <value>
                <fullName>Procurement Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Fringe_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Fringe_Benefits__c</fullName>
    <label>Fringe Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description
  >If employee is salaried, hourly rate is calculated as follows: Salary divided by 2,080 = 40 hour/week Hourly Rate. See http://www.calculators.org/savings/wage-conversion.php.</description>
    <label>Hourly Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Hourly__c.field-meta.xml
<CustomField>
    <fullName>Is_Hourly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hourly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: Rate (hourly) * Projected Grant Hours * Number of Weeks (fringe not included);
All Other Personnel: Wages + Fringe Benefits
Expenses: Rate * Quantity</inlineHelpText>
    <label>Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Fringe_Benefits__c.field-meta.xml
<CustomField>
    <fullName>New_Fringe_Benefits__c</fullName>
    <label>New Fringe Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>New_Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: New Rate (hourly) * Projected Grant Hours * Number of Weeks;
All Other Personnel: New Wages + New Fringe Benefits
Expenses: New Rate * Quantity</inlineHelpText>
    <label>New Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Rate__c</fullName>
    <label>New Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Wages__c.field-meta.xml
<CustomField>
    <fullName>New_Wages__c</fullName>
    <label>New Wages</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <inlineHelpText>Used by BBBSA and NPAL only</inlineHelpText>
    <label>Total Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Wages__c.field-meta.xml
<CustomField>
    <fullName>Wages__c</fullName>
    <label>Wages</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO_Email_text__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email_text__c</fullName>
    <formula>Account__r.CEO_Email_text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEO Email (formula field)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Indirect_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate_Amount__c</fullName>
    <label>Indirect Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/LOA_Sent__c.field-meta.xml
<CustomField>
    <fullName>LOA_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LOA Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Status__c</fullName>
    <formula>TEXT(National_Grant__r.Grant_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/New_Indirect_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Indirect_Rate_Amount__c</fullName>
    <label>New Indirect Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Previously_Awarded_Amount__c.field-meta.xml
<CustomField>
    <fullName>Previously_Awarded_Amount__c</fullName>
    <label>Previously Awarded Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursements_Pending_Approval__c.field-meta.xml
<CustomField>
    <fullName>Reimbursements_Pending_Approval__c</fullName>
    <label>Reimbursements Pending Approval</label>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value
    >Pending First Approval, Pending Second Approval, Pending Third Approval, Pending Fourth Approval, Pending Final Approval, Submitted</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <label>Use Indirect Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Report_Status__c</fullName>
    <label>Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubGrantDetailsController.cls
public with sharing class SubGrantDetailsController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String approverLevel { get; set; }
  public String portalName { get; set; }

  private GrantClass gc = new GrantClass();
  private BudgetItemClass bic = new BudgetItemClass();
  private getIdFromString gifs = new getIdFromString();
  private ContactClass cc = new ContactClass();
  private AccountClass ac = new AccountClass();

  public Account acct { get; set; }
  public Grant__c grant { get; set; }
  public ID grantId { get; set; }
  public Boolean isNationalSubGrant { get; set; }

  public Map<String, List<Budget_Item__c>> expense_map { get; set; }
  public Map<String, List<Budget_Item__c>> labor_map { get; set; }
  public Boolean hasLabor { get; set; }
  public Boolean hasExpenses { get; set; }

  public String statusColor { get; set; }
  public String errorMessage { get; set; }
  public Boolean editMode { get; set; }
  public Boolean incompleteReport { get; set; }
  public Boolean sendBack { get; set; }
  public Boolean deny { get; set; }
  public Boolean canCloseGrant { get; set; }
  public Boolean canReopenGrant { get; set; }

  public Decimal laborRequestedAmount { get; set; }
  public Decimal expenseRequestedAmount { get; set; }
  public Decimal updatedRequestedAmount { get; set; }

  public List<Contact> contacts { get; set; }
  public String boardMemberEmail { get; set; }
  public Boolean sendLOASuccessful { get; set; }
  public Boolean sendFFATASuccessful { get; set; }
  public Boolean sendGCLSuccessful { get; set; }

  public Boolean displayPopupBg { get; set; }
  public Boolean displayLaborNotesPopup { get; set; }
  public Boolean displayExpenseNotesPopup { get; set; }
  public Boolean displayBudgetNotesPopup { get; set; }
  public Boolean displayCloseGrantPopup { get; set; }
  public Boolean displayLOAPopup { get; set; }

  public String newModification { get; set; }
  public Boolean displayModificationPopup { get; set; }
  public Boolean updatePopupNeeded { get; set; }
  public Boolean displayUpdatePopup { get; set; }
  public Boolean displayAwardPopup { get; set; }

  public List<Attachment> att_list { get; set; }

  // BEGIN Constructor
  public SubGrantDetailsController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    approverLevel = userClass.approverLevel;
    portalName = userClass.userProfile;
    if (portalName == 'BBBS')
      portalName = '';

    isNationalSubGrant = false;
    expense_map = new Map<String, List<Budget_Item__c>>();
    labor_map = new Map<String, List<Budget_Item__c>>();
    hasLabor = false;
    hasExpenses = false;

    editMode = false;
    incompleteReport = false;
    sendBack = false;
    deny = false;
    laborRequestedAmount = 0;
    expenseRequestedAmount = 0;
    updatedRequestedAmount = 0;

    displayPopupBg = false;
    displayExpenseNotesPopup = false;
    displayBudgetNotesPopup = false;
    displayModificationPopup = false;
    newModification = '';

    contacts = new List<Contact>();
    att_list = new List<Attachment>();

    String urlGrantId = ApexPages.currentPage().getParameters().get('grantId');
    grantId = gifs.getId(urlGrantId);
    getGrant();
  }
  // END Constructor

  public void getGrant() {
    labor_map.clear();
    expense_map.clear();

    if (grantId != null || grant.Id != null) {
      grant = gc.getGrant(grantId);
      String name = grant.Name;
      if (
        name.contains('JJ2') ||
        name.contains('JJ5') ||
        name.contains('JJ6')
      ) {
        updatePopupNeeded = true;
      }
      for (Attachment a : grant.Attachments) {
        att_list.add(a);
      }
      acct = ac.getAccount(grant.Account__r.Id); //[SELECT ID, Name, RecordType.Name FROM Account WHERE ID = :grant.Account__r.Id];
      for (Contact c : cc.getContactPopupList(acct.Id)) {
        //                if(c.Role__c != null && c.Role__c.contains('Board'))
        if (c.RecordType.Name == 'Contact')
          contacts.add(c);
      }

      canCloseGrant = false;
      canReopenGrant = false;
      if (userAcctType == 'National Organization') {
        if (
          grant.Grant_Status__c != 'Closed' &&
          grant.Reimbursements_Pending_Approval__c == 0
        )
          canCloseGrant = true;
        if (
          grant.Grant_Status__c == 'Closed' &&
          grant.National_Grant_Status__c != 'Closed'
        )
          canReopenGrant = true;
      }

      if (
        grant.Grant_Status__c == null ||
        grant.Grant_Status__c == 'Pending Review' ||
        grant.Grant_Status__c == 'Budget Submitted' ||
        grant.Grant_Status__c == 'Revisions Needed'
      ) {
        editMode = true;
        statusColor = 'text-warning';
      }
      if (grant.Grant_Status__c == 'Denied') {
        statusColor = 'text-danger';
      }
      if (
        grant.Grant_Status__c == 'Approved' ||
        grant.Grant_Status__c == 'Awarded'
      ) {
        statusColor = 'text-success';
      }

      if (
        userAcctType == 'National Organization' &&
        grant.Account__r.Id == userAcct.Id
      ) {
        isNationalSubGrant = true;
      }

      for (Grantee_Report__c gr : [
        SELECT Id, Report_Status__c
        FROM Grantee_Report__c
        WHERE Grant__r.Id = :GrantId
      ]) {
        system.debug('>>> gr = ' + gr);
        if (gr.Report_Status__c == 'In Progress') {
          incompleteReport = true;
        }
      }

      for (Budget_Item__c bi : bic.getBudgetItems(GrantId)) {
        if (bi.RecordType.Name == 'Expense') {
          if (bi.New_Rate__c > 0) {
            if (bi.Total_Expense__c > 0) {
              if (bi.Total_Expense__c == bi.New_Rate__c) {
                bi.New_Rate__c = null;
              }
            }
          }
          if (bi.New_Item_Budget__c > 0) {
            if (bi.Item_Budget__c > 0) {
              if (bi.Item_Budget__c == bi.New_Item_Budget__c) {
                bi.New_Item_Budget__c = null;
              }
            }
          }
          if (
            (grant.Grant_Status__c == 'Approved' ||
            grant.Grant_Status__c == 'Awarded' ||
            grant.Grant_Status__c == 'Denied' ||
            grant.Grant_Status__c == 'Closed') && bi.Item_Budget__c != null
          ) {
            expenseRequestedAmount += bi.Item_Budget__c;
          } else {
            if (bi.New_Item_Budget__c != null) {
              expenseRequestedAmount += bi.New_Item_Budget__c;
            } else if (bi.Item_Budget__c != null) {
              expenseRequestedAmount += bi.Item_Budget__c;
            }
          }
          if (expense_map.containsKey(bi.Category__c)) {
            List<Budget_Item__c> bi_list = expense_map.get(bi.Category__c);
            bi_list.add(bi);
            expense_map.put(bi.Category__c, bi_list);
          } else {
            expense_map.put(bi.Category__c, new List<Budget_Item__c>{ bi });
          }
          if (expense_map.keySet() != null) {
            hasExpenses = true;
          }
        } else {
          if (labor_map.containsKey(bi.Category__c)) {
            List<Budget_Item__c> bi_list = labor_map.get(bi.Category__c);
            bi_list.add(bi);
            labor_map.put(bi.Category__c, bi_list);
          } else {
            labor_map.put(bi.Category__c, new List<Budget_Item__c>{ bi });
          }
          if (labor_map.keySet() != null) {
            hasLabor = true;
          }
          if (
            grant.Grant_Status__c == 'Approved' ||
            grant.Grant_Status__c == 'Awarded' ||
            grant.Grant_Status__c == 'Denied' ||
            grant.Grant_Status__c == 'Closed'
          ) {
            if (bi.Wages__c != null && portalName != '') {
              laborRequestedAmount += bi.Wages__c;
            } else if (bi.Item_Budget__c != null) {
              laborRequestedAmount += bi.Item_Budget__c;
            }
            if (bi.Fringe_Benefits__c != null) {
              laborRequestedAmount += bi.Fringe_Benefits__c;
            }
          } else {
            if (bi.New_Wages__c != null && portalName != '') {
              laborRequestedAmount += bi.New_Wages__c;
            } else if (bi.Wages__c != null && portalName != '') {
              laborRequestedAmount += bi.Wages__c;
            } else if (bi.New_Item_Budget__c != null) {
              laborRequestedAmount += bi.New_Item_Budget__c;
            } else if (bi.Item_Budget__c != null) {
              laborRequestedAmount += bi.Item_Budget__c;
            }
            if (bi.New_Fringe_Benefits__c != null) {
              laborRequestedAmount += bi.New_Fringe_Benefits__c;
            } else if (bi.Fringe_Benefits__c != null) {
              laborRequestedAmount += bi.Fringe_Benefits__c;
            }
          }
        }
      }
      updatedRequestedAmount = laborRequestedAmount + expenseRequestedAmount;
      if (grant.Use_Indirect_Rate__c == 'Yes') {
        if (grant.New_Indirect_Rate_Amount__c != null) {
          updatedRequestedAmount += grant.New_Indirect_Rate_Amount__c;
        } else if (grant.Indirect_Rate_Amount__c != null) {
          updatedRequestedAmount += grant.Indirect_Rate_Amount__c;
        }
      }
      updatedRequestedAmount.setScale(2);
    }
  }

  public void saveNotes() {
    gc.upsertGrant(grant);
    displayBudgetNotesPopup = false;
  }

  public void updateAward() {
    Date dt = date.today();
    String fdt = dt.format();
    String mh =
      fdt +
      ': Award Amount changed from ' +
      grant.Previously_Awarded_Amount__c +
      ' to ' +
      grant.Amount__c +
      ' by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (grant.Modification_History__c == null)
      grant.Modification_History__c = '';
    grant.Modification_History__c += ' \r\n' + mh;
    gc.upsertGrant(grant);
    displayAwardPopup = false;
  }

  public PageReference saveAndClose() {
    gc.upsertGrant(grant);

    List<Budget_Item__c> bi_update_list = new List<Budget_Item__c>();
    List<List<Budget_Item__c>> expense_list = expense_map.values();
    for (Integer i = 0; i < expense_list.size(); i++) {
      for (Budget_Item__c bi : expense_list.get(i)) {
        bi_update_list.add(bi);
      }
    }
    List<List<Budget_Item__c>> labor_list = labor_map.values();
    for (Integer i = 0; i < labor_list.size(); i++) {
      for (Budget_Item__c bi : labor_list.get(i)) {
        bi_update_list.add(bi);
      }
    }
    try {
      bic.upsertItems(bi_update_list);
      System.Debug(
        '>>>> Budget list update successful. bi_update_list = ' + bi_update_list
      );

      PageReference pr = new PageReference('/SubGrants');
      pr.setRedirect(true);
      return pr;
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
    }
    return null;
  }

  public PageReference sendBack() {
    Date dt = date.today();
    String fdt = dt.format();
    String mh =
      fdt +
      ': Returned for corrections by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (grant.Modification_History__c == null) {
      grant.Modification_History__c = '';
    }
    grant.Modification_History__c += ' \r\n' + mh;

    grant.Grant_Status__c = 'Revisions Needed';
    gc.upsertGrant(grant);

    PageReference pr = new PageReference('/SubGrants');
    pr.setRedirect(true);
    return pr;
  }

  public PageReference approveBudget() {
    Date dt = date.today();
    String fdt = dt.format();
    String mh =
      fdt +
      ': Approved by ' +
      currentUser.Contact.Name +
      ' (' +
      currentUser.Id +
      ')';
    if (grant.Modification_History__c == null) {
      grant.Modification_History__c = '';
    }
    grant.Modification_History__c += ' \r\n' + mh;

    grant.Grant_Status__c = 'Approved';
    if (grant.New_Indirect_Rate_Amount__c != null) {
      grant.Indirect_Rate_Amount__c = grant.New_Indirect_Rate_Amount__c;
      grant.New_Indirect_Rate_Amount__c = null;
    }
    gc.upsertGrant(grant);

    List<Budget_Item__c> bi_approve_list = new List<Budget_Item__c>();
    List<List<Budget_Item__c>> expense_list = expense_map.values();
    for (Integer i = 0; i < expense_list.size(); i++) {
      for (Budget_Item__c bi : expense_list.get(i)) {
        if (bi.New_Item_Budget__c != null) {
          bi.Item_Budget__c = bi.New_Item_Budget__c;
          bi.New_Item_Budget__c = null;
        }
        if (bi.New_Rate__c != null) {
          bi.Total_Expense__c = bi.New_Rate__c;
          bi.New_Rate__c = null;
        }
        bi_approve_list.add(bi);
      }
    }
    List<List<Budget_Item__c>> labor_list = labor_map.values();
    for (Integer i = 0; i < labor_list.size(); i++) {
      for (Budget_Item__c bi : labor_list.get(i)) {
        if (bi.New_Item_Budget__c != null) {
          bi.Item_Budget__c = bi.New_Item_Budget__c;
          bi.New_Item_Budget__c = null;
        }
        if (bi.New_Wages__c != null) {
          bi.Wages__c = bi.New_Wages__c;
          bi.New_Wages__c = null;
        }
        if (bi.New_Fringe_Benefits__c != null) {
          bi.Fringe_Benefits__c = bi.New_Fringe_Benefits__c;
          bi.New_Fringe_Benefits__c = null;
        }
        /*
                if(bi.New_Rate__c != null) {
                    if(bi.Is_Hourly__c) {
                        bi.Hourly_Rate__c = bi.New_Rate__c;
                    } else {
                        bi.Salary__c = bi.New_Rate__c;
                        bi.Hourly_Rate__c = bi.New_Rate__c / 2080;
                    }
                    bi.New_Rate__c = null;
                }
                */
        bi_approve_list.add(bi);
      }
    }
    try {
      bic.upsertItems(bi_approve_list);
      System.Debug(
        '>>>> Budget list update successful. bi_approve_list = ' +
        bi_approve_list
      );
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
    }
    editMode = false;

    PageReference pr = new PageReference(
      '/' +
      portalName +
      'SubGrantDetails?GrantID=' +
      GrantID
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference denyBudget() {
    if (
      grant.Previous_Status__c != null &&
      grant.Previous_Status__c != 'Pending Review' &&
      grant.Previous_Status__c != 'Budget Submitted'
    ) {
      grant.Grant_Status__c = grant.Previous_Status__c;
    } else {
      grant.Grant_Status__c = 'Denied';
    }
    gc.upsertGrant(grant);

    List<Budget_Item__c> bi_deny_list = new List<Budget_Item__c>();
    List<List<Budget_Item__c>> expense_list = expense_map.values();
    for (Integer i = 0; i < expense_list.size(); i++) {
      for (Budget_Item__c bi : expense_list.get(i)) {
        bi.New_Item_Budget__c = null;
        bi.New_Rate__c = null;
        bi_deny_list.add(bi);
      }
    }
    List<List<Budget_Item__c>> labor_list = labor_map.values();
    for (Integer i = 0; i < labor_list.size(); i++) {
      for (Budget_Item__c bi : labor_list.get(i)) {
        bi.New_Item_Budget__c = null;
        bi.New_Rate__c = null;
        bi.New_Fringe_Benefits__c = null;
        bi_deny_list.add(bi);
      }
    }
    try {
      bic.upsertItems(bi_deny_list);
      System.Debug(
        '>>>> Budget list update successful. bi_deny_list = ' + bi_deny_list
      );
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
    }
    editMode = false;

    PageReference pr = new PageReference(
      '/' +
      portalName +
      'SubGrantDetails?GrantID=' +
      GrantID
    );
    pr.setRedirect(true);
    return pr;
  }

  public void saveModification() {
    if (newModification != '') {
      Date dt = date.today();
      String fdt = dt.format();
      String mh =
        fdt +
        ': ' +
        newModification +
        ' (' +
        currentUser.Contact.Name +
        ', ' +
        currentUser.Id +
        ')';
      if (grant.Modification_History__c == null) {
        grant.Modification_History__c = '';
      }
      grant.Modification_History__c += ' \r\n' + mh;
      gc.upsertGrant(grant);
    }
    displayModificationPopup = false;
  }

  // BEGIN closeGrant
  public void closeGrant() {
    gc.closeGrant(grant.Id);
    hideCloseGrantPopup();
    getGrant();
  }

  public void reopenGrant() {
    gc.reopenGrant(grant.Id);
    getGrant();
  }
  // END closeGrant

  // BEGIN sendDocs
  public void sendLOA() {
    errorMessage = '';
    SendSertifiDoc ssd = new SendSertifiDoc();
    ssd.SendSertifiDoc(
      'LOA',
      UserInfo.getUserEmail(),
      grant.CEO_Email_text__c,
      boardMemberEmail,
      grant.Id,
      'NPAL_LOA.pdf',
      null
    );
    if (!ApexPages.hasMessages()) {
      sendLOASuccessful = true;
      grant.LOA_Sent__c = true;
      gc.upsertGrant(grant);
    } else
      errorMessage = String.valueOf(ApexPages.getMessages());
    displayLOAPopup = false;
  }
  public void sendFFATA() {
    errorMessage = '';
    SendSertifiDoc ssd = new SendSertifiDoc();
    ssd.SendSertifiDoc(
      'FFATA',
      UserInfo.getUserEmail(),
      grant.CEO_Email_text__c,
      null,
      grant.Id,
      'NPAL_FFATA.pdf',
      null
    );
    if (!ApexPages.hasMessages())
      sendFFATASuccessful = true;
    else
      errorMessage = String.valueOf(ApexPages.getMessages());
  }
  public void sendGCL() {
    errorMessage = '';
    SendSertifiDoc ssd = new SendSertifiDoc();
    ssd.SendSertifiDoc(
      'Grant Closeout Letter',
      UserInfo.getUserEmail(),
      grant.CEO_Email_text__c,
      null,
      grant.Id,
      'NPAL_GCL.pdf',
      null
    );
    if (!ApexPages.hasMessages())
      sendGCLSuccessful = true;
    else
      errorMessage = String.valueOf(ApexPages.getMessages());
  }
  // END sendDocs

  // BEGIN popups
  public void showLaborNotesPopup() {
    displayLaborNotesPopup = true;
  }

  public void closeLaborNotesPopup() {
    displayLaborNotesPopup = false;
  }

  public void showExpenseNotesPopup() {
    displayExpenseNotesPopup = true;
  }

  public void closeExpenseNotesPopup() {
    displayExpenseNotesPopup = false;
  }

  public void cancelBudgetNotesPopup() {
    displayBudgetNotesPopup = false;
  }

  public void updateNotesPopup() {
    sendBack = false;
    deny = false;
    displayBudgetNotesPopup = true;
  }

  public void sendBackPopup() {
    sendBack = true;
    deny = false;
    displayBudgetNotesPopup = true;
  }

  public void denyPopup() {
    sendBack = false;
    deny = true;
    displayBudgetNotesPopup = true;
  }

  public void modificationPopup() {
    displayModificationPopup = true;
  }

  public void cancelModificationPopup() {
    displayModificationPopup = false;
  }

  public void updatePopup() {
    displayUpdatePopup = true;
  }

  public void cancelUpdatePopup() {
    displayUpdatePopup = false;
  }

  public void showAwardPopup() {
    grant.Previously_Awarded_Amount__c = grant.Amount__c;
    displayAwardPopup = true;
  }
  public void hideAwardPopup() {
    displayAwardPopup = false;
  }

  public void showCloseGrantPopup() {
    displayCloseGrantPopup = true;
  }
  public void hideCloseGrantPopup() {
    displayCloseGrantPopup = false;
  }

  public void showLOAPopup() {
    displayLOAPopup = true;
  }
  public void hideLOAPopup() {
    displayLOAPopup = false;
  }
}