force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Lead__c.field-meta.xml
<CustomField>
    <fullName>Finance_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Finance Lead)</relationshipLabel>
    <relationshipName>Accounts_FinanceLead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insurance_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiration_Date__c</fullName>
    <label>Insurance Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Provider__c</fullName>
    <label>Insurance Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Assessment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Status__c</fullName>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Fiscal_Year_Ended__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_Ended__c</fullName>
    <label>Fiscal Year Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/S25_Standards__c.field-meta.xml
<CustomField>
    <fullName>S25_Standards__c</fullName>
    <label>S25: Standards</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assessment_Response</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/S25_Standards_Text__c.field-meta.xml
<CustomField>
    <fullName>S25_Standards_Text__c</fullName>
    <label>S25: Standards Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
                <isActive>false</isActive>
                <label>Resubmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>IF(Assessment__c != null, TEXT(Assessment__r.Year__c), 
IF(Grant__c != null, Grant__r.Year__c, 
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssessmentControllers.cls
@isTest
class TestAssessmentControllers {
  static testMethod void test1() {
    System.Test.startTest();
    Date dt = Date.today();

    Account a1 = new Account(
      EIN__c = '98-7654321',
      Name = 'Org Test',
      Status__c = 'Approved',
      Insurance_Provider__c = 'test',
      Insurance_Expiration_Date__c = dt,
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a1;

    Contact ceo = new Contact(
      accountId = a1.Id,
      lastName = 'CEO',
      firstName = 'Test1',
      Email = 'ceo@example.com'
    );
    insert ceo;

    Contact fl = new Contact(
      accountId = a1.Id,
      lastName = 'FL',
      firstName = 'Test1',
      Email = 'fl@example.com'
    );
    insert fl;

    a1.CEO__c = ceo.Id;
    a1.Finance_Lead__c = fl.Id;
    update a1;

    Assessment__c sa = new Assessment__c(
      Organization__c = a1.Id,
      S25_Standards__c = 'Out',
      S25_Standards_Text__c = 'test',
      Fiscal_Year_Ended__c = dt,
      Year__c = 2017,
      Assessment_Status__c = 'Incomplete'
    );
    insert sa;

    List<Document__c> doc_list = new List<Document__c>();
    Set<String> names = new Set<String>();
    names.add('Strategic Plan');
    names.add('Fund Development Plan');
    names.add('Code of Ethics');
    names.add('Whistleblowers');
    names.add('Separation of Duties for Fiscal Control');
    names.add('Board Development Plan');
    names.add('Written Succession Plan');
    names.add('Audit');
    names.add('Program Manual');
    names.add('Verification Letter');
    names.add('Affiliation Fee Form');
    names.add('AIM Fee Form');
    names.add('Proof of Insurance');
    names.add('Income Statement');
    names.add('Supporting Documentation');
    names.add('Organizational Chart');
    names.add('Bylaws');
    names.add('Advisory Plan');
    names.add('Network Growth Goals');
    names.add('Program Manual');
    names.add('Technology Licenses Form');

    for (String n : names) {
      Document__c d = new Document__c(
        Assessment__c = sa.Id,
        Organization__c = sa.Organization__c,
        Status__c = 'Requested',
        Name = n
      );
      doc_list.add(d);
    }
    insert doc_list;

    Blob body = Blob.valueOf('Test Body');
    Attachment att = new Attachment(
      Name = 'Strategic Plan',
      body = body,
      parentId = doc_list[0].id
    );
    insert att;

    Profile p1 = [SELECT Id FROM Profile WHERE Name = 'BBBSA Level Three'];
    Contact c1 = new Contact(
      accountId = a1.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com'
    );
    insert c1;
    User u1 = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p1.Id,
      UserName = 'levelthree@test1.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;

    System.runAs(u1) {
      System.Test.setCurrentPageReference(
        new PageReference('Page.AssessmentPage1')
      );
      System.currentPageReference().getParameters().put('AssessmentID', sa.Id);
      AssessmentCtrl ctrl1 = new AssessmentCtrl();
      ctrl1.setParams();
      ctrl1.init();
      ctrl1.getOldAttList();
      ctrl1.saveAndContinue();
      ctrl1.saveAndExit();
      ctrl1.submit();
      ctrl1.attPopup();
      ctrl1.closeAttPopup();
      ctrl1.deleteAtt();
      ctrl1.getOptions();
      ctrl1.handleTabClick();
      ctrl1.deletePopup();
      ctrl1.updateAuditDate();
      ctrl1.assess.Fiscal_Year_Ended__c = null;
      ctrl1.updateAuditDate();
      ctrl1.upsertAssessment();
      ctrl1.saveAndRefresh();
      ctrl1.markAsReviewed();
      //   ctrl1.deleteAssessment();

      System.Test.setCurrentPageReference(new PageReference('Page.Compliance'));
      ComplianceCtrl ctrl2 = new ComplianceCtrl();
      ctrl2.getLists();
      ctrl2.assess = sa;
      ctrl2.keyword = 'Test';
      ctrl2.contactPopup();
      ctrl2.closeContactPopup();
      ctrl2.AssessmentId = sa.Id;
      ctrl2.testInnerClasses();

      System.Test.setCurrentPageReference(
        new PageReference('Page.ComplianceReportXLS')
      );
      System.currentPageReference().getParameters().put('type', 'incomplete');
      ComplianceCtrl ctrl3 = new ComplianceCtrl();
      ctrl3.getLists();
    }
    System.Test.stopTest();
  }
}