force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEO_Email__c.field-meta.xml
<CustomField>
    <fullName>CEO_Email__c</fullName>
    <label>CEO Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Grant_Year__c</fullName>
    <label>Current Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DOD_Email__c.field-meta.xml
<CustomField>
    <fullName>DOD_Email__c</fullName>
    <label>DOD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (CEO)</relationshipLabel>
    <relationshipName>CEOGrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/DOD_Email__c.field-meta.xml
<CustomField>
    <fullName>DOD_Email__c</fullName>
    <label>DOD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (Program Coordinator)</relationshipLabel>
    <relationshipName>PC_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reporting_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_End_Date__c</fullName>
    <label>Reporting Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Start_Date__c</fullName>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/PA_Log__c/PA_Log__c.object-meta.xml
<CustomObject>
    <label>PA Log</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Log__c/fields/Monthly_PA_Report__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PA_Report__c</fullName>
    <label>Monthly PA Report</label>
    <referenceTo>Program_Report__c</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>Daily_PA_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>PA_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Reports (CEO)</relationshipLabel>
    <relationshipName>CEO_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Site__r.FirstPic_National_Org_Code__c != null, Site__r.FirstPic_National_Org_Code__c, Site__r.FirstPic_Org_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017 - 2018</fullName>
            </value>
            <value>
                <fullName>2018 - 2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019 - 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Reports (Program Coordinator)</relationshipLabel>
    <relationshipName>PC_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateMonthlyPALogs.cls
public class CreateMonthlyPALogs implements Schedulable {
  public static String CRON_EXP = '0 0 1 1 * ? *';
  /*
    global static String schedule() {
        CreateMonthlyPALogs s = new CreateMonthlyPALogs();
        return System.schedule('Monthly', CRON_EXP, s);
    }
    */
  public void execute(SchedulableContext sc) {
    Date dt = date.today();
    Integer numberOfDays = Date.daysInMonth(dt.year(), dt.month());
    Date firstDayOfMonth = Date.newInstance(dt.year(), dt.month(), 1);
    Date lastDayOfMonth = Date.newInstance(dt.year(), dt.month(), numberOfDays);
    String month = '';
    if (dt.month() == 1)
      month = 'January';
    if (dt.month() == 2)
      month = 'February';
    if (dt.month() == 3)
      month = 'March';
    if (dt.month() == 4)
      month = 'April';
    if (dt.month() == 5)
      month = 'May';
    if (dt.month() == 6)
      month = 'June';
    if (dt.month() == 7)
      month = 'July';
    if (dt.month() == 8)
      month = 'August';
    if (dt.month() == 9)
      month = 'September';
    if (dt.month() == 10)
      month = 'October';
    if (dt.month() == 11)
      month = 'November';
    if (dt.month() == 12)
      month = 'December';

    List<Program_Report__c> pr_list = new List<Program_Report__c>();
    List<Grant__c> g_list = [
      SELECT Id, Account__r.Id
      FROM Grant__c
      WHERE
        RecordType.Name = 'Sub-Grant'
        AND FirstPic_National_Org_Code__c = 'NCAI'
        AND National_Grant__r.Reporting_Period_Start_Date__c <= :dt
        AND National_Grant__r.Reporting_Period_End_Date__c >= :dt
        AND Grant_Status__c != 'Closed'
    ];
    for (Account a : [
      SELECT
        Id,
        Local_Organization__r.Id,
        Local_Organization__r.CEO__c,
        Local_Organization__r.CEO_Email__c,
        Local_Organization__r.Program_Coordinator__c,
        Local_Organization__r.Program_Coordinator_Email__c,
        Local_Organization__r.DOD_Email__c
      FROM Account
      WHERE
        FirstPic_National_Org_Code__c = 'NCAI'
        AND RecordType.Name = 'Site'
        AND Is_Active__c = TRUE
    ]) {
      for (Grant__c g : g_list) {
        if (g.Account__r.Id == a.Local_Organization__r.Id) {
          Program_Report__c pr = new Program_Report__c(
            RecordTypeId = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
              .get('Monthly PA Logs')
              .getRecordTypeId(),
            Name = month + ' ' + dt.year() + ' PA Logs',
            Start_Date__c = firstDayOfMonth,
            End_Date__c = lastDayOfMonth,
            Month__c = month,
            Year__c = string.valueOf(dt.year()),
            Grant__c = g.Id,
            //Grant_Year__c = string.valueOf(g.Current_Grant_Year__c),
            Site__c = a.Id,
            Status__c = 'Not Started',
            CEO__c = a.Local_Organization__r.CEO__c,
            CEO_Email__c = a.Local_Organization__r.CEO_Email__c,
            Program_Coordinator__c = a.Local_Organization__r.Program_Coordinator__c,
            Program_Coordinator_Email__c = a.Local_Organization__r.Program_Coordinator_Email__c,
            DOD_Email__c = a.Local_Organization__r.DOD_Email__c
          );
          pr_list.add(pr);
        }
      }
    }
    insert pr_list;

    List<PA_Log__c> pa_list = new List<PA_Log__c>();
    for (Program_Report__c pr : pr_list) {
      for (
        integer i = 0; i <= pr.Start_Date__c.daysBetween(pr.End_Date__c); i++
      ) {
        Date d = pr.Start_Date__c.addDays(i);
        PA_Log__c pa = new PA_Log__c(
          Date__c = d,
          Monthly_PA_Report__c = pr.Id,
          Site__c = pr.Site__c
        );
        pa_list.add(pa);
      }
    }
    insert pa_list;
  }
}