force-app/main/default/objects/Account/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (CEO)</relationshipLabel>
    <relationshipName>Accounts_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DOD__c.field-meta.xml
<CustomField>
    <fullName>DOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DOD</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Boys &amp; Girls Clubs in Indian Country</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (DOD)</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator_Email__c</fullName>
    <label>Program Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/CEO__c.field-meta.xml
<CustomField>
    <fullName>CEO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEO</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (CEO)</relationshipLabel>
    <relationshipName>CEOGrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants (Program Coordinator)</relationshipLabel>
    <relationshipName>PC_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/TestSchedulable.cls
@isTest
class TestSchedulable {
  public static CronTrigger fetchCronTrigger(String jobId) {
    return [
      SELECT CronExpression, TimesTriggered, NextFireTime
      FROM CronTrigger
      WHERE Id = :jobId
    ];
  }

  static testMethod void testCreateMonthlyPALogs() {
    Account no = new Account(
      EIN__c = '00-2947562',
      Name = 'National Congress of American Indians',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2938746',
      National_Organization__c = no.Id,
      Name = 'Local Organization',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Account site = new Account(
      EIN__c = '00-2568462',
      National_Organization__c = no.Id,
      Local_Organization__c = lo.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site;

    Grant__c grant = new Grant__c(
      Account__c = no.Id,
      Name = 'name',
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Grant')
        .getRecordTypeId()
    );
    insert grant;

    Grant__c subgrant = new Grant__c(
      Account__c = lo.Id,
      Name = 'name',
      National_Grant__c = grant.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert subgrant;

    System.Test.startTest();

    String jobId = System.schedule(
      '_unittest_scheduled_: 001',
      CreateMonthlyPALogs.CRON_EXP,
      new CreateMonthlyPALogs()
    );

    CronTrigger ct = fetchCronTrigger(jobId);

    System.assertEquals(
      CreateMonthlyPALogs.CRON_EXP,
      ct.CronExpression,
      'Did not get the same Cron Expression back'
    );
    System.assertEquals(
      0,
      ct.TimesTriggered,
      'The job has been run and should not have'
    );

    System.Test.stopTest();
  }

  static testMethod void testSendReimbursementReminderEmail() {
    Account no = new Account(
      EIN__c = '00-2947562',
      Name = 'Ripken',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2938746',
      National_Organization__c = no.Id,
      Name = 'Local Organization',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Grant__c grant = new Grant__c(
      Account__c = no.Id,
      Name = 'name',
      Program_Coordinator_Email__c = 'test@test.com',
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Grant')
        .getRecordTypeId()
    );
    insert grant;

    Grant__c subgrant = new Grant__c(
      Account__c = lo.Id,
      Name = 'name',
      National_Grant__c = grant.Id,
      Is_Active__c = true,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert subgrant;

    System.Test.startTest();

    String jobId = System.schedule(
      '_unittest_scheduled_: 001',
      SendReimbursementReminderEmail.CRON_EXP,
      new SendReimbursementReminderEmail()
    );

    CronTrigger ct = fetchCronTrigger(jobId);

    System.assertEquals(
      SendReimbursementReminderEmail.CRON_EXP,
      ct.CronExpression,
      'Did not get the same Cron Expression back'
    );
    System.assertEquals(
      0,
      ct.TimesTriggered,
      'The job has been run and should not have'
    );

    System.Test.stopTest();
  }

  static testMethod void testUpdateAccountRelatedContactFields() {
    Account lo = new Account(
      Name = 'Local Organization',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Account site = new Account(
      Local_Organization__c = lo.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site;

    Contact ceo = new Contact(Account = lo, LastName = 'CEO');
    insert ceo;

    Contact dod = new Contact(Account = lo, LastName = 'DOD');
    insert dod;

    Contact pc = new Contact(Account = lo, LastName = 'PC');
    insert pc;

    lo.CEO__c = ceo.Id;
    lo.DOD__c = dod.Id;
    lo.Program_Coordinator__c = pc.Id;
    update lo;

    System.Test.startTest();

    UpdateAccountRelatedContactFields sh1 = new UpdateAccountRelatedContactFields();
    String sch = '0 0 23 * * ?';
    system.schedule('Test UpdateAccountRelatedContactFields', sch, sh1);

    System.Test.stopTest();
  }
}