force-app/main/default/objects/Account/fields/Coaches__c.field-meta.xml
<CustomField>
    <fullName>Coaches__c</fullName>
    <label>Coaches</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <label>Coach</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Coaches__c.field-meta.xml
<CustomField>
    <fullName>Coaches__c</fullName>
    <label>Coaches</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lesson</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Lesson</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Season</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions (Season)</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <label>Meeting</label>
</RecordType>

force-app/main/default/classes/CohortDetailsCtrl.cls
public with sharing class CohortDetailsCtrl {
  private UserClass uc = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  private SessionClass sc = new SessionClass(null, null);
  public Id sessionId { get; set; }
  public String sessionName { get; set; }
  public Id cohortId { get; set; }
  public Session__c cohort { get; set; }

  public List<SelectOption> coaches { get; set; }

  public string meetingAction { get; set; }
  public Id meetingId { get; set; }
  public Session__c meeting { get; set; }
  public Date meetingDate { get; set; }
  public List<Session__c> meeting_list { get; set; }

  public String lessonName { get; set; }
  public List<SelectOption> lessons { get; set; }

  public Boolean displayMeetingPopup { get; set; }
  public Boolean displayEditCohortPopup { get; set; }
  public Boolean displayDeleteMeetingPopup { get; set; }

  public CohortDetailsCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    userAcctType = uc.userAcctType;
    portalName = uc.userProfile;

    displayMeetingPopup = false;
    displayEditCohortPopup = false;
    displayDeleteMeetingPopup = false;

    meetingDate = Date.today();
    meetingAction = '';
    meeting = new Session__c();

    lessons = new List<SelectOption>();
    meeting_list = new List<Session__c>();

    cohortId = ApexPages.currentPage().getParameters().get('cohortId');
    cohort = new Session__c();

    coaches = new List<SelectOption>();
    for (Contact c : [
      SELECT Id, Name, Email, Phone, RecordType.Name, AccountId
      FROM Contact
    ]) {
      if (c.RecordType.Name == 'Coach' && c.AccountId == userAcct.Id) {
        coaches.add(new SelectOption(c.Name, c.Name));
      }
    }
    getLists();
  }

  public void getLists() {
    meeting_list.clear();
    lessons.clear();

    if (cohortId != null) {
      cohort = sc.getSession(cohortId, false);
      if (userAcctType == 'Site') {
        sessionId = cohort.Session__r.Id;
      } else {
        sessionId = cohort.Session__r.Season__r.Id;
      }
      sessionName = cohort.Session__r.Name;

      meeting_list = sc.getSessionList(cohortId, 'meeting');
      if (sessionId != null) {
        for (Session__c s : sc.getSessionList(sessionId, 'lesson')) {
          if (s.Session__c == cohort.Session__c) {
            lessons.add(new SelectOption(s.Id, s.Name));
          }
        }
      }
    }
  }

  public void addMeeting() {
    if (meeting.Name == null && meeting.Lesson__c != null)
      meeting.Name = [SELECT Name FROM Session__c WHERE ID = :meeting.Lesson__c]
      .Name;
    meeting.RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
      .get('Meeting')
      .getRecordTypeId();
    meeting.Cohort__c = cohortId;
    meeting.Meeting_Date__c = meetingDate;
    sc.upsertSession(meeting);
    meeting_list.add(meeting);
    meeting = new Session__c();
    meetingDate = Date.today();
    //getLists();
    displayMeetingPopup = false;
  }

  public void updateCohort() {
    if (cohort.Coaches__c != null) {
      String c = cohort.Coaches__c;
      c = c.replace('[', '');
      c = c.replace(']', '');
      cohort.Coaches__c = c;
    }
    sc.upsertSession(cohort);
    displayEditCohortPopup = false;
  }

  public void editMeetingPopup() {
    Session__c[] meetings = [
      SELECT
        Name,
        Lesson__c,
        Lesson__r.Name,
        Meeting_Date__c,
        Attendance__c,
        Notes__c
      FROM Session__c
      WHERE Id = :meetingId
    ];
    if (meetings.size() > 0) {
      meeting = meetings[0];
      lessonName = meetings[0].Lesson__r.Name;
      meetingDate = meetings[0].Meeting_Date__c;
    }
    if (meetingAction == 'delete') {
      deleteMeetingPopup();
    } else {
      addMeetingPopup();
    }
  }

  public void deleteMeeting() {
    if (meeting.Id != null) {
      sc.deleteSession(meeting);
      displayDeleteMeetingPopup = false;
      meetingAction = '';
      meeting = new Session__c();
      getLists();
    }
  }

  public void addMeetingPopup() {
    if (displayMeetingPopup == true) {
      displayMeetingPopup = false;
      meeting = new Session__c();
    } else {
      displayMeetingPopup = true;
    }
  }

  public void deleteMeetingPopup() {
    if (displayDeleteMeetingPopup == true) {
      displayDeleteMeetingPopup = false;
      meetingAction = '';
    } else {
      displayDeleteMeetingPopup = true;
    }
  }

  public void editCohortPopup() {
    if (displayEditCohortPopup == true) {
      displayEditCohortPopup = false;
    } else {
      displayEditCohortPopup = true;
    }
  }
}