force-app/main/default/objects/Account/fields/Current_Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Grant_Year__c</fullName>
    <label>Current Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grant_Year_Options__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year_Options__c</fullName>
    <label>Grant Year Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grant_Year_Options__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Year_Options__c</fullName>
    <formula
  >IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2017&quot;),&quot;2017;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2018&quot;),&quot;2018;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2019&quot;),&quot;2019;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2020&quot;),&quot;2020;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2017-2018&quot;),&quot;2017-2018;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2018-2019&quot;),&quot;2018-2019;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2019-2020&quot;),&quot;2019-2020;&quot;,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Year Options</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <formula
  >IF(CONTAINS(RecordType.Name, &apos;GREAT&apos;), &quot;I&apos;m GREAT&quot;,
IF(CONTAINS(RecordType.Name, &apos;Baseball&apos;), &apos;Badges for Baseball&apos;, 
IF(CONTAINS(RecordType.Name, &apos;Special Initiative&apos;), &apos;Special Initiative&apos;,
IF(CONTAINS(RecordType.Name, &apos;Healthy Lifestyles&apos;), &apos;Healthy Lifestyles&apos;,
IF(CONTAINS(RecordType.Name, &apos;TRAIL&apos;), &apos;TRAIL&apos;,
IF(CONTAINS(RecordType.Name, &apos;OVC&apos;), &apos;OVC&apos;,
IF(CONTAINS(RecordType.Name, &apos;SOI&apos;), &apos;SOI&apos;,
&apos;&apos;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Challenge</fullName>
                <default>true</default>
                <label>Challenge</label>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationsCtrl.cls
public with sharing class ApplicationsCtrl {
  private UserClass uc = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String approverLevel { get; set; }
  public String portalName { get; set; }

  private ApplicationClass ac = new ApplicationClass();
  private PaginationClass pc = new PaginationClass();

  public List<Application__c> allApps { get; set; }
  public List<Application__c> apps { get; set; }

  public Id siteId { get; set; }
  public String siteName { get; set; }
  public String appType { get; set; }
  public List<SelectOption> appTypeOptions { get; set; }
  public String grantType { get; set; }
  public List<SelectOption> grantTypeOptions { get; set; }
  public String year { get; set; }
  public List<SelectOption> yearOptions { get; set; }
  public String status { get; set; }
  public List<SelectOption> statusOptions { get; set; }
  public String sortBy { get; set; }
  public List<SelectOption> sortByOptions { get; set; }
  public Boolean viewAll { get; set; }

  Integer counter = 0;
  Integer limitSize = 40;
  Integer totalSize = 0;
  public String recordCount { get; set; }
  public Boolean disablePrevious { get; set; }
  public Boolean disableNext { get; set; }

  public ApplicationsCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    userAcctType = uc.userAcctType;
    approverLevel = uc.approverLevel;
    portalName = uc.userProfile;

    allApps = new List<Application__c>();
    apps = new List<Application__c>();
    viewAll = false;

    String urlSiteId = ApexPages.currentPage().getParameters().get('siteId');
    if (urlSiteId != '' && urlSiteId != null) {
      if (
        Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}')
          .matcher(urlSiteId)
          .matches()
      ) {
        siteId = Id.valueOf(urlSiteId);
      }
    }
    if (siteId == null)
      siteId = userAcct.Id;

    appTypeOptions = new List<SelectOption>();
    appTypeOptions.add(new SelectOption('', 'View All'));
    appTypeOptions.add(new SelectOption('New', 'New'));
    appTypeOptions.add(new SelectOption('Existing', 'Existing'));

    grantType = ApexPages.currentPage().getParameters().get('grantType');
    grantTypeOptions = new List<SelectOption>();
    grantTypeOptions.add(new SelectOption('', 'View All'));
    if (portalName == 'Ripken') {
      grantTypeOptions.add(new SelectOption('GREAT', 'I\'m GREAT'));
      grantTypeOptions.add(
        new SelectOption('Badges for Baseball', 'Badges for Baseball')
      );
      grantTypeOptions.add(
        new SelectOption('Special Initiative', 'Special Initiative')
      );
    }
    if (portalName == 'NCAI') {
      grantTypeOptions.add(new SelectOption('TRAIL', 'TRAIL'));
      grantTypeOptions.add(new SelectOption('OVC', 'OVC'));
    }

    yearOptions = new List<SelectOption>();
    yearOptions.add(new SelectOption('', 'View All'));
    String[] years;
    if (
      userAcctType == 'National Organization' &&
      userAcct.Grant_Year_Options__c != null
    ) {
      for (String i : userAcct.Grant_Year_Options__c.split(';')) {
        yearOptions.add(new SelectOption(i, i));
      }
    } else if (userAcct.National_Grant_Year_Options__c != null) {
      for (String i : userAcct.National_Grant_Year_Options__c.split(';')) {
        yearOptions.add(new SelectOption(i, i));
      }
    }
    if (userAcct.Current_Grant_Year__c != null)
      year = userAcct.Current_Grant_Year__c;

    statusOptions = new List<SelectOption>();
    statusOptions.add(new SelectOption('', 'View All'));
    //Schema.DescribeFieldResult fieldResult = Application__c.Status__c.getDescribe();
    //for(Schema.PicklistEntry f : fieldResult.getPicklistValues()) { statusOptions.add(new SelectOption(f.getLabel(), f.getValue())); }
    statusOptions.add(
      new SelectOption('Sent to Applicant', 'Sent to Applicant')
    );
    statusOptions.add(new SelectOption('Submitted', 'Submitted'));
    statusOptions.add(new SelectOption('Reviewed', 'Reviewed'));
    statusOptions.add(new SelectOption('Sent Back', 'Sent Back'));
    statusOptions.add(new SelectOption('Awarded', 'Awarded'));

    sortByOptions = new List<SelectOption>();
    if (portalName == 'Ripken')
      sortByOptions.add(new SelectOption('Organization__c', 'Site'));
    else
      sortByOptions.add(new SelectOption('Organization__c', 'Organization'));
    sortByOptions.add(new SelectOption('Status__c', 'Status'));
    sortByOptions.add(new SelectOption('Submitted_Date__c', 'Submitted Date'));
    if (userAcctType == 'National Organization') {
      if (!portalName.contains('NCAI'))
        sortByOptions.add(
          new SelectOption(
            'Organization__r.Program_Coordinator__c',
            'Program Coordinator'
          )
        );
      sortBy = 'Status__c';
    } else {
      sortBy = 'Grant_Year__c';
    }
    system.debug('sortByOptions = ' + sortByOptions);
  }

  public void getSOIs() {
    getLists(true);
  }

  public void getApps() {
    getLists(false);
  }

  public void getLists(Boolean isSOIList) {
    Id paId = currentUser.ContactId;
    if (
      userAcctType == 'Local Organization' ||
      viewAll ||
      approverLevel == 'Finance Admin' ||
      portalName.contains('NCAI')
    ) {
      paId = null;
    }

    String soqlAND = '';
    if (appType != null && appType != '')
      soqlAND = ' AND Type__c = \'' + appType + '\'';
    if (isSOIList)
      soqlAND += ' AND Grant_Type__c = \'SOI\'';
    else {
      if (portalName.contains('TRAIL'))
        grantType = 'TRAIL';
      else if (portalName.contains('OVC'))
        grantType = 'OVC';
      if (grantType != null && grantType != '')
        soqlAND += ' AND Grant_Type__c LIKE \'%' + grantType + '%\'';
      soqlAND += ' AND Grant_Type__c != \'SOI\'';
      if (userAcctType == 'National Organization' && year != null && year != '')
        soqlAND += ' AND Grant_Year__c = \'' + year + '\'';
    }

    allApps = ac.getRelatedApplicationList(
      siteId,
      siteName,
      status,
      soqlAND,
      sortBy,
      paId
    );
    totalSize = allApps.size();
    system.debug('allApps = ' + allApps);
    first();
  }

  // BEGIN pagination
  public void first() {
    counter = 0;
    apps = pc.first(allApps, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = true;
    disableNext = pc.getDisableNext(counter, limitSize, totalSize);
  }

  public void next() {
    counter = counter + limitSize;
    apps = pc.next(allApps, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = false;
    disableNext = pc.getDisableNext(counter, limitSize, totalSize);
  }

  public void previous() {
    counter = counter - limitSize;
    apps = pc.previous(allApps, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = pc.getDisablePrevious(counter);
    disableNext = false;
  }

  public void last() {
    counter = pc.getLastCounter(counter, limitSize, totalSize);
    apps = pc.last(allApps, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = false;
    disableNext = true;
  }
  // END pagination
}