force-app/main/default/objects/Account/fields/Current_Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Grant_Year__c</fullName>
    <label>Current Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Exp_Date__c</fullName>
    <label>DUNS Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grant_Year_Options__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year_Options__c</fullName>
    <label>Grant Year Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Has_Sites__c.field-meta.xml
<CustomField>
    <fullName>Has_Sites__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Sites</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Local_Organization__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grant_Year_Options__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Year_Options__c</fullName>
    <formula
  >IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2017&quot;),&quot;2017;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2018&quot;),&quot;2018;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2019&quot;),&quot;2019;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2020&quot;),&quot;2020;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2017-2018&quot;),&quot;2017-2018;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2018-2019&quot;),&quot;2018-2019;&quot;,null)&amp;
IF(INCLUDES(National_Organization__r.Grant_Year_Options__c,&quot;2019-2020&quot;),&quot;2019-2020;&quot;,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Year Options</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grants__c.field-meta.xml
<CustomField>
    <fullName>National_Grants__c</fullName>
    <label>National Grants</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Has_Sites__c.field-meta.xml
<CustomField>
    <fullName>National_Has_Sites__c</fullName>
    <formula>National_Organization__r.Has_Sites__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Has Sites</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserClass.cls
global with sharing class UserClass {
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String userProfile { get; set; }
  public String approverLevel { get; set; }

  public UserClass() {
    currentUser = [
      SELECT
        ContactId,
        Contact.Name,
        Contact.FirstName,
        Contact.LastName,
        Contact.Email,
        Contact.Role__c,
        AccountId,
        Account.Name,
        Account.RecordType.Name,
        IsActive,
        Profile.Name
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];

    if (currentUser.AccountId != null) {
      Account[] accounts = [
        SELECT
          ID,
          Name,
          Account.Session__c,
          RecordType.Name,
          DUNS_Exp_Date__c,
          Local_Organization_Id__c,
          Current_Grant_Year__c,
          Has_Sites__c,
          National_Has_Sites__c,
          National_Grants__c,
          National_Grant_Year_Options__c,
          Grant_Year_Options__c
        FROM Account
        WHERE ID = :currentUser.AccountId
      ];
      if (accounts.size() > 0)
        userAcct = accounts[0];
      userAcctType = currentUser.Account.RecordType.Name;
    }

    userProfile = '';
    String profile = currentUser.Profile.Name;
    if (profile.contains('BBBS')) {
      userProfile = 'BBBS';
    } else if (profile.contains('DMV')) {
      userProfile = 'DMV';
    } else if (profile.contains('PAL')) {
      userProfile = 'NPAL';
    } else if (profile.contains('LEGO')) {
      userProfile = 'LEGO';
    } else if (profile.contains('NCAI')) {
      userProfile = 'NCAI';
    } else if (profile.contains('TRAIL')) {
      userProfile = 'NCAI - TRAIL';
    } else if (profile.contains('OVC')) {
      userProfile = 'NCAI - OVC';
    } else if (profile.contains('STEM')) {
      userProfile = 'STEM';
    } else if (profile.contains('Ripken')) {
      userProfile = 'Ripken';
    } else if (profile.contains('UA')) {
      userProfile = 'UA';
    }

    approverLevel = '';
    if (profile.contains('Level One')) {
      approverLevel = 'Level One';
    } else if (profile.contains('Level Two')) {
      if (profile.contains('Admin')) {
        approverLevel = 'Level Two Admin';
      } else {
        approverLevel = 'Level Two';
      }
    } else if (profile.contains('Level Three')) {
      if (profile.contains('Admin')) {
        approverLevel = 'Level Three Admin';
      } else {
        approverLevel = 'Level Three';
      }
    } else if (profile.contains('Level Four')) {
      approverLevel = 'Level Four';
    } else if (profile.contains('Finance Admin')) {
      approverLevel = 'Finance Admin';
    }
  }
}