force-app/main/default/objects/Account/fields/DUNS_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Exp_Date__c</fullName>
    <label>DUNS Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <label>Hold Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Primary Approver)</relationshipLabel>
    <relationshipName>Accounts_Primary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Secondary Approver)</relationshipLabel>
    <relationshipName>Accounts_Secondary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Access_Mode__c.field-meta.xml
<CustomField>
    <fullName>Access_Mode__c</fullName>
    <label>Access Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Local Read Only</fullName>
            </value>
            <value>
                <fullName>National Access Only</fullName>
            </value>
            <value>
                <fullName>National L2a/L3a Access Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
                <isActive>false</isActive>
                <label>Resubmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <formula>Account__r.Primary_Approver_On_Leave__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DCTAT Reports</relationshipLabel>
    <relationshipName>DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DCTAT Reports (Primary Approver)</relationshipLabel>
    <relationshipName>PA_DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <formula>Organization__r.Primary_Approver_On_Leave__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <formula>TEXT(Grant__r.Account__r.Hold_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hold Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Is_National_Request__c.field-meta.xml
<CustomField>
    <fullName>Is_National_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is National Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <formula>Grant__r.Account__r.Name</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <formula>Grant__r.Account__r.Primary_Approver_On_Leave__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BBBSDashboardCtrl.cls
public with sharing class BBBSDashboardCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String approverLevel { get; set; }
  public String userProfile { get; set; }
  public String approverLevelURL { get; set; }

  private AccountClass ac = new AccountClass();
  public Boolean showDUNSAlert { get; set; }
  public String DUNSAlert { get; set; }
  public List<Document__c> missingDocs { get; set; }
  public List<Account> onHold { get; set; }

  public ID GrantId { get; set; }
  public List<Grant__c> pending_grant_list { get; set; }
  public List<Grant__c> sentBack_grant_list { get; set; }
  public Boolean more_pending_grant { get; set; }
  public Boolean more_sentBack_grant { get; set; }

  public ID RequestId { get; set; }
  public List<Reimbursement_Request__c> pending_request_list { get; set; }
  public List<Reimbursement_Request__c> todo_request_list { get; set; }
  public List<Reimbursement_Request__c> incomplete_request_list { get; set; }
  public Boolean more_pending_request { get; set; }
  public Boolean more_todo_request { get; set; }
  public Boolean more_incomplete_request { get; set; }

  public ID ReportId { get; set; }
  public List<Grantee_Report__c> report_list { get; set; }
  public List<Grantee_Report__c> incomplete_report_list { get; set; }
  public Boolean more_report { get; set; }
  public Boolean more_incomplete_report { get; set; }

  public String rId { get; set; }
  public String rStatus { get; set; }
  public DateTime rDate { get; set; }
  public Integer rCount { get; set; }

  public Date dt = date.today();
  public Date ytd = dt.addDays(-365);
  public String errorMessage { get; set; }

  public BBBSDashboardCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    approverLevel = userClass.approverLevel;
    userProfile = currentUser.Profile.Name;

    Account a = ac.getAccount(userAcct.Id);
    if (a.DUNS_Exp_Date__c < dt) {
      showDUNSAlert = true;
      DUNSAlert = 'Your SAM.gov registration is overdue. Your agency will be on reimbursement hold status for all active Federal Grants until this has been resolved. Updating SAM.gov does not automatically update this system. Please submit your updated registration date via the Organization Info tab.Please update your SAM.gov registration here.';
    } else if (a.DUNS_Exp_Date__c < dt.addDays(45)) {
      showDUNSAlert = true;
      DUNSAlert = 'Your SAM.gov registration will expire within 45 days. You must update the registration in order to remain in compliance with the grant MOA terms and receive reimbursements. Updating SAM.gov does not automatically update this system. Please submit your updated registration date via the Organization Info tab.';
    }

    missingDocs = new List<Document__c>();
    for (Document__c d : [
      SELECT Name, Due_Date__c, Grant__c, Grant__r.Name
      FROM Document__c
      WHERE
        Organization__c = :userAcct.Id
        AND (Status__c = 'Requested'
        OR Status__c = 'Sent Back')
        AND Required__c = TRUE
        AND (Due_Date__c < :dt
        OR Due_Date__c < :dt.addDays(15))
        AND (Access_Mode__c = NULL
        OR Access_Mode__c = ''
        OR Access_Mode__c = 'Local Read Only')
    ]) {
      missingDocs.add(d);
      system.debug(d);
    }

    onHold = ac.getRelatedAccountList(
      userAcct.Id,
      'National Organization',
      null,
      null,
      ' AND Hold_Status__c = \'Hold\''
    );

    if (approverLevel == 'Level One') {
      approverLevelURL = 'First';
    }
    if (approverLevel == 'Level Two') {
      approverLevelURL = 'Second';
    }
    if (approverLevel.contains('Level Three')) {
      approverLevelURL = 'Final';
    }

    pending_grant_list = new List<Grant__c>();
    sentBack_grant_list = new List<Grant__c>();
    pending_request_list = new List<Reimbursement_Request__c>();
    todo_request_list = new List<Reimbursement_Request__c>();
    incomplete_request_list = new List<Reimbursement_Request__c>();
    report_list = new List<Grantee_Report__c>();
    incomplete_report_list = new List<Grantee_Report__c>();

    more_pending_grant = false;
    more_sentBack_grant = false;
    more_pending_request = false;
    more_todo_request = false;
    more_incomplete_request = false;
    more_report = false;
    more_incomplete_report = false;
  }

  public ApexPages.PageReference init() {
    if (currentUser == null || userAcct == null) {
      PageReference pageRef = new PageReference('/login');
      return pageRef;
    }
    if (userProfile.contains('Report Builder')) {
      PageReference pageRef = new PageReference('/00O/o');
      return pageRef;
    }
    return null;
  }

  public void getLists() {
    Integer listLimit = 6;
    rCount = 0;

    for (Grant__c g : [
      SELECT
        Id,
        Name,
        LastModifiedDate,
        Account__r.National_Organization__c,
        Grant_Status__c
      FROM Grant__c
      WHERE Grant_Status__c != 'Closed'
      ORDER BY LastModifiedDate DESC
    ]) {
      if (
        (approverLevel.contains('Level Two') ||
        approverLevel.contains('Level Three')) &&
        (g.Grant_Status__c == 'Pending Review' ||
        g.Grant_Status__c == 'Budget Submitted')
      ) {
        if (pending_grant_list.size() < listLimit) {
          pending_grant_list.add(g);
        } else {
          more_pending_grant = true;
        }
      }
      if (g.Grant_Status__c == 'Revisions Needed') {
        if (sentBack_grant_list.size() < listLimit) {
          sentBack_grant_list.add(g);
        } else {
          more_sentBack_grant = true;
        }
      }
    }

    for (Reimbursement_Request__c r : [
      SELECT
        Id,
        Name,
        LastModifiedDate,
        Is_National_Request__c,
        Grant__r.Account__r.Id,
        Grant__r.Account__r.Primary_Approver__c,
        Grant__r.Account__r.Secondary_Approver__c,
        Grant__r.Account__r.Primary_Approver_On_Leave__c,
        Grant__r.Account__r.National_Organization__c,
        Grant__r.Name,
        Request_Date__c,
        Status__c,
        Paid_Date__c,
        Level_Three_Approved_Date__c
      FROM Reimbursement_Request__c
      WHERE Grant_Status__c != 'Closed'
      ORDER BY LastModifiedDate DESC
    ]) {
      if (userAcctType == 'National Organization') {
        if (approverLevel == 'Level One') {
          if (r.Status__c == 'Pending First Approval') {
            if (
              r.Grant__r.Account__r.Primary_Approver__c ==
              currentUser.ContactId &&
              r.Grant__r.Account__r.Primary_Approver_On_Leave__c == false
            ) {
              if (todo_request_list.size() < listLimit) {
                todo_request_list.add(r);
              } else {
                more_todo_request = true;
              }
            } else if (
              r.Grant__r.Account__r.Secondary_Approver__c ==
              currentUser.ContactId &&
              r.Grant__r.Account__r.Primary_Approver_On_Leave__c == true
            ) {
              if (todo_request_list.size() < listLimit) {
                todo_request_list.add(r);
              } else {
                more_todo_request = true;
              }
            } else {
              if (pending_request_list.size() < listLimit) {
                pending_request_list.add(r);
              } else {
                more_pending_request = true;
              }
            }
          } else if (
            !r.Is_National_Request__c &&
            (r.Status__c == 'Pending Second Approval' ||
            r.Status__c == 'Pending Final Approval')
          ) {
            if (pending_request_list.size() < listLimit) {
              pending_request_list.add(r);
            } else {
              more_pending_request = true;
            }
          }
        }
        if (approverLevel.contains('Level Two')) {
          if (r.Status__c == 'Pending Second Approval') {
            if (todo_request_list.size() < listLimit) {
              todo_request_list.add(r);
            } else {
              more_todo_request = true;
            }
          } else if (
            !r.Is_National_Request__c &&
            (r.Status__c == 'Pending First Approval' ||
            r.Status__c == 'Pending Final Approval')
          ) {
            if (pending_request_list.size() < listLimit) {
              pending_request_list.add(r);
            } else {
              more_pending_request = true;
            }
          }
        }
        if (approverLevel.contains('Level Three')) {
          if (r.Status__c == 'Pending Final Approval') {
            if (todo_request_list.size() < listLimit) {
              todo_request_list.add(r);
            } else {
              more_todo_request = true;
            }
          } else if (
            r.Status__c == 'Pending First Approval' ||
            r.Status__c == 'Pending Second Approval'
          ) {
            if (pending_request_list.size() < listLimit) {
              pending_request_list.add(r);
            } else {
              more_pending_request = true;
            }
          }
        }
        if (
          r.Status__c == 'Incomplete' ||
          r.Status__c == 'Revisions Needed' ||
          r.Status__c == 'Revision in Progress'
        ) {
          if (incomplete_request_list.size() < listLimit) {
            incomplete_request_list.add(r);
          } else {
            more_incomplete_request = true;
          }
        }
        if (r.Status__c == 'Approved' || r.Status__c == 'Paid') {
          rCount += 1;
        }
      }

      if (userAcctType == 'Local Organization') {
        if (r.Status__c == 'Incomplete') {
          if (incomplete_request_list.size() < listLimit) {
            incomplete_request_list.add(r);
          } else {
            more_incomplete_request = true;
          }
        }
        if (
          r.Status__c == 'Revisions Needed' ||
          r.Status__c == 'Revision in Progress'
        ) {
          if (todo_request_list.size() < listLimit) {
            todo_request_list.add(r);
          } else {
            more_todo_request = true;
          }
        }
        if (
          rId == null && (r.Status__c == 'Approved' || r.Status__c == 'Paid')
        ) {
          rId = r.Name;
          rStatus = r.Status__c;
          if (r.Paid_Date__c != null) {
            rDate = r.Paid_Date__c;
          } else if (r.Level_Three_Approved_Date__c != null) {
            rDate = r.Level_Three_Approved_Date__c;
          } else {
            rDate = r.LastModifiedDate;
          }
        }
      }
    }

    for (Grantee_Report__c gr : [
      SELECT
        Grant__r.Name,
        Name,
        Report_Status__c,
        LastModifiedDate,
        Submitted_Date__c
      FROM Grantee_Report__c
      WHERE Grant_Status__c != 'Closed'
      ORDER BY LastModifiedDate DESC
    ]) {
      report_list.add(gr);
      if (gr.Report_Status__c == 'In Progress') {
        if (incomplete_report_list.size() < listLimit) {
          incomplete_report_list.add(gr);
        } else {
          more_incomplete_report = true;
        }
      }
    }
  }

  public List<AggregateResult> requestsByStatus {
    get {
      return [
        SELECT count(Id) requestCount, Status__c
        FROM Reimbursement_Request__c
        WHERE
          Grant__r.Account__r.National_Organization__r.Id = :userAcct.Id
          AND Status__c != NULL
          AND Total_Requested_Amount__c != NULL
        GROUP BY Status__c
      ];
    }
  }
}