force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description
  >Formula to add leading zero to D-U-N-S number if necessary</description>
    <formula>LPAD(TEXT(DUNS__c), 9, &apos;0&apos; )</formula>
    <label>D-U-N-S</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>National_Organization__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Authority_to_Apply__c.field-meta.xml
<CustomField>
    <fullName>Authority_to_Apply__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authority to Apply</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <label>DUNS Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Eligibility_Notice_Received__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Notice_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility Notice Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Existing_Services__c.field-meta.xml
<CustomField>
    <fullName>Existing_Services__c</fullName>
    <label>Existing Services</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Funding_to_Purchase_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_to_Purchase_Vehicle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding to Purchase Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Email__c</fullName>
    <label>Grant Admin Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_First_Name__c</fullName>
    <label>Grant Admin First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Last_Name__c</fullName>
    <label>Grant Admin Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Phone__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Phone__c</fullName>
    <label>Grant Admin Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Is_Statement_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Is_Statement_of_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Statement of Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <label>National Organization Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Needs_Assessment__c</fullName>
    <label>Needs Assessment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/New_or_Existing__c.field-meta.xml
<CustomField>
    <fullName>New_or_Existing__c</fullName>
    <label>New or Existing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/No_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>No_DUNS_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Used in OVC SOI so org can submit prior to receiving DUNS number.</description>
    <label>No DUNS Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <label>Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tribe</fullName>
                <label>Tribal Nation</label>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Designee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/POC_Can_Receive_Communication__c.field-meta.xml
<CustomField>
    <fullName>POC_Can_Receive_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POC Can Receive Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Email__c</fullName>
    <label>Program Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_First_Name__c</fullName>
    <label>Program Contact First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Last_Name__c</fullName>
    <label>Program Contact Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Phone__c</fullName>
    <label>Program Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Statement_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Statement_of_Interest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statement of Interest</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Strategic_Plan__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Plan__c</fullName>
    <label>Strategic Plan</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Strategic_Plan_Victim_Services__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Plan_Victim_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Strategic Plan Victim Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Tribe_Represented__c.field-meta.xml
<CustomField>
    <fullName>Tribe_Represented__c</fullName>
    <description
  >Used in OVC SOI to allow Consortia and Designee submissions to indicate the tribe they represent.</description>
    <label>Tribe Represented</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Challenge</fullName>
                <default>true</default>
                <label>Challenge</label>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <formula>Account.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/StatementOfInterestCtrl.cls
public without sharing class StatementOfInterestCtrl {
  private UserClass uc = new UserClass();
  private UserClassWithoutSharing ucws = new UserClassWithoutSharing();
  private ApplicationClass appClass = new ApplicationClass();
  private AccountClass acctClass = new AccountClass();
  private ContactClass cc = new ContactClass();
  private getIdFromString gifs = new getIdFromString();

  public User currentUser { get; set; }
  public Account userAcct { get; set; }

  public Application__c app { get; set; }
  public Account acct { get; set; }
  public List<Contact> contacts { get; set; }
  public Contact ga { get; set; }
  public Contact pc { get; set; }

  public String errorMessage { get; set; }
  public Boolean showSuccess { get; set; }

  public StatementOfInterestCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;

    app = new Application__c();
    String appUrlId = ApexPages.currentPage().getParameters().get('appId');
    if (appUrlId != null) {
      Id appId = gifs.getId(appUrlId);
      app = appClass.getApplication(appId);
    }

    acct = new Account();
    contacts = new List<Contact>();
    ga = new Contact();
    pc = new Contact();
  }

  // BEGIN save
  public void save() {
    errorMessage = '';
    appClass.upsertApplication(app);
  }
  // END save

  // BEGIN submit
  public PageReference submit() {
    errorMessage = '';
    fieldValidation();
    if (ApexPages.hasMessages() || errorMessage != '') {
      system.debug(
        'Apex Pages has Messages Or ErrorMessgae is not blank: ' +
        errorMessage +
        '\n' +
        apexpages.getMessages()
      );
      return null;
    } else {
      app.National_Organization_Id__c = '0013600001Pxcii';
      app.Is_Statement_of_Interest__c = true;
      app.Status__c = 'Submitted';
      app.Type__c = app.New_or_Existing__c;
      app.Submitted_Date__c = date.today();
      system.debug('app = ' + app);
      appClass.upsertApplication(app);

      if (ApexPages.hasMessages())
        errorMessage += string.valueOf(ApexPages.getMessages());
      if (errorMessage == '')
        showSuccess = true;
    }

    return null;
  }
  // END submit

  // BEGIN fieldValidation
  public void fieldValidation() {
    if (app.Organization_Type__c == null || app.Organization_Type__c == '') {
      errorMessage += 'Applicant Org Type is required <br />';
    }

    if (app.Organization_Name__c == null || app.Organization_Name__c == '')
      errorMessage += 'Organization Name is Missing <br />';

    if (
      (app.DUNS_Number__c == null || app.DUNS_Number__c == '') &&
      !app.No_DUNS_Number__c
    )
      errorMessage += 'DUNS Number is Missing <br />';

    if (app.Address__c == null || app.Address__c == '')
      errorMessage += 'Address is Missing <br />';

    if (app.City__c == null || app.City__c == '')
      errorMessage += 'City is Missing <br />';

    if (app.State__c == null || app.State__c == '')
      errorMessage += 'State is Missing <br />';

    if (app.Postal_Zip_Code__c == null || app.Postal_Zip_Code__c == '')
      errorMessage += 'Zip Code is Missing <br />';

    if (
      app.Grant_Admin_First_Name__c == null ||
      app.Grant_Admin_First_Name__c == ''
    )
      errorMessage += 'Grant Admin First Name is Missing <br />';

    if (
      app.Grant_Admin_Last_Name__c == null ||
      app.Grant_Admin_Last_Name__c == ''
    )
      errorMessage += 'Grant Admin Last Name is Missing <br />';

    if (app.Grant_Admin_Email__c == null || app.Grant_Admin_Email__c == '')
      errorMessage += 'Grant Admin Email is Missing <br />';

    if (app.Grant_Admin_Phone__c == null || app.Grant_Admin_Phone__c == '')
      errorMessage += 'Grant Admin Phone is Missing <br />';

    if (app.POC_Can_Receive_Communication__c == false) {
      if (
        app.Program_Contact_First_Name__c == null ||
        app.Program_Contact_First_Name__c == ''
      )
        errorMessage += 'Alternate First Name is Missing <br />';

      if (
        app.Program_Contact_Last_Name__c == null ||
        app.Program_Contact_Last_Name__c == ''
      )
        errorMessage += 'Alternate Last Name is Missing <br />';

      if (
        app.Program_Contact_Email__c == null ||
        app.Program_Contact_Email__c == ''
      )
        errorMessage += 'Alternate Email is Missing <br />';

      if (
        app.Program_Contact_Phone__c == null ||
        app.Program_Contact_Phone__c == ''
      )
        errorMessage += 'Alternate Phone is Missing <br />';
    }

    if (app.New_or_Existing__c == 'Existing') {
      if (app.Existing_Services__c == null || app.Existing_Services__c == '') {
        errorMessage += 'Please describe your existing victim services <br />';
      }
    }

    if (app.Strategic_Plan_Victim_Services__c) {
      if (app.Strategic_Plan__c == null || app.Strategic_Plan__c == '') {
        errorMessage += 'Please indicate when you completed a strategic plan <br />';
      }
    }

    if (
      app.Eligibility_Notice_Received__c == null ||
      app.New_or_Existing__c == null ||
      app.Needs_Assessment__c == null ||
      app.Needs_Assessment__c == '' ||
      app.Funding_to_Purchase_Vehicle__c == null ||
      app.Strategic_Plan_Victim_Services__c == null ||
      app.Authority_to_Apply__c == null
    ) {
      errorMessage += 'All fields in the Request Details section with an * are required <br />';
    }

    if (
      (app.Organization_Type__c == 'Consortium' ||
      app.Organization_Type__c == 'Designee') &&
      (app.Tribe_Represented__c == '' ||
      app.Tribe_Represented__c == null)
    ) {
      errorMessage +=
        'As a ' +
        app.Organization_Type__c +
        ' please indicate the Tribe you represent <br />';
    }
  }
  // END fieldValidation

  // BEGIN notEligible
  public PageReference notEligible() {
    app.Status__c = 'Closed';
    app.Closed_Date__c = date.today();
    appClass.upsertApplication(app);
    if (ApexPages.hasMessages())
      return null;
    PageReference pr = new PageReference('/SOIList?grantType=soi');
    pr.setRedirect(true);
    return pr;
  }
  // END notEligible

  // BEGIN approve
  public PageReference approve() {
    errorMessage = '';

    if (
      app.Organization__c == null &&
      app.National_Organization__c != null &&
      app.DUNS_Number__c != null
    ) {
      Account[] accts = [
        SELECT Id, DUNS_Number__c
        FROM Account
        WHERE
          DUNS_Number__c = :app.DUNS_Number__c
          AND National_Organization__c = :app.National_Organization__c
      ];
      if (accts.size() > 0) {
        app.Organization__c = accts[0].Id;
        acct.Id = accts[0].Id;
      }
    }
    acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Local Organization')
      .getRecordTypeId();
    acct.National_Organization__c = app.National_Organization__c;
    acct.National_Organization_Name__c = app.National_Organization__r.Name;
    if (app.DUNS_Number__c != null)
      acct.DUNS__c = Integer.valueOf(app.DUNS_Number__c);
    acct.Name = app.Organization_Name__c;
    acct.BillingStreet = app.Address__c;
    acct.BillingCity = app.City__c;
    acct.BillingState = app.State__c;
    acct.BillingPostalCode = app.Postal_Zip_Code__c;

    String grants = acct.National_Grants__c;
    if (grants == null && grants != '')
      grants = 'OVC';
    else
      grants += ';OVC';
    system.debug(grants);
    acct.National_Grants__c = grants;

    User u = new User();
    u = ucws.getUser(' WHERE Alias = \'fpadmin\'');
    if (u == null)
      u = ucws.getUser(' WHERE Profile.Name = \'System Administrator\'');
    system.debug('ApplicationCtrl user for acct owner = ' + u.Name);
    if (u != null)
      acct.OwnerId = u.Id;
    acctClass.upsertAccount(acct);
    system.debug(
      'ApplicationCtrl acct after upsert = ' +
      acct.Id +
      ' ' +
      acct.Name
    );
    if (ApexPages.hasMessages() && !system.Test.isRunningTest())
      return null;

    createContacts();
    ga.AccountId = acct.Id;
    pc.AccountId = acct.Id;
    system.debug('contacts = ' + contacts);
    cc.upsertContactList(contacts);
    if (
      (errorMessage != '' || ApexPages.hasMessages()) &&
      !system.Test.isRunningTest()
    )
      return null;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'NCAI Local All Access'];
    User uga = ucws.getUser(' WHERE ContactID = \'' + ga.Id + '\'');
    if (uga == null || uga.Id == null) {
      String un = ga.Email;
      User[] dup = [SELECT Id FROM User WHERE UserName = :un];
      if (dup.size() == 0) {
        CreateCommunityUser ccu = new CreateCommunityUser();
        ccu.createUser(ga.Id, ga.Email, un, ga.FirstName, ga.LastName, p.Id);
      }
    }
    if (
      (errorMessage != '' || ApexPages.hasMessages()) &&
      !system.Test.isRunningTest()
    )
      return null;

    app.Organization__c = acct.Id;
    app.Status__c = 'Approved';
    appClass.upsertApplication(app);

    Application__c ovc = new Application__c(
      RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName()
        .get('NCAI - OVC')
        .getRecordTypeId(),
      National_Organization__c = app.National_Organization__c,
      Organization__c = acct.Id,
      Organization_Type__c = app.Organization_Type__c,
      DUNS_Number__c = app.DUNS_Number__c,
      Status__c = 'Sent to Applicant',
      Organization_Name__c = app.Organization_Name__c,
      Address__c = app.Address__c,
      City__c = app.City__c,
      State__c = app.State__c,
      Postal_Zip_Code__c = app.Postal_Zip_Code__c,
      Grant_Admin_First_Name__c = app.Grant_Admin_First_Name__c,
      Grant_Admin_Last_Name__c = app.Grant_Admin_Last_Name__c,
      Grant_Admin_Email__c = app.Grant_Admin_Email__c,
      Grant_Admin_Phone__c = app.Grant_Admin_Phone__c,
      Program_Contact_First_Name__c = app.Program_Contact_First_Name__c,
      Program_Contact_Last_Name__c = app.Program_Contact_Last_Name__c,
      Program_Contact_Email__c = app.Program_Contact_Email__c,
      Program_Contact_Phone__c = app.Program_Contact_Phone__c,
      Applied_For_Victim_Services_Program__c = app.Applied_For_Victim_Services_Program__c,
      Tribe_Represented__c = app.Tribe_Represented__c,
      Authority_to_Apply__c = app.Authority_to_Apply__c,
      Statement_of_Interest__c = app.Id
    );
    system.debug('>>>>> ovc: ' + ovc);
    appClass.upsertApplication(ovc);

    if (
      (errorMessage != '' || ApexPages.hasMessages()) &&
      !system.Test.isRunningTest()
    )
      return null;

    PageReference pr = new PageReference('/SOIList?grantType=soi');
    pr.setRedirect(true);
    return pr;
  }
  // END approve

  // BEGIN createContacts
  public void createContacts() {
    contacts.clear();
    Id rId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
      .get('Contact')
      .getRecordTypeId();
    Map<String, Id> emails = new Map<String, Id>();
    for (Contact c : [SELECT Email FROM Contact WHERE AccountId = :acct.Id])
      emails.put(c.Email, c.Id);

    if (app.Grant_Admin_Email__c != null) {
      if (emails.containsKey(app.Grant_Admin_Email__c))
        ga.Id = emails.get(app.Grant_Admin_Email__c);
      ga.Role__c = 'Grant Administrator';
      ga.FirstName = app.Grant_Admin_First_Name__c;
      ga.LastName = app.Grant_Admin_Last_Name__c;
      ga.Email = app.Grant_Admin_Email__c;
      ga.Phone = app.Grant_Admin_Phone__c;
      ga.RecordTypeId = rId;
      contacts.add(ga);
    }

    if (app.Program_Contact_Email__c != null) {
      if (emails.containsKey(app.Program_Contact_Email__c))
        pc.Id = emails.get(app.Program_Contact_Email__c);
      pc.Role__c = 'Program Coordinator';
      pc.FirstName = app.Program_Contact_First_Name__c;
      pc.LastName = app.Program_Contact_Last_Name__c;
      pc.Email = app.Program_Contact_Email__c;
      pc.Phone = app.Program_Contact_Phone__c;
      pc.RecordTypeId = rId;
      contacts.add(pc);
    }
  }
  // END createContacts
}