force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description
  >Formula to add leading zero to D-U-N-S number if necessary</description>
    <formula>LPAD(TEXT(DUNS__c), 9, &apos;0&apos; )</formula>
    <label>D-U-N-S</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Total Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <formula>TEXT(Account__r.DUNS__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DUNS Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Accomplishments_this_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accomplishments_this_Reporting_Period__c</fullName>
    <label>Accomplishments this Reporting Period</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Attended_Events__c.field-meta.xml
<CustomField>
    <fullName>Attended_Events__c</fullName>
    <label>Attended Events</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Attended_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Attended_Meetings__c</fullName>
    <label>Attended Meetings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Chromebooks_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Chromebooks_Utilized__c</fullName>
    <label>Chromebooks Utilized</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Conducted_Outreach__c.field-meta.xml
<CustomField>
    <fullName>Conducted_Outreach__c</fullName>
    <label>Conducted Outreach</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Cooperation_Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Cooperation_Collaboration__c</fullName>
    <label>Cooperation Collaboration</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Distributed_Newsletter__c.field-meta.xml
<CustomField>
    <fullName>Distributed_Newsletter__c</fullName>
    <label>Distributed Newsletter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <label>DUNS Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Hosted_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Hosted_Meetings__c</fullName>
    <label>Hosted Meetings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Increase_in_Perception_of_Social_Support__c.field-meta.xml
<CustomField>
    <fullName>Increase_in_Perception_of_Social_Support__c</fullName>
    <label>Increase in Perception of Social Support</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Innovative_Programs_Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Innovative_Programs_Accomplishments__c</fullName>
    <label>Innovative Programs Accomplishments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Laptops_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Laptops_Utilized__c</fullName>
    <label>Laptops Utilized</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Law_Enforcement_Engaged__c.field-meta.xml
<CustomField>
    <fullName>Law_Enforcement_Engaged__c</fullName>
    <label>Law Enforcement Engaged</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Law_Enforcement_Improved_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Law_Enforcement_Improved_Knowledge__c</fullName>
    <label>Law Enforcement Improved Knowledge</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Major_Activities_Planned__c.field-meta.xml
<CustomField>
    <fullName>Major_Activities_Planned__c</fullName>
    <label>Major Activities Planned</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_Activities__c.field-meta.xml
<CustomField>
    <fullName>Number_Activities__c</fullName>
    <label>Number Activities</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Number of Mentors</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Organization_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name_Text__c</fullName>
    <label>Organization Name Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Other_Describe__c.field-meta.xml
<CustomField>
    <fullName>Other_Describe__c</fullName>
    <label>Other Describe</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Performance_Measurement__c.field-meta.xml
<CustomField>
    <fullName>Performance_Measurement__c</fullName>
    <label>Performance Measurement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Problems_Barriers_Encountered_Details__c.field-meta.xml
<CustomField>
    <fullName>Problems_Barriers_Encountered_Details__c</fullName>
    <label>Problems/Barriers Encountered Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Progress_of_Completed_Goals__c.field-meta.xml
<CustomField>
    <fullName>Progress_of_Completed_Goals__c</fullName>
    <label>Progress of Completed Goals</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Projects_Effectiveness__c.field-meta.xml
<CustomField>
    <fullName>Projects_Effectiveness__c</fullName>
    <label>Project&apos;s Effectiveness</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quarters</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Reason_Requesting_Funds__c.field-meta.xml
<CustomField>
    <fullName>Reason_Requesting_Funds__c</fullName>
    <label>Reason Requesting Funds</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Social_Media_Activities__c.field-meta.xml
<CustomField>
    <fullName>Social_Media_Activities__c</fullName>
    <label>Social Media Activities</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Submitted_By_Text__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By_Text__c</fullName>
    <label>Submitted By Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Topics_Surveyed__c.field-meta.xml
<CustomField>
    <fullName>Topics_Surveyed__c</fullName>
    <label>Topics Surveyed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Satisfaction with Police Services</fullName>
            </value>
            <value>
                <fullName
        >Public Satisfaction with Prosecution Services</fullName>
                <label>Public Satisfaction with Prosecution Services</label>
            </value>
            <value>
                <fullName
        >Public Satisfaction with Public Defender/Indigent Defense Services</fullName>
                <label
        >Public Satisfaction with Public Defender/Indigent Defense Services</label>
            </value>
            <value>
                <fullName>Public Satisfaction with Courts</fullName>
            </value>
            <value>
                <fullName
        >Public Perceptions of Crime/Disorder Problems</fullName>
                <label>Public Perceptions of Crime/Disorder Problems</label>
            </value>
            <value>
                <fullName>Personal Crime Experiences of Citizens</fullName>
            </value>
            <value>
                <fullName
        >None of the Above Surveys were Conducted/Sponsored on these Topics</fullName>
                <label
        >None of the Above Surveys were Conducted/Sponsored on these Topics</label>
            </value>
            <value>
                <fullName>Unsure/Don’t Know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Youth_Wellbeing_Increase__c.field-meta.xml
<CustomField>
    <fullName>Youth_Wellbeing_Increase__c</fullName>
    <label>Youth Wellbeing Increase</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/recordTypes/Quarterly.recordType-meta.xml
<RecordType>
    <fullName>Quarterly</fullName>
    <active>true</active>
    <label>Quarterly</label>
</RecordType>

force-app/main/default/classes/BJAGProgramReportCtrl.cls
public without sharing class BJAGProgramReportCtrl {
  private UserClass uc = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  private FieldLabelClass flc = new FieldLabelClass();
  private ProgressReportClass prc = new ProgressReportClass();
  private SchemaPicklistFields spf = new SchemaPicklistFields();

  private Date dt = date.today();
  private String fdt = dt.format();

  public Progress_Report__c report { get; set; }
  public Map<String, String> fields { get; set; }

  public String reportId { get; set; }
  public String errorMessage { get; set; }
  public String successMessage { get; set; }
  public Boolean readOnly { get; set; }
  public Boolean review { get; set; }

  public List<SelectOption> topicOptions {
    get {
      return spf.getPicklistOptions(
        'Progress_Report__c',
        'Topics_Surveyed__c',
        null
      );
    }
    set;
  }

  public String[] topics {
    get {
      String[] selected = new List<String>();
      List<SelectOption> sos = this.topicOptions;
      for (SelectOption s : sos) {
        if (
          this.report.Topics_Surveyed__c != null &&
          this.report.Topics_Surveyed__c.contains(s.getValue())
        )
          selected.add(s.getValue());
      }
      return selected;
    }
    public set {
      String selectedConcat = '';
      for (String s : value) {
        if (selectedConcat == '')
          selectedConcat += s;
        else
          selectedConcat += ';' + s;
      }
      report.Topics_Surveyed__c = selectedConcat;
    }
  }

  public BJAGProgramReportCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    userAcctType = uc.userAcctType;
    portalName = uc.userProfile;

    reportId = ApexPages.currentPage().getParameters().get('report');
    initBJAG();

    review = false;
    readOnly = true;

    if (
      (report.Status__c == 'Not Started' ||
      report.Status__c == 'In Progress' ||
      report.Status__c == 'Revisions Needed') &&
      userAcctType == 'Local Organization'
    ) {
      readOnly = false;
    }

    if (
      report.Status__c == 'Submitted' &&
      userAcctType == 'National Organization'
    ) {
      review = true;
    }
  }

  // BEGIN BJAG method
  public void initBJAG() {
    fields = new Map<String, String>();
    fields = flc.getFieldLabelMap(
      'Progress_Report__c',
      'MDGO',
      null,
      ' AND Year__c includes (\'2021\')'
    );

    if (reportId == null || reportId == '') {
      Account acct = [
        SELECT Id
        FROM Account
        WHERE Name = 'BJAG Placeholder'
        LIMIT 1
      ];
      report.Organization__c = acct.Id;
      Grant__c grant = [
        SELECT Id
        FROM Grant__c
        WHERE Name = 'BJAG Placeholder'
        LIMIT 1
      ];
      report.Grant__c = grant.Id;
      report.Year__c = '2021';
      report.Quarter__c = 'Q2';
    } else {
      report = prc.getReport(reportId, null, null);
    }
  }
  // END BJAG Method

  public void validation() {
    if (report.DUNS_Number__c == null || report.DUNS_Number__c == '')
      errorMessage += 'DUNS Number is required.<br/>';

    if (report.DUNS_Number__c != null && !report.DUNS_Number__c.isNumeric())
      errorMessage += 'DUNS Number must contain numbers only.<br/>';
    if (report.DUNS_Number__c != null && report.DUNS_Number__c.length() != 9)
      errorMessage += 'DUNS Number must be 9 digits.<br/>';

    if (
      report.Organization_Name_Text__c == null ||
      report.Organization_Name_Text__c == ''
    )
      errorMessage += 'Organization Name is required.<br/>';
    if (
      report.Submitted_By_Text__c == null ||
      report.Submitted_By_Text__c == ''
    )
      errorMessage += 'Submitted By is required.<br/>';

    if (report.Youth_Served__c == null)
      errorMessage += 'Youth Served is required.<br/>';
    if (report.Number_Activities__c == null)
      errorMessage += 'Number of Activities is required.<br/>';
    if (report.Youth_Wellbeing_Increase__c == null)
      errorMessage += 'Number of Youth Reporting an Increased Wellbeing is required.<br/>';
    if (report.Number_of_Mentors__c == null)
      errorMessage += 'Number of Youth Receiving Mentorship is required.<br/>';
    if (report.Law_Enforcement_Engaged__c == null)
      errorMessage += 'Number of Law Enforement Engaged is required.<br/>';
    if (report.Increase_in_Perception_of_Social_Support__c == null)
      errorMessage += 'Number of Youth Reporting an Improved Opinion is required.<br/>';
    if (report.Law_Enforcement_Improved_Knowledge__c == null)
      errorMessage += 'Number of Law Enforcement Increased Knowledge is required.<br/>';
    if (report.Laptops_Utilized__c == null)
      errorMessage += 'Number of Laptops is required.<br/>';
    if (report.Chromebooks_Utilized__c == null)
      errorMessage += 'Number of Chromebooks is required.<br/>';

    if (
      report.Projects_Effectiveness__c == null ||
      report.Projects_Effectiveness__c == ''
    )
      errorMessage += 'Brief Narrative of Effectiveness is required.<br/>';
    if (
      report.Problems_Barriers_Encountered_Details__c == null ||
      report.Problems_Barriers_Encountered_Details__c == ''
    )
      errorMessage += 'Barriers/Challenges is required.<br/>';
    if (
      report.Reason_Requesting_Funds__c == null ||
      report.Reason_Requesting_Funds__c == ''
    )
      errorMessage += 'No or Minimal Funds Expended is required.<br/>';
    if (
      report.Major_Activities_Planned__c == null ||
      report.Major_Activities_Planned__c == ''
    )
      errorMessage += 'Activities Planned is required.<br/>';
    if (
      report.Accomplishments_this_Reporting_Period__c == null ||
      report.Accomplishments_this_Reporting_Period__c == ''
    )
      errorMessage += 'Success and/or Best Practices is required.<br/>';
    if (
      report.Innovative_Programs_Accomplishments__c == null ||
      report.Innovative_Programs_Accomplishments__c == ''
    )
      errorMessage += 'Explanation of Award Helping Reduce Crime is required.<br/>';
    if (
      report.Cooperation_Collaboration__c == null ||
      report.Cooperation_Collaboration__c == ''
    )
      errorMessage += 'Level of Cooperation and Collaboration is required.<br/>';
    if (
      report.Progress_of_Completed_Goals__c == null ||
      report.Progress_of_Completed_Goals__c == ''
    )
      errorMessage += 'Summarize the Progress is required.<br/>';
    if (
      report.Performance_Measurement__c == null ||
      report.Performance_Measurement__c == ''
    )
      errorMessage += 'Brief Narrative of Quarterly Performance is required.<br/>';

    if (topics.isEmpty())
      errorMessage += 'Topics Surveyed is required.<br/>';

    if (report.Hosted_Meetings__c == null)
      errorMessage += 'Hosted Meetings is required.<br/>';
    if (report.Attended_Meetings__c == null)
      errorMessage += 'Attended Meetings is required.<br/>';
    if (report.Distributed_Newsletter__c == null)
      errorMessage += 'Distributed Newsletters is required<br/>';
    if (report.Attended_Events__c == null)
      errorMessage += 'Attended Events is required.<br/>';
    if (report.Social_Media_Activities__c == null)
      errorMessage += 'Social Media Activities is required.<br/>';
    if (report.Conducted_Outreach__c == null)
      errorMessage += 'Conducted Outreach is required.<br/>';
    if (report.Other__c == null)
      errorMessage += 'Other is required.<br/>';
    if (
      (report.Other__c != null && report.Other__c != 'Not Applicable') &&
      (report.Other_Describe__c == null ||
      report.Other_Describe__c == '')
    )
      errorMessage += 'Other Description is required.<br/>';
  }

  public void submit() {
    errorMessage = '';
    successMessage = '';
    report.Submitted_By__c = currentUser.Contact.Id;
    report.Submitted_By_Text__c = currentUser.Contact.Name;
    report.DOD_Email__c = currentUser.Contact.Email;
    report.Organization_Name_Text__c = uc.userAcct.Name;
    report.DUNS_Number__c = [
      SELECT DUNS_Number__c
      FROM Account
      WHERE Id = :uc.userAcct.Id
    ][0]
    .DUNS_Number__c;
    validation();
    if (errorMessage == '') {
      report.Status__c = 'Submitted';
      report.Submitted_Date__c = date.today();

      prc.upsertReport(report);

      if (ApexPages.hasMessages())
        errorMessage += string.valueOf(ApexPages.getMessages());
      else
        successMessage = 'Save successful.';
    }
  }

  public PageReference approve() {
    report.Status__c = 'Approved';
    prc.upsertReport(report);
    PageReference pr = new PageReference(
      '/MDGOProgramReport?report=' + report.Id
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference sendBack() {
    report.Status__c = 'Revisions Needed';
    prc.upsertReport(report);
    PageReference pr = new PageReference(
      '/MDGOProgramReport?report=' + report.Id
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference save() {
    if (userAcctType == 'Local Organization')
      report.Status__c = 'In Progress';
    prc.upsertReport(report);
    PageReference pr = new PageReference('/MDGOProgramReports');
    pr.setRedirect(true);
    return pr;
  }
}