force-app/main/default/objects/Account/fields/DUNS__c.field-meta.xml
<CustomField>
    <fullName>DUNS__c</fullName>
    <label>D-U-N-S Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description
  >Formula to add leading zero to D-U-N-S number if necessary</description>
    <formula>LPAD(TEXT(DUNS__c), 9, &apos;0&apos; )</formula>
    <label>D-U-N-S</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_Org_Code__c</fullName>
    <label>FirstPic Org Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grants__c.field-meta.xml
<CustomField>
    <fullName>National_Grants__c</fullName>
    <label>National Grants</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Authority_to_Apply__c.field-meta.xml
<CustomField>
    <fullName>Authority_to_Apply__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Authority to Apply</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <label>DUNS Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Eligibility_Notice_Received__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Notice_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility Notice Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Existing_Services__c.field-meta.xml
<CustomField>
    <fullName>Existing_Services__c</fullName>
    <label>Existing Services</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Funding_to_Purchase_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Funding_to_Purchase_Vehicle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding to Purchase Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Email__c</fullName>
    <label>Grant Admin Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_First_Name__c</fullName>
    <label>Grant Admin First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Last_Name__c</fullName>
    <label>Grant Admin Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Admin_Phone__c.field-meta.xml
<CustomField>
    <fullName>Grant_Admin_Phone__c</fullName>
    <label>Grant Admin Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <label>National Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (National Organization)</relationshipLabel>
    <relationshipName>NationalApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Needs_Assessment__c</fullName>
    <label>Needs Assessment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/New_or_Existing__c.field-meta.xml
<CustomField>
    <fullName>New_or_Existing__c</fullName>
    <label>New or Existing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <label>Organization Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tribe</fullName>
                <label>Tribal Nation</label>
            </value>
            <value>
                <fullName>Consortium</fullName>
            </value>
            <value>
                <fullName>Designee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/POC_Can_Receive_Communication__c.field-meta.xml
<CustomField>
    <fullName>POC_Can_Receive_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POC Can Receive Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Email__c</fullName>
    <label>Program Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_First_Name__c</fullName>
    <label>Program Contact First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Last_Name__c</fullName>
    <label>Program Contact Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Program_Contact_Phone__c</fullName>
    <label>Program Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Strategic_Plan__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Plan__c</fullName>
    <label>Strategic Plan</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Strategic_Plan_Victim_Services__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Plan_Victim_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Strategic Plan Victim Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Tribe_Represented__c.field-meta.xml
<CustomField>
    <fullName>Tribe_Represented__c</fullName>
    <description
  >Used in OVC SOI to allow Consortia and Designee submissions to indicate the tribe they represent.</description>
    <label>Tribe Represented</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <formula>Account.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/TestSOICtrl.cls
@isTest
public class TestSOICtrl {
  static testMethod void testSOI() {
    Date dt = Date.today();

    Account a1 = new Account(
      FirstPic_Org_Code__c = 'NCAI',
      EIN__c = '98-9827462',
      Name = 'NCAI',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert a1;

    Account a2 = new Account(
      National_Organization__c = a1.Id,
      EIN__c = '98-9827462',
      DUNS__c = 123456789,
      Name = 'NCAI',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a2;

    Application__c app1 = new Application__c(
      National_Organization__c = a1.Id,
      Organization_Name__c = 'Test'
    );
    insert app1;

    Application__c app2 = new Application__c(
      National_Organization__c = a1.Id,
      Organization_Name__c = 'Test',
      Organization_Type__c = 'Consortium',
      DUNS_Number__c = '123456789',
      Address__c = 'Test',
      City__c = 'Test',
      State__c = 'Test',
      Postal_Zip_Code__c = '12345',
      Grant_Admin_First_Name__c = 'Test',
      Grant_Admin_Last_Name__c = 'Test',
      Grant_Admin_Email__c = 'test@ga.com',
      Grant_Admin_Phone__c = '5556667777',
      POC_Can_Receive_Communication__c = false,
      Program_Contact_First_Name__c = 'Test',
      Program_Contact_Last_Name__c = 'Test',
      Program_Contact_Email__c = 'test@pc.com',
      Program_Contact_Phone__c = '5554443333',
      New_or_Existing__c = 'Existing',
      Existing_Services__c = 'Test',
      Strategic_Plan__c = 'Test',
      Eligibility_Notice_Received__c = false,
      Needs_Assessment__c = 'Test',
      Funding_to_Purchase_Vehicle__c = true,
      Strategic_Plan_Victim_Services__c = false,
      Authority_to_Apply__c = true,
      Tribe_Represented__c = 'Test'
    );
    insert app2;

    system.Test.startTest();
    Profile p1 = [SELECT Id FROM Profile WHERE Name = 'NCAI Level One'];
    Contact c1 = new Contact(
      lastName = 'Contact',
      firstName = 'Test',
      Email = 'test@login.com',
      accountId = a1.Id
    );
    insert c1;
    User u1 = new User(
      Alias = 'ksienf',
      Email = 'test@example3467.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p1.Id,
      UserName = 'test@ncailevelone23456.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;

    System.runAs(u1) {
      system.Test.setCurrentPageReference(
        new PageReference('Page.StatementOfInterest')
      );
      StatementOfInterestCtrl ctrl1 = new StatementOfInterestCtrl();
      ctrl1.app = app1;
      ctrl1.submit();
      system.assert(ctrl1.errorMessage != '');
      ctrl1.app = app2;
      ctrl1.submit();
      system.assert(ctrl1.errorMessage == '');
      ctrl1.notEligible();
      ctrl1.save();
      ctrl1.approve();
      Account test1 = [
        SELECT National_Grants__c
        FROM Account
        WHERE Id = :a2.Id
      ];
      system.assertEquals('OVC', test1.National_Grants__c);
    }
    system.Test.stopTest();
  }
}