force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description
  >Formula to add leading zero to D-U-N-S number if necessary</description>
    <formula>LPAD(TEXT(DUNS__c), 9, &apos;0&apos; )</formula>
    <label>D-U-N-S</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>National_Organization__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Primary Approver)</relationshipLabel>
    <relationshipName>Accounts_Primary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula
  >Primary_Approver__r.FirstName + &apos; &apos; + Primary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_On_Leave__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_On_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Approver On Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Program_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Organizations (Program Coordinator)</relationshipLabel>
    <relationshipName>Organizations_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Secondary Approver)</relationshipLabel>
    <relationshipName>Accounts_Secondary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Audit_Finding__c.field-meta.xml
<CustomField>
    <fullName>Audit_Finding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audit Finding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Audit_Fund__c.field-meta.xml
<CustomField>
    <fullName>Audit_Fund__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Audit Fund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Audit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Audit_Notes__c</fullName>
    <label>Audit Notes</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <label>DUNS Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Eligibility_Notice_Received__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Notice_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligibility Notice Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Federal_Debt__c.field-meta.xml
<CustomField>
    <fullName>Federal_Debt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Federal Debt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Organization__r.FirstPic_National_Org_Code__c != &apos;&apos;, Organization__r.FirstPic_National_Org_Code__c, National_Organization__r.FirstPic_Org_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <formula
  >IF(CONTAINS(RecordType.Name, &apos;GREAT&apos;), &quot;I&apos;m GREAT&quot;,
IF(CONTAINS(RecordType.Name, &apos;Baseball&apos;), &apos;Badges for Baseball&apos;, 
IF(CONTAINS(RecordType.Name, &apos;Special Initiative&apos;), &apos;Special Initiative&apos;,
IF(CONTAINS(RecordType.Name, &apos;Healthy Lifestyles&apos;), &apos;Healthy Lifestyles&apos;,
IF(CONTAINS(RecordType.Name, &apos;TRAIL&apos;), &apos;TRAIL&apos;,
IF(CONTAINS(RecordType.Name, &apos;OVC&apos;), &apos;OVC&apos;,
IF(CONTAINS(RecordType.Name, &apos;SOI&apos;), &apos;SOI&apos;,
&apos;&apos;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <label>National Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (National Organization)</relationshipLabel>
    <relationshipName>NationalApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <label>National Organization Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Primary_Approver__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula
  >Primary_Approver__r.FirstName + &apos; &apos; + Primary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Review_Notes__c.field-meta.xml
<CustomField>
    <fullName>Review_Notes__c</fullName>
    <label>Review Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent to Applicant</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Challenge</fullName>
                <default>true</default>
                <label>Challenge</label>
            </value>
            <value>
                <fullName>Freedom</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Human Services</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Review__c/Application_Review__c.object-meta.xml
<CustomObject>
    <label>Application Review</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Application Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Review__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Review__c/recordTypes/NCAI.recordType-meta.xml
<RecordType>
    <fullName>NCAI</fullName>
    <active>true</active>
    <label>NCAI</label>
</RecordType>

force-app/main/default/objects/Application_Review__c/recordTypes/Review.recordType-meta.xml
<RecordType>
    <fullName>Review</fullName>
    <active>true</active>
    <label>Review</label>
</RecordType>

force-app/main/default/objects/Application_Site__c/Application_Site__c.object-meta.xml
<CustomObject>
    <label>Application Site</label>
    <nameField>
        <label>Application Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Site__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Sites</relationshipLabel>
    <relationshipName>Application_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationClass.cls
public without sharing class ApplicationClass {
  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Application__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    //expr = expr.removeEnd(', ');
    expr += 'RecordType.Name, National_Organization__r.Name, Organization__r.Primary_Approver__c, Organization__r.Primary_Approver_Name__c, Organization__r.Secondary_Approver__c, Organization__r.Program_Coordinator__c';

    String soql = 'SELECT ' + expr + ' FROM Application__c';
    system.debug('>>> soql = ' + soql);
    return soql;
  }

  public List<Application__c> getApplicationList() {
    List<Application__c> app_list = new List<Application__c>();
    app_list = Database.query(getSOQL());
    return app_list;
  }

  public List<Application__c> getRelatedApplicationList(
    Id acctId,
    String keyword,
    String status,
    String soqlAND,
    String sortBy,
    Id paId
  ) {
    String soql = 'SELECT Id, Name, RecordType.Name, Organization__r.Id, Organization__r.Name, Organization_Name__c, Status__c, Submitted_Date__c, Primary_Approver__c, Organization__r.Primary_Approver__c, Organization__r.Primary_Approver_Name__c, Primary_Approver_Name__c, Type__c, Grant_Type__c, Eligibility_Notice_Received__c, DUNS_Number__c';
    soql += ', Grant_Year__c, Federal_Debt__c, Audit_Fund__c, Audit_Finding__c, Audit_Notes__c, Review_Notes__c';
    soql += ' FROM Application__c WHERE Name != null';
    if (acctId != null)
      soql +=
        ' AND (Organization__r.Id = \'' +
        acctId +
        '\' OR National_Organization__r.Id = \'' +
        acctId +
        '\')';
    if (keyword != '' && keyword != null)
      soql +=
        ' AND (Name LIKE \'%' +
        String.escapeSingleQuotes(keyword) +
        '%\' OR Organization__r.Name LIKE \'%' +
        String.escapeSingleQuotes(keyword) +
        '%\')';
    if (status != '' && status != null)
      soql += ' AND Status__c = \'' + status + '\'';
    if (paId != null) {
      soql += ' AND (Organization__r.Primary_Approver__c = \'' + paId + '\'';
      soql += ' OR Primary_Approver__c = \'' + paId + '\'';
      soql += ' OR (Organization__r.Secondary_Approver__c = \'' + paId + '\'';
      soql += ' AND (Organization__r.Primary_Approver_On_Leave__c = true OR FirstPic_National_Org_Code__c = \'Ripken\')))';
    }
    if (soqlAND != '' && soqlAND != null)
      soql += soqlAND;
    if (sortBy != '' && sortBy != null)
      soql += ' ORDER BY ' + sortBy + ' desc';
    else
      soql += ' ORDER BY Name';
    system.debug('Application soql = ' + soql);
    List<Application__c> apps = Database.query(soql);
    return apps;
  }

  public Application__c getApplication(Id appId) {
    Application__c app = new Application__c();
    if (appId != null) {
      String soql = getSOQL();
      soql += ' WHERE Id = \'' + appId + '\'';
      Application__c[] apps = Database.query(soql);
      if (apps.size() > 0) {
        app = apps[0];
      }
    }
    return app;
  }

  public List<Application_Site__c> getAppSites(Id appId) {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Application_Site__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');
    String soql =
      'SELECT ' +
      expr +
      ' FROM Application_Site__c WHERE Application__c = \'' +
      appId +
      '\'';
    system.debug('Application Sites soql = ' + soql);
    List<Application_Site__c> appSites = Database.query(soql);
    return appSites;
  }

  public List<Application_Review__c> getAppReviews(Id appId, Id reviewerId) {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Application_Review__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr += 'Reviewer__r.Name';
    String soql = 'SELECT ' + expr + ' FROM Application_Review__c';
    soql += ' WHERE Name != null';
    if (appId != null)
      soql += ' AND Application__c = \'' + appId + '\'';
    if (reviewerId != null)
      soql += ' AND Reviewer__c = \'' + reviewerId + '\'';
    system.debug('Application Reviews soql = ' + soql);
    List<Application_Review__c> items = Database.query(soql);
    return items;
  }

  public void upsertApplication(Application__c app) {
    try {
      upsert app;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }

  public void upsertApplications(List<Application__c> apps) {
    try {
      upsert apps;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }

  public void upsertAppSites(List<Application_Site__c> sites) {
    try {
      upsert sites;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }

  public void upsertAppReview(Application_Review__c review) {
    try {
      upsert review;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }

  public void updateNationalOrgField(List<Application__c> appList) {
    Account[] accts = [
      SELECT Id, FirstPic_National_Org_Code__c
      FROM Account
      WHERE RecordType.Name = 'National Organization'
    ];
    for (Application__c app : appList) {
      for (Account a : accts) {
        if (app.National_Organization_Id__c != null) {
          if (a.Id == app.National_Organization_Id__c) {
            app.National_Organization__c = a.Id;
          }
        } else if (
          app.RecordType.Name == 'Under Armour' &&
          a.FirstPic_National_Org_Code__c == 'UA'
        ) {
          app.National_Organization__c = a.Id;
        } else if (
          app.RecordType.Name.contains('Ripken') &&
          a.FirstPic_National_Org_Code__c == 'Ripken'
        ) {
          app.National_Organization__c = a.Id;
        } else if (
          app.RecordType.Name.contains('NCAI') &&
          a.FirstPic_National_Org_Code__c == 'NCAI'
        ) {
          app.National_Organization__c = a.Id;
        }
      }
    }
    try {
      update appList;
    } catch (Exception e) {
      system.debug(e);
    }
  }

  public void deleteApplicationSites(List<Application_Site__c> sites) {
    try {
      delete sites;
    } catch (Exception e) {
      system.debug(e);
    }
  }
}