force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Chapter_Report__c/Chapter_Report__c.object-meta.xml
<CustomObject>
    <label>Chapter Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Chapter Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chapter_Report__c/fields/Youth_in_Program_Report__c.field-meta.xml
<CustomField>
    <fullName>Youth_in_Program_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Youth in Program Report</label>
    <referenceTo>Youth_in_Program_Report__c</referenceTo>
    <relationshipLabel>Chapter Reports</relationshipLabel>
    <relationshipName>Chapter_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Month__c</fullName>
    <label>Birth Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <label>Birth Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Not specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/listViews/Youth.recordType-meta.xml
<RecordType>
    <fullName>Youth</fullName>
    <active>true</active>
    <label>Youth</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017 - 2018</fullName>
            </value>
            <value>
                <fullName>2018 - 2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019 - 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Test</fullName>
            </value>
            <value>
                <fullName>Post-Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/Youth_in_Program_Report__c.object-meta.xml
<CustomObject>
    <label>Youth in Program Report</label>
    <nameField>
        <displayFormat>Y-{0000}</displayFormat>
        <label>Youth in Program Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Youth in Program Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <formula>Contact__r.Birth_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birth Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Youth in Program Reports</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>TEXT(Contact__r.Gender__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Youth in Program Reports</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <formula>TEXT(Grant__r.Grant_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <formula>IF(TEXT(Program_Report__r.Grant_Year__c) != null,
TEXT(Program_Report__r.Grant_Year__c), 
IF(Grant__r.Year__c != null, Grant__r.Year__c, &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Program_Report__c.field-meta.xml
<CustomField>
    <fullName>Program_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Report</label>
    <referenceTo>Program_Report__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestYouthDataCtrls.cls
@isTest
public class TestYouthDataCtrls {
  static testMethod void testYouthData() {
    Account no = new Account(
      EIN__c = '00-7654321',
      Name = 'National Congress of American Indians',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2837563',
      National_Organization__c = no.Id,
      Name = 'Local',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Account site = new Account(
      EIN__c = '00-2947562',
      National_Organization__c = no.Id,
      Local_Organization__c = lo.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site;

    Contact youth1 = new Contact(
      AccountId = site.Id,
      LastName = '11',
      FirstName = 'Test1',
      Gender__c = 'M',
      Birth_Month__c = 'January',
      Birth_Year__c = '2010',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth1;

    Contact youth2 = new Contact(
      AccountId = site.Id,
      LastName = '2',
      FirstName = 'Test2',
      Gender__c = 'F',
      Birth_Month__c = 'January',
      Birth_Year__c = '2010',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth2;

    Grant__c g = new Grant__c(
      Account__c = no.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Grant')
        .getRecordTypeId()
    );
    insert g;

    Grant__c sg = new Grant__c(
      Account__c = lo.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId(),
      Grant_Status__c = 'Pending Final Approval'
    );
    insert sg;

    Date sd = Date.newInstance(2018, 1, 1);
    Date ed = Date.newInstance(2018, 12, 13);
    Program_Report__c pr1 = new Program_Report__c(
      Name = 'Youth Data Report Y1',
      Status__c = 'Not Started',
      Site__c = site.Id,
      Grant__c = sg.Id,
      Start_Date__c = sd,
      End_Date__c = ed,
      RecordTypeID = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
        .get('Youth Data')
        .getRecordTypeId(),
      Grant_Year__c = '1'
    );
    insert pr1;

    Survey__c pre = new Survey__c(
      Contact__c = youth1.Id,
      Type__c = 'Pre-Test',
      Status__c = 'Not Started'
    );
    insert pre;

    Survey__c post = new Survey__c(
      Contact__c = youth1.Id,
      Type__c = 'Post-Test',
      Status__c = 'Not Started'
    );
    insert post;

    Youth_in_Program_Report__c ypr1 = new Youth_in_Program_Report__c(
      Contact__c = youth1.Id,
      Program_Report__c = pr1.Id,
      Pre_Test__c = pre.Id,
      Post_Test__c = post.Id
    );
    insert ypr1;

    Chapter_Report__c cr1 = new Chapter_Report__c(
      Youth_in_Program_Report__c = ypr1.Id
    );
    insert cr1;

    PA_Challenge__c pac = new PA_Challenge__c(
      Youth_in_Program_Report__c = ypr1.Id,
      Title__c = 'Physical Activity Strength Challenge 2 – Push-ups'
    );
    insert pac;

    system.test.startTest();
    Profile p = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact noc = new Contact(
      accountId = no.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert noc;
    User nou = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = noc,
      ContactId = noc.Id
    );
    insert nou;

    System.runAs(nou) {
      system.test.setCurrentPageReference(
        new PageReference(
          'Page.YouthData?localOrgId=' +
          lo.Id +
          '&siteId=' +
          site.Id +
          '&grantId=' +
          sg.Id +
          '&year=1'
        )
      );
      YouthDataCtrl ctrl1 = new YouthDataCtrl();
      ctrl1.getLists();
      ctrl1.getPACList();
      ctrl1.getReport();
      ctrl1.getYouth();
      ctrl1.clear();

      system.test.setCurrentPageReference(
        new PageReference('Page.YouthForm?youthId=' + youth1.Id)
      );
      YouthDataCtrl ctrl2 = new YouthDataCtrl();
      ctrl2.youthId = youth1.Id;
      ctrl2.getYouth();
      ctrl2.getYouthYPRList();
      ctrl2.youth.LastName = 'a';
      ctrl2.saveYouth();
      ctrl2.showFindYouthPopup();
      ctrl2.hideFindYouthPopup();
      ctrl2.youthDupCheck();
      ctrl2.yprDupCheck();
      ctrl2.updateExistingYouth();
      ctrl2.saveYouthDetails();
      //ctrl2.selectYouth();
      ctrl2.showSendBackPopup();
      ctrl2.hideSendBackPopup();
      ctrl2.showApprovePopup();
      ctrl2.hideApprovePopup();
      ctrl2.hideConfirmPopup();
      ctrl2.clearYouthForm();
      //Survey__c[] surveys = [SELECT Id FROM Survey__c WHERE Contact__c = :youth1.Id];
      //system.assert(surveys.size() > 0);
    }
    system.test.stopTest();
  }

  static testMethod void testSurveys() {
    Account site = new Account(
      EIN__c = '00-2947562',
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site;

    Contact youth1 = new Contact(
      AccountId = site.Id,
      LastName = '11',
      FirstName = 'Test1',
      Gender__c = 'M',
      Birth_Month__c = 'January',
      Birth_Year__c = '2010',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth1;

    Date sd = Date.newInstance(2018, 1, 1);
    Date ed = Date.newInstance(2018, 12, 13);
    Program_Report__c pr1 = new Program_Report__c(
      Name = 'Youth Data Report Y1',
      Status__c = 'Not Started',
      Site__c = site.Id,
      Start_Date__c = sd,
      End_Date__c = ed,
      RecordTypeID = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
        .get('Youth Data')
        .getRecordTypeId(),
      Grant_Year__c = '1'
    );
    insert pr1;

    Survey__c pre = new Survey__c(
      Contact__c = youth1.Id,
      Type__c = 'Pre-Test',
      Status__c = 'Not Started'
    );
    insert pre;

    Survey__c post = new Survey__c(
      Contact__c = youth1.Id,
      Type__c = 'Post-Test',
      Status__c = 'Not Started'
    );
    insert post;

    Youth_in_Program_Report__c ypr1 = new Youth_in_Program_Report__c(
      Contact__c = youth1.Id,
      Program_Report__c = pr1.Id,
      Pre_Test__c = pre.Id,
      Post_Test__c = post.Id
    );
    insert ypr1;

    Chapter_Report__c cr1 = new Chapter_Report__c(
      Youth_in_Program_Report__c = ypr1.Id
    );
    insert cr1;

    PA_Challenge__c pac = new PA_Challenge__c(
      Youth_in_Program_Report__c = ypr1.Id,
      Title__c = 'Physical Activity Strength Challenge 2 – Push-ups'
    );
    insert pac;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'NCAI Level One'];
    Contact sc = new Contact(
      accountId = site.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert sc;
    User su = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = sc,
      ContactId = sc.Id
    );
    insert su;

    system.test.startTest();
    System.runAs(su) {
      system.test.setCurrentPageReference(
        new PageReference('Page.Survey?surveyId=' + pre.Id)
      );
      YouthDataCtrl ctrl3 = new YouthDataCtrl();
      ctrl3.getURLParams();
      ctrl3.getSurvey();
      ctrl3.saveSurvey();
      ctrl3.submitSurvey();

      system.test.setCurrentPageReference(
        new PageReference('Page.PAChallenges?yprId=yprId=' + ypr1.Id)
      );
      YouthDataCtrl ctrl4 = new YouthDataCtrl();
      ctrl4.yprId = ypr1.Id;
      ctrl4.getPACList();
      ctrl4.savePACs();
      ctrl4.saveAndExitPACs();
      ctrl4.submitPACs();
      ctrl4.sendBackPACs();
      ctrl4.approvePACs();

      Youth_in_Program_Report__c updatedYPR = [
        SELECT Pre_Test_Status__c, Post_Test_Status__c, PA_Challenge_Status__c
        FROM Youth_in_Program_Report__c
        WHERE Id = :ypr1.Id
      ];
      //system.assertEquals('Complete', updatedYPR.Pre_Test_Status__c);
      //system.assertEquals('Complete', updatedYPR.PA_Challenge_Status__c);
    }
    system.test.stopTest();
  }

  static testMethod void testYouthDataLists() {
    system.test.startTest();
    Account no = new Account(
      EIN__c = '00-7654321',
      Name = 'National Congress of American Indians',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2837563',
      National_Organization__c = no.Id,
      Name = 'Local',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Account site = new Account(
      EIN__c = '00-2947562',
      National_Organization__c = no.Id,
      Local_Organization__c = lo.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site;

    Contact youth1 = new Contact(
      AccountId = site.Id,
      LastName = '11',
      FirstName = 'Test1',
      Gender__c = 'M',
      Birth_Month__c = 'January',
      Birth_Year__c = '2010',
      RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
        .get('Youth')
        .getRecordTypeId()
    );
    insert youth1;

    Grant__c g = new Grant__c(
      Account__c = no.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Grant')
        .getRecordTypeId()
    );
    insert g;

    Grant__c sg = new Grant__c(
      Account__c = lo.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId(),
      Grant_Status__c = 'Pending Final Approval'
    );
    insert sg;

    List<Program_Report__c> prs = new List<Program_Report__c>();
    for (Integer i = 0; i < 50; i++) {
      Program_Report__c pr = new Program_Report__c(
        Name = 'Youth Data Report Y1',
        Site__c = site.Id,
        Grant__c = sg.Id,
        RecordTypeID = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
          .get('Youth Data')
          .getRecordTypeId()
      );
      prs.add(pr);
    }
    insert prs;

    List<Youth_in_Program_Report__c> yprs = new List<Youth_in_Program_Report__c>();
    for (Program_Report__c pr : prs) {
      Youth_in_Program_Report__c ypr = new Youth_in_Program_Report__c(
        Contact__c = youth1.Id,
        Program_Report__c = pr.Id
      );
      yprs.add(ypr);
    }
    insert yprs;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact noc = new Contact(
      accountId = no.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert noc;
    User nou = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = noc,
      ContactId = noc.Id
    );
    insert nou;

    System.runAs(nou) {
      system.test.setCurrentPageReference(
        new PageReference(
          'Page.YouthData?localOrgId=' +
          lo.Id +
          '&siteId=' +
          site.Id +
          '&grantId=' +
          sg.Id +
          '&year=1'
        )
      );
      YouthDataCtrl ctrl1 = new YouthDataCtrl();
      ctrl1.next();
      ctrl1.previous();
      ctrl1.last();
      ctrl1.clear();

      system.test.setCurrentPageReference(
        new PageReference('Page.ChapterReports')
      );
      ChapterReportCtrl ctrl2 = new ChapterReportCtrl();
      ctrl2.getLists();
      //ctrl2.reportId = cr1.Id;
      ctrl2.getReport();
      ctrl2.save();
      ctrl2.next();
      ctrl2.previous();
      ctrl2.last();
    }
    system.test.stopTest();
  }
}