force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Active_Date__c</fullName>
    <label>Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK( Birthdate ) ) , 
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), 
YEAR (Today()) - YEAR ( Birthdate ), 
YEAR (Today()) - YEAR ( Birthdate ) -1 ), 
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exited_Date__c.field-meta.xml
<CustomField>
    <fullName>Exited_Date__c</fullName>
    <label>Exited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Not specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/listViews/Youth.recordType-meta.xml
<RecordType>
    <fullName>Youth</fullName>
    <active>true</active>
    <label>Youth</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <formula>Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Accomplishments__c</fullName>
    <label>Accomplishments</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6 Years Old</fullName>
            </value>
            <value>
                <fullName>7 Years Old</fullName>
            </value>
            <value>
                <fullName>8 Years Old</fullName>
            </value>
            <value>
                <fullName>9 Years Old</fullName>
            </value>
            <value>
                <fullName>10 Years Old</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Assistance_Needed__c.field-meta.xml
<CustomField>
    <fullName>Assistance_Needed__c</fullName>
    <label>Assistance Needed</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Youth Population Not Directly Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <label>Geography</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>Suburban</fullName>
            </value>
            <value>
                <fullName>Tribal</fullName>
            </value>
            <value>
                <fullName>Urban</fullName>
            </value>
            <value>
                <fullName>Youth Population Not Directly Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <formula>TEXT(Grant__r.Grant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Innovative_Programs_Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Innovative_Programs_Accomplishments__c</fullName>
    <label>Innovative Programs Accomplishments</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Justice__c.field-meta.xml
<CustomField>
    <fullName>Justice__c</fullName>
    <label>Justice</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At-Risk Population</fullName>
                <label>At-Risk Population (no prior offenses)</label>
            </value>
            <value>
                <fullName>First Time Offenders</fullName>
            </value>
            <value>
                <fullName>Repeat Offenders</fullName>
            </value>
            <value>
                <fullName>Sex Offenders</fullName>
            </value>
            <value>
                <fullName>Status Offenders</fullName>
            </value>
            <value>
                <fullName>Violent Offenders</fullName>
            </value>
            <value>
                <fullName>Youth Population Not Directly Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Major_Activities_Planned__c.field-meta.xml
<CustomField>
    <fullName>Major_Activities_Planned__c</fullName>
    <label>Major Activities Planned</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Mentoring_Programs_Operated__c.field-meta.xml
<CustomField>
    <fullName>Mentoring_Programs_Operated__c</fullName>
    <label>Mentoring Programs Operated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Mentors_Left_the_Program__c.field-meta.xml
<CustomField>
    <fullName>Mentors_Left_the_Program__c</fullName>
    <label>Mentors Left the Program</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Mentors_with_Increased_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Mentors_with_Increased_Knowledge__c</fullName>
    <label>Mentors with Increased Knowledge</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/New_Mentors__c.field-meta.xml
<CustomField>
    <fullName>New_Mentors__c</fullName>
    <label>New Mentors</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/New_Mentors_Began_Training__c.field-meta.xml
<CustomField>
    <fullName>New_Mentors_Began_Training__c</fullName>
    <label>New Mentors Began Training</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/New_Mentors_Completed_Training__c.field-meta.xml
<CustomField>
    <fullName>New_Mentors_Completed_Training__c</fullName>
    <label>New Mentors Completed Training</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/New_Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>New_Youth_Served__c</fullName>
    <label>New Youth Served</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mental Health</fullName>
            </value>
            <value>
                <fullName>Pregnant</fullName>
            </value>
            <value>
                <fullName>Substance Abuse</fullName>
            </value>
            <value>
                <fullName>Truant/Dropout</fullName>
            </value>
            <value>
                <fullName>Youth Population Not Directly Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Previous_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Previous_Mentors__c</fullName>
    <label>Previous Mentors</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Previous_Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Previous_Youth_Served__c</fullName>
    <label>Previous Youth Served</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestGranteeReportControllers.cls
@isTest
public class TestGranteeReportControllers {
  static testMethod void test() {
    Date dt = Date.today();

    Account a = new Account(
      EIN__c = '98-7654321',
      Name = 'Name',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a;

    Contact y = new Contact(
      accountId = a.Id,
      lastName = 'Youth',
      firstName = 'Test',
      Active_Date__c = dt,
      Exited_Date__c = dt
    );
    insert y;

    Grant__c g = new Grant__c(
      Account__c = a.Id,
      Grant_Type__c = 'Badges for Baseball',
      Amount__c = 500000,
      End_Date__c = dt.addDays(30),
      Grant_Status__c = 'Pending Review',
      Name = 'name',
      Project_Description__c = 'description test',
      Project_Name__c = 'name',
      Start_Date__c = dt
    );
    insert g;

    Grantee_Report__c r = new Grantee_Report__c(
      Start_Date__c = dt.addDays(-100),
      End_Date__c = dt.addDays(100),
      Accomplishments__c = 'test',
      Age__c = 'test',
      Assistance_Needed__c = 'test',
      Gender__c = 'test',
      Geography__c = 'test',
      Grant__c = g.Id,
      Innovative_Programs_Accomplishments__c = 'test',
      Justice__c = 'test',
      Major_Activities_Planned__c = 'test',
      Mentoring_Programs_Operated__c = 10,
      Mentors_Left_the_Program__c = '10',
      Mentors_with_Increased_Knowledge__c = '10',
      New_Mentors__c = '10',
      New_Mentors_Began_Training__c = '10',
      New_Mentors_Completed_Training__c = '10',
      New_Youth_Served__c = '10',
      Notes__c = 'test',
      Other__c = 'test',
      Previous_Mentors__c = '10',
      Previous_Youth_Served__c = '10',
      Problems_Barriers__c = 'test',
      Program_on_Track__c = 'test',
      Programs_with_Active_Partners__c = '10',
      Race_Ethnicity__c = 'test',
      Report_Status__c = 'In Progress',
      Type__c = 'test',
      Youth_Completed_Program__c = '10',
      Youth_Exited_Program__c = '10',
      Youth_Identify_as_Native_American__c = 10,
      Youth_Received_Additional_Sentence__c = '10',
      Youth_Recommitted_to_Juvenile_Facility__c = '10',
      Youth_Sentenced_to_Adult_Prison__c = '10',
      Youth_Served_via_Evidence_Based_Program__c = 10,
      Youth_Tracked_for_Juvenile_Offenses__c = 10,
      Youth_with_Delinquent_Offenses__c = '10',
      Youth_with_Incarcerate_Parent__c = '10',
      Youth_with_Increased_School_Attendance__c = 10,
      Youth_with_Increased_Social_Support__c = '10',
      Youth_with_Juvenile_Offenses__c = 10,
      Youth_with_Parents_Actively_Serving__c = '10',
      Youth_with_School_Attendance_Mentoring__c = 10,
      Youth_with_Social_Support_Mentoring__c = 10,
      Youth_Completed_20_or_More_Sessions__c = '10',
      Youth_Completed_Less_Than_20_Sessions__c = '10',
      Participated_More_Than_6_Months__c = '10',
      Participated_Fewer_Than_6_Months__c = '10',
      Participated_More_Than_4_Hours_per_Month__c = '10',
      Participated_Less_Than_4_Hours_per_Month__c = '10',
      Describe_How_Plan_Was_Implemented__c = '10'
    );
    insert r;

    Blob bodyBlob1 = Blob.valueOf('Attachment Test Body');
    Attachment att = new Attachment(
      Name = 'Test',
      body = bodyBlob1
      //,parentId = r.id
    );
    //insert att;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'Ripken Local Admin'];
    Contact c1 = new Contact(
      lastName = 'Contact',
      firstName = 'Test',
      Email = 'test@example.com',
      accountId = a.Id
    );
    insert c1;
    User u = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test@example.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u;

    System.runAs(u) {
      System.Test.setCurrentPageReference(
        new PageReference('Page.GranteeReport')
      );
      System.currentPageReference().getParameters().put('ReportID', r.Id);
      GranteeReportController ctrl1 = new GranteeReportController();
      ctrl1.init();
      ctrl1.getTotalYouthServerd();
      ctrl1.resetOutputs();
      ctrl1.resetMatchDetails();
      ctrl1.getAttList();
      ctrl1.errorCheck();
      ctrl1.attPopup();
      ctrl1.attPopup();
      ctrl1.previous();
      ctrl1.saveReport();
      ctrl1.submit();
      ctrl1.attPopup();
      ctrl1.attPopup();
      ctrl1.sendBackPopup();
      ctrl1.sendBackPopup();
      ctrl1.sendBack();
      ctrl1.approveReport();
      ctrl1.deleteAtt();

      System.Test.setCurrentPageReference(
        new PageReference('Page.GranteeReport')
      );
      System.currentPageReference().getParameters().put('GrantID', g.Id);
      GranteeReportController ctrl2 = new GranteeReportController();
      ctrl2.init();

      System.Test.setCurrentPageReference(new PageReference('Page.ReportList'));
      ReportListCtrl ctrl4 = new ReportListCtrl();
      ctrl4.getLists();
      ctrl4.deleteReport();
      ctrl4.getSessionReports();

      System.Test.setCurrentPageReference(
        new PageReference('Page.NPALReportList')
      );
      System.currentPageReference().getParameters().put('GrantID', g.Id);
      ReportListCtrl ctrl5 = new ReportListCtrl();
      ctrl5.ReportID = r.Id;
      ctrl5.getLists();
      ctrl5.deleteReport();
      ctrl5.deleteReportPopup();
      ctrl5.deleteReportPopup();

      System.Test.setCurrentPageReference(
        new PageReference('Page.UAGranteeReport')
      );
      System.currentPageReference().getParameters().put('GrantId', g.Id);
      GranteeReportCtrl ctrl6 = new GranteeReportCtrl();
      ctrl6.save();

      System.Test.setCurrentPageReference(
        new PageReference('Page.RipkenDCTATReport')
      );
      System.currentPageReference().getParameters().put('reportId', r.Id);
      DCTATReportCtrl ctrl7 = new DCTATReportCtrl();
      ctrl7.save();
      ctrl7.submit();
      ctrl7.sendBack();
      ctrl7.approve();
      ctrl7.showSendBackPopup();
      ctrl7.hideSendBackPopup();
      ctrl7.showApprovePopup();
      ctrl7.hideApprovePopup();

      System.Test.setCurrentPageReference(
        new PageReference('Page.SemiAnnualReport')
      );
      System.currentPageReference().getParameters().put('reportId', r.Id);
      DCTATReportCtrl ctrl8 = new DCTATReportCtrl();
      ctrl8.stemFieldValidation();
      ctrl8.submit();
    }
  }
}