force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/TA_Log__c/TA_Log__c.object-meta.xml
<CustomObject>
    <label>TA Log</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TA_Log__c/fields/Additional_TA_Provider__c.field-meta.xml
<CustomField>
    <fullName>Additional_TA_Provider__c</fullName>
    <label>Additional TA Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Flagged_for_Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Flagged_for_Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged for Follow-Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Follow_Up_TA_Log__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_TA_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow-Up TA Log</label>
    <referenceTo>TA_Log__c</referenceTo>
    <relationshipLabel>TA Logs (Follow-Up TA Log)</relationshipLabel>
    <relationshipName>Follow_Up_TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Grantee_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Grantee_Attendee__c</fullName>
    <label>Grantee Attendee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Is_Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Is_Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Follow Up?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Original_TA_Log__c.field-meta.xml
<CustomField>
    <fullName>Original_TA_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original TA Log</label>
    <referenceTo>TA_Log__c</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/TA_By__c.field-meta.xml
<CustomField>
    <fullName>TA_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TA By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestTALogs.cls
@isTest
public class TestTALogs {
  static testMethod void testTALogCtrl() {
    system.test.startTest();
    Date dt = date.today();

    Account no = new Account(
      EIN__c = '00-7654321',
      Name = 'National Congress of American Indians',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2837563',
      National_Organization__c = no.Id,
      Name = 'Local',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Account site1 = new Account(
      EIN__c = '11-2947562',
      National_Organization__c = no.Id,
      Local_Organization__c = lo.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site1;

    Account site2 = new Account(
      EIN__c = '22-2947562',
      National_Organization__c = no.Id,
      Local_Organization__c = lo.Id,
      Name = 'Site2',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert site2;

    TA_Log__c ta1 = new TA_Log__c(
      Organization__c = site1.Id,
      Date__c = dt,
      Additional_TA_Provider__c = 'asdf',
      Flagged_for_Follow_Up__c = true,
      Grantee_Attendee__c = 'asdf',
      Is_Follow_Up__c = false,
      Notes__c = 'asdf'
      //TA_By__c = 'asdf'
    );
    insert ta1;

    List<TA_Log__c> logs = new List<TA_Log__c>();
    for (Integer i = 0; i < 50; i++) {
      TA_Log__c ta = new TA_Log__c(Organization__c = site2.Id, Date__c = dt);
      logs.add(ta);
    }
    insert logs;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact noc = new Contact(
      accountId = no.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert noc;
    User nou = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = noc,
      ContactId = noc.Id
    );
    insert nou;

    System.runAs(nou) {
      system.test.setCurrentPageReference(new PageReference('Page.TALogs'));
      TALogCtrl ctrl1 = new TALogCtrl();
      ctrl1.siteId = site2.Id;
      ctrl1.next();
      ctrl1.previous();
      ctrl1.last();

      ctrl1.selectedLogId = ta1.Id;
      ctrl1.siteId = site1.Id;
      ctrl1.getTALog();
      ctrl1.getOriginalTALog();
      ctrl1.getFollowUpTALog();
      ctrl1.showTALogPopup();
      ctrl1.selectedLogId = ta1.Id;
      ctrl1.showTAFollowUpPopup();
      ctrl1.selectedLog.Notes__c = 'Follow Up Test';
      ctrl1.upsertTALog();
      //            TA_Log__c test1 = [SELECT Original_TA_Log__c FROM TA_Log__c WHERE Is_Follow_Up__c = true];
      //            TA_Log__c test2 = [SELECT Follow_Up_TA_Log__c, Flagged_for_Follow_Up__c FROM TA_Log__c WHERE Id = :ta1.Id];
      //            system.assert(test2.Follow_Up_TA_Log__c != null);
      //            system.assert(test2.Flagged_for_Follow_Up__c == false);
      ctrl1.hideTALogPopup();
    }
  }
}