force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/TestSiteDetailsCtrl.cls
@isTest
public class TestSiteDetailsCtrl {
  static testMethod void testSiteDetails() {
    system.test.startTest();
    Date dt = Date.today();

    Account a1 = new Account(
      EIN__c = '00-7654321',
      Name = 'Cal Ripken Sr. Foundation',
      Phone = '5555555555',
      BillingStreet = 'Street',
      BillingCity = 'City',
      BillingState = 'CA',
      BillingPostalCode = '12345',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert a1;

    Account a2 = new Account(
      EIN__c = '00-2837563',
      National_Organization__c = a1.Id,
      Name = 'Local',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a2;

    Account a3 = new Account(
      EIN__c = '00-2947562',
      National_Organization__c = a1.Id,
      Local_Organization__c = a2.Id,
      Name = 'Site',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Site')
        .getRecordTypeId()
    );
    insert a3;

    List<Account> accts = new List<Account>();
    for (Integer i = 0; i < 30; i++) {
      Account a = new Account(
        Name = 'Local ' + i,
        RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
          .get('Local Organization')
          .getRecordTypeId()
      );
      accts.add(a);
    }
    insert accts;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'NCAI Level Three'];
    Contact c1 = new Contact(
      accountId = a1.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert c1;
    User u1 = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;

    System.runAs(u1) {
      system.test.setCurrentPageReference(
        new PageReference('Page.SiteDetails')
      );
      SiteDetailsCtrl ctrl1 = new SiteDetailsCtrl();
      ctrl1.getLists();
      ctrl1.upsertOrg();
      ctrl1.selectedContactId = c1.Id;
      ctrl1.showEditRelatedContactPopup();
      ctrl1.selectedContact.FirstName = 'Updated';
      ctrl1.upsertContact();
      Contact c1test = [SELECT FirstName FROM Contact WHERE Id = :c1.Id];
      system.assert(c1test.FirstName == 'Updated');
      ctrl1.hideEditRelatedContactPopup();
      ctrl1.showDeleteContactPopup();
      ctrl1.hideDeleteContactPopup();
      ctrl1.showEditOrgPopup();
      ctrl1.hideEditOrgPopup();
      ctrl1.deleteContact();

      ctrl1.getRelatedAccountList();
      ctrl1.siteFirst();
      ctrl1.siteNext();
      ctrl1.sitePrevious();
      ctrl1.siteLast();

      ctrl1.youthFirst();
      ctrl1.youthNext();
      ctrl1.youthPrevious();
      ctrl1.youthLast();

      ctrl1.selectedSiteId = a3.Id;
      ctrl1.showSendApplicationPopup();
      ctrl1.sendApplication();
    }
    system.test.stopTest();
  }
}