force-app/main/default/objects/Account/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Plan__c/fields/Able_to_Recruit__c.field-meta.xml
<CustomField>
    <fullName>Able_to_Recruit__c</fullName>
    <label>Able to Recruit</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Areas_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Areas_of_Service__c</fullName>
    <label>Areas of Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Providing information to crime victims</fullName>
            </value>
            <value>
                <fullName>Referral services for crime victims</fullName>
            </value>
            <value>
                <fullName>Victim advocacy/accompaniment</fullName>
            </value>
            <value>
                <fullName
        >Law enforcement interview advocacy/accompaniment</fullName>
                <label>Law enforcement interview advocacy/accompaniment</label>
            </value>
            <value>
                <fullName
        >Intervention with employer, creditor, landlord or academic institution</fullName>
                <label
        >Intervention with employer, creditor, landlord or academic institution</label>
            </value>
            <value>
                <fullName>Child and/or dependent care assistance</fullName>
            </value>
            <value>
                <fullName>Transportation assistance</fullName>
            </value>
            <value>
                <fullName>Interpreter services</fullName>
            </value>
            <value>
                <fullName>Crisis intervention</fullName>
            </value>
            <value>
                <fullName>Hotline/crisis line counseling</fullName>
            </value>
            <value>
                <fullName>On-scene crisis response</fullName>
            </value>
            <value>
                <fullName
        >Sexual Assault Response Team (SART) team development</fullName>
                <label
        >Sexual Assault Response Team (SART) team development</label>
            </value>
            <value>
                <fullName
        >Coordinated Community Response (CCR) team development</fullName>
                <label
        >Coordinated Community Response (CCR) team development</label>
            </value>
            <value>
                <fullName>Updating tribal codes for victim services</fullName>
            </value>
            <value>
                <fullName
        >Access to Traditional/Cultural Healing ceremonies for victims</fullName>
                <label
        >Access to Traditional/Cultural Healing ceremonies for victims</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Biggest_Issue_Organization_is_Facing__c.field-meta.xml
<CustomField>
    <fullName>Biggest_Issue_Organization_is_Facing__c</fullName>
    <label>Biggest Issue Organization is Facing</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Current_Program_Description__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Description__c</fullName>
    <label>Current Program Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Equipment_and_Supplies__c.field-meta.xml
<CustomField>
    <fullName>Equipment_and_Supplies__c</fullName>
    <label>Equipment and Supplies</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Has_Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Has_Needs_Assessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Needs Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/How_Funds_Utilized__c.field-meta.xml
<CustomField>
    <fullName>How_Funds_Utilized__c</fullName>
    <label>How Funds Utilized</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Other_Challenges__c.field-meta.xml
<CustomField>
    <fullName>Other_Challenges__c</fullName>
    <label>Other Challenges</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestProgramPlans.cls
@isTest
public class TestProgramPlans {
  static testMethod void testListAndDetailsPages() {
    system.test.startTest();
    Date dt = date.today();

    Account no = new Account(
      EIN__c = '00-7654321',
      Name = 'National Congress of American Indians',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('National Organization')
        .getRecordTypeId()
    );
    insert no;

    Account lo = new Account(
      EIN__c = '00-2837563',
      National_Organization__c = no.Id,
      Name = 'Local',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert lo;

    Program_Plan__c pp1 = new Program_Plan__c(Organization__c = lo.Id);
    insert pp1;

    Program_Plan__c pp2 = new Program_Plan__c(
      Organization__c = lo.Id,
      Biggest_Issue_Organization_is_Facing__c = 'test',
      How_Funds_Utilized__c = 'test',
      Has_Needs_Assessment__c = false,
      Has_Strategic_Plan__c = false,
      Areas_of_Service__c = 'Other',
      Current_Program_Description__c = 'test',
      Equipment_and_Supplies__c = 'test',
      Responsibilities__c = 'test',
      Able_to_Recruit__c = 'test',
      Other_Challenges__c = 'test'
    );
    insert pp2;

    List<Program_Plan__c> plans = new List<Program_Plan__c>();
    for (Integer i = 0; i < 50; i++) {
      Program_Plan__c pp = new Program_Plan__c(Organization__c = lo.Id);
      plans.add(pp);
    }
    insert plans;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact noc = new Contact(
      accountId = no.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com',
      Role__c = 'CEO'
    );
    insert noc;
    User nou = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id,
      UserName = 'test1@qerjda.com',
      Contact = noc,
      ContactId = noc.Id
    );
    insert nou;

    System.runAs(nou) {
      system.test.setCurrentPageReference(
        new PageReference('Page.ProgramPlans')
      );
      ProgramPlansCtrl ctrl1 = new ProgramPlansCtrl();
      ctrl1.getLists();
      ctrl1.next();
      ctrl1.previous();
      ctrl1.last();

      // Test with empty program plan
      system.test.setCurrentPageReference(
        new PageReference(
          'Page.ProgramPlan?orgId=' +
          lo.Id +
          'planId=' +
          pp1.Id
        )
      );
      ProgramPlanCtrl ctrl2 = new ProgramPlanCtrl();
      ctrl2.updatePlan();
      ctrl2.submit();
      ctrl2.approve();
      ctrl2.sendBack();

      // Test with completed program plan
      ctrl2.plan = pp2;
      ctrl2.updatePlan();
      ctrl2.submit();
      ctrl2.approve();
      ctrl2.sendBack();

      ProgramPlanClass ctrl3 = new ProgramPlanClass();
      ctrl3.getPlan(pp1.Id);
    }
  }
}