force-app/main/default/objects/Account/fields/Estimated_Date_of_Expo__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Expo__c</fullName>
    <label>Estimated Date of Expo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Implementation_Model__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Model__c</fullName>
    <label>Implementation Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Twice a Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Cohorts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cohorts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Cohorts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Team_Size__c.field-meta.xml
<CustomField>
    <fullName>Team_Size__c</fullName>
    <description>Average # of youth in a single team</description>
    <label>Team Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Date_of_Expo__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Expo__c</fullName>
    <label>Date of Expo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Estimated_Date_of_Expo__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Expo__c</fullName>
    <label>Estimated Date of Expo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Expo_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Expo_Report_Status__c</fullName>
    <label>Expo Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
                <isActive>false</isActive>
                <label>Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/LEGOExpoReportCtrl.cls
public with sharing class LEGOExpoReportCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public Account acct { get; set; }

  public Id SessionId { get; set; }
  public List<SelectOption> options { get; set; }
  public Session__c session { get; set; }

  public Date expoDate { get; set; }
  public Boolean editMode { get; set; }
  public String statusColor { get; set; }

  public Boolean displayAttPopup { get; set; }
  public List<Attachment> att_list { get; set; }
  public Id deleteAttId { get; set; }

  public LEGOExpoReportCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;

    Account acct = new Account();
    Session__c session = new Session__c();

    editMode = true;
    statusColor = 'text-warning';

    SessionSelectOptionsCtrl ssoc = new SessionSelectOptionsCtrl();
    options = ssoc.options;

    String sId = ApexPages.currentPage().getParameters().get('SessionId');
    if (sId == null || sId == '')
      sId = ssoc.sessionId;
    if (sId != null && sId != '') {
      SessionId = sId;
      init();
    }
  }

  public void init() {
    if (userAcct != null) {
      Session__c[] sessions = [
        SELECT Id, Name, Site__c
        //(SELECT Id, Name, Description FROM Attachments ORDER BY LastModifiedDate desc)
        FROM Session__c
        WHERE Id = :SessionId
      ];

      if (sessions.size() > 0) {
        SessionClass sc = new SessionClass(null, null);
        session = sc.getSession(sessions[0].Id, false);
        if (session.Site__c != null) {
          Account[] accts = [
            SELECT
              Name,
              RecordType.Name,
              Type,
              Number_of_Cohorts__c,
              Team_Size__c,
              Implementation_Model__c,
              Start_Date__c,
              Estimated_Date_of_Expo__c
            FROM Account
            WHERE Id = :session.Site__c
          ];
          if (accts.size() > 0) {
            acct = accts[0];
          }
        }
        if (session.Date_of_Expo__c != null) {
          expoDate = session.Date_of_Expo__c;
        } else {
          expoDate = Date.today();
        }
        if (session.Expo_Report_Status__c == 'Submitted') {
          editMode = false;
          statusColor = 'text-success';
        } else {
          editMode = true;
        }
      }
    }
    getAttList();
  }

  public void getAttList() {
    att_list = new List<Attachment>();
    displayAttPopup = false;
    if (session != null) {
      att_list = [
        SELECT Id, Name, Description
        FROM Attachment
        WHERE ParentId = :session.Id
        ORDER BY LastModifiedDate DESC
      ];
    }
  }

  public PageReference save() {
    if (session != null) {
      if (
        session.Expo_Report_Status__c == null ||
        session.Expo_Report_Status__c == 'Not Started'
      ) {
        session.Expo_Report_Status__c = 'In Progress';
      }
      session.Date_of_Expo__c = expoDate;
      try {
        update session;
        PageReference pr = new PageReference('/LEGOReportList');
        pr.setRedirect(true);
        return pr;
      } catch (Exception e) {
        system.debug(e.getMessage());
      }
    }
    return null;
  }

  public PageReference submit() {
    if (session != null) {
      session.Expo_Report_Status__c = 'Submitted';
      session.Date_of_Expo__c = expoDate;
      try {
        update session;
        PageReference pr = new PageReference('/LEGOReportList');
        pr.setRedirect(true);
        return pr;
      } catch (Exception e) {
        system.debug(e.getMessage());
      }
    }
    return null;
  }

  public PageReference sendBack() {
    if (session != null) {
      session.Expo_Report_Status__c = 'In Progress';
      try {
        update session;
        PageReference pr = new PageReference('/LEGOReportList');
        pr.setRedirect(true);
        return pr;
      } catch (Exception e) {
        system.debug(e.getMessage());
      }
    }
    return null;
  }

  // BEGIN deleteAtt
  public void deleteAtt() {
    if (deleteAttId != null) {
      Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteAttId];
      if (a != null) {
        AttachmentClass ac = new AttachmentClass();
        ac.deleteAttachment(a);
      }
    }
    getAttList();
  }
  // END deleteAtt

  // BEGIN popups
  public void attPopup() {
    displayAttPopup = true;
  }

  public void closeAttPopup() {
    displayAttPopup = false;
    getAttList();
  }
  // END popups
}