force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Local_Organization__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>National_Organization__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Email__c</fullName>
    <label>Primary Approver Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Email_text__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Email_text__c</fullName>
    <formula>Primary_Approver__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Email text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula
  >Primary_Approver__r.FirstName + &apos; &apos; + Primary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>Account__r.National_Organization_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Primary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Account__r.Primary_Approver__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reporting_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_End_Date__c</fullName>
    <label>Reporting Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Start_Date__c</fullName>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Grant__r.FirstPic_National_Org_Code__c != null, Grant__r.FirstPic_National_Org_Code__c,  
IF(Organization__r.FirstPic_National_Org_Code__c != null, Organization__r.FirstPic_National_Org_Code__c, 
Organization__r.FirstPic_Org_Code__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <formula>TEXT(Grant__r.Grant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>CASESAFEID(Organization__r.Local_Organization__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/National_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Organization_Id__c</fullName>
    <formula>CASESAFEID(Grant__r.Account__r.National_Organization__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DCTAT Reports</relationshipLabel>
    <relationshipName>DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <formula>IF(Organization__c != null,
CASESAFEID(Organization__r.Id),
CASESAFEID(Grant__r.Account__r.Id)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <formula>IF(Organization__c != null,
Organization__r.Name,
Grant__r.Account__r.Name
)</formula>
    <label>Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Primary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Organization__r.Primary_Approver__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula>Grant__r.Account__r.Primary_Approver_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Report_Status__c</fullName>
    <label>Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DCTATReportClass.cls
public without sharing class DCTATReportClass {
  public String soql { get; set; }
  public String getSOQL() {
    String fields = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Grantee_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      fields += fieldName + ', ';
    }
    fields = fields.removeEnd(', ');

    soql = 'SELECT ' + fields + ' FROM Grantee_Report__c';
    return soql;
  }

  public List<Grantee_Report__c> getReportList() {
    soql = getSOQL();
    soql += ' ORDER BY Report_Status__c, Submitted_Date__c';
    List<Grantee_Report__c> reports = database.query(soql);
    return reports;
  }

  public List<Grantee_Report__c> getRelatedReportList(
    Id acctId,
    String orgName,
    String status,
    String sortBy,
    String soqlAND
  ) {
    String soql = 'SELECT Name, Local_Organization_Name__c, Organization_Name__c, Grant__r.Id, Grant_Name__c, Grant_Type__c, Primary_Approver_Name__c, Primary_Approver_Id__c, Report_Status__c, Submitted_Date__c, Quarter__c, Year__c FROM Grantee_Report__c';
    soql +=
      ' WHERE (National_Organization_Id__c = \'' +
      acctId +
      '\' OR Local_Organization_Id__c = \'' +
      acctId +
      '\' OR Organization_Id__c = \'' +
      acctId +
      '\')';
    if (orgName != '' && orgName != null)
      soql +=
        ' AND (Organization_Name__c LIKE \'%' +
        orgName +
        '%\' or Local_Organization_Name__c LIKE \'%' +
        orgName +
        '%\')';
    if (status != '' && status != null)
      soql += ' AND Report_Status__c = \'' + status + '\'';
    if (soqlAND != '' && soqlAND != null)
      soql += soqlAND;
    if (sortBy != '' && sortBy != null)
      soql += ' ORDER BY ' + sortBy;
    system.debug('DCTATReportClass getRelatedReportList soql = ' + soql);
    List<Grantee_Report__c> reports = database.query(soql);
    return reports;
  }

  public Grantee_Report__c getReport(Id reportId) {
    soql = getSOQL();
    if (reportId != null)
      soql += ' WHERE Id = \'' + reportId + '\'';

    Grantee_Report__c report = new Grantee_Report__c();
    Grantee_Report__c[] reports = database.query(soql);
    if (reports.size() > 0)
      report = reports[0];
    return report;
  }

  public void upsertReport(Grantee_Report__c report) {
    try {
      upsert report;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void createReports(String fpNatCode, String quarter) {
    if (fpNatCode == null)
      fpNatCode = 'Ripken';
    Date dt = date.today();
    List<Grantee_Report__c> r_list = new List<Grantee_Report__c>();
    Integer count = 0;
    for (Grant__c g : [
      SELECT Id, Account__r.Id, Account__r.Primary_Approver_Email_text__c
      FROM Grant__c
      WHERE
        RecordType.Name = 'Sub-Grant'
        AND FirstPic_National_Org_Code__c = :fpNatCode
        AND Year__c = :string.valueOf(dt.year())
    ]) {
      count++;
      Grantee_Report__c r = new Grantee_Report__c(
        Year__c = string.valueOf(dt.year()),
        Grant__c = g.Id,
        Organization__c = g.Account__c,
        Report_Status__c = 'Not Started',
        Quarter__c = quarter,
        Primary_Approver_Email__c = g.Account__r.Primary_Approver_Email_text__c
      );
      r_list.add(r);
    }
    system.debug('count = ' + count);
    system.debug('r_list = ' + r_list);
    insert r_list;
  }

  public void createReportsForSites(
    String orgCode,
    String year,
    String quarter
  ) {
    Date dt = date.today();
    if (orgCode == null)
      orgCode = 'STEM';
    if (year == null)
      year = string.valueOf(dt.year());
    if (quarter == null)
      quarter = 'Q2';

    List<Grantee_Report__c> items = new List<Grantee_Report__c>();
    List<Grant__c> grants = [
      SELECT Id, Account__c
      FROM Grant__c
      WHERE
        FirstPic_National_Org_Code__c = :orgCode
        AND Grant_Status__c != 'Closed'
        AND National_Grant__r.Reporting_Period_Start_Date__c <= :dt
        AND National_Grant__r.Reporting_Period_End_Date__c >= :dt
    ];
    List<Account> accts = [
      SELECT Id, Local_Organization_Id__c, Primary_Approver_Email_text__c
      FROM Account
      WHERE
        FirstPic_National_Org_Code__c = :orgCode
        AND RecordType.Name = 'Site'
        AND Is_Active__c = TRUE
    ];
    Integer count = 0;
    for (Account a : accts) {
      for (Grant__c g : grants) {
        if (a.Local_Organization_Id__c == g.Account__c) {
          count++;
          Grantee_Report__c r = new Grantee_Report__c(
            Grant__c = g.Id,
            Organization__c = a.Id,
            Report_Status__c = 'Not Started',
            Year__c = year,
            Quarter__c = quarter,
            Primary_Approver_Email__c = a.Primary_Approver_Email_text__c
          );
          items.add(r);
        }
      }
    }
    system.debug(count);
    system.debug(items);
    insert items;
  }
}