force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Local_Organization__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Account__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Site__r.FirstPic_National_Org_Code__c != null, Site__r.FirstPic_National_Org_Code__c, Site__r.FirstPic_Org_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017 - 2018</fullName>
            </value>
            <value>
                <fullName>2018 - 2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019 - 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Month_Int__c.field-meta.xml
<CustomField>
    <fullName>Month_Int__c</fullName>
    <formula>IF(ISPICKVAL(Month__c, &apos;January&apos;), 1,
 IF(ISPICKVAL(Month__c, &apos;February&apos;), 2,
  IF(ISPICKVAL(Month__c, &apos;March&apos;), 3,
   IF(ISPICKVAL(Month__c, &apos;April&apos;), 4,
    IF(ISPICKVAL(Month__c, &apos;May&apos;), 5,
     IF(ISPICKVAL(Month__c, &apos;June&apos;), 6,
      IF(ISPICKVAL(Month__c, &apos;July&apos;), 7,
       IF(ISPICKVAL(Month__c, &apos;August&apos;), 8,
        IF(ISPICKVAL(Month__c, &apos;September&apos;), 9,
         IF(ISPICKVAL(Month__c, &apos;October&apos;), 10,
          IF(ISPICKVAL(Month__c, &apos;November&apos;), 11,
           IF(ISPICKVAL(Month__c, &apos;December&apos;), 12, 0
))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Int</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Id__c</fullName>
    <formula>Site__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramReportClass.cls
public without sharing class ProgramReportClass {
  public ProgramReportClass() {
  }
  public String soql { get; set; }

  public void getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Program_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr += 'RecordType.Name, Site__r.Name, Grant__r.Name';

    soql = 'SELECT ' + expr + ' FROM Program_Report__c';
  }

  public Program_Report__c getCurrentReport(Id acctId) {
    Date dt = date.today();
    Program_Report__c[] reports = [
      SELECT Id
      FROM Program_Report__c
      WHERE Site__c = :acctId AND Month_Int__c = :dt.month()
    ];
    if (reports.size() > 0) {
      return reports[0];
    }
    return null;
  }

  public Program_Report__c getReport(Id reportId) {
    getSoql();
    Program_Report__c report = new Program_Report__c();

    if (reportId != null)
      soql += ' WHERE Id = \'' + reportId + '\'';

    Program_Report__c[] reports = Database.query(soql);
    if (reports.size() == 1) {
      report = reports[0];
    }
    return report;
  }

  public Program_Report__c getYouthDataReport(
    Id reportId,
    Id siteId,
    Id grantId,
    String year
  ) {
    getSoql();
    //soql = 'SELECT Name, Status__c, Site__c, Site_Id__c, Site_Name__c, Grant__c, Grant__r.Name, Start_Date__c, End_Date__c, Grant_Year__c';
    //soql += ' FROM Program_Report__c WHERE RecordType.Name = \'Youth Data\'';
    soql += ' WHERE RecordType.Name = \'Youth Data\'';
    if (reportId != null) {
      soql += ' AND Id = \'' + reportId + '\'';
    } else if (siteId != null && grantId != null && year != null) {
      soql +=
        ' AND Site__c = \'' +
        siteId +
        '\' AND Grant__c = \'' +
        grantId +
        '\' AND Grant_Year__c = \'' +
        year +
        '\'';
    }
    system.debug('Program Report soql = ' + soql);

    Program_Report__c report = new Program_Report__c();
    Program_Report__c[] reports = Database.query(soql);
    if (reports.size() == 1) {
      report = reports[0];
    }
    return report;
  }

  public List<Program_Report__c> getRelatedReportList(
    Id acctId,
    String userAcctType,
    Id localOrgId,
    Id siteId,
    Id grantId,
    String soqlAND
  ) {
    getSOQL();
    if (siteId != null) {
      soql += ' WHERE Site__c = \'' + siteId + '\'';
    } else if (localOrgId != null) {
      soql += ' WHERE Site__r.Local_Organization__c = \'' + localOrgId + '\'';
    } else if (userAcctType == 'National Organization') {
      soql += ' WHERE Site__r.National_Organization__c = \'' + acctId + '\'';
    } else if (userAcctType == 'Local Organization') {
      soql +=
        ' WHERE (Site__c = \'' +
        acctId +
        '\' OR Site__r.Local_Organization__c = \'' +
        acctId +
        '\')';
    } else {
      soql += ' WHERE Site__c = \'' + acctId + '\'';
    }
    if (grantId != null)
      soql +=
        ' AND (Grant__r.Id = \'' +
        grantId +
        '\' OR Grant__r.National_Grant__r.Id = \'' +
        grantId +
        '\')';
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    system.debug('Program Report soql = ' + soql);

    List<Program_Report__c> reports = Database.query(soql);
    return reports;
  }

  public void upsertReport(Program_Report__c report) {
    try {
      upsert report;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  public void createYouthDataReport(Id siteId, Id grantId, String year) {
    Program_Report__c pr = new Program_Report__c(
      Name = year + ' Youth Data Report',
      Status__c = 'Not Started',
      Site__c = siteId,
      Grant__c = grantId,
      RecordTypeID = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
        .get('Youth Data')
        .getRecordTypeId(),
      Grant_Year__c = year
    );
    system.debug(pr);
    insert pr;
  }

  public void createYouthDataReports(String naOrgName) {
    List<Program_Report__c> prs = new List<Program_Report__c>();
    List<Grant__c> grants = [
      SELECT Id, Account__c
      FROM Grant__c
      WHERE
        FirstPic_National_Org_Code__c = :naOrgName
        AND Grant_Status__c != 'Closed'
    ];
    List<Account> accts = [
      SELECT Id, Local_Organization_Id__c
      FROM Account
      WHERE FirstPic_National_Org_Code__c = :naOrgName
    ];
    Date sd = Date.newInstance(2018, 1, 1);
    Date ed = Date.newInstance(2018, 12, 31);
    Id rid = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
      .get('Youth Data')
      .getRecordTypeId();
    for (Account a : accts) {
      for (Grant__c g : grants) {
        if (a.Local_Organization_Id__c == g.Account__c) {
          Program_Report__c pr = new Program_Report__c(
            Name = 'Youth Data Report Y1',
            Status__c = 'Not Started',
            Site__c = a.Id,
            Grant__c = g.Id,
            Start_Date__c = sd,
            End_Date__c = ed,
            RecordTypeID = rid,
            Grant_Year__c = '2017 - 2018'
          );
          prs.add(pr);
        }
      }
    }
    system.debug(prs);
    insert prs;
  }
}