force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Local_Organization__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>Site__r.FirstPic_National_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>CASESAFEID( Site__r.Local_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Local_Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Name__c</fullName>
    <formula>Site__r.Local_Organization__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <label>Reporting Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017-2018 Q1</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q2</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q3</fullName>
            </value>
            <value>
                <fullName>2017-2018 Q4</fullName>
            </value>
            <value>
                <fullName>2017 Q4</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q1</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q2</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q3</fullName>
            </value>
            <value>
                <fullName>2018-2019 Q4</fullName>
            </value>
            <value>
                <fullName>2018 Q1</fullName>
            </value>
            <value>
                <fullName>2018 Q2</fullName>
            </value>
            <value>
                <fullName>2018 Q3</fullName>
            </value>
            <value>
                <fullName>2018 Q4</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q1</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q2</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q3</fullName>
            </value>
            <value>
                <fullName>2019-2020 Q4</fullName>
            </value>
            <value>
                <fullName>2019 Q1</fullName>
            </value>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017-2018</fullName>
            </value>
            <value>
                <fullName>2018-2019</fullName>
            </value>
            <value>
                <fullName>2019-2020</fullName>
            </value>
            <value>
                <fullName>2020-2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SessionReportClass.cls
public without sharing class SessionReportClass {
  public String soql { get; set; }

  public void getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Session_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM Session_Report__c';
  }

  public SessionReportClass() {
    getSoql();
  }

  public Id getLatestReportId(Id siteId) {
    Session_Report__c[] reports = [
      SELECT Id
      FROM Session_Report__c
      WHERE Site__c = :siteId
      ORDER BY LastModifiedDate DESC
    ];
    if (reports.size() > 0) {
      Id reportId = reports[0].Id;
      return reportId;
    }
    return null;
  }

  public Session_Report__c getReport(Id reportId, Id sessionId, Id siteId) {
    getSoql();
    Session_Report__c report = new Session_Report__c();

    if (reportId != null) {
      soql += ' WHERE Id = \'' + reportId + '\'';
    }
    if (sessionId != null) {
      soql += ' WHERE Session__c = \'' + sessionId + '\'';
      if (siteId != null) {
        soql += ' AND Site__c = \'' + siteId + '\'';
      }
    }
    system.debug('>>> report soql = ' + soql);

    Session_Report__c[] reports = Database.query(soql);
    if (reports.size() == 1) {
      report = reports[0];
    }
    return report;
  }

  public List<Session_Report__c> getReportList() {
    getSoql();
    List<Session_Report__c> report_list = new List<Session_Report__c>();
    report_list = Database.query(soql);
    return report_list;
  }

  public List<Session_Report__c> getRelatedReportList(
    Id acctId,
    Id siteId,
    String userAcctType,
    String siteName,
    String reportName,
    String status,
    String sortBy,
    String soqlAND
  ) {
    String soql = 'SELECT Name, Local_Organization_Name__c, Site__r.Id, Site__r.Name, Site_Id__c, Site_Name__c, Status__c, Submitted_Date__c, Reporting_Period__c, Year__c, LastModifiedDate FROM Session_Report__c';
    soql += ' WHERE Name != null';
    if (siteId == null) {
      if (userAcctType == 'National Organization') {
        soql += ' AND Site__r.National_Organization__c = \'' + acctId + '\'';
      }
      if (userAcctType == 'Local Organization') {
        soql +=
          ' AND (Site__c = \'' +
          acctId +
          '\' OR Site__r.Local_Organization__c = \'' +
          acctId +
          '\')';
      }
    } else {
      soql += ' AND Site__c = \'' + siteId + '\'';
    }
    if (siteName != '' && siteName != null)
      soql +=
        ' AND (Site__r.Name LIKE \'%' +
        siteName +
        '%\' OR Local_Organization_Name__c LIKE \'%' +
        siteName +
        '%\')';
    if (reportName != '' && reportName != null)
      soql += ' AND Name LIKE \'%' + reportName + '%\'';
    if (status != '' && status != null && status != 'All Reports')
      soql += ' AND Status__c = \'' + status + '\'';
    if (soqlAND != '' && soqlAND != null)
      soql += soqlAND;
    if (sortBy != '' && sortBy != null)
      soql += ' ORDER BY ' + sortBy;
    system.debug('SessionReportClass getRelatedReportList soql = ' + soql);

    List<Session_Report__c> report_list = new List<Session_Report__c>();
    report_list = Database.query(soql);
    return report_list;
  }

  public void upsertReport(Session_Report__c report) {
    try {
      upsert report;
      system.debug('>>> report = ' + report);
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public void createProgressReports(String natOrg, String reportingPeriod) {
    if (natOrg == null)
      natOrg = 'TRAIL';
    List<Session_Report__c> reports = new List<Session_Report__c>();
    for (Account a : [
      SELECT Id, Name, Local_Organization_Id__c
      FROM Account
      WHERE FirstPic_National_Org_Code__c = :natOrg AND RecordType.Name = 'Site'
    ]) {
      String name = a.Name;
      List<String> elems = name.split(' ');
      name = '';
      for (String x : elems) {
        name += x.substring(0, 1).toUpperCase();
      }
      name = name.replace('&', '');
      name = name.replace('(', '');
      name = name.replace('-', '');

      Session_Report__c report = new Session_Report__c(
        Name = name + ' ' + reportingPeriod + ' Progress Report',
        Status__c = 'Not Started',
        Site__c = a.Id,
        Reporting_Period__c = reportingPeriod,
        RecordTypeID = Schema.SObjectType.Session_Report__c.getRecordTypeInfosByName()
          .get('Progress Report')
          .getRecordTypeId()
      );
      reports.add(report);
    }
    system.debug(reports);
    insert reports;
  }

  public void createSessionReports(String natOrg, String sessionId) {
    List<Session_Report__c> items = new List<Session_Report__c>();
    Session__c[] sessions = [
      SELECT Name, Site__r.Name
      FROM Session__c
      WHERE Id = :sessionId
    ];
    for (Account a : [
      SELECT Id, Name
      FROM Account
      WHERE
        FirstPic_National_Org_Code__c = :natOrg
        AND RecordType.Name = 'Site'
        AND Is_Active__c = TRUE
    ]) {
      Session_Report__c i = new Session_Report__c(
        Name = a.Name.left(30) +
          ' - ' +
          sessions[0].Name.left(30) +
          ' Program Report',
        Session__c = sessionId,
        Site__c = a.Id,
        Status__c = 'Not Started',
        RecordTypeID = Schema.SObjectType.Session_Report__c.getRecordTypeInfosByName()
          .get('Session Report')
          .getRecordTypeId()
      );
      items.add(i);
    }
    system.debug(items);
    insert items;
  }
}