force-app/main/default/objects/Account/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula>National_Organization__r.FirstPic_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Attachment_Status__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Status__c</fullName>
    <label>Attachment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Hide_Standards__c.field-meta.xml
<CustomField>
    <fullName>Hide_Standards__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Standards</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Reviewed__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Reviewed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/FirstPic_National_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>FirstPic_National_Org_Code__c</fullName>
    <formula
  >IF(Organization__c != null, Organization__r.FirstPic_National_Org_Code__c,  
IF(Grant__c != null, Grant__r.FirstPic_National_Org_Code__c, 
IF(Reimbursement__c != null, Reimbursement__r.FirstPic_National_Org_Code__c,
IF(Session_Report__c != null, Session_Report__r.FirstPic_National_Org_Code__c,
&apos;&apos;))))</formula>
    <label>FirstPic National Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <label>Group Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
                <isActive>false</isActive>
                <label>Resubmitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>IF(Assessment__c != null, TEXT(Assessment__r.Year__c), 
IF(Grant__c != null, Grant__r.Year__c, 
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssessmentClass.cls
public without sharing class AssessmentClass {
  public String soql { get; set; }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Assessment__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM Assessment__c';
    return soql;
  }

  public Assessment__c getAssessment(Id aId) {
    getSOQL();
    Assessment__c assessment = new Assessment__c();
    if (aId != null) {
      soql += ' WHERE Id = \'' + aId + '\'';
      Assessment__c[] assessments = Database.query(soql);
      if (assessments.size() > 0) {
        assessment = assessments[0];
      }
    }
    return assessment;
  }

  public void upsertAssessment(Assessment__c assess) {
    try {
      upsert assess;
      System.Debug('>>>> Assessment upsert successful. assess = ' + assess);
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  // BEGIN getAttStatus
  public void getAttStatus(Set<Id> saIds) {
    List<Assessment__c> sa_list = new List<Assessment__c>();
    Map<Id, String> sa_map = new Map<Id, String>();
    Set<String> doc_list = new Set<String>();
    doc_list.add('Strategic and Annual Plan');
    //doc_list.add('Fund Development Plan');
    //doc_list.add('Separation of Duties for Fiscal Control');
    doc_list.add('Board Development Plan');
    //doc_list.add('Written Succession Plan');
    //doc_list.add('Previous Audit');
    //doc_list.add('AIM Fee Form');
    doc_list.add('Audit');
    doc_list.add('Affiliation Fee Form');
    doc_list.add('Income Statement');
    doc_list.add('Network Growth Goals');
    doc_list.add('Network Growth Goals & Innovative Programs');
    doc_list.add('Organizational Chart');
    doc_list.add('Program Manual');
    doc_list.add('Proof of Insurance');
    doc_list.add('Supporting Documentation for Affiliation Fee Form');
    doc_list.add('Technology Licenses Form');
    doc_list.add('Verification Letter');

    for (Document__c d : [
      SELECT Name, Status__c, Assessment__c
      FROM Document__c
      WHERE
        Assessment__c IN :saIds
        AND Status__c = 'Approved'
        AND Required__c = TRUE
    ]) {
      if (doc_list.contains(d.Name))
        sa_map.put(d.Assessment__c, 'Approved');
    }
    for (Document__c d : [
      SELECT Name, Status__c, Assessment__c
      FROM Document__c
      WHERE
        Assessment__c IN :saIds
        AND Status__c = 'Submitted'
        AND Required__c = TRUE
    ]) {
      if (doc_list.contains(d.Name))
        sa_map.put(d.Assessment__c, 'Submitted');
    }
    for (Document__c d : [
      SELECT Name, Status__c, Assessment__c
      FROM Document__c
      WHERE
        Assessment__c IN :saIds
        AND Status__c = 'Incomplete'
        AND Required__c = TRUE
    ]) {
      if (doc_list.contains(d.Name))
        sa_map.put(d.Assessment__c, 'Incomplete');
    }
    for (Document__c d : [
      SELECT Name, Status__c, Assessment__c
      FROM Document__c
      WHERE Assessment__c IN :saIds AND Status__c = 'Sent Back'
    ]) {
      if (doc_list.contains(d.Name))
        sa_map.put(d.Assessment__c, 'Sent Back');
    }

    for (Assessment__c sa : [
      SELECT Id, Attachment_Status__c
      FROM Assessment__c
      WHERE Id IN :sa_map.keyset()
    ]) {
      sa.Attachment_Status__c = sa_map.get(sa.Id);
      if (sa_map.get(sa.Id) == 'Sent Back')
        sa.Reviewed__c = 'No';
      sa_list.add(sa);
    }
    try {
      upsert sa_list;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }
  // END getAttStatus

  // BEGIN createAssessments
  public void createAssessments(Integer year, Boolean hideStandards) {
    List<Assessment__c> sas = new List<Assessment__c>();
    for (Account a : [
      SELECT Id, Name
      FROM Account
      WHERE FirstPic_National_Org_Code__c = 'BBBSA'
    ]) {
      Assessment__c sa = new Assessment__c(
        Organization__c = a.Id,
        Year__c = year,
        Hide_Standards__c = hideStandards
      );
      sas.add(sa);
    }
    insert sas;

    List<Document__c> doc_list = new List<Document__c>();
    Set<String> names = new Set<String>();
    Set<String> addNames = new Set<String>();
    names.add('Audit');
    addNames.add('Affiliation Fee Form');
    addNames.add('Income Statement');
    addNames.add('Network Growth Goals');
    addNames.add('Organizational Chart');
    addNames.add('Program Manual');
    names.add('Proof of Insurance');
    addNames.add('Supporting Documentation for Affiliation Fee Form');
    addNames.add('Technology Licenses Form');
    addNames.add('Verification Letter');

    for (Assessment__c sa : [
      SELECT Id, Organization__c
      FROM Assessment__c
      WHERE Year__c = :year
    ]) {
      for (String n : addNames) {
        Document__c d = new Document__c(
          Assessment__c = sa.Id,
          Organization__c = sa.Organization__c,
          Status__c = 'Requested',
          Name = n,
          Group_Id__c = 'Additional Documents',
          Required__c = true
        );
        doc_list.add(d);
      }
      for (String n : names) {
        Document__c d = new Document__c(
          Assessment__c = sa.Id,
          Organization__c = sa.Organization__c,
          Status__c = 'Requested',
          Name = n,
          Required__c = true
        );
        doc_list.add(d);
      }
    }
    system.debug(doc_list);
    insert doc_list;
  }
  // END createAssessments
}