force-app/main/default/objects/Account/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <label>Hold Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/BBBS_Grant_ID__c.field-meta.xml
<CustomField>
    <fullName>BBBS_Grant_ID__c</fullName>
    <label>BBBS Grant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Requested Amount</inlineHelpText>
    <label>Total Requested Amount</label>
    <summarizedField>Budget_Item__c.Total_Requested_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/Drawdown_Status__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Status__c</fullName>
    <label>Drawdown Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Report</fullName>
            </value>
            <value>
                <fullName>Drawndown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Drawndown_Date__c.field-meta.xml
<CustomField>
    <fullName>Drawndown_Date__c</fullName>
    <label>Drawndown Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/EFT__c.field-meta.xml
<CustomField>
    <fullName>EFT__c</fullName>
    <label>EFT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <formula>TEXT(Grant__r.Account__r.Hold_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hold Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Modification_History__c.field-meta.xml
<CustomField>
    <fullName>Modification_History__c</fullName>
    <label>Modification History</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Request_Month__c.field-meta.xml
<CustomField>
    <fullName>Request_Month__c</fullName>
    <formula
  >CASE(MONTH(End_Date__c), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;,  4, &quot;April&quot;,  5, &quot;May&quot;,  6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;None&quot;) + &quot;, &quot; +  TEXT(Year(End_Date__c))</formula>
    <label>Request Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <formula
  >Requested_Amount__c + IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), IF( Grant__r.National_Grant_Type__c == &apos;OVC&apos;, Requested_Indirect_Costs__c, Indirect_Rate_Amount__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Requested_Amount__c + IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), Indirect_Rate_Amount__c, 0)</inlineHelpText>
    <label>Requested + Indirect Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DrawdownReportCtrl.cls
public with sharing class DrawdownReportCtrl {
  // DEPRECATED. Used only for BBBSA.
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String approverLevel { get; set; }

  public ReimbursementClass requestClass = new ReimbursementClass();

  public String reportId { get; set; }
  public String pendingReportId { get; set; }
  public Id GrantID { get; set; }
  public Grant__c grant { get; set; }

  public List<Reimbursement_Request__c> approved_list { get; set; }
  public List<Reimbursement_Request__c> inPending_list { get; set; }
  public List<Reimbursement_Request__c> inReport_list { get; set; }
  public List<Reimbursement_Request__c> completed_list { get; set; }
  //public Map<String, Date> report_map { get; set; }
  public List<innerClass> report_list { get; set; }
  Set<String> rdates { get; set; }
  public Set<Id> rIds { get; set; }
  public Boolean selectAllApproved { get; set; }
  public Boolean selectAllInReport { get; set; }
  public Decimal reportTotal { get; set; }
  public Decimal drawdownTotal { get; set; }

  public Date startDate { get; set; }
  public Date endDate { get; set; }

  public Boolean displaySuccess { get; set; }
  public String errorMessage { get; set; }

  public DrawdownReportCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    approverLevel = userClass.approverLevel;

    reportId = '';
    pendingReportId = '';
    reportId = ApexPages.currentPage().getParameters().get('reportId');
    if (reportId != null)
      pendingReportId = reportId;
    GrantID = ApexPages.currentPage().getParameters().get('grantId');

    approved_list = new List<Reimbursement_Request__c>();
    inPending_list = new List<Reimbursement_Request__c>();
    inReport_list = new List<Reimbursement_Request__c>();
    completed_list = new List<Reimbursement_Request__c>();
    //report_map = new Map<String, Date>();
    report_list = new List<innerClass>();
    rIds = new Set<Id>();
    selectAllApproved = true;
    selectAllInReport = true;
    reportTotal = 0;
    drawdownTotal = 0;
    displaySuccess = false;

    //endDate = date.today();
    //startDate = endDate.addDays(-30);

    if (grantId != null) {
      Grant__c[] grants = [
        SELECT Id, Name, BBBS_Grant_ID__c
        FROM Grant__c
        WHERE Id = :grantId
      ];
      if (grants.size() > 0) {
        grant = grants[0];
      }
    } else {
      for (Grant__c g : [
        SELECT Id, Account__r.ID, Name, BBBS_Grant_ID__c
        FROM Grant__c
      ]) {
        if (userAcct != null && g.Account__r.ID == userAcct.Id) {
          grant = g;
          grantId = g.Id;
        }
      }
    }
  }

  public void getLists() {
    approved_list.clear();
    inPending_list.clear();
    inReport_list.clear();
    completed_list.clear();
    //report_map.clear();
    report_list.clear();
    reportTotal = 0;
    drawdownTotal = 0;
    displaySuccess = false;

    Set<String> reportIdSet = new Set<String>();
    for (Reimbursement_Request__c r : [
      SELECT
        Id,
        Name,
        Grant__r.Name,
        Grant__r.National_Grant__c,
        Status__c,
        Selected__c,
        Drawdown_Status__c,
        Paid_Date__c,
        Total_Requested_Amount__c,
        Report_Id__c,
        EFT__c,
        Drawndown_Date__c,
        Request_Month__c,
        Modification_History__c,
        Hold_Status__c
      FROM Reimbursement_Request__c
      WHERE Grant__r.National_Grant__c = :grantId
    ]) {
      if (
        (reportId != null && reportId != '') ||
        (pendingReportId != null &&
        pendingReportId != '')
      ) {
        string rId = r.Report_Id__c;
        system.debug('rId = ' + rId);
        system.debug('reportId = ' + reportId);
        system.debug('pendingReportId = ' + pendingReportId);
        if (
          rId != null &&
          (reportId != null && reportId != '' &&
          rId.toLowerCase().contains(reportId.toLowerCase()) ||
          (pendingReportId != null &&
          pendingReportId != '' &&
          rId.toLowerCase().contains(pendingReportId.toLowerCase())))
        ) {
          if (r.Drawdown_Status__c != 'Drawndown')
            inPending_list.add(r);
          else {
            if (r.EFT__c == null) {
              completed_list.add(r);
              drawdownTotal += r.Total_Requested_Amount__c;
            } else if (
              (r.Paid_Date__c >= startDate &&
              endDate == null) ||
              (r.Paid_Date__c <= endDate &&
              startDate == null) ||
              (r.Paid_Date__c >= startDate &&
              r.Paid_Date__c <= endDate)
            ) {
              completed_list.add(r);
              drawdownTotal += r.Total_Requested_Amount__c;
            }
          }
          inReport_list.add(r);
          reportTotal += r.Total_Requested_Amount__c;
        }
      } else {
        if (r.Drawdown_Status__c == 'In Report') {
          inPending_list.add(r);
          reportTotal += r.Total_Requested_Amount__c;
        } else if (r.Drawdown_Status__c == 'Drawndown') {
          if (r.EFT__c == null) {
            completed_list.add(r);
            drawdownTotal += r.Total_Requested_Amount__c;
          } else if (
            (r.Paid_Date__c >= startDate &&
            endDate == null) ||
            (r.Paid_Date__c <= endDate &&
            startDate == null) ||
            (r.Paid_Date__c >= startDate &&
            r.Paid_Date__c <= endDate)
          ) {
            completed_list.add(r);
            drawdownTotal += r.Total_Requested_Amount__c;
          }
        }
      }
      if (r.Status__c == 'Approved' && r.Hold_Status__c != 'Hold') {
        r.Selected__c = true;
        if (r.Drawdown_Status__c == '' || r.Drawdown_Status__c == null)
          approved_list.add(r);
      }
      if (
        !reportIdSet.contains(r.Report_Id__c) &&
        r.Drawdown_Status__c == 'Drawndown' &&
        r.Drawndown_Date__c != null
      ) {
        if (
          (startDate == null &&
          endDate == null) ||
          (r.Drawndown_Date__c >= startDate &&
          endDate == null) ||
          (r.Drawndown_Date__c <= endDate &&
          startDate == null) ||
          (r.Drawndown_Date__c >= startDate &&
          r.Drawndown_Date__c <= endDate)
        ) {
          //report_map.put(r.Report_Id__c, r.Drawndown_Date__c);
          innerClass ic = new innerClass(r.Report_Id__c, r.Drawndown_Date__c);
          report_list.add(ic);
          reportIdSet.add(r.Report_Id__c);
        }
      }
    }
  }

  public void selectAllApproved() {
    if (selectAllApproved)
      selectAllApproved = false;
    else
      selectAllApproved = true;
    for (Reimbursement_Request__c r : approved_list)
      r.Selected__c = selectAllApproved;
  }

  public void selectAllInReport() {
    if (selectAllInReport)
      selectAllInReport = false;
    else
      selectAllInReport = true;
    for (Reimbursement_Request__c r : inPending_list)
      r.Selected__c = selectAllInReport;
  }

  public void createReport() {
    List<Reimbursement_Request__c> selected_list = new List<Reimbursement_Request__c>();
    RandomString randomString = new RandomString();
    if (grant.BBBS_Grant_ID__c != null)
      reportId = grant.BBBS_Grant_ID__c;
    else
      reportId = randomString.randStr;

    DateTime d = Datetime.now();
    String dateStr = d.format('yyyy-MM-dd_h:mm');
    reportId += '_' + dateStr;

    for (Reimbursement_Request__c r : approved_list) {
      system.debug('approved_list r = ' + r);
      if (r.Selected__c != null && r.Selected__c) {
        r.Drawdown_Status__c = 'In Report';
        r.Report_ID__c = reportId;
        rIds.add(r.Id);
      }
    }
    try {
      requestClass.upsertRequestList(approved_list);
      getLists();
    } catch (Exception e) {
      system.debug(e);
    }
  }

  public void updateReport() {
    for (Reimbursement_Request__c r : inPending_list) {
      if (!r.Selected__c) {
        r.Report_Id__c = null;
        r.Drawdown_Status__c = null;
      }
    }
    try {
      requestClass.upsertRequestList(inPending_list);
    } catch (Exception e) {
      system.debug(e);
    }
    reportId = null;
    getLists();
  }

  public void completeDrawdown() {
    errorMessage = '';
    Integer size = 0;
    for (Reimbursement_Request__c r : inPending_list)
      if (r.Selected__c)
        size++;
    if (size == 0)
      errorMessage = 'No Requests in Pending Drawdown Report';
    else {
      for (Reimbursement_Request__c r : inPending_list) {
        if (r.Selected__c) {
          r.Drawdown_Status__c = 'Drawndown';
          r.Drawndown_Date__c = Date.today();
          size++;
        } else {
          r.Report_Id__c = null;
          r.Drawdown_Status__c = null;
        }
      }
      try {
        requestClass.upsertRequestList(inPending_list);
      } catch (Exception e) {
        system.debug(e);
      }
      reportId = null;
      getLists();
    }
  }

  public void processEFT() {
    Date dt = date.today();
    String fdt = dt.format();

    for (Reimbursement_Request__c r : completed_list) {
      if (r.EFT__c != null) {
        if (r.Status__c != 'Paid') {
          if (r.Paid_Date__c == null)
            r.Paid_Date__c = date.today();
          r.Status__c = 'Paid';
        }
        String mh =
          fdt +
          ': Paid by ' +
          currentUser.Contact.Name +
          ' (' +
          currentUser.Id +
          ') - EFT: ' +
          r.EFT__c;
        if (r.Modification_History__c == null)
          r.Modification_History__c = '';
        r.Modification_History__c += ' \r\n' + mh;
      }
    }
    try {
      requestClass.upsertRequestList(completed_list);
      getLists();
      displaySuccess = true;
    } catch (Exception e) {
      system.debug(e);
      errorMessage = e.getMessage();
    }
  }

  public void saveAttach() {
    Attachment a = new Attachment();
    a.ParentId = grant.ID;
    a.Name = 'Drawdown Report ' + reportId;
    if (System.Test.IsRunningTest())
      a.Body = Blob.valueOf('TEST');
    else
      a.Body = ApexPages.currentPage().getcontentAsPdf();
    a.ContentType = 'application/pdf';
    try {
      insert a;
      System.Debug('>>>> attachment insert successful. a = ' + a);
    } catch (Exception e) {
      ApexPages.addmessage(
        new ApexPages.message(ApexPages.severity.ERROR, e.getMessage())
      );
    }
  }

  // BEGIN Inner Class
  public class innerClass {
    public String reportId { get; set; }
    public Date reportDate { get; set; }

    public innerClass(String rId, Date rDate) {
      reportId = rId;
      reportDate = rDate;
    }
  }
  // END inner Class
}