force-app/main/default/objects/Account/fields/Hold_Status__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status__c</fullName>
    <label>Hold Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/National_Grants__c.field-meta.xml
<CustomField>
    <fullName>National_Grants__c</fullName>
    <label>National Grants</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TA_Log__c/TA_Log__c.object-meta.xml
<CustomObject>
    <label>TA Log</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TA_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/TA_By__c.field-meta.xml
<CustomField>
    <fullName>TA_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TA By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HeaderCtrl.cls
public with sharing class HeaderCtrl {
  private UserClass uc = new UserClass();
  private AccountClass ac = new AccountClass();
  private TALogClass lc = new TALogClass();

  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public TA_Log__c log { get; set; }
  public List<SelectOption> orgOptions { get; set; }

  public Boolean hasOVC { get; set; }
  public Boolean displayHoldPopup { get; set; }
  public Boolean displayTALogPopup { get; set; }

  public HeaderCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    System.debug('userAcctType: ' + uc.userAcctType);
    userAcctType = uc.userAcctType;

    Account a = ac.getAccount(userAcct.Id);
    if (a.Hold_Status__c == 'Hold')
      displayHoldPopup = true;

    hasOVC = false;
    if (
      userAcct.National_Grants__c != null &&
      userAcct.National_Grants__c.contains('OVC')
    )
      hasOVC = true;
  }

  public void hideHoldPopup() {
    displayHoldPopup = false;
  }

  public void upsertTALog() {
    lc.upsertTALog(log, currentUser.ContactId);
    displayTALogPopup = false;
  }
  public void showTALogPopup() {
    orgOptions = ac.getOrgOptions(userAcct.Id, userAcctType, uc.userProfile);
    log = new TA_Log__c(
      TA_By__c = currentUser.ContactId,
      Date__c = date.today()
    );
    displayTALogPopup = true;
  }
  public void hideTALogPopup() {
    displayTALogPopup = false;
  }
}