force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Dental_Premium__c.field-meta.xml
<CustomField>
    <fullName>Dental_Premium__c</fullName>
    <label>Dental Premium</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/FICA_Percent__c.field-meta.xml
<CustomField>
    <fullName>FICA_Percent__c</fullName>
    <label>FICA Percent</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Hourly__c.field-meta.xml
<CustomField>
    <fullName>Is_Hourly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hourly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Note__c.field-meta.xml
<CustomField>
    <fullName>Item_Note__c</fullName>
    <label>Item Note</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Life_Premium__c.field-meta.xml
<CustomField>
    <fullName>Life_Premium__c</fullName>
    <label>Life Premium</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Fringe_Benefits__c.field-meta.xml
<CustomField>
    <fullName>New_Fringe_Benefits__c</fullName>
    <label>New Fringe Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>New_Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: New Rate (hourly) * Projected Grant Hours * Number of Weeks;
All Other Personnel: New Wages + New Fringe Benefits
Expenses: New Rate * Quantity</inlineHelpText>
    <label>New Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Rate__c</fullName>
    <label>New Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Wages__c.field-meta.xml
<CustomField>
    <fullName>New_Wages__c</fullName>
    <label>New Wages</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Premium__c.field-meta.xml
<CustomField>
    <fullName>Other_Premium__c</fullName>
    <label>Other Premium</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Grant_Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Projected_Grant_Hours_Per_Week__c</fullName>
    <label>Projected Grant Hours Per Week</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Projected_Hours_Per_Week__c</fullName>
    <label>Projected Hours Per Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Projected_Percent_Time_on_Grant__c.field-meta.xml
<CustomField>
    <fullName>Projected_Percent_Time_on_Grant__c</fullName>
    <label>Projected Percent Time on Grant</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Retirement_Percent__c.field-meta.xml
<CustomField>
    <fullName>Retirement_Percent__c</fullName>
    <label>Retirement Percent</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Short_Term_Premium__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_Premium__c</fullName>
    <label>Short Term Premium</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/SUTA_Percent__c.field-meta.xml
<CustomField>
    <fullName>SUTA_Percent__c</fullName>
    <label>SUTA Percent</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mileage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Vision_Premium__c.field-meta.xml
<CustomField>
    <fullName>Vision_Premium__c</fullName>
    <label>Vision Premium</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Estimated_FTE__c.field-meta.xml
<CustomField>
    <fullName>Estimated_FTE__c</fullName>
    <label>Estimated FTE</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/TestBudgetDetails.cls
@isTest
public class TestBudgetDetails {
  static testMethod void test() {
    Date dt = Date.today();

    Account a = new Account(
      Name = 'Account Name',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get('Local Organization')
        .getRecordTypeId()
    );
    insert a;

    Grant__c ng = new Grant__c(
      Account__c = a.Id,
      Amount__c = 500000,
      End_Date__c = dt.addDays(600),
      Name = 'Grant',
      Start_Date__c = dt.addDays(-200),
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Grant')
        .getRecordTypeId()
    );
    insert ng;

    Grant__c sg = new Grant__c(
      Account__c = a.Id,
      National_Grant__c = ng.Id,
      Amount__c = 500000,
      Name = 'Sub-Grant',
      Grant_Status__c = 'Pending Final Approval',
      Youth_Served__c = 100,
      Youth_Served_with_Grant_Funding__c = 50,
      Estimated_FTE__c = 200,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId()
    );
    insert sg;

    Profile p1 = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact c1 = new Contact(
      lastName = 'Contact',
      firstName = 'Test',
      Email = 'test123@example.com',
      accountId = a.Id
    );
    insert c1;
    User u1 = new User(
      Alias = 'testu',
      Email = 'test123@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p1.Id,
      UserName = 'test1232@example.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;

    system.Test.startTest();
    System.runAs(u1) {
      // BEGIN Test BudgetCtrl
      system.Test.setCurrentPageReference(
        new PageReference('Page.BudgetDetails')
      );
      System.currentPageReference().getParameters().put('grantId', sg.Id);
      BudgetCtrl ctrl1 = new BudgetCtrl();
      ctrl1.getBudgetCtrl();
      ctrl1.init();
      ctrl1.durationWks = 52.14;
      system.assertEquals(ctrl1.statusColor, 'text-warning');

      ctrl1.addLaborItem();
      ctrl1.newLaborItem_list[0].Projected_Hours_Per_Week__c = 20;
      ctrl1.newLaborItem_list[0].Projected_Grant_Hours_Per_Week__c = 10;
      ctrl1.newLaborItem_list[0].New_Rate__c = 10;
      ctrl1.newLaborItem_list[0].Is_Hourly__c = true;

      ctrl1.addLaborItem();
      ctrl1.newLaborItem_list[1].Projected_Hours_Per_Week__c = 20;
      ctrl1.newLaborItem_list[1].Projected_Grant_Hours_Per_Week__c = 10;
      ctrl1.newLaborItem_list[1].New_Rate__c = 10000;
      ctrl1.newLaborItem_list[1].Fica_Percent__c = 1;
      ctrl1.newLaborItem_list[1].SUTA_Percent__c = 1;
      ctrl1.newLaborItem_list[1].Workers_Comp_Percent__c = 1;
      ctrl1.newLaborItem_list[1].Retirement_Percent__c = 1;
      ctrl1.newLaborItem_list[1].Other_Percent__c = 1;
      ctrl1.newLaborItem_list[1].Medical_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Dental_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Vision_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Short_Term_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Long_Term_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Life_Premium__c = 100;
      ctrl1.newLaborItem_list[1].Other_Premium__c = 100;

      ctrl1.updateNewLaborAmounts();
      system.assertEquals(
        50,
        ctrl1.newLaborItem_list[0].Projected_Percent_Time_on_Grant__c
      );
      system.assertEquals(5214, ctrl1.newLaborItem_list[0].New_Wages__c);
      system.assertEquals(5000, ctrl1.newLaborItem_list[1].New_Wages__c);
      system.assertEquals(ctrl1.newLaborItem_list.size(), 2);
      ctrl1.savePersonnel();

      ctrl1.addExpenseItem();
      ctrl1.newExpenseItem_list[0].Is_Active__c = true;
      ctrl1.newExpenseItem_list[0].New_Rate__c = 100;
      ctrl1.newExpenseItem_list[0].Quantity__c = 10;

      ctrl1.addMileageItem();
      ctrl1.newExpenseItem_list[1].Type__c = 'Mileage';
      ctrl1.newExpenseItem_list[1].Mileage_Rate__c = 1.123;
      ctrl1.newExpenseItem_list[1].Quantity__c = 1;

      ctrl1.updateNewExpenseAmounts();
      system.assertEquals(
        1000,
        ctrl1.newExpenseItem_list[0].New_Item_Budget__c
      );
      system.assertEquals(
        1.12,
        ctrl1.newExpenseItem_list[1].New_Item_Budget__c
      );
      system.assertEquals(ctrl1.newExpenseItem_list.size(), 2);
      ctrl1.saveExpenses();

      ctrl1.getBudgetItems();

      ctrl1.laborItem_list[0].Projected_Grant_Hours_Per_Week__c = 0;
      ctrl1.updateExistingLaborAmounts();
      ctrl1.updateAllLaborAmounts();
      system.assertEquals(
        0,
        ctrl1.laborItem_list[0].Projected_Percent_Time_on_Grant__c
      );

      ctrl1.laborItem_list[0].Selected__c = true;
      ctrl1.markPersonnelInactive();
      system.assertEquals(ctrl1.laborItem_list[0].New_Wages__c, 0);
      system.assertEquals(ctrl1.laborItem_list[0].New_Fringe_Benefits__c, 0);

      Integer laborSize = ctrl1.laborItem_list.size();
      ctrl1.laborItem_list[0].Selected__c = true;
      ctrl1.deleteLaborItems();
      ctrl1.deleteNewLaborItems();
      ctrl1.deleteExpenseItems();
      ctrl1.deleteNewExpenseItems();
      system.assertEquals(ctrl1.laborItem_list.size(), laborSize - 1);

      ctrl1.expenseItem_list[0].Quantity__c = 0;
      ctrl1.updateExistingExpenseAmounts();
      ctrl1.updateAllExpenseAmounts();
      system.assertEquals(ctrl1.expenseItem_list[0].New_Item_Budget__c, 0);

      ctrl1.expenseItem_list[0].Selected__c = true;
      ctrl1.markExpensesInactive();
      system.assertEquals(ctrl1.expenseItem_list[0].Is_Active__c, false);

      ctrl1.selectedItemId = ctrl1.laborItem_list[0].Id;
      ctrl1.showNotesPopup();
      ctrl1.selectedItem.Item_Note__c = 'test';
      ctrl1.selectedItemType = 'labor';
      ctrl1.upsertItem();
      Budget_Item__c noteTest = [
        SELECT Item_Note__c
        FROM Budget_Item__c
        WHERE Id = :ctrl1.selectedItemId
      ];
      system.assertEquals('test', noteTest.Item_Note__c);

      ctrl1.hideNotesPopup();
      ctrl1.showNewExpenseNotesPopup();
      ctrl1.hideNewExpenseNotesPopup();
      ctrl1.showNewLaborNotesPopup();
      ctrl1.hideNewLaborNotesPopup();
      ctrl1.showSendBackPopup();
      ctrl1.hideSendBackPopup();
      ctrl1.showApprovePopup();
      ctrl1.hideApprovePopup();

      ctrl1.getTotals();
      ctrl1.next();
      ctrl1.previous();
      ctrl1.review();
      ctrl1.submit();
      Grant__c grantTest1 = [
        SELECT Grant_Status__c, Modification_History__c
        FROM Grant__c
        WHERE Id = :ctrl1.grant.Id
      ];
      system.assertEquals('Pending First Approval', grantTest1.Grant_Status__c);
      system.assert(grantTest1.Modification_History__c != null);

      ctrl1.approverLevel = 'Level One';
      ctrl1.approve();
      Grant__c grantTest2 = [
        SELECT Grant_Status__c
        FROM Grant__c
        WHERE Id = :ctrl1.grant.Id
      ];
      system.assertEquals(
        'Pending Second Approval',
        grantTest2.Grant_Status__c
      );

      ctrl1.approverLevel = 'Level Two';
      ctrl1.approve();
      ctrl1.approverLevel = 'Level Three';
      ctrl1.approve();

      ctrl1.sendBackTo = 'levelone';
      ctrl1.sendBack();
      Grant__c grantTest3 = [
        SELECT Grant_Status__c
        FROM Grant__c
        WHERE Id = :ctrl1.grant.Id
      ];
      system.assertEquals('Pending First Approval', grantTest3.Grant_Status__c);
      ctrl1.sendBackTo = 'levelthree';
      ctrl1.sendBack();
      ctrl1.sendBackTo = 'leveltwo';
      ctrl1.sendBack();
      ctrl1.sendBackTo = 'affiliate';
      ctrl1.sendBack();

      ctrl1.createMOU();
      ctrl1.sendFFATA();
      ctrl1.showUpdatePopup();
      ctrl1.updateBudget();
      ctrl1.hideUpdatePopup();
      ctrl1.showCloseGrantPopup();
      ctrl1.closeGrant();
      ctrl1.hideCloseGrantPopup();
      ctrl1.reopenGrant();

      // END Test BudgetCtrl
    }
    system.Test.stopTest();
  }
}