force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Item_Budget__c - Total_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Item Budget - Total Approved Amount</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description
  >If employee is salaried, hourly rate is calculated as follows: Salary divided by 2,080 = 40 hour/week Hourly Rate. See http://www.calculators.org/savings/wage-conversion.php.</description>
    <label>Hourly Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rate__c</fullName>
    <label>Monthly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Other_Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Other Factor Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <label>Use Indirect Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/Reimbursement_Item__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Item</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Item__c/fields/Budget_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Item__c</fullName>
    <label>Budget Item</label>
    <referenceTo>Budget_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Factor Percent</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Item__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement Item</label>
    <referenceTo>Reimbursement_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Request__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Request__c</fullName>
    <label>Reimbursement Request</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Request_Notes__c.field-meta.xml
<CustomField>
    <fullName>Request_Notes__c</fullName>
    <label>Request Notes</label>
    <length>20000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_FTE_at_Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Total_FTE_at_Affiliate__c</fullName>
    <label>Total FTE at Affiliate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <formula
  >IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Use Indirect Rate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Youth_Served_with_Grant_Funding__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_with_Grant_Funding__c</fullName>
    <label>Youth Served with Grant Funding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RequestFormController.cls
public with sharing class RequestFormController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  private BudgetItemClass budgetItemClass = new BudgetItemClass();
  private ReimbursementClass requestClass = new ReimbursementClass();
  private ReimbursementItemClass requestItemClass = new ReimbursementItemClass();

  public Account acct { get; set; }
  public ID grantId { get; set; }
  public List<SelectOption> grant_list { get; set; }
  public Grant__c grant { get; set; }
  public List<Budget_Item__c> bi_list { get; set; }

  public ID RequestID { get; set; }
  public Reimbursement_Request__c request { get; set; }
  public List<Reimbursement_Item__c> ri_list { get; set; }
  public Id laborId = Schema.SObjectType.Reimbursement_Item__c.getRecordTypeInfosByName()
    .get('Labor')
    .getRecordTypeId();
  public Id expenseId = Schema.SObjectType.Reimbursement_Item__c.getRecordTypeInfosByName()
    .get('Expense')
    .getRecordTypeId();

  public Date startDate { get; set; }
  public Date endDate { get; set; }

  public Boolean factorConfirm { get; set; }
  public String errorMessage { get; set; }

  // BEGIN Constructor
  public RequestFormController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;
    if (portalName == 'BBBS')
      portalName = '';

    grantId = ApexPages.currentPage().getParameters().get('GrantId');
    RequestID = ApexPages.currentPage().getParameters().get('RequestID');

    grant_list = new List<SelectOption>();
    request = new Reimbursement_Request__c();
    bi_list = new List<Budget_Item__c>();
    ri_list = new List<Reimbursement_Item__c>();

    factorConfirm = false;
    errorMessage = '';

    if (RequestID != null) {
      Reimbursement_Request__c[] requests = [
        SELECT
          Grant__c,
          Previous_Status__c,
          Status__c,
          Request_Notes__c,
          Start_Date__c,
          End_Date__c,
          Total_FTE_at_Affiliate__c,
          Youth_Served__c,
          Youth_Served_with_Grant_Funding__c
        FROM Reimbursement_Request__c
        WHERE Id = :RequestID
      ];
      if (requests.size() > 0) {
        request = requests[0];
        startDate = request.Start_Date__c;
        endDate = request.End_Date__c;
        grantId = request.Grant__c;
      }
    }

    if (grantId == null) {
      grant_list.add(new SelectOption('', '-- Select a Sub-Grant --'));
      for (Grant__c g : [
        SELECT Id, Name
        FROM Grant__c
        WHERE Account__c = :userAcct.Id AND Grant_Status__c = 'Approved'
      ]) {
        grant_list.add(new SelectOption(g.Id, g.Name));
      }
    } else {
      getGrant();
    }
  }

  public void getGrant() {
    if (grantId != null) {
      Grant__c[] grants = [
        SELECT
          Account__r.Id,
          Name,
          Balance__c,
          Use_Indirect_Rate__c,
          Account__r.RecordType.Name
        FROM Grant__c
        WHERE Id = :GrantId
      ];
      if (grants.size() > 0) {
        grant = grants[0];
      }
      acct = [
        SELECT ID, Name, RecordType.Name
        FROM Account
        WHERE ID = :grant.Account__r.Id
      ];
    }
  }

  public void getItemList() {
    for (Budget_Item__c bi : [
      SELECT
        Id,
        Name,
        RecordType.Name,
        Is_Active__c,
        Hourly_Rate__c,
        Monthly_Rate__c,
        Other_Factor_Percent__c,
        Factor_Type__c
      FROM Budget_Item__c
      WHERE Grant__c = :GrantId
    ]) {
      if (bi.Name != 'Benefits' && bi.Is_Active__c == true) {
        bi_list.add(bi);
      }
    }
    system.debug('>>> bi_list = ' + bi_list);

    system.debug('>>> request = ' + request);
    if (request.Id != null) {
      //ri_list = ric.getRequestItems(request.Id);
      ri_list = [
        SELECT Id
        FROM Reimbursement_Item__c
        WHERE Reimbursement_Request__c = :request.Id
      ];
      system.debug('>>> ri_list = ' + ri_list);

      if (
        (ri_list == null ||
        ri_list.size() == 0) &&
        bi_list != null &&
        bi_list.size() > 0
      ) {
        for (Budget_Item__c bi : bi_list) {
          if (bi.Is_Active__c) {
            Reimbursement_Item__c r = new Reimbursement_Item__c();
            r.Reimbursement_Request__c = request.Id;
            r.Budget_Item__c = bi.Id;
            if (bi.RecordType.Name == 'Labor') {
              r.RecordTypeId = laborId;
              if (bi.Hourly_Rate__c != null) {
                r.Rate__c = (bi.Hourly_Rate__c).setScale(2);
              }
            } else {
              r.RecordTypeId = expenseId;
              if (bi.Monthly_Rate__c != null) {
                r.Rate__c = bi.Monthly_Rate__c;
              }
              if (bi.Factor_Type__c == 'Other') {
                if (
                  bi.Other_Factor_Percent__c > 0 &&
                  r.Factor_Percent__c <= 100
                ) {
                  r.Factor_Percent__c = bi.Other_Factor_Percent__c;
                } else {
                  r.Factor_Percent__c = 100;
                }
              }
            }
            ri_list.add(r);
          }
        }
        requestItemClass.upsertItems(ri_list);
      }
    }
  }

  public PageReference next() {
    errorMessage = '';

    if (portalName == 'BBBS') {
      if (factorConfirm == false) {
        errorMessage = 'Please confirm that you\'d like to proceed using current indirect rate or factor value';
      }
      //if(request.Youth_Served__c == null || request.Youth_Served_with_Grant_Funding__c == null || request.Youth_Served_with_Grant_Funding__c > request.Youth_Served__c) {
      if (
        request.Youth_Served_with_Grant_Funding__c > request.Youth_Served__c
      ) {
        errorMessage = 'The number of youth served with grant funding should not exceed total number of youth served';
      }
      //if(request.Youth_Served_with_Grant_Funding__c == 0 || request.Youth_Served_with_Grant_Funding__c == null) {
      //    errorMessage = 'The number of youth served with grant funding should not be zero';
      //}
      if (
        request.Total_FTE_at_Affiliate__c == 0 ||
        request.Total_FTE_at_Affiliate__c == null
      ) {
        errorMessage = 'The total employee hours at affiliate should not be zero';
      }
    }

    if (String.isBlank(errorMessage)) {
      Date dt = date.today();
      String fdt = dt.format();
      if (request.Id == null) {
        request.Grant__c = grant.ID;
        request.Modification_History__c =
          fdt +
          ': Request Submitted by ' +
          currentUser.Contact.Name +
          ' (' +
          currentUser.Id +
          ')';
      }

      if (grant.Account__r.RecordType.Name == 'National Organization') {
        request.Is_National_Request__c = true;
      }

      request.Request_Date__c = dt;
      if (portalName == 'MDGO') {
        if (startDate != null)
          request.Start_Date__c = startDate;
        if (endDate != null)
          request.End_Date__c = endDate;
      }
      request.Previous_Status__c = request.Status__c;
      if (request.Status__c == 'Revisions Needed') {
        request.Status__c = 'Revision in Progress';
      } else if (request.Status__c == null) {
        request.Status__c = 'Incomplete';
      }
      if (
        request.Youth_Served_with_Grant_Funding__c > 0 &&
        request.Youth_Served__c > 0
      ) {
        request.Youth_Served_Percent__c =
          request.Youth_Served_with_Grant_Funding__c /
          request.Youth_Served__c *
          100;
      } else {
        request.Youth_Served_Percent__c = 0;
      }
      if (request.Youth_Served_Percent__c > 100) {
        errorMessage = 'The projected # of children served with grant funding during the Grant performance period should not exceed the total # of children served.';
      }
      try {
        RequestClass.upsertRequest(request);
        getItemList();
      } catch (Exception e) {
        errorMessage =
          'An error occurred whil upserting the request: ' + e.getMessage();
        system.debug('error = ' + e.getMessage());
        return null;
      }
    }
    PageReference pr = new PageReference(
      '/' +
      portalName +
      'RequestPersonnelForm?RequestID=' +
      request.Id
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference cancel() {
    PageReference pr = new PageReference('/Reimbursements');
    pr.setRedirect(true);
    return pr;
  }
}