force-app/main/default/objects/Account/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child Safety</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contract Specialists</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Other Costs</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Sub Awards</fullName>
            </value>
            <value>
                <fullName>Consultant Travel</fullName>
            </value>
            <value>
                <fullName>Indirect Costs</fullName>
            </value>
            <value>
                <fullName>Procurement Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <inlineHelpText>BBBSA only: 
if Factor Type = FTE, New Item Budget = New Rate * Estimated FTE (from Sub-Grant);
if Factor Type = TCS, New Item Budget = New Rate * Youth Served % (from Sub-Grant);
if Factor Type = Other, New Item Budget = New Rate * Other Factor %;</inlineHelpText>
    <label>Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTE</fullName>
            </value>
            <value>
                <fullName>TCS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Fringe_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Fringe_Benefits__c</fullName>
    <label>Fringe Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <label>Indirect Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: Rate (hourly) * Projected Grant Hours * Number of Weeks (fringe not included);
All Other Personnel: Wages + Fringe Benefits
Expenses: Rate * Quantity</inlineHelpText>
    <label>Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Note__c.field-meta.xml
<CustomField>
    <fullName>Item_Note__c</fullName>
    <label>Item Note</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Monthly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rate__c</fullName>
    <label>Monthly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Fringe_Benefits__c.field-meta.xml
<CustomField>
    <fullName>New_Fringe_Benefits__c</fullName>
    <label>New Fringe Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>New_Item_Budget__c</fullName>
    <inlineHelpText
  >BBBSA Personnel: New Rate (hourly) * Projected Grant Hours * Number of Weeks;
All Other Personnel: New Wages + New Fringe Benefits
Expenses: New Rate * Quantity</inlineHelpText>
    <label>New Item Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Rate__c</fullName>
    <label>New Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/New_Wages__c.field-meta.xml
<CustomField>
    <fullName>New_Wages__c</fullName>
    <label>New Wages</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Other_Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Other Factor Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Items: Approved Amount where Reimbursement Status = Approved, Paid, Closed</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Reimbursement_Item__c.Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field
    >Reimbursement_Item__c.Reimbursement_Status_for_Formula_Fields__c</field>
        <operation>contains</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Item__c.Budget_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <inlineHelpText>Used by BBBSA and NPAL only</inlineHelpText>
    <label>Total Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Wages__c.field-meta.xml
<CustomField>
    <fullName>Wages__c</fullName>
    <label>Wages</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Estimated_FTE__c.field-meta.xml
<CustomField>
    <fullName>Estimated_FTE__c</fullName>
    <label>Estimated FTE</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Indirect Rate</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/New_Indirect_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>New_Indirect_Rate_Amount__c</fullName>
    <label>New Indirect Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Approved Amount</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Budget_Item__c.Total_Approved_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <label>Use Indirect Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served__c</fullName>
    <label>Youth Served</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served_Percent__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Youth Served Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <label>Indirect Rate</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <formula>Approved_Salary__c + Approved_Benefits__c + Approved_Expenses__c + 
IF(AND( 
NOT(ISPICKVAL(Status__c, &apos;Incomplete&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Revisions Needed&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Revisions in Progress&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Denied&apos;)),
NOT(ISPICKVAL(Status__c, &apos;Pending First Approval&apos;))
), 
Indirect_Rate_Amount__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Approved_Salary__c + Approved_Benefits__c + Approved_Expenses__c + 
IF([Status__c not any Incomplete], Indirect_Rate_Amount__c, 0)</inlineHelpText>
    <label>Total Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <formula
  >IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Use Indirect Rate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Youth_Served_Percent__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_Percent__c</fullName>
    <label>Youth Served Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Youth_Served_with_Grant_Funding__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_with_Grant_Funding__c</fullName>
    <label>Youth Served with Grant Funding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubGrantBudgetExpensesController.cls
public with sharing class SubGrantBudgetExpensesController {
}
/*
    public UserClass userClass = new UserClass();
    public User currentUser { get; set; }
    public Account userAcct { get; set; }
    public String userAcctType { get; set; }
    public String portalName { get; set; }
    
    public GrantClass grantClass = new GrantClass();
    public BudgetItemClass budgetItemClass = new BudgetItemClass();
    
    public Account acct { get; set; }
    public ID GrantId { get; set; }
    public Grant__c grant { get; set; }
    public Id expenseId { get; set; }
    public Decimal laborRequestedAmount { get; set; }
    public Decimal expenseRequestedAmount { get; set; }
    public Decimal totalRequestedAmount { get; set; }
    public String errorMessage { get; set; }    
    public Boolean amountError { get; set; } 
    public Boolean displayExpenseNotesPopup { get; set; }
    public Boolean displayNewExpenseNotesPopup { get; set; }
    public Boolean displayAttPopup { get; set; }
    
    public List<SelectOption> categories { get; set; } 
    public List<SelectOption> factorTypes { get; set; } 
    
    public Map<String, List<Budget_Item__c>> expense_map { get; set; }
    public boolean hasExpenses { get; set; }
    public List<itemClass> newExpense_list { get; set; }
    public Integer selectedExpense { get; set; } 
    public Integer expenseCount = 0;
    
    public Attachment att { get; set; }
    public List<Attachment> att_list { get; set; }
    public Id deleteAttId { get; set; }
    
    public Boolean hasReimbursements { get; set; }
    public List<SelectOption> options { get; set; }
    public string bulkAction { get; set; }
    
    // BEGIN Constructor
    public SubGrantBudgetExpensesController () {
        currentUser = userClass.currentUser;
        userAcct = userClass.userAcct;
        userAcctType = userClass.userAcctType;
        portalName = userClass.userProfile;
        
        GrantId = ApexPages.currentPage().getParameters().get('GrantId');  
        expenseId = Schema.SObjectType.Budget_Item__c.getRecordTypeInfosByName().get('Expense').getRecordTypeId();
        
        acct = new Account();
        grant = new Grant__c();
        
        laborRequestedAmount = 0;
        expenseRequestedAmount = 0;
        totalRequestedAmount = 0;
        errorMessage = '';
        amountError = false;
        displayExpenseNotesPopup = false; 
        displayNewExpenseNotesPopup = false; 
        displayAttPopup = false;
            
        newExpense_list = new List<itemClass>();
        expense_map = new Map<String, List<Budget_Item__c>>();
        hasExpenses = false;
        selectedExpense = 0;  
        
        att = new Attachment();
        att_list = new List<Attachment>();
        
        if(GrantID != null) {
            grant = grantClass.getGrant(GrantID);
            system.debug('>>> grant = ' + grant);
            
            for(Attachment a : grant.Attachments) {
                att_list.add(a);
            }
            
            if(grant.Youth_Served_Percent__c == null && grant.Youth_Served_with_Grant_Funding__c > 0 && grant.Youth_Served__c > 0) {
                grant.Youth_Served_Percent__c = grant.Youth_Served_with_Grant_Funding__c / grant.Youth_Served__c;
            }      
            acct = [SELECT ID, Name, RecordType.Name FROM Account WHERE ID = :grant.Account__r.Id];
            
            Reimbursement_Request__c[] requests = [SELECT Id FROM Reimbursement_Request__c WHERE Grant__r.Id = :GrantId];
            if(requests.size() > 0) {
                hasReimbursements = true;
            }
        }
        
        categories = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult1 = Budget_Item__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> ple1 = fieldResult1.getPicklistValues();
        for(Schema.PicklistEntry f1 : ple1)
        {
            categories.add(new SelectOption(f1.getLabel(), f1.getValue()));
        }
        
        factorTypes = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult2 = Budget_Item__c.Factor_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple2 = fieldResult2.getPicklistValues();
        for(Schema.PicklistEntry f2 : ple2)
        {
            factorTypes.add(new SelectOption(f2.getLabel(), f2.getValue()));
        }
        
        options = new List<SelectOption>();
        options.add(new SelectOption('','Select an Action'));
        options.add(new SelectOption('delete','Delete'));
        options.add(new SelectOption('disable','Mark Inactive'));
        //options.add(new SelectOption('enable','Mark Active'));
    }
    // END Constructor
    
    // BEGIN getLists
    public void getLists() {
        expense_map.clear();
        laborRequestedAmount = 0;
        expenseRequestedAmount = 0;
        totalRequestedAmount = 0;
        
        for(itemClass i : newExpense_list) {
            if(i.item.New_Item_Budget__c != null) {
                expenseRequestedAmount += i.item.New_Item_Budget__c;
            }
        }
        BudgetItemClass bic = new BudgetItemClass();
        for(Budget_Item__c bi : bic.getBudgetItems(GrantId)) {
            if(bi.RecordType.Name == 'Expense') {
                if(bi.Is_Active__c == false && bi.Total_Approved_Amount__c != null) {
                    expenseRequestedAmount += bi.Total_Approved_Amount__c;
                }
                if(bi.New_Item_Budget__c == null && bi.Item_Budget__c != null) {
                    bi.New_Item_Budget__c = bi.Item_Budget__c;
                }
                if(bi.New_Rate__c == null) {
                    if(bi.Total_Expense__c != null) {
                        bi.New_Rate__c = bi.Total_Expense__c;
                    } else if(bi.Monthly_Rate__c != null) {
                        bi.New_Rate__c = bi.Monthly_Rate__c;
                    }
                }
                if(bi.New_Item_Budget__c != null) {
                    if(bi.New_Rate__c > 0) {
                        if(grant.Use_Indirect_Rate__c == 'Yes') {
                            bi.New_Item_Budget__c = bi.New_Rate__c;//(bi.New_Rate__c * grant.Indirect_Rate__c / 100).setScale(2);
                        } else {
                            if(bi.Factor_Type__c == 'FTE' && grant.Estimated_FTE__c != null) {
                                bi.New_Item_Budget__c = (bi.New_Rate__c * grant.Estimated_FTE__c / 100).setScale(2);
                            } else if(bi.Factor_Type__c == 'TCS' && grant.Youth_Served_Percent__c != null) {
                                bi.New_Item_Budget__c = (bi.New_Rate__c * grant.Youth_Served_Percent__c / 100).setScale(2);
                            }  else if(bi.Factor_Type__c == 'Other') {
                                bi.New_Item_Budget__c = (bi.New_Rate__c * bi.Other_Factor_Percent__c / 100).setScale(2);
                            } else {
                                bi.New_Item_Budget__c = bi.New_Rate__c;
                            }
                        }
                        expenseRequestedAmount += bi.New_Item_Budget__c;
                    } 
                }
                if(expense_map.containsKey(bi.Category__c)) {
                    List<Budget_Item__c> bi_list = expense_map.get(bi.Category__c);
                    bi_list.add(bi);
                    expense_map.put(bi.Category__c, bi_list);
                } else {
                    expense_map.put(bi.Category__c, new List<Budget_Item__c>{bi});
                }
                if(expense_map.keySet() != null) {
                    hasExpenses = true;
                }
            } else {
                if(portalName == 'NPAL' && bi.New_Wages__c != null) {
                    laborRequestedAmount += bi.New_Wages__c;
                } else if(portalName == 'NPAL' && bi.Wages__c != null) {
                    laborRequestedAmount += bi.Wages__c;
                } else if(bi.New_Item_Budget__c != null) {
                    laborRequestedAmount += bi.New_Item_Budget__c;
                } else if(bi.Item_Budget__c != null) {
                    laborRequestedAmount += bi.Item_Budget__c;
                }
                if(bi.New_Fringe_Benefits__c != null) {
                    laborRequestedAmount += bi.New_Fringe_Benefits__c; 
                } else if(bi.Fringe_Benefits__c != null) {
                    laborRequestedAmount += bi.Fringe_Benefits__c; 
                }
            }
            system.debug('>>> expense_map = ' + expense_map);
        }
        getTotals();
    }
    // END getList
    
    // BEGIN getAttList
    public void getAttList() { 
        att_list.clear();
        Grant__c g = [
            SELECT Id
            ,(SELECT Id, Name, Description FROM Attachments ORDER BY LastModifiedDate desc) 
            FROM Grant__c
            WHERE Id = :grant.Id
        ];
        for(Attachment a : g.Attachments) {
            att_list.add(a);
        }
    }
    // END getAttList
    
    // BEGIN updateAmounts
    public void updateAmounts()
    {
        errorMessage = '';
        expenseRequestedAmount = 0;
            
        for(ItemClass ic : newExpense_list) {   
            system.debug('>>> ic = ' + ic);               
            if(ic.item.New_Rate__c != null && ic.item.New_Rate__c != 0) {
                if(grant.Use_Indirect_Rate__c == 'Yes') {
                    ic.item.New_Item_Budget__c = ic.item.New_Rate__c;//(ic.item.New_Rate__c * grant.Indirect_Rate__c / 100).setScale(2);
                    expenseRequestedAmount += ic.item.New_Rate__c.setScale(2);
                } else if (portalName == '') {
                    if(ic.factorType == 'FTE') {
                        ic.item.New_Item_Budget__c = (ic.item.New_Rate__c * grant.Estimated_FTE__c / 100).setScale(2);
                    } else if(ic.factorType == 'TCS') {
                        ic.item.New_Item_Budget__c = (ic.item.New_Rate__c * grant.Youth_Served_Percent__c / 100).setScale(2);
                    }  else if(ic.factorType == 'Other') {
                        if(ic.item.Other_Factor_Percent__c > 0) {
                            ic.item.New_Item_Budget__c = (ic.item.New_Rate__c * ic.item.Other_Factor_Percent__c / 100).setScale(2);
                        } else {
                            errorMessage = 'Factor Percent is required for ' + ic.item.Name;
                        }
                    } else {
                        errorMessage = 'Total Expense is required for ' + ic.item.Name;
                    }
                } else {
                    ic.item.New_Item_Budget__c = ic.item.New_Rate__c;
                }
                if(ic.item.New_Item_Budget__c != null) {
                    expenseRequestedAmount += ic.item.New_Item_Budget__c.setScale(2);
                }
            } else {
                errorMessage = 'Please enter a valid amount for ' + ic.item.Name;
            }
            if(portalName == '' && ic.factorType == 'Other' && String.isBlank(ic.itemNote)) {
                errorMessage = 'Please enter a note for ' + ic.item.Name;
            }
        }
        
        List<Budget_Item__c> expense_update_list = new List<Budget_Item__c>();
        List<List<Budget_Item__c>> expense_list = expense_map.values();
        for(Integer i = 0; i < expense_list.size(); i++) {
            for(Budget_Item__c bi : expense_list.get(i)) {
                system.debug('>>> bi = ' + bi);   
                if(bi.Is_Active__c) {
                    if(bi.New_Rate__c > 0) {
                        if(grant.Use_Indirect_Rate__c == 'Yes') {
                            bi.New_Item_Budget__c = bi.New_Rate__c;//(bi.New_Rate__c * grant.Indirect_Rate__c / 100).setScale(2);
                        } else if (portalName == '') {
                            if(bi.Factor_Type__c == 'FTE' && grant.Estimated_FTE__c != null) {
                                bi.New_Item_Budget__c = (bi.New_Rate__c * grant.Estimated_FTE__c / 100).setScale(2);
                            } else if(bi.Factor_Type__c == 'TCS' && grant.Youth_Served_Percent__c != null) {
                                bi.New_Item_Budget__c = (bi.New_Rate__c * grant.Youth_Served_Percent__c / 100).setScale(2);
                            }  else if(bi.Factor_Type__c == 'Other') {
                                if(bi.Other_Factor_Percent__c > 0 && bi.Other_Factor_Percent__c != null) {
                                    bi.New_Item_Budget__c = (bi.New_Rate__c * bi.Other_Factor_Percent__c / 100).setScale(2);
                                } else {
                                    errorMessage = 'Factor Percent is required for ' + bi.Name;
                                }
                            } else {
                                errorMessage = 'Please enter a valid Factor Type for ' + bi.Name;
                            }
                        } else {
                            bi.New_Item_Budget__c = bi.New_Rate__c;
                        }
                        if(bi.New_Item_Budget__c != null) {
                            expenseRequestedAmount += bi.New_Item_Budget__c.setScale(2);
                        }
                    }
                } else if (bi.Total_Approved_Amount__c !=  null) {
                    bi.New_Item_Budget__c = bi.Total_Approved_Amount__c;
                    expenseRequestedAmount += bi.New_Item_Budget__c; 
                }
                if(portalName == '' && bi.Factor_Type__c == 'Other' && bi.Is_Active__c == true && String.isBlank(bi.Item_Note__c)) {
                    errorMessage = 'Please enter a note for ' + bi.Name;
                }
                expense_update_list.add(bi);
            }
        }
        budgetItemClass.upsertItems(expense_update_list);
        
        getTotals();
    }
    // END updateAmounts
    
    // BEGIN getTotals
    public void getTotals() {
        system.debug('>>> expenseRequestedAmount = ' + expenseRequestedAmount);
        if(grant.Use_Indirect_Rate__c == 'Yes') {
            grant.New_Indirect_Rate_Amount__c = ((laborRequestedAmount + expenseRequestedAmount) * grant.Indirect_Rate__c / 100).setScale(2);
            totalRequestedAmount = laborRequestedAmount + expenseRequestedAmount + grant.New_Indirect_Rate_Amount__c;
        } else {
            totalRequestedAmount = (laborRequestedAmount + expenseRequestedAmount).setScale(2);
        }
        if(grant.Amount__c != null && (totalRequestedAmount.setScale(2) - 0.001) > grant.Amount__c.setScale(2)) {
            amountError = true;
            errorMessage = 'Requested Amount Exceeds Sub-Grant Amount';
        } else {
            amountError = false;
        }
    }
    // END getTotals
    
    // BEGIN updateSelected
    public void updateSelected() {
        system.debug('bulkAction = ' + bulkAction);
        List<Budget_Item__c> active_list = new List<Budget_Item__c>();
        List<Budget_Item__c> delete_list = new List<Budget_Item__c>();
        List<List<Budget_Item__c>> expense_list = expense_map.values();
        
        if(bulkAction != '') {
            for(Integer i = 0; i < expense_list.size(); i++) {
                for(Budget_Item__c bi : expense_list.get(i)) {
                    if(bi.Selected__c) {
                        if(bulkAction.toLowerCase() == 'disable') {
                            bi.Is_Active__c = false;
                            if(bi.Total_Approved_Amount__c != null) {
                                bi.New_Item_Budget__c = bi.Total_Approved_Amount__c;
                                bi.New_Rate__c = bi.Total_Approved_Amount__c;
                            } else {
                                bi.New_Item_Budget__c = 0;
                            }
                            active_list.add(bi);
                        }
                        if(bulkAction.toLowerCase() == 'enable') {
                            bi.Is_Active__c = true;
                            active_list.add(bi);
                        }
                        if(bulkAction.toLowerCase() == 'delete') {
                            if(bi.Total_Approved_Amount__c > 0) {
                                errorMessage = 'Item cannot be deleted';
                            } else {
                                delete_list.add(bi);
                            }
                        }
                    }
                    bi.Selected__c = false;
                }
            }
            if(active_list.size() > 0) {
                budgetItemClass.upsertItems(active_list);
            }
            if(delete_list.size() > 0) {
                budgetItemClass.deleteItems(delete_list);
            }
        }
        bulkAction = '';
        getLists();
    }
    // END updateSelected
    
    // BEGIN saveExpenses
    public void saveExpenses()
    {
        updateAmounts();
        List<Budget_Item__c> expense_upsert_list = new List<Budget_Item__c>();
        
        // Add items in list for insert
        for(ItemClass ic : newExpense_list){
            system.debug('>>> ic = ' + ic);
            if(ic.item.Id == null && ic.item.Name != null && ic.item.New_Item_Budget__c != null) {
                Budget_Item__c bi = new Budget_Item__c();
                bi = ic.item;
                bi.Category__c = ic.category;
                bi.Factor_Type__c = ic.factorType;
                bi.Item_Note__c = ic.itemNote;
                expense_upsert_list.add(bi);
                system.debug('>>> bi = ' + bi);
            }
        }
        budgetItemClass.upsertItems(expense_upsert_list);
    }
    // END saveExpenses
    
    // BEGIN deleteAtt
    public void deleteAtt() {
        if(deleteAttId != null) {
            Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteAttId];
            if(a != null) {
                delete a;
            }
        }
        getAttList();
    }
    // END deleteAtt
    
    // BEGIN previous
    public PageReference previous()
    {
        saveExpenses();
        grantClass.upsertGrant(grant);
        
        PageReference pr = new PageReference('/' + portalName + 'BudgetPersonnel?GrantID=' + GrantID);
        pr.setRedirect(True);
        return pr;
    }
    // END previous
    
    // BEGIN saveAndExit
    public PageReference saveAndExit()
    {
        saveExpenses();
        grantClass.upsertGrant(grant);
        
        if(String.isBlank(errorMessage)) {
            PageReference pr = new PageReference('/' + portalName + 'SubGrantDetails?GrantID=' + GrantID);
            pr.setRedirect(True);
            return pr;
        }
        return null;
    }
    // END saveAndExit
    
    // BEGIN submit
    public PageReference submit()
    {
        errorMessage = '';
        saveExpenses();
        
        if(portalName == '' && (grant.Youth_Served_Percent__c == null || grant.Youth_Served_Percent__c == 0)) {
            errorMessage = 'TCS must be greater than zero.';
        } 
        if (portalName == '' && (grant.Estimated_FTE__c == null || grant.Estimated_FTE__c == 0)) {
            errorMessage = 'FTE must be greater than zero.';
        } 
        
        if(errorMessage == '') {
            Date dt = date.today();
            String fdt = dt.format();
            String mh = fdt + ': Modification Submitted by ' + currentUser.Contact.Name + ' (' + currentUser.Id + ')';
            if(grant.Modification_History__c == null) {
                grant.Modification_History__c = '';
            } 
            grant.Modification_History__c += ' \r\n' + mh;
            
            grant.Previous_Status__c = grant.Grant_Status__c;
            if(grant.Grant_Status__c == 'Approved') {
                grant.Grant_Status__c = 'Pending Review';
            } else {
                grant.Grant_Status__c = 'Budget Submitted';
            }
            grant.Primary_Contact__c = currentUser.ContactID;
            grantClass.upsertGrant(grant);
            
            PageReference pr = new PageReference('/' + portalName + 'SubGrantDetails?GrantID=' + GrantID);
            pr.setRedirect(True);
            return pr;
        }
        return null;
    }
    // END submit
    
    public void expenseNotesPopup() {  
        if(displayExpenseNotesPopup == true) {
            displayExpenseNotesPopup = false; 
        } else {
            displayExpenseNotesPopup = true; 
        }
    }
    
    public void newExpenseNotesPopup() {  
        if(displayNewExpenseNotesPopup == true) {
            displayNewExpenseNotesPopup = false; 
        } else {
            displayNewExpenseNotesPopup = true; 
        }
    }
    
    public void attPopup() {  
        getAttList();
        if(displayAttPopup == true) {
            displayAttPopup = false; 
        } else {
            displayAttPopup = true; 
        }
    }
    
    
    // BEGIN Inner Class
    public class itemClass
    {       
        SubGrantBudgetExpensesController outerClass; 
        
        public Budget_Item__c item { get; set; }
        public Integer itemIndex { get; set; }    
        public String category { get; set; }
        public String factorType { get; set; }
        public Decimal rate { get; set; }
        public String itemNote { get; set; }
        
        // BEGIN Inner Class Constructor
        public itemClass(SubGrantBudgetExpensesController outerClass, Integer intCount, Budget_Item__c bi)
        {
            system.debug('>>> bi = ' + bi);
            itemIndex = intCount;
            item = bi;  
            
            rate = bi.Monthly_Rate__c;
            if(rate == null) {
                if(bi.New_Rate__c != null) {
                    rate = bi.New_Rate__c.setScale(2);
                } else if(bi.Item_Budget__c != null) {
                    rate = bi.Item_Budget__c.setScale(2);
                }
            }
        }
        // END Inner class Constructor  
    }
    // END inner Class
    
    // BEGIN addItem
    public void addItem()
    {   
        Budget_Item__c bi = new Budget_Item__c();
        bi.Grant__c = grant.Id;
        bi.RecordTypeId = expenseId;
        bi.Category__c = 'Other Costs';
        bi.Is_Active__c = true;
        
        itemClass ic = new itemClass(this, expenseCount, bi);
        expenseCount = expenseCount + 1;
        newExpense_list.add(ic);
        system.debug('>>> newExpense_list = ' + newExpense_list);
    }
    // END addItem
    
    // BEGIN delete
    public void deleteItem()
    {
        newExpense_list.remove(selectedExpense);
        expenseCount = 0;
        for(itemClass ic : newExpense_list) {
            ic.itemIndex = expenseCount;
            expenseCount = expenseCount + 1;
        }
    }
    // END delete
}
*/