force-app/main/default/objects/Account/fields/Local_Organization__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>LocalOrganization</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Month__c</fullName>
    <label>Birth Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <label>Birth Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Extension__c.field-meta.xml
<CustomField>
    <fullName>Extension__c</fullName>
    <label>Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Not specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Highest_Chapter_Completed__c.field-meta.xml
<CustomField>
    <fullName>Highest_Chapter_Completed__c</fullName>
    <label>Highest Chapter Completed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_Guardian__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent/Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Parents_Guardians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Finance Coordinator</fullName>
            </value>
            <value>
                <fullName>Program Coordinator</fullName>
            </value>
            <value>
                <fullName>Site Coordinator</fullName>
            </value>
            <value>
                <fullName>Board Chair</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Fund Development Lead</fullName>
            </value>
            <value>
                <fullName>Marketing/Recruitment Lead</fullName>
            </value>
            <value>
                <fullName>Finance Lead</fullName>
            </value>
            <value>
                <fullName>Secondary Signer</fullName>
            </value>
            <value>
                <fullName>Grant Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/User_Profile__c.field-meta.xml
<CustomField>
    <fullName>User_Profile__c</fullName>
    <label>User Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self Assessment Only</fullName>
            </value>
            <value>
                <fullName>Program Admin</fullName>
            </value>
            <value>
                <fullName>All Access</fullName>
            </value>
            <value>
                <fullName>Inactive User</fullName>
            </value>
            <value>
                <fullName>Level One</fullName>
            </value>
            <value>
                <fullName>Level Two</fullName>
            </value>
            <value>
                <fullName>Level Three</fullName>
            </value>
            <value>
                <fullName>Treasurer</fullName>
            </value>
            <value>
                <fullName>Report Builder</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Season</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions (Season)</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactClass.cls
public without sharing class ContactClass {
  public String soql { get; set; }

  public ContactClass() {
    getSOQL();
  }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Contact.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    //expr = expr.removeEnd(', ');
    expr += 'RecordType.Name, Parent_Guardian__r.AccountId, Parent_Guardian__r.Name, Account.Name, Cohort__r.Name, Cohort__r.Session__r.Season__r.Id';

    soql = 'SELECT ' + expr + ' FROM Contact';
    return soql;
  }

  public List<Contact> getContactList() {
    getSOQL();
    List<Contact> contact_list = new List<Contact>();
    soql += ' ORDER BY LastName';
    contact_list = Database.query(soql);
    return contact_list;
  }

  public List<Contact> getContactPopupList(Id orgId) {
    List<Contact> contact_list = [
      SELECT
        Id,
        Account.Name,
        Name,
        Title,
        Role__c,
        Email,
        Phone,
        RecordType.Name
      FROM Contact
      WHERE AccountId = :orgId
      ORDER BY LastName
    ];
    return contact_list;
  }

  public List<Contact> getRelatedContactList(
    Id acctId,
    String recordType,
    String name,
    String soqlAND
  ) {
    String soql = 'SELECT Name, FirstName, LastName, Email, Phone, Title, Role__c, Extension__c, User_Profile__c, RecordType.Name, Account.Name, Account.RecordType.Name, Highest_Chapter_Completed__c';
    soql +=
      ' FROM Contact WHERE (AccountId = \'' +
      acctId +
      '\' OR Account.Local_Organization__c =  \'' +
      acctId +
      '\')';
    if (recordType != null && recordType != '')
      soql += ' AND RecordType.Name = \'' + recordType + '\'';
    if (name != null && name != '')
      soql += ' AND Name LIKE \'%' + name + '%\'';
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    soql += ' ORDER BY Name';
    system.debug('getRelatedContactList soql = ' + soql);
    List<Contact> contact_list = database.query(soql);
    return contact_list;
  }

  public Contact getContact(Id contactId) {
    getSOQL();
    Contact c = new Contact();
    if (contactId != null) {
      soql += ' WHERE Id = \'' + contactId + '\' LIMIT 1';
      Contact[] contacts = Database.query(soql);
      if (contacts.size() > 0) {
        c = contacts[0];
      }
    }
    return c;
  }

  public List<Contact> getDuplicateContact(Id acctId, Contact contact) {
    Contact[] dups = [
      SELECT Name
      FROM Contact
      WHERE
        (AccountId = :acctId
        OR Account.Local_Organization__c = :acctId)
        AND FirstName = :contact.FirstName
        AND LastName = :contact.LastName
        AND Gender__c = :contact.Gender__c
        AND Birth_Month__c = :contact.Birth_Month__c
        AND Birth_Year__c = :contact.Birth_Year__c
    ];
    return dups;
  }

  public void upsertContact(Contact contact) {
    try {
      upsert contact;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void upsertContactList(List<Contact> contactList) {
    system.debug('ContactClass upsertContactList contactList = ' + contactList);
    try {
      upsert contactList;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void deleteContact(Contact cont) {
    try {
      delete cont;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }
}