force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Lesson__c.field-meta.xml
<CustomField>
    <fullName>Lesson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lesson</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Lesson</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Program_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Program_Report_Status__c</fullName>
    <label>Program Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Season</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions (Season)</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <label>Meeting</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Season.recordType-meta.xml
<RecordType>
    <fullName>Season</fullName>
    <active>true</active>
    <label>Season</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/SessionClass.cls
public without sharing class SessionClass {
  public String expr { get; set; }
  public String soql { get; set; }

  public SessionClass(Id sessionId, String sType) {
  }

  public void getSOQL() {
    expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Session__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    //expr = expr.removeEnd(', ');
    expr += 'RecordType.Name, Site__r.Id, Site__r.Name, Season__r.Program_Report_Status__c, Session__r.Site__r.Id, Session__r.Season__r.Id, Session__r.Season__r.Name, Session__r.Name, Site__r.National_Organization__r.Id, Lesson__r.Name';

    soql = 'SELECT ' + expr + ' FROM Session__c';
  }

  public Session__c getSession(Id sessionId, Boolean includeAttachments) {
    if (sessionId != null) {
      getSOQL();
      String thisExpr = expr;
      if (includeAttachments) {
        expr += ' ,(SELECT Id, Name, Description FROM Attachments ORDER BY LastModifiedDate desc)';
      }
      String thisSOQL = 'SELECT ' + expr + ' FROM Session__c';
      thisSOQL += ' WHERE Id = \'' + sessionId + '\'';
      Session__c i = database.query(thisSOQL);
      return i;
    }
    return null;
  }

  public List<Session__c> getSessionList(Id sessionId, String sType) {
    if (sessionId != null) {
      getSOQL();
      if (sType == 'season') {
        soql += ' WHERE RecordType.Name = \'Season\'';
      } else if (sType == 'cohort') {
        soql += ' WHERE RecordType.Name = \'Cohort\'';
        if (sessionId != null)
          soql += ' AND Session__c = \'' + sessionId + '\'';
      } else if (sType == 'lesson') {
        soql += ' WHERE RecordType.Name = \'Lesson\'';
        if (sessionId != null)
          soql += ' AND Session__c = \'' + sessionId + '\'';
      } else if (sType == 'meeting') {
        soql += ' WHERE RecordType.Name = \'Meeting\'';
        if (sessionId != null)
          soql += ' AND Cohort__c = \'' + sessionId + '\'';
      } else {
        soql += ' WHERE RecordType.Name = \'Session\'';
        if (sessionId != null)
          soql += ' AND Season__c = \'' + sessionId + '\'';
      }
      system.debug('SessionClass getSessionList soql = ' + soql);
      List<Session__c> i = database.query(soql);
      return i;
    }
    return null;
  }

  public void upsertSession(Session__c i) {
    try {
      upsert i;
      system.debug('Session updated successfully: ' + i);
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public void deleteSession(Session__c i) {
    try {
      delete i;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }
}