force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/Victims_Served_Report__c.object-meta.xml
<CustomObject>
    <label>Victims Served Report</label>
    <nameField>
        <displayFormat>VS-{00000}</displayFormat>
        <label>Victims Served Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Victims Served Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Victims_Served_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Victims Served Reports</relationshipLabel>
    <relationshipName>Victims_Served_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revisions in Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <label>Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VictimsServedReportClass.cls
public without sharing class VictimsServedReportClass {
  public String getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Victims_Served_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    String soql = 'SELECT ' + expr + ' FROM Victims_Served_Report__c';
    return soql;
  }

  public Victims_Served_Report__c getReport(Id reportId) {
    String soql = getSoql();
    Victims_Served_Report__c report = new Victims_Served_Report__c();

    if (reportId != null)
      soql += ' WHERE Id = \'' + reportId + '\'';

    Victims_Served_Report__c[] reports = Database.query(soql);
    if (reports.size() == 1) {
      report = reports[0];
    }
    return report;
  }

  public List<Victims_Served_Report__c> getRelatedReportList(
    Id acctId,
    String userAcctType,
    String orgName,
    String soqlAND
  ) {
    String soql = 'SELECT Id, Name, Organization__c, Organization_Name__c, Year__c, Month__c, Status__c, Submitted_Date__c FROM Victims_Served_Report__c';
    if (orgName != null && orgName != '') {
      soql +=
        ' WHERE Organization_Name__c LIKE \'%' +
        String.escapeSingleQuotes(orgName) +
        '%\'';
    } else if (userAcctType == 'National Organization') {
      soql +=
        ' WHERE Organization__r.National_Organization__c = \'' +
        acctId +
        '\'';
    } else if (acctId != null) {
      soql += ' WHERE Organization__c = \'' + acctId + '\'';
    }
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    system.debug('Victims Served Report soql = ' + soql);

    List<Victims_Served_Report__c> reports = Database.query(soql);
    return reports;
  }

  public void upsertReport(Victims_Served_Report__c report) {
    try {
      upsert report;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}