force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Plan__c/TA_Plan__c.object-meta.xml
<CustomObject>
    <label>TA Plan</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TA Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TA Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TA_Plan__c/fields/Compliance_Score__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Score__c</fullName>
    <label>Compliance Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Score</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TA_Plan__c/fields/Finance_Score__c.field-meta.xml
<CustomField>
    <fullName>Finance_Score__c</fullName>
    <label>Finance Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Score</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TA_Plan__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TA Plans</relationshipLabel>
    <relationshipName>TA_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TA_Plan__c/fields/Program_Score__c.field-meta.xml
<CustomField>
    <fullName>Program_Score__c</fullName>
    <label>Program Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Score</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TAPlanClass.cls
public without sharing class TAPlanClass {
  public String getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.TA_Plan__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    String soql = 'SELECT ' + expr + ' FROM TA_Plan__c';
    return soql;
  }

  public TA_Plan__c getPlan(Id orgId, Id planId) {
    String soql = getSoql();
    TA_Plan__c plan = new TA_Plan__c();

    if (planId != null)
      soql += ' WHERE Id = \'' + planId + '\'';
    else if (orgId != null)
      soql += ' WHERE Organization__c = \'' + orgId + '\'';

    TA_Plan__c[] plans = Database.query(soql);
    if (plans.size() == 1) {
      plan = plans[0];
    }
    return plan;
  }

  public List<TA_Plan__c> getRelatedPlans(
    Id acctId,
    String userAcctType,
    String orgName,
    String soqlAND
  ) {
    String soql = 'SELECT Id, Name, Organization__c, Organization_Name__c, LastModifiedDate, Compliance_Score__c, Finance_Score__c, Program_Score__c FROM TA_Plan__c';
    if (orgName != null && orgName != '') {
      soql +=
        ' WHERE Organization_Name__c LIKE \'%' +
        String.escapeSingleQuotes(orgName) +
        '%\'';
    } else if (userAcctType == 'National Organization') {
      soql +=
        ' WHERE Organization__r.National_Organization__c = \'' +
        acctId +
        '\'';
    } else if (acctId != null) {
      soql += ' WHERE Organization__c = \'' + acctId + '\'';
    }
    if (soqlAND != null && soqlAND != '')
      soql += soqlAND;
    system.debug('TA Plan soql = ' + soql);

    List<TA_Plan__c> plans = Database.query(soql);
    return plans;
  }

  public void upsertPlan(TA_Plan__c plan) {
    try {
      upsert plan;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}