force-app/main/default/objects/Account/fields/National_Grants__c.field-meta.xml
<CustomField>
    <fullName>National_Grants__c</fullName>
    <label>National Grants</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OVC</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TA_Log__c/TA_Log__c.object-meta.xml
<CustomObject>
    <label>TA Log</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TA_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Flagged_for_Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Flagged_for_Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged for Follow-Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Follow_Up_TA_Log__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_TA_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow-Up TA Log</label>
    <referenceTo>TA_Log__c</referenceTo>
    <relationshipLabel>TA Logs (Follow-Up TA Log)</relationshipLabel>
    <relationshipName>Follow_Up_TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Is_Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Is_Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Follow Up?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Original_TA_Log__c.field-meta.xml
<CustomField>
    <fullName>Original_TA_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original TA Log</label>
    <referenceTo>TA_Log__c</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/TA_By__c.field-meta.xml
<CustomField>
    <fullName>TA_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TA By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TA Logs</relationshipLabel>
    <relationshipName>TA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Log__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Performance Measures Reporting</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Program Design</fullName>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
            <value>
                <fullName>Statement of Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TALogClass.cls
public without sharing class TALogClass {
  public TA_Log__c selectedLog { get; set; }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.TA_Log__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    String soql = 'SELECT ' + expr + ' FROM TA_Log__c';
    return soql;
  }

  public TA_Log__c getTALog(Id logId) {
    String soql = getSOQL();
    newTALog(null, null);
    TA_Log__c log = selectedLog;
    if (logId != null) {
      soql += ' WHERE Id = \'' + logId + '\'';
      TA_Log__c[] logs = Database.query(soql);
      if (logs.size() > 0) {
        log = logs[0];
      }
    }
    return log;
  }

  public List<TA_Log__c> getTALogs(
    Id orgId,
    Boolean followUpOnly,
    Integer listLimit,
    String userProfile,
    String soqlAND
  ) {
    String soql = getSOQL();
    soql += ' WHERE Date__c != null';
    if (orgId != null)
      soql += ' AND Organization__c = \'' + orgId + '\'';
    if (followUpOnly == true)
      soql += ' AND Flagged_for_Follow_Up__c = true';
    if (userProfile.contains('TRAIL'))
      soql += ' AND Organization__r.National_Grants__c INCLUDES (\'TRAIL\')';
    else if (userProfile.contains('OVC'))
      soql += ' AND Organization__r.National_Grants__c INCLUDES (\'OVC\')';
    if (soqlAND != null)
      soql += soqlAND;
    system.debug('>>>> TALogClass getTALogs soqlAND = ' + soqlAND);
    soql += ' ORDER BY Date__c desc';
    if (listLimit != null)
      soql += ' LIMIT ' + listLimit;
    system.debug('>>>> TALogClass getTALogs soql = ' + soql);

    List<TA_Log__c> logs = new List<TA_Log__c>();
    logs = Database.query(soql);
    return logs;
  }

  public void upsertTALog(TA_Log__c log, Id contactId) {
    if (log.TA_By__c == null && contactId != null)
      log.TA_By__c = contactId;
    try {
      system.debug('upsertTALog log = ' + log);
      upsert log;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
    if (log.Original_TA_Log__c != null) {
      TA_Log__c original = getTALog(log.Original_TA_Log__c);
      original.Flagged_for_Follow_Up__c = false;
      original.Follow_Up_TA_Log__c = log.Id;
      try {
        system.debug('upsertTALog original = ' + original);
        upsert original;
      } catch (Exception e) {
        system.debug('error = ' + e.getMessage());
        ApexPages.addMessage(
          new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
        );
      }
    }
  }

  public void newTALog(Id selectedLogId, Id siteId) {
    if (selectedLogId != null)
      selectedLog = getTALog(selectedLogId);
    else {
      User u = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
      selectedLog = new TA_Log__c(Date__c = date.today());
      if (siteId != null)
        selectedLog.Organization__c = siteId;
      if (u != null)
        selectedLog.TA_By__c = u.ContactId;
    }
  }

  public void newTAFollowUp(Id selectedLogId, Id siteId) {
    TA_Log__c original = new TA_Log__c();
    if (selectedLogId != null) {
      original = getTALog(selectedLogId);
      if (siteId == null)
        siteId = original.Organization__c;
    }
    selectedLog = new TA_Log__c(
      Organization__c = siteId,
      Date__c = date.today()
    );
    if (original.Id != null)
      selectedLog.Original_TA_Log__c = original.Id;
    selectedLog.Topic__c = original.Topic__c;
    selectedLog.Is_Follow_Up__c = true;
  }
}