force-app/main/default/objects/Account/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>National Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Local Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Organization__c.field-meta.xml
<CustomField>
    <fullName>National_Organization__c</fullName>
    <formula>National_Grant__r.Account__r.Name</formula>
    <label>National Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Requests: Total Approved Amount where Status = Approved, Paid, Closed</inlineHelpText>
    <label>Reimbursement Approved Amount</label>
    <summarizedField
  >Reimbursement_Request__c.Total_Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Requested_Amount__c</fullName>
    <formula
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c</inlineHelpText>
    <label>Total Reimbursement Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Budgeted__c.field-meta.xml
<CustomField>
    <fullName>Total_Budgeted__c</fullName>
    <formula>IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;,
Total_Item_Budget__c + Total_Fringe_Benefits__c +
IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), Indirect_Rate_Amount__c, 0),
Total_Indirect_Rate_Budgeted__c + IF(AND(NOT(ISPICKVAL(Grant_Status__c, &apos;Approved&apos;)), NOT(ISPICKVAL(Grant_Status__c, &apos;Closed&apos;))), Total_New_Item_Budget__c,Total_Item_Budget__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >if Org = BBBSA: Total_Item_Budget__c + Total_Fringe_Benefits__c +  Indirect_Rate_Amount__c.
else: Total_Item_Budget__c +  Total_Indirect_Rate_Budgeted__c)</inlineHelpText>
    <label>Total Budgeted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Item_Balance__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Balance__c</fullName>
    <formula>Total_Item_Budget__c - Reimbursement_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Total_Item_Budget__c - Reimbursement_Approved_Amount__c</inlineHelpText>
    <label>Total Item Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Budget__c</fullName>
    <inlineHelpText>Roll-Up Summary of Budget Item: Item Budget</inlineHelpText>
    <label>Total Item Budget</label>
    <summarizedField>Budget_Item__c.Item_Budget__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/SubGrantListCtrl.cls
public with sharing class SubGrantListCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }
  public String approverLevel { get; set; }

  private GrantClass grantClass = new GrantClass();
  public ID NPALGrantID { get; set; }
  public ID GrantID { get; set; }
  public ID SubGrantID { get; set; }
  public List<Grant__c> nationalGrant_list { get; set; }
  public List<Grant__c> grant_list { get; set; }
  public List<Grant__c> incomplete_list { get; set; }
  public List<Grant__c> pending_list { get; set; }
  public List<Grant__c> approved_list { get; set; }
  public Boolean more_incomplete { get; set; }
  public Boolean more_pending { get; set; }
  public Boolean more_approved { get; set; }

  public String listType { get; set; }
  public Integer listLimit { get; set; }
  public String keyword { get; set; }
  public String sortBy { get; set; }
  public List<SelectOption> sortByOptions { get; set; }
  public String errorMessage { get; set; }

  public SubGrantListCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    approverLevel = userClass.approverLevel;
    portalName = userClass.userProfile;

    GrantId = ApexPages.currentPage().getParameters().get('GrantId');
    nationalGrant_list = new List<Grant__c>();
    grant_list = new List<Grant__c>();
    incomplete_list = new List<Grant__c>();
    pending_list = new List<Grant__c>();
    approved_list = new List<Grant__c>();

    listType = ApexPages.currentPage().getParameters().get('type');
    if (listType == '' || listType == null) {
      listType = '';
      listLimit = 10;
    } else {
      listLimit = 1000;
    }

    keyword = '';
    sortBy = '';
    sortByOptions = new List<SelectOption>();
    sortByOptions.add(new SelectOption('Name', 'Name'));
    sortByOptions.add(new SelectOption('Amount__c', 'Awarded'));
    sortByOptions.add(new SelectOption('Total_Budgeted__c', 'Total Budgeted'));
    sortByOptions.add(
      new SelectOption('Reimbursement_Requested_Amount__c', 'Requested Amount')
    );
    sortByOptions.add(
      new SelectOption('Reimbursement_Approved_Amount__c', 'Approved Amount')
    );
    sortByOptions.add(new SelectOption('Balance__c', 'Balance'));
    sortByOptions.add(new SelectOption('Grant_Status__c', 'Status'));

    /*
        if(portalName == 'NPAL') {
            Grant__c[] grants = [SELECT Id FROM Grant__c WHERE Account__r.Name = 'National PAL' AND RecordType.Name = 'Grant'];
            if(grants.size() > 0) NPALGrantID = grants[0].Id;
        }
        */
  }

  public void getLists() {
    grant_list.clear();

    String qry = 'SELECT Id, RecordType.Name, Name, Account__r.Id, Account__r.Name, Account__r.National_Organization__c, National_Grant__r.Account__c';
    qry += ', Start_Date__c, End_Date__c, LastModifiedDate, Amount__c, Total_Budgeted__c, Total_Item_Budget__c, Total_Item_Balance__c, Reimbursement_Requested_Amount__c, Reimbursement_Approved_Amount__c, Balance__c, Grant_Status__c';
    qry += ' FROM Grant__c WHERE RecordType.Name = \'Sub-Grant\'';
    if (listType == 'pending') {
      qry += ' AND (Grant_Status__c = \'Pending Review\' OR Grant_Status__c = \'Budget Submitted\')';
    }
    if (sortBy != '') {
      qry += ' ORDER BY ' + sortBy + ' ASC';
    }

    for (Grant__c g : Database.query(qry)) {
      if (userAcctType == 'National Organization') {
        if (g.Account__r.ID == userAcct.Id) {
          nationalGrant_list.add(g);
        }
        if (
          g.Account__r.National_Organization__c == userAcct.Id ||
          g.Account__c == userAcct.Id
        ) {
          if (g.National_Grant__r.Account__c == g.Account__c) {
            if (GrantId == null || g.National_Grant__r.Id == GrantID) {
              if (
                approverLevel == 'Level Two Admin' ||
                approverLevel == 'Level Three'
              ) {
                grant_list.add(g);
              }
            }
          } else if (GrantId != null) {
            if (g.National_Grant__r.Id == GrantID) {
              grant_list.add(g);
            }
          } else if (GrantId == null) {
            grant_list.add(g);
          }
        }
      } else if (g.Account__r.Id == userAcct.Id) {
        if (GrantId != null && g.National_Grant__r.Id == GrantID) {
          grant_list.add(g);
        } else if (GrantId == null) {
          grant_list.add(g);
        }
      }
    }

    if (keyword != null) {
      Integer i = 0;
      while (i < grant_list.size()) {
        String name = grant_list.get(i).Name;
        if (
          !name.toLowerCase().contains(String.valueOf(keyword).toLowerCase())
        ) {
          grant_list.remove(i);
        } else {
          i++;
        }
      }
    }
  }

  public void getRelatedGrants() {
    incomplete_list.clear();
    pending_list.clear();
    approved_list.clear();
    more_incomplete = false;
    more_pending = false;
    more_approved = false;

    for (
      Grant__c g : grantClass.getRelatedSubGrants(
        userAcct.Id,
        null,
        '',
        sortBy,
        '',
        keyword,
        null
      )
    ) {
      String status = '';
      if (g.Grant_Status__c != null)
        status = g.Grant_Status__c;

      if (
        status == '' ||
        status.contains('Incomplete') ||
        status == 'Revisions Needed'
      ) {
        if (incomplete_list.size() < listLimit) {
          incomplete_list.add(g);
        } else {
          more_incomplete = true;
        }
      } else if (status.contains('Approval')) {
        if (userAcctType != 'National Organization')
          g.Grant_Status__c = 'Pending Approval';
        if (pending_list.size() < listLimit) {
          pending_list.add(g);
        } else {
          more_pending = true;
        }
      } else if (status == 'Approved') {
        if (approved_list.size() < listLimit) {
          approved_list.add(g);
        } else {
          more_approved = true;
        }
      }
    }
  }
}