force-app/main/default/objects/Account/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Total Number of Mentors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Accomplishments_this_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accomplishments_this_Reporting_Period__c</fullName>
    <label>Accomplishments this Reporting Period</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Assistance_Needed__c.field-meta.xml
<CustomField>
    <fullName>Assistance_Needed__c</fullName>
    <label>Assistance Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Assistance_Needed_Details__c.field-meta.xml
<CustomField>
    <fullName>Assistance_Needed_Details__c</fullName>
    <label>Assistance Needed Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Curriculum_Used__c.field-meta.xml
<CustomField>
    <fullName>Curriculum_Used__c</fullName>
    <label>Curriculum Used</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NPAL/ Digital Harbor Technology</fullName>
            </value>
            <value>
                <fullName
        >McGruff Club- National Crime Prevention Council</fullName>
                <label>McGruff Club- National Crime Prevention Council</label>
            </value>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>NPAL Cambridge Self-Advocacy</fullName>
            </value>
            <value>
                <fullName>Innovation 4.0</fullName>
            </value>
            <value>
                <fullName>DEA</fullName>
            </value>
            <value>
                <fullName>Unfinished Business</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <formula>TEXT(Grant__r.Grant_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Increase_in_Perception_of_Social_Support__c.field-meta.xml
<CustomField>
    <fullName>Increase_in_Perception_of_Social_Support__c</fullName>
    <label>Increase in Perception of Social Support</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Innovative_Programs_Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Innovative_Programs_Accomplishments__c</fullName>
    <label>Innovative Programs Accomplishments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Is_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Is_Overdue__c</fullName>
    <formula>AND(
TODAY() &gt; Due_Date__c,
NOT(ISPICKVAL(Status__c, &apos;Submitted&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Approved&apos;))
)</formula>
    <label>Is Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Major_Activities_Planned__c.field-meta.xml
<CustomField>
    <fullName>Major_Activities_Planned__c</fullName>
    <label>Major Activities Planned</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Mentor_Training_Survey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Training_Survey_Completed__c</fullName>
    <label>Mentor Training Survey Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Needs_Attention__c.field-meta.xml
<CustomField>
    <fullName>Needs_Attention__c</fullName>
    <formula>OR(
ISPICKVAL(Problems_Barriers_Encountered__c, &apos;Yes&apos;),
ISPICKVAL(Assistance_Needed__c, &apos;Yes&apos;),
ISPICKVAL(On_Track_to_Complete_Program__c, &apos;No&apos;) 
)</formula>
    <label>Needs Attention</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_of_Mentors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors__c</fullName>
    <label>Number of Mentors</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_of_Mentors_Completed_Training__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors_Completed_Training__c</fullName>
    <label>Number of Mentors Completed Training</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_of_Mentors_Left_Program__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Mentors_Left_Program__c</fullName>
    <label>Number of Mentors Left Program</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Number_of_New_Mentors_this_Month__c.field-meta.xml
<CustomField>
    <fullName>Number_of_New_Mentors_this_Month__c</fullName>
    <label>Number of New Mentors this Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/On_Track_to_Complete_Program__c.field-meta.xml
<CustomField>
    <fullName>On_Track_to_Complete_Program__c</fullName>
    <label>On Track to Complete Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/On_Track_to_Complete_Program_Details__c.field-meta.xml
<CustomField>
    <fullName>On_Track_to_Complete_Program_Details__c</fullName>
    <label>On Track to Complete Program Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <formula>Organization__r.Name</formula>
    <label>Organization Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Problems_Barriers_Encountered__c.field-meta.xml
<CustomField>
    <fullName>Problems_Barriers_Encountered__c</fullName>
    <label>Problems/Barriers Encountered</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Problems_Barriers_Encountered_Details__c.field-meta.xml
<CustomField>
    <fullName>Problems_Barriers_Encountered_Details__c</fullName>
    <label>Problems/Barriers Encountered Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Sent_Back_By__c.field-meta.xml
<CustomField>
    <fullName>Sent_Back_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sent Back By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Progress Reports (Sent Back By)</relationshipLabel>
    <relationshipName>Progress_Reports1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Updated_Youth_Data__c.field-meta.xml
<CustomField>
    <fullName>Updated_Youth_Data__c</fullName>
    <label>Updated Youth Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_or_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Youth_Participated_Less_Than_4_Hours__c.field-meta.xml
<CustomField>
    <fullName>Youth_Participated_Less_Than_4_Hours__c</fullName>
    <label>Youth Participated Less Than 4 Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Youth_Participated_More_Than_4_Hours__c.field-meta.xml
<CustomField>
    <fullName>Youth_Participated_More_Than_4_Hours__c</fullName>
    <label>Youth Participated More Than 4 Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Youth_Who_Offend__c.field-meta.xml
<CustomField>
    <fullName>Youth_Who_Offend__c</fullName>
    <label>Youth Who Offend</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MonthlyProgressReportCtrl.cls
public without sharing class MonthlyProgressReportCtrl {
  /*
    private UserClass userClass = new UserClass();
    public User currentUser { get; set; }
    public Account userAcct { get; set; }
    public String userAcctType { get; set; }
    
    private ProgressReportClass prc = new ProgressReportClass();
    private PaginationClass pc = new PaginationClass();
    
    public Id orgId { get; set; }
    public List<Progress_Report__c> allReports { get; set; }
    public List<Progress_Report__c> reports { get; set; }
    public Progress_Report__c report { get; set; }
    public List<Attachment> atts { get; set; }
    
    public String orgName { get; set; }
    public String reportId { get; set; }
    public String grantStatus { get; set; }
    public String month { get; set; }
    public List<SelectOption> monthOptions { get; set; }
    public Integer year { get; set; }
    public List<SelectOption> yearOptions { get; set; }
    public String status { get; set; }
    public List<SelectOption> statusOptions { get; set; }
    public String sortBy { get; set; }
    public List<SelectOption> sortByOptions { get; set; }
    
    public Boolean showOnlyNeedsAttention { get; set; }
    public Boolean showOnlyOverdue { get; set; }
    
    public Boolean displayAttPopup { get; set; }
    public Boolean displaySendBackPopup { get; set; }
    public String errorMessage { get; set; }
    public String successMessage { get; set; }
    
    Integer counter = 0;
    Integer limitSize = 40; 
    Integer totalSize = 0;
    public String recordCount { get; set;}
    public Boolean disablePrevious { get; set; }
    public Boolean disableNext { get; set; }
    
    public MonthlyProgressReportCtrl() {
        currentUser = userClass.currentUser;
        userAcct = userClass.userAcct;
        userAcctType = userClass.userAcctType;
        
        month = ApexPages.currentPage().getParameters().get('month'); 
        grantStatus = ApexPages.currentPage().getParameters().get('grantStatus'); 
        status = ApexPages.currentPage().getParameters().get('status'); 
        
        showOnlyNeedsAttention = false;
        showOnlyOverdue = false;
        String overdueUrl = ApexPages.currentPage().getParameters().get('overdue'); 
        if(overdueUrl == 'true') showOnlyOverdue = true;
        
        allReports = new List<Progress_Report__c>();
        reports = new List<Progress_Report__c>();
        report = new Progress_Report__c();
        atts = new List<Attachment>();
    }
    
    public void getOptions() {
        orgId = null;
        if(userAcctType == 'Site') orgId = userAcct.Id;
        String urlOrgId = ApexPages.currentPage().getParameters().get('orgId'); 
        if(urlOrgId != '' && urlOrgId != null) {
            if(Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}').matcher(urlOrgId).matches() ){
                orgId = Id.valueOf(urlOrgId);
            }
        }
        
        Date dt = date.today();
        monthOptions = new List<SelectOption>();
        monthOptions.add(new SelectOption('', 'View All'));
        Schema.DescribeFieldResult fieldResult1 = Progress_Report__c.Month__c.getDescribe();
        for(Schema.PicklistEntry f : fieldResult1.getPicklistValues()) monthOptions.add(new SelectOption(f.getLabel(), f.getValue()));
        
        yearOptions = new List<SelectOption>();
        yearOptions.add(new SelectOption('', 'View All'));
        Schema.DescribeFieldResult fieldResult2 = Progress_Report__c.Year__c.getDescribe();
        for(Schema.PicklistEntry f : fieldResult2.getPicklistValues()) yearOptions.add(new SelectOption(f.getLabel(), f.getValue()));
        year = dt.year();
        
        statusOptions = new List<SelectOption>();
        statusOptions.add(new SelectOption('All Reports', 'View All'));
        Schema.DescribeFieldResult fieldResult3 = Progress_Report__c.Status__c.getDescribe();
        for(Schema.PicklistEntry f : fieldResult3.getPicklistValues()) statusOptions.add(new SelectOption(f.getLabel(), f.getValue()));
        if(status == '' || status == null) status = 'All Reports';
            
        sortByOptions = new List<SelectOption>();
        sortByOptions.add(new SelectOption('Name','Report Id'));
        if(userAcctType != 'Site') sortByOptions.add(new SelectOption('Organization_Name__c','Organization'));
        sortByOptions.add(new SelectOption('Status__c','Status'));
        sortByOptions.add(new SelectOption('Submitted_Date__c', 'Submitted Date'));
        sortBy = 'Name';
        
        getLists();
    }
    
    public void getLists() {
        String soqlAND = '';
        if(showOnlyOverdue) soqlAND += ' AND Is_Overdue__c = true';
        if(showOnlyNeedsAttention) soqlAND += ' AND Needs_Attention__c = true';
        if(grantStatus == 'Closed') soqlAND += ' AND Grant_Status__c = \'Closed\'';
        else soqlAND += ' AND Grant_Status__c != \'Closed\'';
        allReports = prc.getRelatedReportList(userAcct.Id, orgId, userAcctType, orgName, reportId, month, year, status, sortBy, soqlAND);
        totalSize = allReports.size();
        first();
    }
    
    public void getReport() {
        String urlReportId = ApexPages.currentPage().getParameters().get('reportId'); 
        if(urlReportId != '' && urlReportId != null) {
            if(Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}').matcher(urlReportId).matches() ){
                reportId = Id.valueOf(urlReportId);
            }
        }
        report = prc.getReport(reportId, null, null);
        report.Previous_Status__c = report.Status__c;
        getAtts();
    }
    
    public void getAtts() {
        Id rId;
        if(report.Id != null) rId = report.Id;
        else if(reportId != null) rId = reportId;
        atts = [SELECT Id, Name FROM Attachment WHERE ParentId = :report.Id ORDER BY CreatedDate desc LIMIT 1];
    }
    
    public void edit() {
        report.Status__c = 'In Progress';
        prc.upsertReport(report);
    }
    
    // BEGIN fieldValidation
    public void fieldValidation() {
        errorMessage = '';
        //report.Curriculum_Used__c == null ||
        if(report.Updated_Youth_Data__c == null) errorMessage += 'Question 1 is Required <br />';
        if(report.Number_of_Mentors__c == null) errorMessage += 'Question 4 is Required <br />';
        if(report.Number_of_Mentors_Left_Program__c == null) errorMessage += 'Question 5 is Required <br />';
        if(report.Number_of_New_Mentors_this_Month__c == null) errorMessage += 'Question 6 is Required <br />';
        if(report.Number_of_Mentors_Completed_Training__c == null) errorMessage += 'Question 7 is Required <br />';
        if(report.Mentor_Training_Survey_Completed__c == null) errorMessage += 'Question 8 is Required <br />';
        if(report.Accomplishments_this_Reporting_Period__c == null) errorMessage += 'Question 9 is Required <br />';
        if(report.Problems_Barriers_Encountered__c == null) errorMessage += 'Question 10 is Required <br />';
        if(report.Problems_Barriers_Encountered__c == 'Yes' && report.Problems_Barriers_Encountered_Details__c == null) errorMessage += 'Question 10a is Required <br />';
        if(report.Assistance_Needed__c == null) errorMessage += 'Question 11 is Required <br />';
        if(report.Assistance_Needed__c == 'Yes' && report.Assistance_Needed_Details__c == null) errorMessage += 'Question 11a is Required <br />';
        if(report.On_Track_to_Complete_Program__c == null) errorMessage += 'Question 12 is Required <br />';
        if(report.On_Track_to_Complete_Program__c == 'No' && report.On_Track_to_Complete_Program_Details__c == null) errorMessage += 'Question 12a is Required <br />';
        if(report.Major_Activities_Planned__c == null) errorMessage += 'Question 13 is Required <br />';
        if(report.Innovative_Programs_Accomplishments__c == null) errorMessage += 'Question 14 is Required <br />';
        if(report.Month__c == 'June' || report.Month__c == 'December') {
            if(report.Youth_Participated_More_Than_4_Hours__c == null) errorMessage += 'Question 15 is Required <br />';
            if(report.Youth_Participated_Less_Than_4_Hours__c == null) errorMessage += 'Question 16 is Required <br />';
            if(report.Increase_in_Perception_of_Social_Support__c == null) errorMessage += 'Question 17 is Required <br />';
            if(report.Youth_Who_Offend__c == null) errorMessage += 'Question 18 is Required <br />';
        }
        if(atts.size() == 0) errorMessage += 'Attendance Report is Required';
        if(errorMessage != '') successMessage = '';
    }
    // END fieldValidation
    
    public void save() {
        if(report.Status__c == 'Not Started') report.Status__c = 'In Progress';
        prc.upsertReport(report);
        if(ApexPages.hasMessages()) errorMessage += string.valueOf(ApexPages.getMessages());
        else successMessage = 'Save successful.';
    }
    
    public PageReference submit() {
        fieldValidation();
        if(errorMessage != '') return null;
        
        report.Status__c = 'Submitted';
        report.Submitted_By__c = currentUser.ContactId;
        report.Submitted_Date__c = date.today();
        report.Modification_History__c = getModHist('Submitted');
        prc.upsertReport(report);
        if(ApexPages.hasMessages()) return null;
        
        PageReference pr = new PageReference('/MonthlyProgressReports');
        pr.setRedirect(True);
        return pr;
    }
    
    public PageReference sendBack() {
        report.Status__c = 'Revisions Needed';
        report.Sent_Back_By__c = currentUser.ContactId;
        report.Modification_History__c = getModHist('Sent Back');
        prc.upsertReport(report);
        if(ApexPages.hasMessages()) return null;
        
        PageReference pr = new PageReference('/MonthlyProgressReports');
        pr.setRedirect(True);
        return pr;
    }
    
    // BEGIN modHist
    public String getModHist(String status) {
        Date dt = date.today();
        String fdt = dt.format();
        String modHist = fdt + ': Report '+ status +' by ' + currentUser.Contact.Name + ' (' + currentUser.Id + ')';
        if(modHist != '') {
            if(report.Modification_History__c == null) {
                report.Modification_History__c = modHist;
            } else {
                report.Modification_History__c += ' \r\n' + modHist;
            }
        }
        return modHist;
    }
    // END modHist
    
    // BEGIN popups
    public void showAttPopup() {
        displayAttPopup = true;
    }
    public void hideAttPopup() {
        displayAttPopup = false;
        getAtts();
    }
    
    public void showSendBackPopup() {
        displaySendBackPopup = true;
    }
    public void hideSendBackPopup() {
        displaySendBackPopup = false;
    }
    // END popups
    
    // BEGIN Pagination
    public void first() {
        counter = 0;
        reports = pc.first(allReports, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = true;
        disableNext = pc.getDisableNext(counter, limitSize, totalSize);
    }
    
    public void next() {
        counter = counter + limitSize;
        reports = pc.next(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = false;
        disableNext = pc.getDisableNext(counter, limitSize, totalSize);
    }
    
    public void previous() {
        counter = counter - limitSize;       
        reports = pc.previous(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = pc.getDisablePrevious(counter);
        disableNext = false;
    }

    public void last() {
        counter = pc.getLastCounter(counter, limitSize, totalSize);
        reports = pc.last(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = false;
        disableNext = true;
    }
    // END Pagination
	*/
}