force-app/main/default/objects/Account/fields/Number_of_Cohorts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cohorts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Cohorts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Today__c.field-meta.xml
<CustomField>
    <fullName>Today__c</fullName>
    <label>Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/TestTriggers.cls
@istest
class TestTriggers {
  /*
    static testmethod void test() {
system.Test.startTest();
        
        Account a = new Account();
        a.Name = 'Today Test';
        insert a;
        
        Contact c = new Contact(
            accountId = a.Id
            ,lastName = 'Contact'
            ,firstName = 'Test1'
            ,Email = 'newtest1@example.com'
        );
        insert c;
        
        Session__c s = new Session__c(
            Name = 'Test Session'
            ,Site__c = a.Id
            ,RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName().get('Session').getRecordTypeId()
        );
        insert s;
        
        Session__c co = new Session__c(
            Name = 'Test Cohort'
            ,Site__c = a.Id
            ,Session__c = s.Id
            ,RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName().get('Cohort').getRecordTypeId()
        );
        insert co;
        
        c.Cohort__c = co.Id;
        update c;
        delete c;
            
        Decimal d = 0;
        Account[] accts = [SELECT Number_of_Cohorts__c FROM Account WHERE Id = :a.Id];
        if(accts.size() > 0) {
            d = accts[0].Number_of_Cohorts__c;
        }
        system.debug('decimal = ' + d);
        //System.assertEquals(1, d);
        
        // Schedule the test job
        String jobId = System.schedule('testBasicScheduledApex', DailyDateUpdate.CRON_EXP, new DailyDateUpdate());
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(DailyDateUpdate.CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run
        Date dt = date.today();
        Date t = dt.addDays(1);
        System.assertEquals(string.valueOf(t) + ' 00:00:00', String.valueOf(ct.NextFireTime));
        System.assertNotEquals(dt,
                               [SELECT id, Today__c FROM account WHERE id = :a.id].Today__c);
        
        system.Test.stopTest();
        
        System.assertEquals(dt,
                            [SELECT Id, Today__c FROM Account WHERE Id = :a.Id].Today__c);
        
    }
	*/
}