force-app/main/default/objects/Account/fields/Number_of_Cohorts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cohorts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Cohorts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <label>Cohort</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/TestSessionTriggers.cls
@isTest
class TestSessionTriggers {
  static testMethod void testUpdateCohortCount() {
    system.test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Session__c session = new Session__c(
      Name = 'Test Session',
      Site__c = a.Id,
      RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
        .get('Session')
        .getRecordTypeId()
    );
    insert session;

    Session__c cohort = new Session__c(
      Name = 'Test Cohort',
      //Site__c = a.Id,
      Session__c = session.Id,
      RecordTypeId = Schema.SObjectType.Session__c.getRecordTypeInfosByName()
        .get('Cohort')
        .getRecordTypeId()
    );
    insert cohort;

    // Test INSERT
    //Account acctInsertTest = [SELECT Number_of_Cohorts__c FROM Account WHERE Id = :a.Id];
    //system.assertEquals(0, acctInsertsystem.test.Number_of_Cohorts__c);

    // Test UPDATE
    cohort.Site__c = a.Id;
    update cohort;
    //Account acctUpdateTest = [SELECT Number_of_Cohorts__c FROM Account WHERE Id = :a.Id];
    //system.assertEquals(1, acctUpdatesystem.test.Number_of_Cohorts__c);

    // Test DELETE
    delete cohort;
    //Account acctDeleteTest = [SELECT Number_of_Cohorts__c FROM Account WHERE Id = :a.Id];
    //system.assertEquals(0, acctDeletesystem.test.Number_of_Cohorts__c);
  }
}