force-app/main/default/objects/Account/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Session__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Season</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions (Season)</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Season_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_End_Date__c</fullName>
    <label>Season End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Season_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Season_Start_Date__c</fullName>
    <label>Season Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/recordTypes/Season.recordType-meta.xml
<RecordType>
    <fullName>Season</fullName>
    <active>true</active>
    <label>Season</label>
</RecordType>

force-app/main/default/objects/Session__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/SessionSelectOptionsCtrl.cls
public with sharing class SessionSelectOptionsCtrl {
  public UserClass userClass = new UserClass();
  public String userAcctType = userClass.userAcctType;
  public List<SelectOption> options { get; set; }
  public String sessionId { get; set; }

  public SessionSelectOptionsCtrl() {
    options = new List<SelectOption>();
    //Date dt = date.today();
    String soql = 'SELECT Id, Name, Season__r.Name FROM Session__c';

    if (userAcctType != null && userAcctType.contains('National')) {
      options.add(new SelectOption('', 'Select a Season'));
      soql += ' WHERE RecordType.Name = \'Season\'';
      soql += ' ORDER BY LastModifiedDate desc';
      for (Session__c s : database.query(soql)) {
        options.add(new SelectOption(s.Id, s.Name));
      }
    } else {
      options.add(new SelectOption('', 'Select a Session'));
      soql += ' WHERE RecordType.Name = \'Session\'';
      soql += ' AND Site__r.Id = \'' + userClass.userAcct.Id + '\'';
      soql += ' ORDER BY LastModifiedDate desc';
      for (Session__c s : database.query(soql)) {
        options.add(new SelectOption(s.Id, s.Season__r.Name + ': ' + s.Name));
      }

      //soql += ' AND Season__r.Season_Start_Date__c <= ' + string.valueOf(dt);
      //soql += ' AND Season__r.Season_End_Date__c >= ' + string.valueOf(dt);
    }

    system.debug('SessionSelectOptionsCtrl options = ' + options);
    if (options.size() > 1) {
      String i = options[1].getValue();
      SessionId = Id.valueOf(i);
    }
  }
}