force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Grantee_Report__c/Grantee_Report__c.object-meta.xml
<CustomObject>
    <label>DCTAT Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Grantee Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCTAT Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grantee_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipName>Grantee_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DCTAT Reports</relationshipLabel>
    <relationshipName>DCTAT_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grantee_Report__c/fields/Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Report_Status__c</fullName>
    <label>Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Sent Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <formula>TEXT(Grant__r.Grant_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/recordTypes/Monthly.recordType-meta.xml
<RecordType>
    <fullName>Monthly</fullName>
    <active>true</active>
    <label>Monthly</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <formula>Grant__r.Account__r.Name</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDashboards.cls
@isTest
public class TestDashboards {
  static testMethod void test() {
    system.test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Grant__c g1 = new Grant__c(
      Account__c = a.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId(),
      Grant_Status__c = 'Pending First Approval'
    );
    insert g1;

    Grant__c g2 = new Grant__c(
      Account__c = a.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId(),
      Grant_Status__c = 'Pending Second Approval'
    );
    insert g2;

    Grant__c g3 = new Grant__c(
      Account__c = a.Id,
      RecordTypeId = Schema.SObjectType.Grant__c.getRecordTypeInfosByName()
        .get('Sub-Grant')
        .getRecordTypeId(),
      Grant_Status__c = 'Pending Third Approval'
    );
    insert g3;

    Reimbursement_Request__c rr1 = new Reimbursement_Request__c(
      Grant__c = g1.Id,
      Status__c = 'Pending First Approval'
    );
    insert rr1;

    Reimbursement_Request__c rr2 = new Reimbursement_Request__c(
      Grant__c = g1.Id,
      Status__c = 'Pending Second Approval'
    );
    insert rr2;

    Reimbursement_Request__c rr3 = new Reimbursement_Request__c(
      Grant__c = g1.Id,
      Status__c = 'Pending Third Approval'
    );
    insert rr3;

    Session_Report__c r1 = new Session_Report__c(Site__c = a.Id);
    insert r1;

    Session_Report__c r2 = new Session_Report__c(
      Site__c = a.Id,
      Status__c = 'Submitted'
    );
    insert r2;

    Progress_Report__c pg1 = new Progress_Report__c(
      Organization__c = a.Id,
      Grant__c = g1.Id,
      Status__c = 'Revisions Needed'
    );
    insert pg1;

    Progress_Report__c pg2 = new Progress_Report__c(
      Organization__c = a.Id,
      Grant__c = g1.Id,
      Status__c = 'Submitted'
    );
    insert pg2;

    Program_Report__c pr1 = new Program_Report__c(
      RecordTypeId = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
        .get('Monthly PA Logs')
        .getRecordTypeId(),
      Name = 'Test PA Logs',
      Grant__c = g1.Id,
      Site__c = a.Id,
      Status__c = 'Not Started'
    );
    insert pr1;

    Program_Report__c pr2 = new Program_Report__c(
      RecordTypeId = Schema.SObjectType.Program_Report__c.getRecordTypeInfosByName()
        .get('Monthly PA Logs')
        .getRecordTypeId(),
      Name = 'Test PA Logs',
      Grant__c = g1.Id,
      Site__c = a.Id,
      Status__c = 'Submitted'
    );
    insert pr2;

    Grantee_Report__c gr1 = new Grantee_Report__c(
      Grant__c = g1.Id,
      Report_Status__c = 'In Progress'
    );
    insert gr1;

    Grantee_Report__c gr2 = new Grantee_Report__c(
      Grant__c = g1.Id,
      Report_Status__c = 'Submitted'
    );
    insert gr2;

    Profile p1 = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level One'];
    Contact c1 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com'
    );
    insert c1;
    User u1 = new User(
      Alias = 'testu',
      Email = 'test1@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p1.Id,
      UserName = 'levelone@test1.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;
    System.runAs(u1) {
      system.test.setCurrentPageReference(new PageReference('Page.Dashboard'));
      DashboardCtrl ctrl1 = new DashboardCtrl();
      ctrl1.getLists();
    }

    Profile p2 = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Two'];
    Contact c2 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test2',
      Email = 'newtest2@example.com'
    );
    insert c2;
    User u2 = new User(
      Alias = 'testu',
      Email = 'test2@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test2',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p2.Id,
      UserName = 'leveltwo@test2.com',
      Contact = c2,
      ContactId = c2.Id
    );
    insert u2;
    System.runAs(u2) {
      system.test.setCurrentPageReference(new PageReference('Page.Dashboard'));
      DashboardCtrl ctrl2 = new DashboardCtrl();
      ctrl2.getLists();
    }

    Profile p3 = [SELECT Id FROM Profile WHERE Name = 'TRAIL Level Three'];
    Contact c3 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test3',
      Email = 'newtest3@example.com'
    );
    insert c3;
    User u3 = new User(
      Alias = 'testu',
      Email = 'test3@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test3',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p3.Id,
      UserName = 'levelthree@test1.com',
      Contact = c3,
      ContactId = c3.Id
    );
    insert u3;
    System.runAs(u3) {
      system.test.setCurrentPageReference(new PageReference('Page.Dashboard'));
      DashboardCtrl ctrl3 = new DashboardCtrl();
      ctrl3.init();
      ctrl3.getLists();
    }

    system.test.stopTest();
  }
}