force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/PA_Log__c.object-meta.xml
<CustomObject>
    <label>PA Log</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Log__c/fields/Monthly_PA_Report__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PA_Report__c</fullName>
    <label>Monthly PA Report</label>
    <referenceTo>Program_Report__c</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>Daily_PA_Logs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>PA_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PALogClass.cls
public without sharing class PALogClass {
  public PALogClass() {
  }
  public String soql { get; set; }

  public void getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.PA_Log__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr += 'Site__r.Name';

    soql = 'SELECT ' + expr + ' FROM PA_Log__c';
  }

  public List<PA_Log__c> getLogs(Id reportId) {
    getSOQL();
    soql += ' WHERE Monthly_PA_Report__c = \'' + reportId + '\'';
    soql += ' ORDER BY Date__c asc';
    List<PA_Log__c> logs = database.query(soql);
    return logs;
  }

  public void upsertLogs(List<PA_Log__c> logs) {
    try {
      upsert logs;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}