force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgressReportsCtrl.cls
public without sharing class ProgressReportsCtrl {
  /*
    private UserClass userClass = new UserClass();
    public User currentUser { get; set; }
    public Account userAcct { get; set; }
    public String userAcctType { get; set; }
    
    private SessionReportClass src = new SessionReportClass();
    private PaginationClass pc = new PaginationClass();
    
    public Id siteId { get; set; }
    public List<Session_Report__c> allReports { get; set; }
    public List<Session_Report__c> reports { get; set; }
    
    public String orgName { get; set; }
    public String reportName { get; set; }
    public String status { get; set; }
    public List<SelectOption> statusOptions { get; set; }
    public String sortBy { get; set; }
    public List<SelectOption> sortByOptions { get; set; }
    
    Integer counter = 0;
    Integer limitSize = 40; 
    Integer totalSize = 0;
    public String recordCount { get; set;}
    public Boolean disablePrevious { get; set; }
    public Boolean disableNext { get; set; }
    
    public ProgressReportsCtrl() {
        currentUser = userClass.currentUser;
        userAcct = userClass.userAcct;
        userAcctType = userClass.userAcctType;
        
        siteId = null;
        if(userAcctType == 'Site') siteId = userAcct.Id;
        String urlSiteId = ApexPages.currentPage().getParameters().get('siteId'); 
        if(urlSiteId != '' && urlSiteId != null) {
            if(Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}').matcher(urlSiteId).matches() ){
                siteId = Id.valueOf(urlSiteId);
            }
        }
        
        statusOptions = new List<SelectOption>();
        statusOptions.add(new SelectOption('All Reports', 'View All'));
        Schema.DescribeFieldResult fieldResult = Session_Report__c.Status__c.getDescribe();
        for(Schema.PicklistEntry f : fieldResult.getPicklistValues()) statusOptions.add(new SelectOption(f.getLabel(), f.getValue()));
        status = 'All Reports';
            
        sortByOptions = new List<SelectOption>();
        sortByOptions.add(new SelectOption('Name','Name'));
        if(userAcctType != 'Site') sortByOptions.add(new SelectOption('Site__r.Name','Site'));
        sortByOptions.add(new SelectOption('Status__c','Status'));
        sortByOptions.add(new SelectOption('Submitted_Date__c', 'Submitted Date'));
        sortBy = 'Name';
        
        allReports = new List<Session_Report__c>();
        reports = new List<Session_Report__c>();
    }
    
    public void getLists() {
        allReports = src.getRelatedReportList(userAcct.Id, siteId, userAcctType, orgName, reportName, status, sortBy, null);
        totalSize = allReports.size();
        first();
    }
    
    // BEGIN Pagination
    public void first() {
        counter = 0;
        reports = pc.first(allReports, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = true;
        disableNext = pc.getDisableNext(counter, limitSize, totalSize);
    }
    
    public void next() {
        counter = counter + limitSize;
        reports = pc.next(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = false;
        disableNext = pc.getDisableNext(counter, limitSize, totalSize);
    }
    
    public void previous() {
        counter = counter - limitSize;       
        reports = pc.previous(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = pc.getDisablePrevious(counter);
        disableNext = false;
    }

    public void last() {
        counter = pc.getLastCounter(counter, limitSize, totalSize);
        reports = pc.last(allReports, counter, limitSize);
        recordCount = pc.getRecordCount(counter, limitSize, totalSize);
        disablePrevious = false;
        disableNext = true;
    }
    // END Pagination
	*/
}