force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/PA_Log__c/PA_Log__c.object-meta.xml
<CustomObject>
    <label>PA Log</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Log__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club Activity</fullName>
            </value>
            <value>
                <fullName>Club Closed</fullName>
            </value>
            <value>
                <fullName>No Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Minutes_of_Activity__c.field-meta.xml
<CustomField>
    <fullName>Minutes_of_Activity__c</fullName>
    <label>Minutes of Activity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Number_of_Boys__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Boys__c</fullName>
    <label>Number of Boys</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Number_of_Girls__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Girls__c</fullName>
    <label>Number of Girls</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>PA_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PA_Log__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PA Logs</relationshipLabel>
    <relationshipName>PA_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/Days_in_Month__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Month__c</fullName>
    <formula>End_Date__c - Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant_Name__c.field-meta.xml
<CustomField>
    <fullName>Grant_Name__c</fullName>
    <formula>Grant__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Months</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <formula>Site__r.Local_Organization__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Org Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Total_Daily_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Daily_Minutes__c</fullName>
    <label>Total Daily Minutes</label>
    <summarizedField>PA_Log__c.Minutes_of_Activity__c</summarizedField>
    <summaryFilterItems>
        <field>PA_Log__c.Activity_Status__c</field>
        <operation>equals</operation>
        <value>Club Activity, No Activity</value>
    </summaryFilterItems>
    <summaryForeignKey>PA_Log__c.Monthly_PA_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Total_Days_Reported_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Days_Reported_Open__c</fullName>
    <label>Total Days Reported Open</label>
    <summaryFilterItems>
        <field>PA_Log__c.Activity_Status__c</field>
        <operation>equals</operation>
        <value>Club Activity, No Activity</value>
    </summaryFilterItems>
    <summaryForeignKey>PA_Log__c.Monthly_PA_Report__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Total_Number_of_Boys__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Boys__c</fullName>
    <label>Total Number of Boys</label>
    <summarizedField>PA_Log__c.Number_of_Boys__c</summarizedField>
    <summaryFilterItems>
        <field>PA_Log__c.Activity_Status__c</field>
        <operation>equals</operation>
        <value>Club Activity, No Activity</value>
    </summaryFilterItems>
    <summaryForeignKey>PA_Log__c.Monthly_PA_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Total_Number_of_Girls__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Girls__c</fullName>
    <label>Total Number of Girls</label>
    <summarizedField>PA_Log__c.Number_of_Girls__c</summarizedField>
    <summaryFilterItems>
        <field>PA_Log__c.Activity_Status__c</field>
        <operation>equals</operation>
        <value>Club Activity, No Activity</value>
    </summaryFilterItems>
    <summaryForeignKey>PA_Log__c.Monthly_PA_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PALogCtrl.cls
public with sharing class PALogCtrl {
  private UserClass userClass = new UserClass();
  private ProgramReportClass prc = new ProgramReportClass();
  private PALogClass plc = new PALogClass();
  private SchemaPicklistFields spf = new SchemaPicklistFields();

  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public Id acctId { get; set; }

  public Program_Report__c report { get; set; }
  public List<Program_Report__c> report_list { get; set; }

  public Id reportId { get; set; }
  public List<PA_Log__c> log_list { get; set; }

  public String site { get; set; }
  public String month { get; set; }
  public List<SelectOption> months { get; set; }
  public String year { get; set; }
  public List<SelectOption> years { get; set; }
  public String status { get; set; }
  public List<SelectOption> statusOptions { get; set; }
  public String sortBy { get; set; }
  public List<SelectOption> sortByOptions { get; set; }

  public Decimal paLogCount { get; set; }
  public Decimal daysReportedOpen { get; set; }
  public Decimal minutes { get; set; }
  public Decimal miutesAverage { get; set; }
  public Decimal boys { get; set; }
  public Decimal boysAverage { get; set; }
  public Decimal girls { get; set; }
  public Decimal girlsAverage { get; set; }

  public Date dt = Date.today();
  public Integer currentYear = dt.year();

  public Boolean displaySendBackPopup { get; set; }
  public Boolean displayApprovePopup { get; set; }
  public String sizeErrorMessage { get; set; }
  public String errorMessage { get; set; }

  public PALogCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;

    report = new Program_Report__c();
    log_list = new List<PA_Log__c>();
    report_list = new List<Program_Report__c>();

    String urlrReportId = ApexPages.currentPage()
      .getParameters()
      .get('reportId');
    if (urlrReportId != '' && urlrReportId != null) {
      if (
        Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}')
          .matcher(urlrReportId)
          .matches()
      ) {
        reportId = Id.valueOf(urlrReportId);
      }
    }
  }

  public void getDropdowns() {
    String urlAcctId = ApexPages.currentPage().getParameters().get('acctId');
    if (urlAcctId != '' && urlAcctId != null) {
      if (
        Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}')
          .matcher(urlAcctId)
          .matches()
      ) {
        acctId = Id.valueOf(urlAcctId);
      }
    }
    if (acctId == null)
      acctId = userAcct.Id;

    months = new List<SelectOption>();
    months.add(new SelectOption('', ''));
    Schema.DescribeFieldResult m = Program_Report__c.Month__c.getDescribe();
    for (Schema.PicklistEntry f : m.getPicklistValues()) {
      months.add(new SelectOption(f.getLabel(), f.getValue()));
    }

    years = new List<SelectOption>();
    years = spf.getPicklistOptions('Program_Report__c', 'Year__c', null);
    year = string.valueOf(currentYear);

    status = '';
    statusOptions = new List<SelectOption>();
    statusOptions = spf.getPicklistOptions(
      'Program_Report__c',
      'Status__c',
      'View All'
    );

    sortByOptions = new List<SelectOption>();
    if (userAcctType != 'Site')
      sortByOptions.add(new SelectOption('Name', 'Report Title'));
    sortByOptions.add(new SelectOption('Site__r.Name', 'Site'));
    sortByOptions.add(new SelectOption('Grant_Name__c', 'Grant Name'));
    sortByOptions.add(new SelectOption('Month__c', 'Month'));
    sortBy = 'Name';

    getReportLists();
  }

  public void getReportLists() {
    sizeErrorMessage = '';
    errorMessage = '';
    Decimal days = 0;
    paLogCount = 0;
    daysReportedOpen = 0;
    minutes = 0;
    miutesAverage = 0;
    boys = 0;
    boysAverage = 0;
    girls = 0;
    girlsAverage = 0;

    report_list.clear();

    String soqlAND = ' AND RecordType.Name = \'Monthly PA Logs\'';
    if (month != null && month != '')
      soqlAND += ' AND Month__c = \'' + month + '\'';
    if (year != null && year != '')
      soqlAND += ' AND Year__c = \'' + year + '\'';
    if (status != null && status != 'View All')
      soqlAND += ' AND Status__c = \'' + status + '\'';
    if (site != null && site != '')
      soqlAND +=
        ' AND (Site_Name__c LIKE \'%' +
        site +
        '%\' OR Org_Name__c LIKE \'%' +
        site +
        '%\')';
    soqlAND += ' ORDER BY ' + sortBy;

    List<Program_Report__c> reports = prc.getRelatedReportList(
      acctId,
      userAcctType,
      null,
      null,
      null,
      soqlAND
    );
    if (reports.size() > 999)
      sizeErrorMessage = 'List of results is too large to display. Please narrow search criteria and refresh results.';
    else {
      for (Program_Report__c pr : reports) {
        if (site != null && site != '')
          String name = pr.Site__r.Name.toLowerCase();
        report_list.add(pr);
      }

      for (Program_Report__c pr : report_list) {
        paLogCount++;
        if (pr.Total_Days_Reported_Open__c != null)
          daysReportedOpen += pr.Total_Days_Reported_Open__c;
        if (pr.Total_Daily_Minutes__c != null)
          minutes += pr.Total_Daily_Minutes__c;
        if (pr.Total_Number_of_Boys__c != null)
          boys += pr.Total_Number_of_Boys__c;
        if (pr.Total_Number_of_Girls__c != null)
          girls += pr.Total_Number_of_Girls__c;
        if (pr.Days_in_Month__c != null)
          days += pr.Days_in_Month__c;
      }
      if (days > 0) {
        miutesAverage = (minutes / days).setScale(2);
        boysAverage = (boys / days).setScale(2);
        girlsAverage = (girls / days).setScale(2);
      }
    }
  }

  public void getPALists() {
    if (reportId != null) {
      report = prc.getReport(reportId);
      log_list = plc.getLogs(reportId);
    }
  }

  public void updateStatus() {
    for (PA_Log__c p : log_list) {
      if (
        p.Activity_Status__c == 'No Activity' ||
        p.Activity_Status__c == 'Club Closed'
      ) {
        p.Number_of_Boys__c = 0;
        p.Number_of_Girls__c = 0;
        p.Minutes_of_Activity__c = 0;
      }
    }
  }

  public void save() {
    errorMessage = '';
    plc.upsertLogs(log_list);

    report.Status__c = 'In Progress';
    prc.upsertReport(report);
  }

  public void submit() {
    errorMessage = '';
    plc.upsertLogs(log_list);
    for (PA_Log__c p : log_list) {
      if (
        p.Activity_Status__c == null ||
        p.Number_of_Boys__c == null ||
        p.Number_of_Girls__c == null ||
        p.Minutes_of_Activity__c == null
      ) {
        errorMessage = 'All fields are required';
      }
    }

    if (errorMessage == '') {
      report.Status__c = 'Submitted';
      report.Submitted_Date__c = date.today();
      report.Submitted_By__c = currentUser.ContactID;
      prc.upsertReport(report);
    }
  }

  // BEGIN sendBack
  public void sendBack() {
    report.Status__c = 'Revisions Needed';
    prc.upsertReport(report);
    hideSendBackPopup();
  }
  // END sendBack

  // BEGIN approve
  public void approve() {
    report.Status__c = 'Approved';
    prc.upsertReport(report);
    hideApprovePopup();
  }
  // END approve

  // BEGIN popups
  public void showSendBackPopup() {
    displaySendBackPopup = true;
  }
  public void hideSendBackPopup() {
    displaySendBackPopup = false;
  }

  public void showApprovePopup() {
    displayApprovePopup = true;
  }
  public void hideApprovePopup() {
    displayApprovePopup = false;
  }
  // END popups
}