force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Type__c</fullName>
    <formula>TEXT(National_Grant__r.Grant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Requests: Total Approved Amount where Status = Approved, Paid, Closed</inlineHelpText>
    <label>Reimbursement Approved Amount</label>
    <summarizedField
  >Reimbursement_Request__c.Total_Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Requested_Amount__c</fullName>
    <formula
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c</inlineHelpText>
    <label>Total Reimbursement Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursements_Pending_Approval__c.field-meta.xml
<CustomField>
    <fullName>Reimbursements_Pending_Approval__c</fullName>
    <label>Reimbursements Pending Approval</label>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value
    >Pending First Approval, Pending Second Approval, Pending Third Approval, Pending Fourth Approval, Pending Final Approval, Submitted</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Item_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Budget__c</fullName>
    <inlineHelpText>Roll-Up Summary of Budget Item: Item Budget</inlineHelpText>
    <label>Total Item Budget</label>
    <summarizedField>Budget_Item__c.Item_Budget__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/GrantCtrl.cls
public with sharing class GrantCtrl {
  private UserClass uc = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String portalName { get; set; }

  private GrantClass gc = new GrantClass();
  private ReimbursementClass rc = new ReimbursementClass();
  private BudgetItemClass bic = new BudgetItemClass();
  private getIdFromString gifs = new getIdFromString();

  public List<Grant__c> grants { get; set; }
  public Grant__c grant { get; set; }
  public ID grantId { get; set; }
  public Decimal totalAwarded { get; set; }
  public Decimal totalBudgeted { get; set; }
  public Decimal totalRequested { get; set; }
  public Decimal totalApproved { get; set; }

  public Boolean canCloseGrant { get; set; }
  public Boolean displayCloseGrantPopup { get; set; }

  public GrantCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    portalName = uc.userProfile;

    grants = new List<Grant__c>();
    grant = new Grant__c();

    String urlGrantId = ApexPages.currentPage().getParameters().get('grantId');
    grantId = gifs.getId(urlGrantId);
  }

  public void getGrants() {
    String soql = 'SELECT Id, Name, Amount__c, Balance__c, Start_Date__c, End_Date__c, Grant_Status__c FROM Grant__c WHERE RecordType.Name = \'Grant\'';
    if (portalName.contains('TRAIL'))
      soql += ' AND (Grant_Type__c = \'TRAIL\' OR National_Grant_Type__c = \'TRAIL\')';
    if (portalName.contains('OVC'))
      soql += ' AND (Grant_Type__c = \'OVC\' OR National_Grant_Type__c = \'OVC\')';
    grants = database.query(soql);
  }

  public PageReference getGrantDetails() {
    if (grantId == null)
      return new PageReference('/Grants');
    grant = gc.getGrant(grantId);

    totalAwarded = 0;
    totalBudgeted = 0;
    totalRequested = 0;
    totalApproved = 0;
    if (grant.Grant_Status__c != 'Closed')
      canCloseGrant = true;
    for (
      Grant__c sg : gc.getRelatedSubGrants(
        userAcct.Id,
        grantId,
        null,
        null,
        null,
        null,
        null
      )
    ) {
      if (sg.Amount__c != null)
        totalAwarded += sg.Amount__c;
      if (sg.Total_Item_Budget__c != null)
        totalBudgeted += sg.Total_Item_Budget__c;
      if (sg.Reimbursement_Requested_Amount__c != null)
        totalRequested += sg.Reimbursement_Requested_Amount__c;
      if (sg.Reimbursement_Approved_Amount__c != null)
        totalApproved += sg.Reimbursement_Approved_Amount__c;
      if (sg.Reimbursements_Pending_Approval__c > 0)
        canCloseGrant = false;
    }
    return null;
  }

  // BEGIN closeGrant
  public void closeGrant() {
    gc.closeGrant(grant.Id);
    hideCloseGrantPopup();
  }
  // END closeGrant

  // BEGIN popups
  public void showCloseGrantPopup() {
    displayCloseGrantPopup = true;
  }
  public void hideCloseGrantPopup() {
    displayCloseGrantPopup = false;
  }
  // END popups
}