force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Item_Budget__c - Total_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Item Budget - Total Approved Amount</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child Safety</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contract Specialists</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Other Costs</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Sub Awards</fullName>
            </value>
            <value>
                <fullName>Consultant Travel</fullName>
            </value>
            <value>
                <fullName>Indirect Costs</fullName>
            </value>
            <value>
                <fullName>Procurement Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Factor_Type__c.field-meta.xml
<CustomField>
    <fullName>Factor_Type__c</fullName>
    <inlineHelpText>BBBSA only: 
if Factor Type = FTE, New Item Budget = New Rate * Estimated FTE (from Sub-Grant);
if Factor Type = TCS, New Item Budget = New Rate * Youth Served % (from Sub-Grant);
if Factor Type = Other, New Item Budget = New Rate * Other Factor %;</inlineHelpText>
    <label>Factor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTE</fullName>
            </value>
            <value>
                <fullName>TCS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <label>Indirect Rate</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Other_Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Other Factor Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Indirect Rate</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <label>Use Indirect Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Youth_Served_Percent__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Youth Served Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/Reimbursement_Item__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Item</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Item__c/fields/Budget_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Item__c</fullName>
    <label>Budget Item</label>
    <referenceTo>Budget_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Budget_Item__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Factor_Percent__c.field-meta.xml
<CustomField>
    <fullName>Factor_Percent__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Factor Percent</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Indirect Rate</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Item__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement Item</label>
    <referenceTo>Reimbursement_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Request__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Request__c</fullName>
    <label>Reimbursement Request</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/FTE__c.field-meta.xml
<CustomField>
    <fullName>FTE__c</fullName>
    <label>FTE</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Rate__c</fullName>
    <label>Indirect Rate</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary for Reimbursement Items: Requested Amount</inlineHelpText>
    <label>Requested Amount</label>
    <summarizedField>Reimbursement_Item__c.Requested_Amount__c</summarizedField>
    <summaryForeignKey
  >Reimbursement_Item__c.Reimbursement_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Use_Indirect_Rate__c.field-meta.xml
<CustomField>
    <fullName>Use_Indirect_Rate__c</fullName>
    <formula
  >IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Use Indirect Rate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Youth_Served_Percent__c.field-meta.xml
<CustomField>
    <fullName>Youth_Served_Percent__c</fullName>
    <label>Youth Served Percent</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/RequestExpensesFormController.cls
public with sharing class RequestExpensesFormController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  public GrantClass grantClass = new GrantClass();
  public ReimbursementClass requestClass = new ReimbursementClass();
  public ReimbursementItemClass requestItemClass = new ReimbursementItemClass();
  public AttachmentClass attachClass = new AttachmentClass();

  public Account acct { get; set; }
  public ID GrantID { get; set; }
  public ID RequestID { get; set; }
  public Grant__c grant { get; set; }
  public Reimbursement_Request__c request { get; set; }
  public Set<ID> riId_set { get; set; }
  public Decimal laborRequestedAmount { get; set; }
  public Decimal expenseRequestedAmount { get; set; }
  public Decimal totalRequestedAmount { get; set; }
  public Boolean amountError { get; set; }
  public Boolean attachMissing { get; set; }
  public String errorMessage { get; set; }

  public Id expenseId { get; set; }
  public Map<String, List<Reimbursement_Item__c>> expense_map { get; set; }

  public Boolean displayPopupBg { get; set; }
  public Boolean displayExpenseNotesPopup { get; set; }
  public Boolean displayAttPopup { get; set; }
  public Boolean displayItemAttPopup { get; set; }

  public Attachment att { get; set; }
  public List<Attachment> att_list { get; set; }
  public List<Attachment> itemAtt_list { get; set; }
  public Id deleteAttId { get; set; }
  public Id deleteItemAttId { get; set; }

  public Date dt = date.today();
  public String fdt = dt.format();

  // BEGIN Constructor
  public RequestExpensesFormController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;
    if (portalName == 'BBBS')
      portalName = '';

    GrantID = ApexPages.currentPage().getParameters().get('GrantId');
    RequestID = ApexPages.currentPage().getParameters().get('RequestID');
    expenseId = Schema.SObjectType.Reimbursement_Item__c.getRecordTypeInfosByName()
      .get('Expense')
      .getRecordTypeId();

    request = new Reimbursement_Request__c();
    riId_set = new Set<ID>();

    laborRequestedAmount = 0;
    expenseRequestedAmount = 0;
    totalRequestedAmount = 0;
    errorMessage = '';
    amountError = false;
    attachMissing = false;

    displayPopupBg = false;
    displayExpenseNotesPopup = false;
    displayAttPopup = false;
    displayItemAttPopup = false;

    expense_map = new Map<String, List<Reimbursement_Item__c>>();

    att_list = new List<Attachment>();
    itemAtt_list = new List<Attachment>();

    if (RequestID != null) {
      request = requestClass.getRequest(RequestId);
      request.Previous_Status__c = request.Status__c;
      GrantID = request.Grant__c;
      getAttList();
    }

    if (GrantID != null) {
      grant = grantClass.getGrant(GrantId);
      acct = [
        SELECT ID, Name, RecordType.Name
        FROM Account
        WHERE ID = :grant.Account__r.Id
      ];
    }
  }

  public Boolean initalized = false;
  public void getLists() {
    if (!initalized) {
      if (request.Id != null) {
        for (
          Reimbursement_Item__c ri : requestItemClass.getRequestItems(
            request.Id,
            'labor'
          )
        ) {
          if (ri.Requested_Amount__c != null) {
            laborRequestedAmount += ri.Requested_Amount__c;
          }
        }
        for (
          Reimbursement_Item__c ri : requestItemClass.getRequestItems(
            request.Id,
            'expense'
          )
        ) {
          riId_set.add(ri.Id);

          if (ri.Attachments.size() == 0) {
            Attachment a = new Attachment();
            a.ParentId = ri.Id;
            itemAtt_list.add(a);
          }

          if (
            portalName == 'NPAL' ||
            portalName == 'DMV' ||
            portalName == 'MDGO'
          )
            ri.Factor_Percent__c = 100;
          else {
            if (ri.Budget_Item__r.Factor_Type__c == 'FTE') {
              ri.Factor_Percent__c = request.FTE__c;
            } else if (ri.Budget_Item__r.Factor_Type__c == 'TCS') {
              ri.Factor_Percent__c = request.Youth_Served_Percent__c;
            }
          }
          /*
else if(ri.Budget_Item__r.Factor_Type__c == 'Other') {
ri.Factor_Percent__c = ri.Budget_Item__r.Other_Factor_Percent__c;
} 
*/
          if (ri.Factor_Percent__c > 100) {
            ri.Factor_Percent__c = 100;
          }

          if (ri.Rate__c > 0) {
            if (
              grant.Use_Indirect_Rate__c != 'Yes' &&
              ri.Factor_Percent__c > 0
            ) {
              ri.Requested_Amount__c = (ri.Rate__c *
                ri.Factor_Percent__c /
                100)
                .setScale(2);
            } else {
              ri.Requested_Amount__c = ri.Rate__c.setScale(2);
            }
          } else {
            ri.Requested_Amount__c = 0;
          }
          expenseRequestedAmount += ri.Requested_Amount__c;

          if (expense_map.containsKey(ri.Budget_Item__r.Category__c)) {
            List<Reimbursement_Item__c> item_list = expense_map.get(
              ri.Budget_Item__r.Category__c
            );
            item_list.add(ri);
            expense_map.put(ri.Budget_Item__r.Category__c, item_list);
          } else {
            expense_map.put(
              ri.Budget_Item__r.Category__c,
              new List<Reimbursement_Item__c>{ ri }
            );
          }
        }

        getTotals();

        for (Attachment att : [
          SELECT ID, ParentID, Name
          FROM Attachment
          WHERE ParentId IN :riId_set
          ORDER BY LastModifiedDate DESC
        ]) {
          itemAtt_list.add(att);
        }
      }
      initalized = true;
    }
  }

  // BEGIN getAttList
  public void getAttList() {
    att_list.clear();
    Reimbursement_Request__c r = [
      SELECT
        Id,
        (
          SELECT Id, Name, Description
          FROM Attachments
          ORDER BY LastModifiedDate DESC
        )
      FROM Reimbursement_Request__c
      WHERE Id = :request.Id
    ];
    Set<String> names = new Set<String>();
    for (Attachment a : r.Attachments) {
      if (
        a.Name == 'General Ledger' ||
        a.Name == 'TCS Report' ||
        a.Name == 'FTE Report'
      ) {
        if (!names.contains(a.Name)) {
          att_list.add(a);
          names.add(a.Name);
        }
      }
    }
  }
  // END getAttList

  // BEGIN deleteAtt
  public void deleteAtt() {
    if (deleteAttId != null) {
      Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteAttId];
      if (a != null) {
        attachClass.deleteAttachment(a);
      }
    }
    getAttList();
  }
  // END deleteAtt

  // BEGIN getItemAttList
  public void getItemAttList() {
    itemAtt_list.clear();

    List<Reimbursement_Item__c> ri_att_list = [
      SELECT
        ID,
        (
          SELECT ID, ParentID, Name
          FROM Attachments
          ORDER BY LastModifiedDate DESC
          LIMIT 1
        )
      FROM Reimbursement_Item__c
      WHERE
        Reimbursement_Request__c = :request.Id
        AND RecordType.Name = 'Expense'
    ];

    Set<Id> ri_att_Id_set = new Set<Id>();
    for (Reimbursement_Item__c ri : ri_att_list) {
      ri_att_Id_set.add(ri.Id);

      if (ri.Attachments.size() == 0) {
        Attachment a = new Attachment();
        a.ParentId = ri.Id;
        itemAtt_list.add(a);
      }
    }
    for (Attachment att : [
      SELECT ID, ParentID, Name
      FROM Attachment
      WHERE ParentId IN :ri_att_Id_set
      ORDER BY LastModifiedDate DESC
    ]) {
      itemAtt_list.add(att);
    }
  }
  // END getItemAttList

  // BEGIN deleteItemAtt
  public void deleteItemAtt() {
    if (deleteItemAttId != null) {
      Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteItemAttId];
      if (a != null) {
        attachClass.deleteAttachment(a);
      }
    }
    getItemAttList();
  }
  // END deleteItemAtt

  // BEGIN updateAmounts
  public void updateAmounts() {
    system.debug('>>> RequestExpensesFormController updateAmounts');
    errorMessage = '';
    attachMissing = false;
    expenseRequestedAmount = 0;
    totalRequestedAmount = laborRequestedAmount;

    List<Attachment> att_upsert_list = new List<Attachment>();
    List<List<Reimbursement_Item__c>> expense_list = expense_map.values();
    for (Integer i = 0; i < expense_list.size(); i++) {
      for (Reimbursement_Item__c ri : expense_list.get(i)) {
        if (portalName != 'MDGO') {
          if (ri.Rate__c > 0) {
            if (
              ri.Factor_Percent__c != null &&
              grant.Use_Indirect_Rate__c != 'Yes'
            ) {
              ri.Requested_Amount__c = (ri.Rate__c *
                ri.Factor_Percent__c /
                100)
                .setScale(2);
            } else {
              ri.Requested_Amount__c = ri.Rate__c.setScale(2);
            }
          } else {
            ri.Requested_Amount__c = 0;
          }
        } else {
          ri.Requested_Amount__c = ri.Rate__c;
        }
        ri.Requested_Amount__c.setScale(2);
        expenseRequestedAmount += ri.Requested_Amount__c;
        totalRequestedAmount += ri.Requested_Amount__c;
      }
    }
    try {
      upsert att_upsert_list;
      getItemAttList();
    } catch (Exception e) {
      errorMessage = e.getMessage();
      system.debug('error = ' + e.getMessage());
    }

    if (totalRequestedAmount > grant.Balance__c) {
      amountError = true;
      errorMessage = 'Requested Amount Exceeds Sub-Grant Balance';
    } else {
      amountError = false;
    }
    getTotals();
  }

  public void getTotals() {
    if (grant.Use_Indirect_Rate__c == 'Yes') {
      request.Indirect_Rate_Amount__c = ((laborRequestedAmount +
        expenseRequestedAmount) *
        grant.Indirect_Rate__c /
        100)
        .setScale(2);
      totalRequestedAmount =
        laborRequestedAmount +
        expenseRequestedAmount +
        request.Indirect_Rate_Amount__c;
    } else {
      totalRequestedAmount = (laborRequestedAmount + expenseRequestedAmount)
        .setScale(2);
    }
    if (grant.Amount__c != null && totalRequestedAmount > grant.Amount__c) {
      amountError = true;
      errorMessage = 'Requested Amount Exceeds Sub-Grant Amount';
    } else {
      amountError = false;
    }
    system.debug(
      '>>> RequestExpensesFormController totalRequestedAmount = ' +
      totalRequestedAmount
    );
  }
  // END updateAmounts

  // BEGIN saveExpense
  public void saveExpense() {
    updateAmounts();
    requestClass.upsertRequest(request);

    Boolean hasLedger = false;
    for (Attachment a : att_list) {
      if (a.Name == 'General Ledger') {
        hasLedger = true;
      }
    }
    if (!hasLedger && portalName != 'NPAL' && portalName != 'MDGO') {
      errorMessage = 'A General Ledger document is required';
    }

    List<Reimbursement_Item__c> expense_update_list = new List<Reimbursement_Item__c>();
    List<List<Reimbursement_Item__c>> expense_list = expense_map.values();
    for (Integer i = 0; i < expense_list.size(); i++) {
      for (Reimbursement_Item__c ri : expense_list.get(i)) {
        expense_update_list.add(ri);
      }
    }
    requestItemClass.upsertItems(expense_update_list);
  }
  // END saveExpense

  // BEGIN previous
  public PageReference previous() {
    saveExpense();

    PageReference pr = new PageReference(
      '/' +
      portalName +
      'RequestPersonnelForm?GrantID=' +
      GrantID +
      '&RequestID=' +
      RequestID
    );
    pr.setRedirect(true);
    return pr;
  }
  // END previous

  // BEGIN saveAndExit
  public PageReference saveAndExit() {
    saveExpense();

    PageReference pr = new PageReference('/Reimbursements');
    pr.setRedirect(true);
    return pr;
  }
  // END saveAndExit

  // BEGIN submit
  public PageReference submit() {
    saveExpense();

    system.debug('>>> errorMessage = ' + errorMessage);
    if (String.isBlank(errorMessage)) {
      String mh = '';
      if (request.Status__c == 'Incomplete') {
        request.Request_Date__c = dt;
        mh =
          fdt +
          ': Reimbursement Request Submitted by ' +
          currentUser.Contact.Name +
          ' (' +
          currentUser.Id +
          ')';
      } else {
        request.Modification_Last_Submitted_Date__c = dt;
        mh =
          fdt +
          ': Modification Submitted by ' +
          currentUser.Contact.Name +
          ' (' +
          currentUser.Id +
          ')';
      }
      if (request.Modification_History__c == null) {
        request.Modification_History__c = '';
      }
      request.Modification_History__c += ' \r\n' + mh;

      if (
        portalName == 'NPAL' &&
        grant.Account__r.RecordType.Name == 'National Organization'
      ) {
        request.Status__c = 'Approved';
      } else if (request.Is_National_Request__c) {
        request.Status__c = 'Pending Final Approval';
      } else {
        request.Status__c = 'Pending First Approval';
      }
      request.Primary_Contact__c = currentUser.ContactID;
      requestClass.upsertRequest(request);

      PageReference pr = new PageReference('/Reimbursements');
      pr.setRedirect(true);
      return pr;
    }
    return null;
  }
  // END submit

  // BEGIN popups
  public void expenseNotesPopup() {
    if (displayExpenseNotesPopup == true) {
      displayPopupBg = false;
      displayExpenseNotesPopup = false;
    } else {
      displayPopupBg = true;
      displayExpenseNotesPopup = true;
    }
  }

  public void attPopup() {
    getAttList();
    if (displayAttPopup == true) {
      displayPopupBg = false;
      displayAttPopup = false;
    } else {
      displayPopupBg = true;
      displayAttPopup = true;
    }
  }

  public void itemAttPopup() {
    getItemAttList();
    if (displayItemAttPopup == true) {
      displayPopupBg = false;
      displayItemAttPopup = false;
    } else {
      displayPopupBg = true;
      displayItemAttPopup = true;
    }
  }
  // END popups
}