force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/LOA_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>LOA_Submitted_Date__c</fullName>
    <label>LOA Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Victims_Served_Report__c/Victims_Served_Report__c.object-meta.xml
<CustomObject>
    <label>Victims Served Report</label>
    <nameField>
        <displayFormat>VS-{00000}</displayFormat>
        <label>Victims Served Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Victims Served Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Victims_Served_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Victims Served Reports</relationshipLabel>
    <relationshipName>Victims_Served_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revisions in Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateOVCProgramReports.cls
public class CreateOVCProgramReports implements Schedulable {
  private GetMonthAsString gms = new GetMonthAsString();

  public void execute(SchedulableContext sc) {
    Date dt = date.today();
    GetMonthAsString gms = new GetMonthAsString();
    String month = gms.getMonth(dt.month());

    if (
      month == 'March' ||
      month == 'June' ||
      month == 'September' ||
      month == 'December'
    ) {
      if (month == 'March')
        month = 'Jan - Mar';
      if (month == 'June')
        month = 'Apr - Jun';
      if (month == 'September')
        month = 'Jul - Sep';
      if (month == 'December')
        month = 'Oct - Dec';

      List<Victims_Served_Report__c> pr_list = new List<Victims_Served_Report__c>();

      List<Grant__c> g_list = [
        SELECT Id, Account__r.Id
        FROM Grant__c
        WHERE
          RecordType.Name = 'Sub-Grant'
          AND LOA_Submitted_Date__c != NULL
          AND Grant_Type__c = 'OVC'
      ];
      for (Grant__c g : g_list) {
        Victims_Served_Report__c pr = new Victims_Served_Report__c(
          Month__c = month,
          Year__c = dt.year(),
          Organization__c = g.Account__r.Id,
          Status__c = 'Requested'
        );
        pr_list.add(pr);
      }
      insert pr_list;
    }
  }
}