force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Total_Item_Balance__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Balance__c</fullName>
    <formula>Total_Item_Budget__c - Reimbursement_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Total_Item_Budget__c - Reimbursement_Approved_Amount__c</inlineHelpText>
    <label>Total Item Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DMVDashboardCtrl.cls
public with sharing class DMVDashboardCtrl {
  private UserClass uc = new UserClass();
  public User currentUser { get; set; }
  public String userProfile { get; set; }
  public Account userAcct { get; set; }
  public String approverLevel { get; set; }
  public String userAcctType { get; set; }

  private GrantClass gc = new GrantClass();
  public List<Grant__c> grants_list { get; set; }
  public Boolean more_grants { get; set; }

  private ReimbursementClass rc = new ReimbursementClass();
  public List<Reimbursement_Request__c> incomplete_request_list { get; set; }
  public List<Reimbursement_Request__c> pending_approval_list { get; set; }
  public List<Reimbursement_Request__c> sentBack_request_list { get; set; }
  public Boolean more_incomplete_request { get; set; }
  public Boolean more_pending_approval { get; set; }
  public Boolean more_sentBack_request { get; set; }

  private ProgressReportClass prc = new ProgressReportClass();
  public List<Progress_Report__c> report_list { get; set; }
  public Boolean more_report { get; set; }

  public DMVDashboardCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    userAcctType = uc.userAcctType;
    approverLevel = uc.approverLevel;
    userProfile = currentUser.Profile.Name;

    grants_list = new List<Grant__c>();
    incomplete_request_list = new List<Reimbursement_Request__c>();
    pending_approval_list = new List<Reimbursement_Request__c>();
    sentBack_request_list = new List<Reimbursement_Request__c>();
    report_list = new List<Progress_Report__c>();
  }

  public ApexPages.PageReference init() {
    if (currentUser == null || userAcct == null) {
      PageReference pageRef = new PageReference('/login');
      return pageRef;
    }
    if (userProfile.contains('Report Builder')) {
      PageReference pageRef = new PageReference('/00O/o');
      return pageRef;
    }
    getLists();
    return null;
  }

  public void getLists() {
    Integer listLimit = 6;

    for (
      Grant__c g : gc.getRelatedSubGrants(
        userAcct.Id,
        null,
        null,
        'Total_Item_Balance__c',
        null,
        null,
        null
      )
    ) {
      if (grants_list.size() < listLimit) {
        grants_list.add(g);
      } else {
        more_grants = true;
      }
    }

    for (
      Reimbursement_Request__c r : rc.getRelatedRequests(
        userAcct.Id,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      )
    ) {
      String status = r.Status__c;
      if (status == 'Incomplete') {
        if (incomplete_request_list.size() < listLimit) {
          incomplete_request_list.add(r);
        } else {
          more_incomplete_request = true;
        }
      } else if (status.contains('Pending')) {
        if (pending_approval_list.size() < listLimit) {
          pending_approval_list.add(r);
        } else {
          more_pending_approval = true;
        }
      } else if (status.contains('Revision')) {
        if (sentBack_request_list.size() < listLimit) {
          sentBack_request_list.add(r);
        } else {
          more_sentBack_request = true;
        }
      }
    }

    for (
      Progress_Report__c pr : prc.getRelatedReportList(
        userAcct.Id,
        null,
        userAcctType,
        null,
        null,
        null,
        null,
        null,
        null,
        ''
      )
    ) {
      if (report_list.size() < listLimit)
        report_list.add(pr);
      else
        more_report = true;
    }
  }
}