force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Accepted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Plan__c/fields/Able_to_Recruit__c.field-meta.xml
<CustomField>
    <fullName>Able_to_Recruit__c</fullName>
    <label>Able to Recruit</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Additional_Resources_for_Strategic_Plan__c.field-meta.xml
<CustomField>
    <fullName>Additional_Resources_for_Strategic_Plan__c</fullName>
    <label>Additional Resources for Strategic Plan</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Areas_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Areas_of_Service__c</fullName>
    <label>Areas of Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Providing information to crime victims</fullName>
            </value>
            <value>
                <fullName>Referral services for crime victims</fullName>
            </value>
            <value>
                <fullName>Victim advocacy/accompaniment</fullName>
            </value>
            <value>
                <fullName
        >Law enforcement interview advocacy/accompaniment</fullName>
                <label>Law enforcement interview advocacy/accompaniment</label>
            </value>
            <value>
                <fullName
        >Intervention with employer, creditor, landlord or academic institution</fullName>
                <label
        >Intervention with employer, creditor, landlord or academic institution</label>
            </value>
            <value>
                <fullName>Child and/or dependent care assistance</fullName>
            </value>
            <value>
                <fullName>Transportation assistance</fullName>
            </value>
            <value>
                <fullName>Interpreter services</fullName>
            </value>
            <value>
                <fullName>Crisis intervention</fullName>
            </value>
            <value>
                <fullName>Hotline/crisis line counseling</fullName>
            </value>
            <value>
                <fullName>On-scene crisis response</fullName>
            </value>
            <value>
                <fullName
        >Sexual Assault Response Team (SART) team development</fullName>
                <label
        >Sexual Assault Response Team (SART) team development</label>
            </value>
            <value>
                <fullName
        >Coordinated Community Response (CCR) team development</fullName>
                <label
        >Coordinated Community Response (CCR) team development</label>
            </value>
            <value>
                <fullName>Updating tribal codes for victim services</fullName>
            </value>
            <value>
                <fullName
        >Access to Traditional/Cultural Healing ceremonies for victims</fullName>
                <label
        >Access to Traditional/Cultural Healing ceremonies for victims</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Biggest_Issue_Organization_is_Facing__c.field-meta.xml
<CustomField>
    <fullName>Biggest_Issue_Organization_is_Facing__c</fullName>
    <label>Biggest Issue Organization is Facing</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Current_Program_Description__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Description__c</fullName>
    <label>Current Program Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Equipment_and_Supplies__c.field-meta.xml
<CustomField>
    <fullName>Equipment_and_Supplies__c</fullName>
    <label>Equipment and Supplies</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Has_Equipment_and_Supplies__c.field-meta.xml
<CustomField>
    <fullName>Has_Equipment_and_Supplies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Equipment and Supplies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Has_Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Has_Needs_Assessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Needs Assessment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/How_Funds_Utilized__c.field-meta.xml
<CustomField>
    <fullName>How_Funds_Utilized__c</fullName>
    <label>How Funds Utilized</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Needs_Assessment__c</fullName>
    <label>Needs Assessment</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Other_Challenges__c.field-meta.xml
<CustomField>
    <fullName>Other_Challenges__c</fullName>
    <label>Other Challenges</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Previous_Experiences__c.field-meta.xml
<CustomField>
    <fullName>Previous_Experiences__c</fullName>
    <label>Previous Experiences</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Plan__c/fields/Strategic_Plan__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Plan__c</fullName>
    <label>Strategic Plan</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProgramPlanCtrl.cls
public with sharing class ProgramPlanCtrl {
  private UserClass uc = new UserClass();
  private ProgramPlanClass ppc = new ProgramPlanClass();
  private FieldLabelClass flc = new FieldLabelClass();
  private SchemaPicklistFields spf = new SchemaPicklistFields();

  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }

  public Id planId { get; set; }
  public Program_Plan__c plan { get; set; }
  public Map<String, String> labels { get; set; }

  public Boolean readOnly { get; set; }
  public String errorMessage { get; set; }

  public List<SelectOption> serviceOptions {
    get {
      return spf.getPicklistOptions(
        'Program_Plan__c',
        'Areas_of_Service__c',
        null
      );
    }
    set;
  }
  public String[] services {
    get {
      String[] selected = new List<String>();
      List<SelectOption> sos = this.serviceOptions;
      for (SelectOption s : sos) {
        if (
          this.plan.Areas_of_Service__c != null &&
          this.plan.Areas_of_Service__c.contains(s.getValue())
        )
          selected.add(s.getValue());
      }
      return selected;
    }
    public set {
      String selectedConcat = '';
      for (String s : value) {
        if (selectedConcat == '')
          selectedConcat += s;
        else
          selectedConcat += ';' + s;
      }
      plan.Areas_of_Service__c = selectedConcat;
    }
  }

  public ProgramPlanCtrl() {
    currentUser = uc.currentUser;
    userAcct = uc.userAcct;
    userAcctType = uc.userAcctType;

    readOnly = true;

    plan = new Program_Plan__c();
    String urlPlanId = ApexPages.currentPage().getParameters().get('planId');
    if (urlPlanId != '' && urlPlanId != null) {
      if (
        Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}')
          .matcher(urlPlanId)
          .matches()
      ) {
        planId = Id.valueOf(urlPlanId);
        plan = ppc.getPlan(planId);
      }
    }

    if (plan != null) {
      if (
        userAcctType == 'Local Organization' &&
        plan.Status__c == 'Revisions Needed'
      )
        readOnly = false;
      labels = flc.getFieldLabelMap('Program_Plan__c', null, null, null);
    }
  }

  public void updatePlan() {
    plan = plan.clone(false, true, false, false);
    readOnly = false;
  }

  public void submit() {
    errorMessage = '';

    if (plan.Biggest_Issue_Organization_is_Facing__c == null)
      errorMessage += 'Issue that will be addressed is required <br />';
    if (plan.How_Funds_Utilized__c == null)
      errorMessage += 'How you would like to use the requested funding is required <br />';

    if (
      plan.Has_Needs_Assessment__c == true &&
      (plan.Previous_Experiences__c == null ||
      plan.Needs_Assessment__c == null)
    )
      errorMessage += 'Needs Assessment questions are required <br />';

    if (
      plan.Has_Strategic_Plan__c == true &&
      (plan.Strategic_Plan__c == null ||
      plan.Additional_Resources_for_Strategic_Plan__c == null)
    )
      errorMessage += 'Strategic Plan questions are required <br />';

    if (
      plan.Areas_of_Service__c == null ||
      plan.Current_Program_Description__c == null
    )
      errorMessage += 'Support for Victim Services questions are required <br />';

    if (
      plan.Has_Equipment_and_Supplies__c == true &&
      plan.Equipment_and_Supplies__c == null
    )
      errorMessage += 'Equipment and Supplies questions are required <br />';

    if (plan.Responsibilities__c == null || plan.Able_to_Recruit__c == null)
      errorMessage += 'Capabilities and Competencies questions are required <br />';

    if (plan.Other_Challenges__c == null)
      errorMessage += 'Plan for Collecting Data is required <br />';

    if (errorMessage == '') {
      plan.Status__c = 'Submitted';
      plan.Submitted_Date__c = Date.today();
      ppc.upsertPlan(plan, true);
      readOnly = true;
    }
  }

  public void approve() {
    plan.Status__c = 'Approved';
    ppc.upsertPlan(plan, false);
    readOnly = true;
  }

  public void sendBack() {
    plan.Status__c = 'Revisions Needed';
    ppc.upsertPlan(plan, false);
    readOnly = true;
  }
}