force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Item_Budget__c - Total_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Item Budget - Total Approved Amount</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/FICA__c.field-meta.xml
<CustomField>
    <fullName>FICA__c</fullName>
    <label>FICA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Item_Note__c.field-meta.xml
<CustomField>
    <fullName>Item_Note__c</fullName>
    <label>Item Note</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Life__c.field-meta.xml
<CustomField>
    <fullName>Life__c</fullName>
    <label>Life</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Other_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Other_Benefits__c</fullName>
    <label>Other Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Item__c/Reimbursement_Item__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Item</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Item__c/fields/Budget_Item__c.field-meta.xml
<CustomField>
    <fullName>Budget_Item__c</fullName>
    <label>Budget Item</label>
    <referenceTo>Budget_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Dental__c.field-meta.xml
<CustomField>
    <fullName>Dental__c</fullName>
    <label>Dental</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Fringe_Benefit__c.field-meta.xml
<CustomField>
    <fullName>Fringe_Benefit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fringe Benefit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Long_Term_Disability__c.field-meta.xml
<CustomField>
    <fullName>Long_Term_Disability__c</fullName>
    <label>Long Term Disability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Percent_Towards_Grant__c.field-meta.xml
<CustomField>
    <fullName>Percent_Towards_Grant__c</fullName>
    <label>Percent Towards Grant</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Quantity_Towards_Grant__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Towards_Grant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Towards Grant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Item__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement Item</label>
    <referenceTo>Reimbursement_Item__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Reimbursement_Request__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Request__c</fullName>
    <label>Reimbursement Request</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Reimbursement Items</relationshipLabel>
    <relationshipName>Reimbursement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Requested_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Requested_Benefits__c</fullName>
    <label>Requested Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Requested_Salary__c.field-meta.xml
<CustomField>
    <fullName>Requested_Salary__c</fullName>
    <label>Requested Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/fields/Short_Term_Disability__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_Disability__c</fullName>
    <label>Short Term Disability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/FTE__c.field-meta.xml
<CustomField>
    <fullName>FTE__c</fullName>
    <label>FTE</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary for Reimbursement Items: Requested Amount</inlineHelpText>
    <label>Requested Amount</label>
    <summarizedField>Reimbursement_Item__c.Requested_Amount__c</summarizedField>
    <summaryForeignKey
  >Reimbursement_Item__c.Reimbursement_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Requested_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Requested_Benefits__c</fullName>
    <inlineHelpText
  >Roll-Up Summary for Reimbursement Items: Requested Benefits</inlineHelpText>
    <label>Requested Benefits</label>
    <summarizedField
  >Reimbursement_Item__c.Requested_Benefits__c</summarizedField>
    <summaryForeignKey
  >Reimbursement_Item__c.Reimbursement_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Requested_Salary__c.field-meta.xml
<CustomField>
    <fullName>Requested_Salary__c</fullName>
    <inlineHelpText
  >Roll-Up Summary for Reimbursement Items: Requested Salary</inlineHelpText>
    <label>Requested Salary</label>
    <summarizedField>Reimbursement_Item__c.Requested_Salary__c</summarizedField>
    <summaryForeignKey
  >Reimbursement_Item__c.Reimbursement_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_FTE_at_Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Total_FTE_at_Affiliate__c</fullName>
    <label>Total FTE at Affiliate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RequestPersonnelFormController.cls
public with sharing class RequestPersonnelFormController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }

  public GrantClass grantClass = new GrantClass();
  public ReimbursementClass requestClass = new ReimbursementClass();
  public ReimbursementItemClass requestItemClass = new ReimbursementItemClass();
  public AttachmentClass attachClass = new AttachmentClass();

  public Account acct { get; set; }
  public ID GrantID { get; set; }
  public ID RequestID { get; set; }
  public Grant__c grant { get; set; }
  public Reimbursement_Request__c request { get; set; }
  public List<Reimbursement_Item__c> ri_list { get; set; }
  public Set<ID> riId_set { get; set; }
  public Decimal FTE { get; set; }
  public Decimal totalRequestedAmount { get; set; }
  public Boolean amountError { get; set; }
  public String errorMessage { get; set; }

  public Id laborId { get; set; }
  public List<itemClass> labor_list { get; set; }
  public Integer selectedLabor { get; set; }
  public Integer laborCount = 0;
  public Boolean displayLaborNotesPopup { get; set; }
  public Boolean displayAttPopup { get; set; }

  public List<Attachment> att_list { get; set; }
  public Id deleteAttId { get; set; }

  public Decimal requestSub { get; set; }
  public Decimal fICASub { get; set; }
  public Decimal medicalSub { get; set; }
  public Decimal dentalSub { get; set; }
  public Decimal shortTermSub { get; set; }
  public Decimal longTermSub { get; set; }
  public Decimal lifeSub { get; set; }
  public Decimal otherSub { get; set; }
  public Decimal benefitsSub { get; set; }
  public Decimal requstedBenefitsSub { get; set; }

  // BEGIN Constructor
  public RequestPersonnelFormController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;
    if (portalName == 'BBBS')
      portalName = '';

    GrantID = ApexPages.currentPage().getParameters().get('GrantId');
    RequestID = ApexPages.currentPage().getParameters().get('RequestID');
    laborId = Schema.SObjectType.Reimbursement_Item__c.getRecordTypeInfosByName()
      .get('Labor')
      .getRecordTypeId();

    request = new Reimbursement_Request__c();
    ri_list = new List<Reimbursement_Item__c>();
    riId_set = new Set<ID>();
    labor_list = new List<itemClass>();

    totalRequestedAmount = 0;
    amountError = false;

    att_list = new List<Attachment>();

    selectedLabor = 0;
    displayLaborNotesPopup = false;
    displayAttPopup = false;

    if (RequestID != null) {
      request = requestClass.getRequest(RequestId);
      FTE = request.FTE__c;
      GrantID = request.Grant__c;
      getAttList();
    }

    if (GrantID != null) {
      grant = grantClass.getGrant(GrantID);
      if (grant.Id != null) {
        acct = [
          SELECT ID, Name, RecordType.Name
          FROM Account
          WHERE ID = :grant.Account__r.Id
        ];
      }
    }
  }

  public Boolean initalized = false;
  public void getLists() {
    if (!initalized) {
      if (request.Id != null) {
        ri_list.clear();
        ri_list = requestItemClass.getRequestItems(request.Id, 'labor');

        for (Reimbursement_Item__c ri : ri_list) {
          if (ri.Requested_Amount__c != null) {
            totalRequestedAmount += ri.Requested_Amount__c;
          }
          itemClass ic = new itemClass(this, laborCount, ri, RequestID);
          laborCount = laborCount + 1;
          labor_list.add(ic);
        }
      }
      updateAmounts();
      initalized = true;
    }
  }

  // BEGIN getAttList
  public void getAttList() {
    att_list.clear();
    Reimbursement_Request__c r = [
      SELECT
        Id,
        (
          SELECT Id, Name, Description
          FROM Attachments
          ORDER BY LastModifiedDate DESC
        )
      FROM Reimbursement_Request__c
      WHERE Id = :request.Id
    ];
    Set<String> names = new Set<String>();
    for (Attachment a : r.Attachments) {
      if (
        a.Name == 'Payroll' ||
        a.Name == 'Timesheet' ||
        a.Name == 'Benefits' ||
        a.Name == 'Other Personnel Documentation'
      ) {
        if (!names.contains(a.Name)) {
          att_list.add(a);
          names.add(a.Name);
        }
      }
    }
  }
  // END getAttList

  // BEGIN deleteAtt
  public void deleteAtt() {
    if (deleteAttId != null) {
      Attachment a = [SELECT Id FROM Attachment WHERE Id = :deleteAttId];
      if (a != null) {
        attachClass.deleteAttachment(a);
      }
    }
    getAttList();
  }
  // END deleteAtt

  // BEGIN updateAmounts
  public void updateAmounts() {
    requestSub = 0;
    fICASub = 0;
    medicalSub = 0;
    dentalSub = 0;
    shortTermSub = 0;
    longTermSub = 0;
    lifeSub = 0;
    otherSub = 0;
    benefitsSub = 0;
    requstedBenefitsSub = 0;
    totalRequestedAmount = 0;
    errorMessage = '';
    FTE = 0;

    for (itemClass ic : labor_list) {
      if (
        ic.reimItem.Quantity__c > 0 &&
        ic.reimItem.Quantity_Towards_Grant__c > 0 &&
        ic.reimItem.Rate__c > 0
      ) {
        ic.monthlyTotal = (ic.reimItem.Quantity__c * ic.reimItem.Rate__c)
          .setScale(2);
        ic.reimItem.Percent_Towards_Grant__c =
          ic.reimItem.Quantity_Towards_Grant__c /
          ic.reimItem.Quantity__c *
          100;
        ic.reimItem.Requested_Salary__c = (ic.reimItem.Quantity_Towards_Grant__c *
          ic.reimItem.Rate__c)
          .setScale(2);

        Decimal fb = 0;
        ic.reimItem.Fringe_Benefit__c = 0;
        if (ic.reimItem.FICA__c != null) {
          fb += ic.reimItem.FICA__c;
          ficaSub += ic.reimItem.FICA__c;
        }
        if (ic.reimItem.Medical__c != null) {
          fb += ic.reimItem.Medical__c;
          medicalSub += ic.reimItem.Medical__c;
        }
        if (ic.reimItem.Dental__c != null) {
          fb += ic.reimItem.Dental__c;
          dentalSub += ic.reimItem.Dental__c;
        }
        if (ic.reimItem.Short_Term_Disability__c != null) {
          fb += ic.reimItem.Short_Term_Disability__c;
          shortTermSub += ic.reimItem.Short_Term_Disability__c;
        }
        if (ic.reimItem.Long_Term_Disability__c != null) {
          fb += ic.reimItem.Long_Term_Disability__c;
          longTermSub += ic.reimItem.Long_Term_Disability__c;
        }
        if (ic.reimItem.Life__c != null) {
          fb += ic.reimItem.Life__c;
          lifeSub += ic.reimItem.Life__c;
        }
        if (ic.reimItem.Other_Benefits__c != null) {
          fb += ic.reimItem.Other_Benefits__c;
          otherSub += ic.reimItem.Other_Benefits__c;
        }
        if (fb > 0) {
          ic.reimItem.Fringe_Benefit__c += fb;
          benefitsSub += fb;
        }
        ic.reimItem.Requested_Benefits__c = (ic.reimItem.Fringe_Benefit__c *
          ic.reimItem.Percent_Towards_Grant__c /
          100)
          .setScale(2);
        requstedBenefitsSub += ic.reimItem.Requested_Benefits__c;

        requestSub += ic.reimItem.Requested_Salary__c;
        ic.reimItem.Requested_Amount__c = (ic.reimItem.Requested_Salary__c +
          ic.reimItem.Requested_Benefits__c)
          .setScale(2);
        totalRequestedAmount += ic.reimItem.Requested_Amount__c;
        FTE += ic.reimItem.Quantity_Towards_Grant__c;
      } else {
        ic.monthlyTotal = 0;
        //ic.reimItem.Quantity__c = 0;
        ic.reimItem.Quantity_Towards_Grant__c = 0;
        ic.reimItem.Percent_Towards_Grant__c = 0;
        ic.reimItem.Requested_Salary__c = 0;
        ic.reimItem.Requested_Benefits__c = 0;
        ic.reimItem.Requested_Amount__c = 0;
      }
      if (ic.reimItem.Percent_Towards_Grant__c > 100) {
        errorMessage = 'The hours worked on grant should not exceed total number of hours worked';
      }
    }
    if (request.Total_FTE_at_Affiliate__c == 0) {
      FTE = 0;
    } else if (request.Total_FTE_at_Affiliate__c != null) {
      FTE = FTE / request.Total_FTE_at_Affiliate__c * 100;

      if (FTE > 100) {
        errorMessage = 'Invalid FTE';
      }
    }
    if (totalRequestedAmount > grant.Balance__c) {
      amountError = true;
      errorMessage = 'Requested Amount Exceeds Sub-Grant Balance';
    } else {
      amountError = false;
    }
  }
  // END updateAmounts

  // BEGIN saveLabor
  public void saveLabor() {
    updateAmounts();

    request.FTE__c = FTE;
    requestClass.upsertRequest(request);

    List<Reimbursement_Item__c> labor_update_list = new List<Reimbursement_Item__c>();

    // COMPARE EXISTING REIMBURSEMENT ITEMS TO NEW ITEMS
    for (itemClass ic : labor_list) {
      for (Reimbursement_Item__c ri : ri_list) {
        system.debug('>>> ri = ' + ri);
        if (
          ic.reimItem != null &&
          ic.reimItem.Id == ri.Id &&
          ri.RecordType.Name == 'Labor'
        ) {
          if (ic.itemNote != null) {
            ri.Item_Note__c = ic.ItemNote;
          }
          labor_update_list.add(ri);
        }
      }
    }

    requestItemClass.upsertItems(labor_update_list);
  }
  // END saveLabor

  // BEGIN previous
  public PageReference previous() {
    saveLabor();

    PageReference pr = new PageReference(
      '/' +
      portalName +
      'RequestForm?GrantID=' +
      GrantID +
      '&RequestID=' +
      RequestID
    );
    pr.setRedirect(true);
    return pr;
  }
  // END previous

  // BEGIN saveAndContinue
  public PageReference saveAndContinue() {
    saveLabor();

    if (totalRequestedAmount > 0 && portalName != 'DMV') {
      Boolean hasPayroll = false;
      Boolean hasTimesheet = false;
      for (Attachment a : att_list) {
        if (a.Name == 'Timesheet') {
          hasTimesheet = true;
        }
        if (a.Name == 'Payroll') {
          hasPayroll = true;
        }
      }
      if (!hasTimesheet) {
        errorMessage = 'A Timesheet is required';
      }
      if (!hasPayroll) {
        errorMessage = 'A Payroll document is required';
      }
    }

    if (String.isBlank(errorMessage)) {
      PageReference pr = new PageReference(
        '/' +
        portalName +
        'RequestExpensesForm?GrantID=' +
        GrantID +
        '&RequestID=' +
        RequestID
      );
      pr.setRedirect(true);
      return pr;
    }
    return null;
  }
  // END saveAndContinue

  // BEGIN saveAndExit
  public PageReference saveAndExit() {
    saveLabor();

    if (String.isBlank(errorMessage)) {
      PageReference pr = new PageReference('/Reimbursements');
      pr.setRedirect(true);
      return pr;
    }
    return null;
  }
  // END saveAndExit

  // BEGIN popups
  public void laborNotesPopup() {
    system.debug('>>> selectedLabor = ' + selectedLabor);
    if (displayLaborNotesPopup == true) {
      displayLaborNotesPopup = false;
    } else {
      displayLaborNotesPopup = true;
    }
  }

  public void attPopup() {
    getAttList();
    if (displayAttPopup == true) {
      displayAttPopup = false;
    } else {
      displayAttPopup = true;
    }
  }
  // END popups

  // BEGIN INNER CLASS
  public class itemClass {
    RequestPersonnelFormController outerClass;

    public Integer itemIndex { get; set; }
    public Reimbursement_Item__c reimItem { get; set; }
    public String itemName { get; set; }
    public Id requestId { get; set; }
    public Id recordTypeId { get; set; }
    public Decimal monthlyTotal { get; set; } //Before deductions
    public Decimal factorPercent { get; set; }
    public String itemNote { get; set; }
    public String response { get; set; }
    public Integer noteCount { get; set; }

    public itemClass(
      RequestPersonnelFormController outerClass,
      Integer intCount,
      Reimbursement_Item__c ri,
      ID rId
    ) {
      this.outerClass = outerClass;
      itemIndex = intCount;
      reimItem = ri;
      requestId = rId;
      itemName = ri.Budget_Item__r.Name;
      itemNote = ri.Item_Note__c;
      response = ri.Response__c;
      noteCount = 0;
      if (itemNote != null) {
        noteCount = noteCount + 1;
      }
      if (response != null) {
        noteCount = noteCount + 1;
      }
      if (ri.Rate__c != null) {
        if (ri.Quantity__c != null) {
          monthlyTotal = (ri.Quantity__c * ri.Rate__c).setScale(2);
          if (ri.Quantity_Towards_Grant__c != null) {
            ri.Requested_Salary__c = (ri.Quantity_Towards_Grant__c * ri.Rate__c)
              .setScale(2);
          }
        }
      } else {
        monthlyTotal = 0;
        ri.Requested_Salary__c = 0;
      }
      if (ri.Fringe_Benefit__c != null && ri.Percent_Towards_Grant__c != null) {
        ri.Requested_Benefits__c = (ri.Fringe_Benefit__c *
          ri.Percent_Towards_Grant__c /
          100)
          .setScale(2);
      } else {
        ri.Requested_Benefits__c = 0;
      }
    }
  }
}