force-app/main/default/objects/Budget_Item__c/Budget_Item__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Budget Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child Safety</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contract Specialists</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Fringe Benefits</fullName>
            </value>
            <value>
                <fullName>Other Costs</fullName>
            </value>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Sub Awards</fullName>
            </value>
            <value>
                <fullName>Consultant Travel</fullName>
            </value>
            <value>
                <fullName>Indirect Costs</fullName>
            </value>
            <value>
                <fullName>Procurement Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Budget Items</relationshipLabel>
    <relationshipName>Budget_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Items: Approved Amount where Reimbursement Status = Approved, Paid, Closed</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Reimbursement_Item__c.Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field
    >Reimbursement_Item__c.Reimbursement_Status_for_Formula_Fields__c</field>
        <operation>contains</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Item__c.Budget_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Items: Requested Amount where Reimbursement Status != Incomplete or Denied</inlineHelpText>
    <label>Total Requested Amount</label>
    <summarizedField>Reimbursement_Item__c.Requested_Amount__c</summarizedField>
    <summaryFilterItems>
        <field
    >Reimbursement_Item__c.Reimbursement_Status_for_Formula_Fields__c</field>
        <operation>notEqual</operation>
        <value>Incomplete, Denied</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Item__c.Budget_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget_Item__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Budget_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Requests: Total Approved Amount where Status = Approved, Paid, Closed</inlineHelpText>
    <label>Reimbursement Approved Amount</label>
    <summarizedField
  >Reimbursement_Request__c.Total_Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Requested_Amount__c</fullName>
    <formula
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c</inlineHelpText>
    <label>Total Reimbursement Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursements_Pending_Approval__c.field-meta.xml
<CustomField>
    <fullName>Reimbursements_Pending_Approval__c</fullName>
    <label>Reimbursements Pending Approval</label>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value
    >Pending First Approval, Pending Second Approval, Pending Third Approval, Pending Fourth Approval, Pending Final Approval, Submitted</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Approved Amount</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Budget_Item__c.Total_Approved_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Budgeted__c.field-meta.xml
<CustomField>
    <fullName>Total_Budgeted__c</fullName>
    <formula>IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;,
Total_Item_Budget__c + Total_Fringe_Benefits__c +
IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), Indirect_Rate_Amount__c, 0),
Total_Indirect_Rate_Budgeted__c + IF(AND(NOT(ISPICKVAL(Grant_Status__c, &apos;Approved&apos;)), NOT(ISPICKVAL(Grant_Status__c, &apos;Closed&apos;))), Total_New_Item_Budget__c,Total_Item_Budget__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >if Org = BBBSA: Total_Item_Budget__c + Total_Fringe_Benefits__c +  Indirect_Rate_Amount__c.
else: Total_Item_Budget__c +  Total_Indirect_Rate_Budgeted__c)</inlineHelpText>
    <label>Total Budgeted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Requested Amount</inlineHelpText>
    <label>Total Requested Amount</label>
    <summarizedField>Budget_Item__c.Total_Requested_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/GrantDetailsController.cls
public with sharing class GrantDetailsController {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public Account acct { get; set; }
  public String portalName { get; set; }
  public String url { get; set; }
  public String approverLevel { get; set; }

  public GrantClass gc = new GrantClass();
  public BudgetItemClass bic = new BudgetItemClass();
  private getIdFromString gifs = new getIdFromString();

  public ID grantId { get; set; }
  public Grant__c grant { get; set; }
  public Decimal awarded { get; set; }
  public Decimal budgeted { get; set; }
  public Decimal requested { get; set; }
  public Decimal approved { get; set; }

  public Map<String, List<Budget_Item__c>> labor_map { get; set; }
  public Map<String, List<Budget_Item__c>> expense_map { get; set; }
  public Boolean hasLabor { get; set; }
  public Boolean hasExpenses { get; set; }
  public String errorMessage { get; set; }

  public Sertifi2_0__EDocument__c mou { get; set; }
  public Attachment mouAtt { get; set; }

  public Boolean canCloseGrant { get; set; }
  public Boolean displayCloseGrantPopup { get; set; }

  // BEGIN Constructor
  public GrantDetailsController() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    portalName = userClass.userProfile;
    approverLevel = userClass.approverLevel;

    url = '';
    if (portalName == 'NPAL')
      url = 'NPAL';

    labor_map = new Map<String, List<Budget_Item__c>>();
    expense_map = new Map<String, List<Budget_Item__c>>();
    hasLabor = false;
    hasExpenses = false;

    awarded = 0;
    budgeted = 0;
    requested = 0;
    approved = 0;

    String urlGrantId = ApexPages.currentPage().getParameters().get('grantId');
    grantId = gifs.getId(urlGrantId);
    if (grantId != null) {
      grant = gc.getGrant(GrantId);
      acct = [
        SELECT ID, Name, RecordType.Name
        FROM Account
        WHERE ID = :grant.Account__r.Id
      ];

      Sertifi2_0__EDocument__c[] eDocs = [
        SELECT
          Id,
          Name,
          Sertifi2_0__Status__c,
          Sertifi2_0__SignedLink__c,
          (SELECT Id FROM Attachments)
        FROM Sertifi2_0__EDocument__c
        WHERE
          Sertifi2_0__TestContract__r.Grant__c = :GrantId
          AND Sertifi2_0__Name__c = 'Letter of Agreement'
      ];
      if (eDocs.size() > 0) {
        mou = eDocs[0];
        mouAtt = eDocs[0].attachments[0];
      }

      if (grant.Grant_Status__c != 'Closed')
        canCloseGrant = true;
      for (
        Grant__c g : gc.getRelatedSubGrants(
          acct.Id,
          grant.Id,
          null,
          null,
          null,
          null,
          null
        )
      ) {
        if (g.Amount__c != null) {
          awarded += g.Amount__c;
        }
        if (g.Total_Budgeted__c != null) {
          budgeted += g.Total_Budgeted__c;
        }
        if (g.Total_Requested_Amount__c != null) {
          requested += g.Reimbursement_Requested_Amount__c;
        }
        if (g.Total_Approved_Amount__c != null) {
          approved += g.Reimbursement_Approved_Amount__c;
        }
        if (g.Reimbursements_Pending_Approval__c > 0)
          canCloseGrant = false;
      }
      awarded = awarded.setScale(2);
      budgeted = budgeted.setScale(2);
      requested = requested.setScale(2);
      approved = approved.setScale(2);

      for (Budget_Item__c bi : bic.getBudgetItems(GrantId)) {
        if (bi.RecordType.Name == 'Expense') {
          system.debug('>>> expense item = ' + bi);
          if (expense_map.containsKey(bi.Category__c)) {
            List<Budget_Item__c> bi_list = expense_map.get(bi.Category__c);
            bi_list.add(bi);
            expense_map.put(bi.Category__c, bi_list);
          } else {
            expense_map.put(bi.Category__c, new List<Budget_Item__c>{ bi });
          }
          if (expense_map.keySet() != null) {
            hasExpenses = true;
          }
        } else {
          system.debug('>>> labor item = ' + bi);
          if (labor_map.containsKey(bi.Category__c)) {
            List<Budget_Item__c> bi_list = labor_map.get(bi.Category__c);
            bi_list.add(bi);
            labor_map.put(bi.Category__c, bi_list);
          } else {
            labor_map.put(bi.Category__c, new List<Budget_Item__c>{ bi });
          }
          if (labor_map.keySet() != null) {
            hasLabor = true;
          }
        }
      }
      system.debug('>>> expense_map count = ' + expense_map.size());
      system.debug('>>> labor_map count = ' + labor_map.size());
    }
  }
  // END Constructor

  public ApexPages.PageReference init() {
    if (grantId == null || grant == null) {
      PageReference pageRef = new PageReference('/Error');
      return pageRef;
    }
    return null;
  }

  // BEGIN closeGrant
  public void closeGrant() {
    gc.closeGrant(grant.Id);
    hideCloseGrantPopup();
  }
  // END closeGrant

  // BEGIN popups
  public void showCloseGrantPopup() {
    displayCloseGrantPopup = true;
  }
  public void hideCloseGrantPopup() {
    displayCloseGrantPopup = false;
  }
  // END popups

  public PageReference goToSubGrantList() {
    PageReference pr = new PageReference(
      '/' +
      url +
      'SubGrantList?grantId=' +
      grantId
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference goToReimbursementsList() {
    PageReference pr = new PageReference(
      '/' +
      url +
      'ReimbursementList?grantId=' +
      grantId
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference goToReportsList() {
    PageReference pr = new PageReference(
      '/' +
      url +
      'GranteeReportList?grantId=' +
      grantId
    );
    pr.setRedirect(true);
    return pr;
  }

  public PageReference createDrawdown() {
    PageReference pr = new PageReference('/DrawdownReport?grantId=' + grantId);
    pr.setRedirect(true);
    return pr;
  }
}