force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <label>Group Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Has_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Has_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Attachment(s)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>Organization__r.Local_Organization_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Modification_History__c.field-meta.xml
<CustomField>
    <fullName>Modification_History__c</fullName>
    <label>Modification History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reimbursement</label>
    <referenceTo>Reimbursement_Request__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Session_Report__c.field-meta.xml
<CustomField>
    <fullName>Session_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Report</label>
    <referenceTo>Session_Report__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/Session_Report__c.object-meta.xml
<CustomObject>
    <label>Session Report</label>
    <nameField>
        <label>Session Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Report__c/fields/Local_Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Organization_Id__c</fullName>
    <formula>CASESAFEID( Site__r.Local_Organization__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Organization Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Report__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Reports</relationshipLabel>
    <relationshipName>Session_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DocumentClass.cls
public without sharing class DocumentClass {
  public String soql { get; set; }
  public Set<Id> docIds { get; set; }

  public String getSOQL(
    Id orgId,
    Id grantId,
    Id assessId,
    Id reportId,
    Id requestId,
    String groupId,
    String soqlAND,
    Boolean includeAtts
  ) {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Document__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr;
    if (includeAtts)
      soql += ', (SELECT Id, Name, Description, ParentId FROM Attachments)';
    soql += ' FROM Document__c ';
    String soqlWhere = ' WHERE Name != null ';
    if (assessId != null)
      soqlWhere += ' AND Assessment__c = \'' + assessId + '\'';
    else if (reportId != null)
      soqlWhere += ' AND Session_Report__c = \'' + reportId + '\'';
    else if (requestId != null)
      soqlWhere += ' AND Reimbursement__c = \'' + requestId + '\'';
    else if (grantId != null)
      soqlWhere += ' AND Grant__c = \'' + grantId + '\'';
    else if (orgId != null)
      soqlWhere +=
        ' AND (Local_Organization_Id__c = \'' +
        orgId +
        '\' OR Organization__c = \'' +
        orgId +
        '\')';

    if (groupId != null && groupId != '')
      soqlWhere += ' AND Group_Id__c = \'' + groupId + '\'';
    if (soqlAND != null && soqlAND != '')
      soqlWhere += soqlAND;
    system.debug('DocumentClass soqlWhere = ' + soqlWhere);
    soql += soqlWhere + ' ORDER BY Name';
    soql += ' LIMIT 1000';
    return soql;
  }

  public List<Document__c> getDocList(
    Id orgId,
    Id grantId,
    Id assessId,
    Id reportId,
    Id requestId,
    String groupId,
    String soqlAND
  ) {
    getSOQL(
      orgId,
      grantId,
      assessId,
      reportId,
      requestId,
      groupId,
      soqlAND,
      false
    );
    docIds = new Set<Id>();
    List<Document__c> doc_list = new List<Document__c>();
    for (Document__c d : database.query(soql)) {
      doc_list.add(d);
      docIds.add(d.Id);
    }
    system.debug('DocumentClass getDocList doc_list = ' + doc_list);
    return doc_list;
  }

  public List<Document__c> getDocWithAttList(
    Id orgId,
    Id grantId,
    Id assessId,
    Id reportId,
    Id requestId,
    String groupId,
    String soqlAND
  ) {
    getSOQL(
      orgId,
      grantId,
      assessId,
      reportId,
      requestId,
      groupId,
      soqlAND,
      true
    );
    List<Document__c> doc_list = database.query(soql);
    system.debug('DocumentClass getDocWithAttList doc_list = ' + doc_list);
    return doc_list;
  }

  public List<Attachment> getAttList() {
    List<Attachment> att_list = new List<Attachment>();
    for (Attachment a : [
      SELECT Id, Name, ParentId, Description, CreatedDate
      FROM Attachment
      WHERE ParentId IN :docIds
    ]) {
      att_list.add(a);
    }
    system.debug('DocumentClass getAttList att_list = ' + att_list);
    return att_list;
  }

  public void upsertDoc(Document__c doc) {
    try {
      upsert doc;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void upsertDocs(List<Document__c> docs) {
    try {
      upsert docs;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void deleteDoc(Document__c doc) {
    try {
      delete doc;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }

  public void getHasAtts(
    Map<Id, Id> parent_contact_ids,
    Map<Id, String> modHist
  ) {
    List<Document__c> docs = new List<Document__c>();
    for (Document__c d : [
      SELECT
        Id,
        Has_Attachments__c,
        Submitted_By__c,
        Submitted_Date__c,
        Modification_History__c,
        (SELECT Id FROM Attachments)
      FROM Document__c
      WHERE Id IN :parent_contact_ids.keySet()
    ]) {
      d.Submitted_By__c = parent_contact_ids.get(d.Id);
      d.Submitted_Date__c = date.today();
      if (d.Modification_History__c == null)
        d.Modification_History__c = modHist.get(d.Id);
      else
        d.Modification_History__c += ' \r\n' + modHist.get(d.Id);
      d.Has_Attachments__c = false;
      for (Attachment a : d.Attachments)
        d.Has_Attachments__c = true;
      docs.add(d);
    }
    try {
      upsert docs;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
    }
  }
}