force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/Program_Report__c.object-meta.xml
<CustomObject>
    <label>Program Report</label>
    <nameField>
        <label>Program Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Program Reports</relationshipLabel>
    <relationshipName>Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <label>Grant Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017 - 2018</fullName>
            </value>
            <value>
                <fullName>2018 - 2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019 - 2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Report__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <formula>Site__r.Local_Organization__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Org Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/Youth_in_Program_Report__c.object-meta.xml
<CustomObject>
    <label>Youth in Program Report</label>
    <nameField>
        <displayFormat>Y-{0000}</displayFormat>
        <label>Youth in Program Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Youth in Program Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Youth in Program Reports</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Youth in Program Reports</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Grant_Year__c.field-meta.xml
<CustomField>
    <fullName>Grant_Year__c</fullName>
    <formula>IF(TEXT(Program_Report__r.Grant_Year__c) != null,
TEXT(Program_Report__r.Grant_Year__c), 
IF(Grant__r.Year__c != null, Grant__r.Year__c, &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grant Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <formula
  >IF(OR(ISBLANK(Program_Report__c), ISNULL(Program_Report__c)), Grant__r.Account__r.Name, Program_Report__r.Org_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Org Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Program_Report__c.field-meta.xml
<CustomField>
    <fullName>Program_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Report</label>
    <referenceTo>Program_Report__c</referenceTo>
    <relationshipLabel>Youth</relationshipLabel>
    <relationshipName>Youth_in_Program_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Contact__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YouthInProgramReportClass.cls
public without sharing class YouthInProgramReportClass {
  public YouthInProgramReportClass() {
  }
  public String soql { get; set; }

  public void getSoql() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Youth_in_Program_Report__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM Youth_in_Program_Report__c';
  }

  public Youth_in_Program_Report__c getYPR(
    Id yprId,
    Id contactId,
    Id reportId,
    Id grantId
  ) {
    getSOQL();
    Youth_in_Program_Report__c ypr = new Youth_in_Program_Report__c();
    soql += ' WHERE Name != null';
    if (yprId != null)
      soql += ' AND Id = \'' + yprId + '\'';
    else {
      if (contactId != null)
        soql += ' AND Contact__c = \'' + contactId + '\'';
      if (reportId != null)
        soql += ' AND Program_Report__c = \'' + reportId + '\'';
      if (grantId != null)
        soql += ' AND Grant__c = \'' + grantId + '\'';
    }
    system.debug('Youth_in_Program_Report__c soql = ' + soql);
    Youth_in_Program_Report__c[] yprs = Database.query(soql);
    if (yprs.size() > 0)
      ypr = yprs[0];
    return ypr;
  }

  public List<Youth_in_Program_Report__c> getRelatedYPRList(
    Set<Id> prIds,
    String sortBy
  ) {
    getSOQL();
    soql += ' WHERE Program_Report__c IN :prIds AND Is_Deleted__c = false';
    if (sortBy != null && sortBy != '')
      soql += ' ORDER BY ' + sortBy;
    else
      soql += ' ORDER BY Site_Name__c, Contact_Name__c';
    soql += ' LIMIT 1000';
    system.debug('Youth_in_Program_Report__c soql = ' + soql);
    List<Youth_in_Program_Report__c> yprs = Database.query(soql);
    return yprs;
  }

  public List<Youth_in_Program_Report__c> getRelatedGrantYPRList(
    Set<Id> gIds,
    String sortBy
  ) {
    getSOQL();
    soql += ' WHERE Grant__c IN :gIds AND Is_Deleted__c = false';
    if (sortBy != null && sortBy != '')
      soql += ' ORDER BY ' + sortBy;
    else
      soql += ' ORDER BY Org_Name__c, Contact_Name__c';
    soql += ' LIMIT 1000';
    system.debug('Youth_in_Program_Report__c soql = ' + soql);
    List<Youth_in_Program_Report__c> yprs = Database.query(soql);
    return yprs;
  }

  public List<Youth_in_Program_Report__c> getYouthYPRList(Id youthId) {
    getSOQL();
    soql +=
      ' WHERE Contact__c = \'' +
      youthId +
      '\' AND Is_Deleted__c = false ORDER BY Grant_Year__c';
    system.debug('Youth_in_Program_Report__c soql = ' + soql);
    List<Youth_in_Program_Report__c> yprs = Database.query(soql);
    return yprs;
  }

  public void upsertYPR(Youth_in_Program_Report__c ypr) {
    try {
      upsert ypr;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  public void upsertYPRs(List<Youth_in_Program_Report__c> yprs) {
    try {
      upsert yprs;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  public void deleteYPR(Youth_in_Program_Report__c ypr) {
    ypr.Is_Deleted__c = true;
    try {
      upsert ypr;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}