force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Breakdown_of_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Breakdown_of_Expenses__c</fullName>
    <label>Breakdown of Expenses</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Opportunities_Provided_by_Funding__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Provided_by_Funding__c</fullName>
    <label>Opportunities Provided by Funding</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Overview_of_Outcomes_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Overview_of_Outcomes_Achieved__c</fullName>
    <label>Overview of Outcomes Achieved</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Report_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Submitted_Date__c</fullName>
    <label>Report Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Successes_Challenges_Experiencesd__c.field-meta.xml
<CustomField>
    <fullName>Successes_Challenges_Experiencesd__c</fullName>
    <label>Successes/Challenges Experiencesd</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Unmet_Needs_Description__c.field-meta.xml
<CustomField>
    <fullName>Unmet_Needs_Description__c</fullName>
    <label>Unmet Needs Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/GranteeReportCtrl.cls
public class GranteeReportCtrl {
  public ID GrantID { get; set; }
  public Grant__c grant { get; set; }
  public Boolean showSuccess { get; set; }

  public GranteeReportCtrl() {
    GrantID = ApexPages.currentPage().getParameters().get('GrantId');
    grant = new Grant__c();

    if (GrantID != null) {
      grant = [
        SELECT
          Name,
          Account__r.Name,
          Project_Name__c,
          Overview_of_Outcomes_Achieved__c,
          Successes_Challenges_Experiencesd__c,
          Opportunities_Provided_by_Funding__c,
          Breakdown_of_Expenses__c,
          Unmet_Needs_Description__c
        FROM Grant__c
        WHERE Id = :GrantId
      ];
    }
  }

  public void save() {
    grant.Report_Submitted_Date__c = date.today();
    try {
      update grant;
      showSuccess = true;
    } catch (Exception e) {
      system.debug('>>> error = ' + e.getMessage());
    }
  }
}