force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant__c.field-meta.xml
<CustomField>
    <fullName>National_Grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Grant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Grant__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Grant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Sub-Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Type__c</fullName>
    <formula>TEXT(National_Grant__r.Grant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Number_of_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Approvals_Required__c</fullName>
    <defaultValue>3</defaultValue>
    <label># of Approvals Required</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Prevent_Skip_Reimbursement_Approvals__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Skip_Reimbursement_Approvals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prevent Skip Reimbursement Approvals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Primary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Account__r.Primary_Approver__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Approved Amount</inlineHelpText>
    <label>Total Approved Amount</label>
    <summarizedField>Budget_Item__c.Total_Approved_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Item_Balance__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Balance__c</fullName>
    <formula>Total_Item_Budget__c - Reimbursement_Approved_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Total_Item_Budget__c - Reimbursement_Approved_Amount__c</inlineHelpText>
    <label>Total Item Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Budget Item: Total Requested Amount</inlineHelpText>
    <label>Total Requested Amount</label>
    <summarizedField>Budget_Item__c.Total_Requested_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Item__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/Reimbursement_Request__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reimbursement Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reimbursement_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>Grant</label>
    <referenceTo>Grant__c</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Reimbursement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Is_National_Request__c.field-meta.xml
<CustomField>
    <fullName>Is_National_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is National Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_Four_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Level_Four_Approved_Date__c</fullName>
    <label>Level Four Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_One_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Level_One_Approved_Date__c</fullName>
    <label>Level One Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_One_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level_One_Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Level One Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reimbursement Requests</relationshipLabel>
    <relationshipName>Level_One_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_Three_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Level_Three_Approved_Date__c</fullName>
    <label>Level Three Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_Three_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level_Three_Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Level Three Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel
  >Reimbursement Requests (Level Three Approver)</relationshipLabel>
    <relationshipName>Level_Three_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_Two_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Level_Two_Approved_Date__c</fullName>
    <label>Level Two Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Level_Two_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level_Two_Approver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Level Two Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel
  >Reimbursement Requests (Level Two Approver)</relationshipLabel>
    <relationshipName>Level_Two_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Number_of_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Approvals_Required__c</fullName>
    <formula
  >Grant__r.National_Grant__r.Number_Reimbursement_Approvals_Required__c</formula>
    <label># of Approvals Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <formula>Grant__r.Account__r.Name</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Prevent_Skip_Reimbursement_Approvals__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Skip_Reimbursement_Approvals__c</fullName>
    <formula
  >OR(Grant__r.Prevent_Skip_Reimbursement_Approvals__c,  Grant__r.National_Grant__r.Prevent_Skip_Reimbursement_Approvals__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prevent Skip Reimbursement Approvals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Primary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Grant__r.Account__r.Primary_Approver__c)</formula>
    <label>Primary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Primary_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Name__c</fullName>
    <formula
  >Grant__r.Account__r.Primary_Approver__r.FirstName + &apos; &apos; +  Grant__r.Account__r.Primary_Approver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Revision in Progress</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Amount__c</fullName>
    <formula>Approved_Salary__c + Approved_Benefits__c + Approved_Expenses__c + 
IF(AND( 
NOT(ISPICKVAL(Status__c, &apos;Incomplete&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Revisions Needed&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Revisions in Progress&apos;)), 
NOT(ISPICKVAL(Status__c, &apos;Denied&apos;)),
NOT(ISPICKVAL(Status__c, &apos;Pending First Approval&apos;))
), 
Indirect_Rate_Amount__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Approved_Salary__c + Approved_Benefits__c + Approved_Expenses__c + 
IF([Status__c not any Incomplete], Indirect_Rate_Amount__c, 0)</inlineHelpText>
    <label>Total Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_Requested__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested__c</fullName>
    <formula
  >Requested_Salary__c + Requested_Benefits__c + Requested_Expenses__c + Indirect_Rate_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Requested_Salary__c + Requested_Benefits__c + Requested_Expenses__c + Indirect_Rate_Amount__c</inlineHelpText>
    <label>Total Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reimbursement_Request__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <formula
  >Requested_Amount__c + IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), IF( Grant__r.National_Grant_Type__c == &apos;OVC&apos;, Requested_Indirect_Costs__c, Indirect_Rate_Amount__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Requested_Amount__c + IF(ISPICKVAL(Grant__r.Use_Indirect_Rate__c, &apos;Yes&apos;), Indirect_Rate_Amount__c, 0)</inlineHelpText>
    <label>Requested + Indirect Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReimbursementClass.cls
public without sharing class ReimbursementClass {
  public String soql { get; set; }

  public ReimbursementClass() {
    getSOQL();
  }

  public String getSOQL() {
    String fields = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Reimbursement_Request__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      fields += fieldName + ', ';
    }
    //fields = fields.removeEnd(', ');
    fields += 'Grant__r.Name, Grant__r.Amount__c, Grant__r.Total_Item_Balance__c, Grant__r.Account__c, Grant__r.Account__r.Id, Grant__r.National_Grant__r.Account__c, Grant__r.National_Grant__r.Account__r.Id';
    fields += ', Level_One_Approver__r.Name, Level_Two_Approver__r.Name, Level_Three_Approver__r.Name';
    fields += ',(SELECT ID, Name, Description FROM Attachments ORDER BY LastModifiedDate desc)';

    soql = 'SELECT ' + fields + ' FROM Reimbursement_Request__c';
    return soql;
  }

  public Reimbursement_Request__c getRequest(Id requestId) {
    getSOQL();
    Reimbursement_Request__c request = new Reimbursement_Request__c();
    if (requestId != null) {
      soql += ' WHERE Id = \'' + requestId + '\'';
      Reimbursement_Request__c[] requests = Database.query(soql);
      if (requests.size() > 0) {
        request = requests[0];
      }
    }
    return request;
  }

  public List<Reimbursement_Request__c> getRequestList() {
    getSOQL();
    List<Reimbursement_Request__c> requestList = new List<Reimbursement_Request__c>();
    soql += ' ORDER BY Request_Date__c asc';
    requestList = Database.query(soql);
    return requestList;
  }

  public List<Reimbursement_Request__c> getRelatedRequests(
    Id acctId,
    Id grantId,
    String status,
    String sortBy,
    String orgName,
    String keyword,
    Id primaryApproverId,
    String soqlAND
  ) {
    List<Reimbursement_Request__c> requests = new List<Reimbursement_Request__c>();

    String qry = 'SELECT Id, Name, LastModifiedDate, Is_National_Request__c, Grant__r.Account__r.Id, Grant__r.Name, Grant__r.Grant_Type__c, Grant__r.National_Grant_Type__c, Primary_Approver_Id__c, Primary_Approver_Name__c, Number_of_Approvals_Required__c';
    qry += ', Organization__c, Request_Date__c, Start_Date__c, End_Date__c, Status__c, Paid_Date__c, Total_Approved_Amount__c, Total_Requested__c, Total_Requested_Amount__c, Prevent_Skip_Reimbursement_Approvals__c';
    qry += ', Level_One_Approved_Date__c, Level_Two_Approved_Date__c, Level_Three_Approved_Date__c, Level_Four_Approved_Date__c, Level_One_Sent_Back_Date__c, Level_Two_Sent_Back_Date__c, Level_Three_Sent_Back_Date__c, Level_Four_Sent_Back_Date__c, Level_One_Sent_Back_Count__c, Level_Two_Sent_Back_Count__c, Level_Three_Sent_Back_Count__c, Level_Four_Sent_Back_Count__c, Modification_Last_Submitted_Date__c';
    qry += ' FROM Reimbursement_Request__c WHERE Name != null';
    if (grantId != null) {
      qry +=
        ' AND (Grant__r.Id = \'' +
        grantId +
        '\' OR Grant__r.National_Grant__r.Id = \'' +
        grantId +
        '\')';
    } else if (acctId != null) {
      qry +=
        ' AND (Grant__r.Account__r.Id = \'' +
        acctId +
        '\' OR Grant__r.National_Grant__r.Account__r.Id = \'' +
        acctId +
        '\')';
    }
    if (keyword != '' && keyword != null) {
      qry +=
        ' AND (Name LIKE \'%' +
        keyword +
        '%\' OR Grant__r.Name LIKE \'%' +
        keyword +
        '%\')';
    } else {
      if (status != '' && status != null && status != 'View All') {
        if (status.toLowerCase() == 'pendingfirst')
          status = 'Pending First Approval';
        if (status.toLowerCase() == 'pendingsecond')
          status = 'Pending Second Approval';
        if (
          status.toLowerCase() == 'pendingfinal' ||
          status.toLowerCase() == 'pendingthird'
        )
          status = 'Pending Third Approval';

        if (status == 'Pending Approval')
          qry += ' AND Status__c LIKE \'Pending%\'';
        else if (status == 'All Revisions')
          qry += ' AND Status__c LIKE \'Revision%\'';
        else if (status == 'All In Progress')
          qry += ' AND (Status__c LIKE \'Pending%\' OR Status__c LIKE \'Revision%\' OR Status__c = \'Incomplete\')';
        else
          qry += ' AND Status__c = \'' + status + '\'';

        if (status == 'Pending First Approval' && primaryApproverId != null) {
          qry += ' AND (Primary_Approver_Id__c = \'' + primaryApproverId + '\'';
          qry +=
            ' OR (Secondary_Approver_Id__c = \'' +
            primaryApproverId +
            '\'';
          qry += ' AND (Primary_Approver_On_Leave__c = true OR FirstPic_National_Org_Code__c = \'Ripken\')))';
        }
      }
      if (orgName != '' && orgName != null)
        qry += ' AND Organization__c LIKE \'%' + orgName + '%\'';
      if (soqlAND != '' && soqlAND != null)
        qry += soqlAND;
    }
    if (sortBy != '' && sortBy != null)
      qry += ' ORDER BY ' + sortBy + ' ASC LIMIT 1000';
    system.debug('getRelatedRequests qry = ' + qry);

    requests = database.query(qry);
    return requests;
  }

  public void upsertRequest(Reimbursement_Request__c request) {
    try {
      upsert request;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public void upsertRequestList(List<Reimbursement_Request__c> requestList) {
    try {
      upsert requestList;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }

  public void deleteRequest(Reimbursement_Request__c request) {
    try {
      delete request;
    } catch (Exception e) {
      system.debug('error = ' + e.getMessage());
      ApexPages.addMessage(
        new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage())
      );
    }
  }
}