force-app/main/default/objects/Grant__c/Grant__c.object-meta.xml
<CustomObject>
    <label>Grant</label>
    <nameField>
        <label>Grant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>IF(Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</description>
    <formula>IF(National_Grant__r.Allow_Budget_to_Exceed_Award__c = true,
Amount__c - Reimbursement_Approved_Amount__c, Total_Budgeted__c - Reimbursement_Approved_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Status__c.field-meta.xml
<CustomField>
    <fullName>Grant_Status__c</fullName>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application In Review</fullName>
            </value>
            <value>
                <fullName>LOA Submitted</fullName>
            </value>
            <value>
                <fullName>Budget Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending First Approval</fullName>
            </value>
            <value>
                <fullName>Pending Second Approval</fullName>
            </value>
            <value>
                <fullName>Pending Third Approval</fullName>
            </value>
            <value>
                <fullName>Pending Fourth Approval</fullName>
            </value>
            <value>
                <fullName>Pending Final Approval</fullName>
            </value>
            <value>
                <fullName>Revisions Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awarded</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Badges for Baseball</fullName>
            </value>
            <value>
                <fullName>Special Initiative</fullName>
            </value>
            <value>
                <fullName>I&apos;m GREAT</fullName>
            </value>
            <value>
                <fullName>STEM</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles</fullName>
            </value>
            <value>
                <fullName>TRAIL</fullName>
            </value>
            <value>
                <fullName>OVC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/National_Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>National_Grant_Type__c</fullName>
    <formula>TEXT(National_Grant__r.Grant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>National Grant Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Primary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Account__r.Primary_Approver__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Approved_Amount__c</fullName>
    <inlineHelpText
  >Roll-Up Summary of Reimbursement Requests: Total Approved Amount where Status = Approved, Paid, Closed</inlineHelpText>
    <label>Reimbursement Approved Amount</label>
    <summarizedField
  >Reimbursement_Request__c.Total_Approved_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Reimbursement_Request__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved, Paid, Closed</value>
    </summaryFilterItems>
    <summaryForeignKey>Reimbursement_Request__c.Grant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Reimbursement_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursement_Requested_Amount__c</fullName>
    <formula
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Reimbursement_Requested_Salary__c + Reimbursement_Requested_Benefits__c + Requested_Amount_Submitted__c + IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;, Requested_Indirect_Rate_Amount__c, Requested_Indirect_Costs__c</inlineHelpText>
    <label>Total Reimbursement Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Secondary_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Approver_Id__c</fullName>
    <formula>CASESAFEID(Account__r.Secondary_Approver__c)</formula>
    <label>Secondary Approver Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <formula
  >IF(ST_Baltimore_Gas_Electric__c &gt; 0, &apos;Baltimore Gas &amp; Electric &apos;, &apos;&apos;) + 
IF(ST_Bauer_Foundation__c &gt; 0, &apos;Bauer Foundation &apos;, &apos;&apos;) + 
IF(ST_CareFirst__c &gt; 0, &apos;CareFirst &apos;, &apos;&apos;) + 
IF(ST_Charles_Crane_Foundation__c &gt; 0, &apos;Charles Crane Foundation &apos;, &apos;&apos;) + 
IF(ST_COPS__c &gt; 0, &apos;COPS &apos;, &apos;&apos;) + 
IF(ST_CRSF__c &gt; 0, &apos;CRSF &apos;, &apos;&apos;) + 
IF(ST_Fund_II__c &gt; 0, &apos;Fund II &apos;, &apos;&apos;) + 
IF(ST_GEICO__c &gt; 0, &apos;GEICO &apos;, &apos;&apos;) + 
IF(ST_Healthy_Lifestyles_HL__c &gt; 0, &apos;Healthy Lifestyles (HL) &apos;, &apos;&apos;) + 
IF(ST_Herb_Block_Foundation__c &gt; 0, &apos;Herb Block Foundation &apos;, &apos;&apos;) + 
IF(ST_JeepChrysler__c &gt; 0, &apos;JeepChrysler &apos;, &apos;&apos;) + 
IF(ST_Marriott_Foundation__c &gt; 0, &apos;Marriott Foundation &apos;, &apos;&apos;) + 
IF(ST_Mississippi_Dept_of_Human_Services__c &gt; 0, &apos;Mississippi Dept. of Human Services &apos;, &apos;&apos;) + 
IF(ST_Naples_Children_Education__c &gt; 0, &apos;Naples Children &amp; Education Foundation &apos;, &apos;&apos;) + 
IF(ST_Niagara_Cares__c &gt; 0, &apos;Niagara Cares &apos;, &apos;&apos;) + 
IF(ST_Niagara_Cares_Hurricane_Relief__c &gt; 0, &apos;Niagara Cares Hurricane Relief Foundation &apos;, &apos;&apos;) + 
IF(ST_North_Carolina_Department_of_Justice__c &gt; 0, &apos;North Carolina Department of Justice &apos;, &apos;&apos;)+ 
IF(ST_Office_of_Juvenile_Justice__c &gt; 0, &apos;Office of Juvenile Justice &amp; Delinquency Prevention &apos;, &apos;&apos;) + 
IF(ST_Ohio_Office_of_the_Attorney_General__c &gt; 0, &apos;Ohio Office of the Attorney General &apos;, &apos;&apos;) + 
IF(ST_Perdue_Henson_Foundation__c &gt; 0, &apos;Perdue &amp; Henson Foundation &apos;, &apos;&apos;) + 
IF(ST_Prince_William_HIDTA__c &gt; 0, &apos;Prince William HIDTA &apos;, &apos;&apos;) + 
IF(ST_Private_Grants__c &gt; 0, &apos;Private Grants &apos;, &apos;&apos;) + 
IF(ST_Roanoke_HIDTA__c &gt; 0, &apos;Roanoke HIDTA &apos;, &apos;&apos;) + 
IF(ST_SUEZ__c &gt; 0, &apos;SUEZ &apos;, &apos;&apos;) + 
IF(ST_Sun_Trust_Bank__c &gt; 0, &apos;Sun Trust Bank &apos;, &apos;&apos;) + 
IF(ST_TransAmerica__c &gt; 0, &apos;TransAmerica &apos;, &apos;&apos;) + 
IF(ST_Under_Armour__c &gt; 0, &apos;Under Armour &apos;, &apos;&apos;) + 
IF(ST_United_Health_Care__c &gt; 0, &apos;United Health Care &apos;, &apos;&apos;) + 
IF(ST_US_Department_of_State__c &gt; 0, &apos;US Department of State &apos;, &apos;&apos;) + 
IF(ST_Washington_Baltimore_HIDTA__c &gt; 0, &apos;Washington/Baltimore HIDTA &apos;, &apos;&apos;) + 
IF(ST_Wisconsin_Department_of_Justice__c &gt; 0, &apos;Wisconsin Department of Justice &apos;, &apos;&apos;) + 
IF(ST_YDP_Growth_Fund__c &gt; 0, &apos;YDP Growth Fund &apos;, &apos;&apos;) + 
IF(ST_Viragh_Family_Foundation__c &gt; 0, &apos;Viragh Family Foundation &apos;, &apos;&apos;) + 
IF(ST_Charles_T_Bauer_Charitable_Fdn__c &gt; 0, &apos;Charles T. Bauer Charitable Fdn &apos;, &apos;&apos;) + 
IF(ST_Sherman_Fairchild_Fdn__c &gt; 0, &apos;Sherman Fairchild Fdn &apos;, &apos;&apos;) + 
IF(ST_Toledo_Community_Fdn__c &gt; 0, &apos;Toledo Community Fdn &apos;, &apos;&apos;) + 
IF(ST_PNC__c &gt; 0, &apos;PNC &apos;, &apos;&apos;) +
IF(ST_Blue_Cross_Blue_Shield__c &gt; 0, &apos;Blue Cross Blue Shield &apos;, &apos;&apos;)</formula>
    <label>Source Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Source_Type_Options__c.field-meta.xml
<CustomField>
    <fullName>Source_Type_Options__c</fullName>
    <label>Source Type Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baltimore Gas &amp; Electric</fullName>
            </value>
            <value>
                <fullName>Bauer Foundation</fullName>
            </value>
            <value>
                <fullName>Blue Cross Blue Shield</fullName>
            </value>
            <value>
                <fullName>CareFirst</fullName>
            </value>
            <value>
                <fullName>Charles Crane Foundation</fullName>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CRSF</fullName>
            </value>
            <value>
                <fullName>Fund II</fullName>
            </value>
            <value>
                <fullName>GEICO</fullName>
            </value>
            <value>
                <fullName>Healthy Lifestyles (HL)</fullName>
            </value>
            <value>
                <fullName>Herb Block Foundation</fullName>
            </value>
            <value>
                <fullName>Marriott Foundation</fullName>
            </value>
            <value>
                <fullName>Mississippi Department of Human Services</fullName>
            </value>
            <value>
                <fullName>Naples Children &amp; Education Foundation</fullName>
            </value>
            <value>
                <fullName>Niagara Cares</fullName>
            </value>
            <value>
                <fullName>Niagara Cares Hurricane Relief Foundation</fullName>
            </value>
            <value>
                <fullName>North Carolina Department of Justice</fullName>
            </value>
            <value>
                <fullName
        >Office of Juvenile Justice &amp; Delinquency Prevention</fullName>
                <label
        >Office of Juvenile Justice &amp; Delinquency Prevention</label>
            </value>
            <value>
                <fullName>Ohio Office of the Attorney General</fullName>
            </value>
            <value>
                <fullName>Perdue &amp; Henson Foundation</fullName>
            </value>
            <value>
                <fullName>Prince William HIDTA</fullName>
            </value>
            <value>
                <fullName>Private Grants</fullName>
            </value>
            <value>
                <fullName>Roanoke HIDTA</fullName>
            </value>
            <value>
                <fullName>SUEZ</fullName>
            </value>
            <value>
                <fullName>Sun Trust Bank</fullName>
            </value>
            <value>
                <fullName>TransAmerica</fullName>
            </value>
            <value>
                <fullName>Under Armour</fullName>
            </value>
            <value>
                <fullName>United Health Care</fullName>
            </value>
            <value>
                <fullName>US Department of State</fullName>
            </value>
            <value>
                <fullName>Viragh Family Foundation</fullName>
            </value>
            <value>
                <fullName>Washington/Baltimore HIDTA</fullName>
            </value>
            <value>
                <fullName>Wisconsin Department of Justice</fullName>
            </value>
            <value>
                <fullName>YDP Growth Fund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grant__c/fields/Total_Budgeted__c.field-meta.xml
<CustomField>
    <fullName>Total_Budgeted__c</fullName>
    <formula>IF(FirstPic_National_Org_Code__c = &apos;BBBSA&apos;,
Total_Item_Budget__c + Total_Fringe_Benefits__c +
IF(ISPICKVAL(Use_Indirect_Rate__c, &apos;Yes&apos;), Indirect_Rate_Amount__c, 0),
Total_Indirect_Rate_Budgeted__c + IF(AND(NOT(ISPICKVAL(Grant_Status__c, &apos;Approved&apos;)), NOT(ISPICKVAL(Grant_Status__c, &apos;Closed&apos;))), Total_New_Item_Budget__c,Total_Item_Budget__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >if Org = BBBSA: Total_Item_Budget__c + Total_Fringe_Benefits__c +  Indirect_Rate_Amount__c.
else: Total_Item_Budget__c +  Total_Indirect_Rate_Budgeted__c)</inlineHelpText>
    <label>Total Budgeted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grant__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <label>Grant</label>
</RecordType>

force-app/main/default/classes/SubGrantsCtrl.cls
public with sharing class SubGrantsCtrl {
  public UserClass userClass = new UserClass();
  public User currentUser { get; set; }
  public Account userAcct { get; set; }
  public String userAcctType { get; set; }
  public String portalName { get; set; }
  public String approverLevel { get; set; }

  private GrantClass gc = new GrantClass();
  private SelectOptionsClass soc = new SelectOptionsClass();
  private PaginationClass pc = new PaginationClass();
  private SchemaPicklistFields spf = new SchemaPicklistFields();

  public List<Grant__c> allsubgrants { get; set; }
  public List<Grant__c> subgrants { get; set; }

  public String orgName { get; set; }
  public String grantName { get; set; }
  public Id grantId { get; set; }
  public List<SelectOption> grantOptions { get; set; }
  public String status { get; set; }
  public List<SelectOption> statusOptions { get; set; }
  public String sourceType { get; set; }
  public List<SelectOption> sourceTypeOptions { get; set; }
  public String sortBy { get; set; }
  public List<SelectOption> sortByOptions { get; set; }
  public Boolean displayStatus { get; set; }
  public Boolean viewAll { get; set; }

  Integer counter = 0;
  Integer limitSize = 40;
  Integer totalSize = 0;
  public String recordCount { get; set; }
  public Boolean disablePrevious { get; set; }
  public Boolean disableNext { get; set; }

  public String errorMessage { get; set; }

  public SubGrantsCtrl() {
    currentUser = userClass.currentUser;
    userAcct = userClass.userAcct;
    userAcctType = userClass.userAcctType;
    approverLevel = userClass.approverLevel;
    portalName = userClass.userProfile;

    allsubgrants = new List<Grant__c>();
    subgrants = new List<Grant__c>();
    sourceType = '';

    String urlGrantId = ApexPages.currentPage().getParameters().get('grantId');
    if (urlGrantId != '' && urlGrantId != null) {
      if (
        Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}')
          .matcher(urlGrantId)
          .matches()
      ) {
        grantId = Id.valueOf(urlGrantId);
      }
    }

    status = ApexPages.currentPage().getParameters().get('status');
    if (status != null)
      status = status.capitalize();
    if (status == 'completed')
      status = 'Approved';

    grantName = ApexPages.currentPage().getParameters().get('grantName');
    sortBy = ApexPages.currentPage().getParameters().get('sortBy');
    if (sortBy != null)
      sortBy = 'Name';

    viewAll = true;
    if (approverLevel == 'Level One')
      viewAll = false;
  }

  public void getOptions() {
    String gt = 'grant';
    String soqlAND = '';
    if (userAcctType == 'Local Organization') {
      gt = 'subgrant';
      soqlAND = ' AND Grant_Status__c != \'Closed\'';
    }
    if (portalName.contains('TRAIL'))
      soqlAND += ' AND (Grant_Type__c = \'TRAIL\' OR National_Grant_Type__c = \'TRAIL\')';
    if (portalName.contains('OVC'))
      soqlAND += ' AND (Grant_Type__c = \'OVC\' OR National_Grant_Type__c = \'OVC\')';

    grantOptions = gc.getGrantOptions(
      userAcctType,
      userAcct.Id,
      null,
      'Name',
      '',
      gt,
      soqlAND
    );
    if (grantId == null)
      grantId = gc.selectedGrantId;

    sourceType = '';
    sourceTypeOptions = new List<SelectOption>();
    sourceTypeOptions = spf.getPicklistOptions(
      'Grant__c',
      'Source_Type_Options__c',
      'View All'
    );

    sortByOptions = new List<SelectOption>();
    if (userAcctType == 'National Organization')
      sortByOptions.add(new SelectOption('Account__r.Name', 'Organization'));
    sortByOptions.add(new SelectOption('Name', 'Name'));
    sortByOptions.add(new SelectOption('Amount__c', 'Awarded'));
    sortByOptions.add(new SelectOption('Total_Budgeted__c', 'Total Budgeted'));
    sortByOptions.add(
      new SelectOption('Reimbursement_Requested_Amount__c', 'Requested Amount')
    );
    sortByOptions.add(
      new SelectOption('Reimbursement_Approved_Amount__c', 'Approved Amount')
    );
    sortByOptions.add(new SelectOption('Balance__c', 'Balance'));
    if (userAcctType == 'National Organization')
      sortByOptions.add(new SelectOption('Grant_Status__c', 'Status'));
    if (sortBy == null)
      sortBy = 'Name';

    getStatusOptions();
    getLists();
  }

  public void getStatusOptions() {
    statusOptions = soc.getStatusOptions(
      userAcctType,
      portalName,
      grantId,
      'grant'
    );
    status = soc.getDefaultStatus(
      portalName,
      userAcctType,
      grantId,
      'grant',
      approverLevel,
      status
    );
  }

  public void getLists() {
    errorMessage = '';
    String soqlAND = '';
    if (userAcctType == 'Local Organization') {
      soqlAND += '';
      if (status != 'Closed') {
        soqlAND += ' AND Grant_Status__c != \'Closed\'';
      }
    }
    if (sourceType != '' && sourceType != 'View All')
      soqlAND += ' AND Source_Type__c LIKE \'%' + sourceType + '%\'';
    if (userAcctType == 'National Organization' && viewAll == false) {
      soqlAND +=
        ' AND (Primary_Approver_Id__c = \'' +
        currentUser.ContactId +
        '\'';
      soqlAND +=
        ' OR (Secondary_Approver_Id__c = \'' +
        currentUser.ContactId +
        '\'';
      soqlAND += ' AND (Primary_Approver_On_Leave__c = true OR FirstPic_National_Org_Code__c = \'Ripken\')))';
    }
    if (portalName.contains('TRAIL'))
      soqlAND += ' AND (Grant_Type__c = \'TRAIL\' OR National_Grant_Type__c = \'TRAIL\')';
    if (portalName.contains('OVC'))
      soqlAND += ' AND (Grant_Type__c = \'OVC\' OR National_Grant_Type__c = \'OVC\')';
    allSubGrants = gc.getRelatedSubGrants(
      userAcct.Id,
      grantId,
      status,
      sortBy,
      orgName,
      grantName,
      soqlAND
    );

    displayStatus = false;
    if (
      status == null ||
      status == '' ||
      status == 'View All' ||
      status == 'All In Progress' ||
      status == 'Pending Approval' ||
      (grantName != '' &&
      grantName != null)
    )
      displayStatus = true;

    totalSize = allsubgrants.size();
    if (totalSize > 999)
      errorMessage =
        'List of ' +
        totalSize +
        ' results is too large to display. Please narrow search criteria and refresh results';
    else
      first();
  }

  // BEGIN Pagination
  public void first() {
    counter = 0;
    subgrants = pc.first(allsubgrants, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = true;
    disableNext = pc.getDisableNext(counter, limitSize, totalSize);
  }

  public void next() {
    counter = counter + limitSize;
    subgrants = pc.next(allsubgrants, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = false;
    disableNext = pc.getDisableNext(counter, limitSize, totalSize);
  }

  public void previous() {
    counter = counter - limitSize;
    subgrants = pc.previous(allsubgrants, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = pc.getDisablePrevious(counter);
    disableNext = false;
  }

  public void last() {
    counter = pc.getLastCounter(counter, limitSize, totalSize);
    subgrants = pc.last(allsubgrants, counter, limitSize);
    recordCount = pc.getRecordCount(counter, limitSize, totalSize);
    disablePrevious = false;
    disableNext = true;
  }
  // END Pagination
}