force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Victims_Served_Report__c/Victims_Served_Report__c.object-meta.xml
<CustomObject>
    <label>Victims Served Report</label>
    <nameField>
        <displayFormat>VS-{00000}</displayFormat>
        <label>Victims Served Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Victims Served Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Victims_Served_Report__c/fields/Adult_Physical_Assault__c.field-meta.xml
<CustomField>
    <fullName>Adult_Physical_Assault__c</fullName>
    <label>Adult Physical Assault</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Adult_Sexual_Assault__c.field-meta.xml
<CustomField>
    <fullName>Adult_Sexual_Assault__c</fullName>
    <label>Adult Sexual Assault</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Adults_Sexually_Abused__c.field-meta.xml
<CustomField>
    <fullName>Adults_Sexually_Abused__c</fullName>
    <label>Adults Sexually Abused</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Age_Tracked__c.field-meta.xml
<CustomField>
    <fullName>Age_Tracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Age Tracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Arson__c.field-meta.xml
<CustomField>
    <fullName>Arson__c</fullName>
    <label>Arson</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Bullying__c.field-meta.xml
<CustomField>
    <fullName>Bullying__c</fullName>
    <label>Bullying</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Burglary__c.field-meta.xml
<CustomField>
    <fullName>Burglary__c</fullName>
    <label>Burglary</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Child_Physical_Abuse__c.field-meta.xml
<CustomField>
    <fullName>Child_Physical_Abuse__c</fullName>
    <label>Child Physical Abuse</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Child_Pornography__c.field-meta.xml
<CustomField>
    <fullName>Child_Pornography__c</fullName>
    <label>Child Pornography</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Child_Sexual_Abuse__c.field-meta.xml
<CustomField>
    <fullName>Child_Sexual_Abuse__c</fullName>
    <label>Child Sexual Abuse</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Clients_Surveyed_for_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Clients_Surveyed_for_Feedback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clients Surveyed for Feedback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Deaf_Hard_of_Hearing__c.field-meta.xml
<CustomField>
    <fullName>Deaf_Hard_of_Hearing__c</fullName>
    <label>Deaf/Hard-of-Hearing</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Domestic_Violence__c.field-meta.xml
<CustomField>
    <fullName>Domestic_Violence__c</fullName>
    <label>Domestic Violence</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/DUI_DWI__c.field-meta.xml
<CustomField>
    <fullName>DUI_DWI__c</fullName>
    <label>DUI/DWI</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Elder_Abuse__c.field-meta.xml
<CustomField>
    <fullName>Elder_Abuse__c</fullName>
    <label>Elder Abuse</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Emotional_Support_Services_Provided__c.field-meta.xml
<CustomField>
    <fullName>Emotional_Support_Services_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emotional Support Services Provided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Gender_Tracked__c.field-meta.xml
<CustomField>
    <fullName>Gender_Tracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gender Tracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Hate_Crime__c.field-meta.xml
<CustomField>
    <fullName>Hate_Crime__c</fullName>
    <label>Hate Crime</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Homeless__c.field-meta.xml
<CustomField>
    <fullName>Homeless__c</fullName>
    <label>Homeless</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Human_Trafficking_Labor__c.field-meta.xml
<CustomField>
    <fullName>Human_Trafficking_Labor__c</fullName>
    <label>Human Trafficking: Labor</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Human_Trafficking_Sex__c.field-meta.xml
<CustomField>
    <fullName>Human_Trafficking_Sex__c</fullName>
    <label>Human Trafficking: Sex</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Identity_Theft__c.field-meta.xml
<CustomField>
    <fullName>Identity_Theft__c</fullName>
    <label>Identity Theft</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Immigrants_Refugees_Asylum_Seekers__c.field-meta.xml
<CustomField>
    <fullName>Immigrants_Refugees_Asylum_Seekers__c</fullName>
    <label>Immigrants/Refugees/Asylum Seekers</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Info_and_Referral_Services_Provided__c.field-meta.xml
<CustomField>
    <fullName>Info_and_Referral_Services_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info and Referral Services Provided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Justice_System_Services_Provided__c.field-meta.xml
<CustomField>
    <fullName>Justice_System_Services_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Justice System Services Provided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Kidnapping_Custodial__c.field-meta.xml
<CustomField>
    <fullName>Kidnapping_Custodial__c</fullName>
    <label>Kidnapping (Custodial)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Kidnapping_Non_custodial__c.field-meta.xml
<CustomField>
    <fullName>Kidnapping_Non_custodial__c</fullName>
    <label>Kidnapping (Non-custodial)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/LGBTQ__c.field-meta.xml
<CustomField>
    <fullName>LGBTQ__c</fullName>
    <label>LGBTQ</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Mass_Violence__c.field-meta.xml
<CustomField>
    <fullName>Mass_Violence__c</fullName>
    <label>Mass Violence</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Number_w_Multiple_Type_of_Victimization__c.field-meta.xml
<CustomField>
    <fullName>Number_w_Multiple_Type_of_Victimization__c</fullName>
    <label>Number w/ Multiple Type of Victimization</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/On_Track_Fiscally__c.field-meta.xml
<CustomField>
    <fullName>On_Track_Fiscally__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Track Fiscally</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Victims Served Reports</relationshipLabel>
    <relationshipName>Victims_Served_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Other_Special_Classification__c.field-meta.xml
<CustomField>
    <fullName>Other_Special_Classification__c</fullName>
    <label>Other Special Classification</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Other_Vehicular_Victimization__c.field-meta.xml
<CustomField>
    <fullName>Other_Vehicular_Victimization__c</fullName>
    <label>Other Vehicular Victimization</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Other_Victimization__c.field-meta.xml
<CustomField>
    <fullName>Other_Victimization__c</fullName>
    <label>Other Victimization</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Personal_Advocacy_Services_Provided__c.field-meta.xml
<CustomField>
    <fullName>Personal_Advocacy_Services_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Advocacy Services Provided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Race_Ethnicity_Tracked__c.field-meta.xml
<CustomField>
    <fullName>Race_Ethnicity_Tracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Race/Ethnicity Tracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Robbery__c.field-meta.xml
<CustomField>
    <fullName>Robbery__c</fullName>
    <label>Robbery</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Shelter_Housing_Services_Provided__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Housing_Services_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shelter/Housing Services Provided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Stalking__c.field-meta.xml
<CustomField>
    <fullName>Stalking__c</fullName>
    <label>Stalking</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Survivors_of_Homicide_Victims__c.field-meta.xml
<CustomField>
    <fullName>Survivors_of_Homicide_Victims__c</fullName>
    <label>Survivors of Homicide Victims</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Teen_Dating_Victimization__c.field-meta.xml
<CustomField>
    <fullName>Teen_Dating_Victimization__c</fullName>
    <label>Teen Dating Victimization</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Terrorism__c.field-meta.xml
<CustomField>
    <fullName>Terrorism__c</fullName>
    <label>Terrorism</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Tracking_New_Individuals__c.field-meta.xml
<CustomField>
    <fullName>Tracking_New_Individuals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tracking New Individuals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Veterans__c.field-meta.xml
<CustomField>
    <fullName>Veterans__c</fullName>
    <label>Veterans</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Victims_with_Disabilities__c.field-meta.xml
<CustomField>
    <fullName>Victims_with_Disabilities__c</fullName>
    <label>Victims with Disabilities</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Victims_Served_Report__c/fields/Victims_with_Limited_English_Proficiency__c.field-meta.xml
<CustomField>
    <fullName>Victims_with_Limited_English_Proficiency__c</fullName>
    <label>Victims with Limited English Proficiency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestVictimsServedReport.cls
@isTest
public class TestVictimsServedReport {
  static testMethod void testVictimsServedReports() {
    system.test.startTest();

    Account a = new Account(Name = 'Test Account');
    insert a;

    Victims_Served_Report__c report = new Victims_Served_Report__c(
      Organization__c = a.Id,
      Month__c = 'Jan - Mar',
      Year__c = 2020,
      Tracking_New_Individuals__c = true,
      Race_Ethnicity_Tracked__c = true,
      Gender_Tracked__c = true,
      Age_Tracked__c = true,
      Info_and_Referral_Services_Provided__c = true,
      Personal_Advocacy_Services_Provided__c = true,
      Emotional_Support_Services_Provided__c = true,
      Shelter_Housing_Services_Provided__c = true,
      Justice_System_Services_Provided__c = true,
      Clients_Surveyed_for_Feedback__c = true,
      On_Track_Fiscally__c = true,
      Adult_Physical_Assault__c = 'nt',
      Adult_Sexual_Assault__c = 'nt',
      Adults_Sexually_Abused__c = 'nt',
      Arson__c = 'nt',
      Bullying__c = 'nt',
      Burglary__c = 'nt',
      Child_Physical_Abuse__c = 'nt',
      Child_Pornography__c = 'nt',
      Child_Sexual_Abuse__c = 'nt',
      Domestic_Violence__c = 'nt',
      DUI_DWI__c = 'nt',
      Elder_Abuse__c = 'nt',
      Hate_Crime__c = 'nt',
      Human_Trafficking_Labor__c = 'nt',
      Human_Trafficking_Sex__c = 'nt',
      Identity_Theft__c = 'nt',
      Kidnapping_Non_custodial__c = 'nt',
      Kidnapping_Custodial__c = 'nt',
      Mass_Violence__c = 'nt',
      Other_Vehicular_Victimization__c = 'nt',
      Robbery__c = 'nt',
      Stalking__c = 'nt',
      Survivors_of_Homicide_Victims__c = 'nt',
      Teen_Dating_Victimization__c = 'nt',
      Terrorism__c = 'nt',
      Other_Victimization__c = 'nt',
      Number_w_Multiple_Type_of_Victimization__c = 'nt',
      Deaf_Hard_of_Hearing__c = 'nt',
      Homeless__c = 'nt',
      Immigrants_Refugees_Asylum_Seekers__c = 'nt',
      LGBTQ__c = 'nt',
      Veterans__c = 'nt',
      Victims_with_Disabilities__c = 'nt',
      Victims_with_Limited_English_Proficiency__c = 'nt',
      Other_Special_Classification__c = 'nt'
    );
    insert report;

    List<Victims_Served_Report__c> reports = new List<Victims_Served_Report__c>();
    for (Integer i = 0; i < 50; i++) {
      Victims_Served_Report__c r = new Victims_Served_Report__c(
        Organization__c = a.Id,
        Month__c = 'Jan - Mar',
        Year__c = 2020
      );
      reports.add(r);
    }
    insert reports;

    Profile p1 = [SELECT Id FROM Profile WHERE Name = 'OVC Level Three'];
    Contact c1 = new Contact(
      accountId = a.Id,
      lastName = 'Contact',
      firstName = 'Test1',
      Email = 'newtest1@example.com'
    );
    insert c1;
    User u1 = new User(
      Alias = 'testu',
      Email = 'test@example.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Test1',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p1.Id,
      UserName = 'levelthree@test1.com',
      Contact = c1,
      ContactId = c1.Id
    );
    insert u1;

    System.runAs(u1) {
      system.test.setCurrentPageReference(
        new PageReference('Page.OVCProgramReport?reportId=' + report.Id)
      );
      VictimsServedReportCtrl ctrl1 = new VictimsServedReportCtrl();
      ctrl1.updateFieldVisibility();
      ctrl1.next();
      ctrl1.next();
      ctrl1.next();
      ctrl1.previous();
      ctrl1.save();
      ctrl1.submit();
      ctrl1.showValidationPopup();
      ctrl1.hideValidationPopup();
      ctrl1.hideValidationPopupAndContinue();
      //            Victims_Served_Report__c result = [SELECT Burglary__c FROM Victims_Served_Report__c WHERE Id = :report.id];
      //            system.assertEquals('N/T', result.Burglary__c);

      VictimsServedReportsCtrl ctrl2 = new VictimsServedReportsCtrl();
      ctrl2.getLists();
      ctrl2.next();
      ctrl2.previous();
      ctrl2.last();
      ctrl2.getLastCounter();
      ctrl2.getRecordCount();
      ctrl2.getDisableNext();
      ctrl2.getDisablePrevious();
    }

    system.test.stopTest();
  }
}