force-app/main/default/objects/PA_Challenge__c/PA_Challenge__c.object-meta.xml
<CustomObject>
    <label>PA Challenge</label>
    <nameField>
        <displayFormat>PAC-{0000}</displayFormat>
        <label>PA Challenge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Challenges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_1__c.field-meta.xml
<CustomField>
    <fullName>Challenge_1__c</fullName>
    <label>Challenge 1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_2__c.field-meta.xml
<CustomField>
    <fullName>Challenge_2__c</fullName>
    <label>Challenge 2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_3__c.field-meta.xml
<CustomField>
    <fullName>Challenge_3__c</fullName>
    <label>Challenge 3</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_4__c.field-meta.xml
<CustomField>
    <fullName>Challenge_4__c</fullName>
    <label>Challenge 4</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_5__c.field-meta.xml
<CustomField>
    <fullName>Challenge_5__c</fullName>
    <label>Challenge 5</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Challenge_6__c.field-meta.xml
<CustomField>
    <fullName>Challenge_6__c</fullName>
    <label>Challenge 6</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Limit_to_Whole_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Limit_to_Whole_Numbers__c</fullName>
    <formula
  >IF(Measurement__c == &apos;Number Completed&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Limit to Whole Numbers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PA_Challenge__c/fields/Youth_in_Program_Report__c.field-meta.xml
<CustomField>
    <fullName>Youth_in_Program_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Youth in Program Report</label>
    <referenceTo>Youth_in_Program_Report__c</referenceTo>
    <relationshipLabel>PA Challenges</relationshipLabel>
    <relationshipName>PA_Challenges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Youth_in_Program_Report__c/Youth_in_Program_Report__c.object-meta.xml
<CustomObject>
    <label>Youth in Program Report</label>
    <nameField>
        <displayFormat>Y-{0000}</displayFormat>
        <label>Youth in Program Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Youth in Program Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PAChallengeClass.cls
public without sharing class PAChallengeClass {
  public String soql { get; set; }

  public String getSOQL() {
    String expr = '';
    Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.PA_Challenge__c.fields.getMap();
    for (String fieldName : schemaFieldMap.keySet()) {
      expr += fieldName + ', ';
    }
    expr = expr.removeEnd(', ');

    soql = 'SELECT ' + expr + ' FROM PA_Challenge__c';
    return soql;
  }

  public List<PA_Challenge__c> getPACList(Id yprId) {
    getSOQL();
    soql += ' WHERE Youth_in_Program_Report__c = \'' + yprId + '\'';
    List<PA_Challenge__c> pacs = new List<PA_Challenge__c>();
    pacs = Database.query(soql);
    return pacs;
  }

  public void upsertPAC(PA_Challenge__c pac) {
    try {
      upsert pac;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }

  public void upsertPACs(List<PA_Challenge__c> pacs) {
    for (PA_Challenge__c p : pacs) {
      if (p.Limit_to_Whole_Numbers__c) {
        if (p.Challenge_1__c != null)
          p.Challenge_1__c = p.Challenge_1__c.setScale(0);
        if (p.Challenge_2__c != null)
          p.Challenge_2__c = p.Challenge_2__c.setScale(0);
        if (p.Challenge_3__c != null)
          p.Challenge_3__c = p.Challenge_3__c.setScale(0);
        if (p.Challenge_4__c != null)
          p.Challenge_4__c = p.Challenge_4__c.setScale(0);
        if (p.Challenge_5__c != null)
          p.Challenge_5__c = p.Challenge_5__c.setScale(0);
        if (p.Challenge_6__c != null)
          p.Challenge_6__c = p.Challenge_6__c.setScale(0);
      }
    }
    try {
      upsert pacs;
    } catch (Exception e) {
      ApexPages.addMessages(e);
    }
  }
}